### PR TITLE
Linux: update install script to remove command -v check

### PR DESCRIPTION
**Pull request by CalebJohn**
#2906 is a bit hard to track down because I can't reliably reproduce it. I think the issue was the interaction between the call to `set -e` at the top and my call to `command -v` 

`set -e` causes the script to quit out immediately if a non-zero exit status is encountered.
`command -v` returns  a non-zero exit message if a listed command can't be found (`uname` in this case).

I think there's a weird condition where these 2 conspire together to quit the script with no exit status. To that end I've changed the script to hopefully prevent ever having the exit status of 1.

edit: With some testing it appears that this fix isn't enough, will keep trying.

### CODE REVIEW

**Comment by tessus** [comment]
@CalebJohn PR #2719 cleans up the script pretty nicely. maybe you want to involve the OP of that PR.

**Comment by laurent22** [comment]
Actually we can merge that other PR first if that helps. Feel free to do so @tessus if it's ready to merge.

**Comment by laurent22** [comment]
Also @CalebJohn could this PR be related to this silent errors you're tracking? https://github.com/laurent22/joplin/pull/2913

**Comment by tessus** [comment]
Unfortunately there was a change to the install file and now there are conflicts in that PR. I was afraid that something like that might happen. I certainly lost track of it.
I'll ask the OP to solve the conflicts and merge.

**Comment by CalebJohn** [comment]
dpoulton's reply on the forum here confirms that the issue is  indeed the one in #2913  once that's merged it should be fixed. I'll merge master in here just because this is a bit cleaner and the work is already done.

**Comment by laurent22** [comment]
Are we ok about merging this PR?

**Comment by CalebJohn** [comment]
I left the WIP label on by mistake, this is ready to go.

**Comment by laurent22** [comment]
Looks good, thanks @CalebJohn!

**Pull request merged**
