### PR TITLE
PDF Viewer: Zoom In/Out

### PR DESCRIPTION
**Pull request by asrient**
This is a subset of the previously opened PR: https://github.com/laurent22/joplin/pull/6740

## Major features added to the viewer

- Zoom in/ zoom out.

## Screenshot

Screen Shot 2022-08-27 at 9 17 46 PM

https://user-images.githubusercontent.com/44570278/187043945-76d4ce2e-97a7-48a6-a7bd-b02c837ed34e.mov

### CODE REVIEW

**Comment by laurent22** [comment]
This is wrong, I see the same code as in https://github.com/laurent22/joplin/pull/6747

**Comment by laurent22** [comment]
@asrient, please fix the conflicts and rebase your branch so that it can be reviewed.

**Comment by laurent22** [comment]
ok looks good, let's merge

**Comment by asrient** [comment]
Hi, I was about to mention it here, if you notice there was a change in build command in root `package.json`.
After adding some new packages to `pdf-viewer` related to fontawesome, I noticed the build on CI was failing. On inspection I saw that everytime, `app-desktop` is being built before `pdf-viewer` and this caused copying build assets of the viewer to fail.
To fix this I added `--topological ` arg to `buildSequential` command.

### -t,--topological
> Run the command after all workspaces it depends on (regular) have finished.

Documentation for the argument is [here](https://yarnpkg.com/cli/workspaces/foreach).

**Pull request merged**
