### PR TITLE
Mobile: fixes #4810, #4610 iOS Sync bug by using aws-sdk-js-v3

### LINKED ISSUE #4810: AWS S3 Synchronisation Error on iOS deivce
## Environment

Joplin version: 10.7.2 (Latest on iOS for now)
Platform: iOS
OS specifics: 14.4.1 on iPhone (Latest for now)

## Steps to reproduce

1. First time synchronisation on windows with E2EE enable
2. Synchronisation to AWS S3 Server
3. First time synchronisation on iOS
4. got an error like this:
         “XMLParserError：Non-whitespace before first tag.
         Line: 0
         Column: 1
         Char: S”。

## Describe what you expected to happen
The notes seems fine in the first time that I synchronisation on iOS (This Error message appear when the synchronisation is almost finished) , but when this error appear,  the synchronisation function is totally broken and noting can be synchronisation neither other platform---->iOS nor iOS-----> other platform.

The notes that I have, almost all notes is I manually added, and a few is I import form md files that I exported from Notion app. 

I tried 10 times, even change the provider of the server and it can be resocced every time.
## Logfile

IMG_0782
IMG_0783
IMG_0784
IMG_0785

### PR DESCRIPTION
**Pull request by leematos**
The core of this Pull Request is https://github.com/laurent22/joplin/pull/5176/files#diff-d06c6d5b2a13f7fa8da76bfd1d45a14e77df2d2ad3f92995e7dfe8c13a0616ef where I've implemented the new aws-sdk-js-v3 only for the HEAD command. This is the command that generated two bug reports (I also hit this) so I scoped the fix here.

I wanted to start a discussion on how best to proceed. There are three options:

1. Use the old API and build exception handling for this specific error. (Hackish, but should work and the change will be isolated to mobile clients.)
2. Use this fix as a stop gap (S3 is in beta) and if we don't see side effects, then convert the rest of the S3 endpoints to use the v3 SDK. (Change affects mobile and desktop as it's at the driver level. Limits scope of change, and risk.)
3. Convert all endpoints to the v3 endpoints for the S3 file driver. (not hard, more technically correct, but a larger scoped change.)

This has NOT been tested on Android or Desktop yet as depending on the strategy will dictate what kind of testing I'd need to do.

Let me know how you'd like to proceed and I can go forward. I'm eager to get this fix mainlined as I'm blocked by this and can't use Joplin on my iPhone with my shiny new S3 buckets 😄 

The rest of the changes are package updates (I ran npm install from root as I had some problems trying to just update the lib or mobile packages. Not sure if that's right or how you want to merge package update changes.) 

I also removed flipper which was causing me huge troubles building on xCode, but that's not needed for the patch. (It's a debugging tool as far as I understand it.) We can add it back and/or remove it in other commits if you'd like.

### CODE REVIEW

**Comment by laurent22** [comment]
Not sure who can review this because I have no idea about any of it. If I'm the only one reviewing, I prefer the quick hack to make it work on iOS. Otherwise you might need to find someone who is familiar with this part of the code and who is willing to review.

**Comment by laurent22** [comment]
If we were to proceed with your changes, can we remove the "aws-sdk" package? Because it probably takes half the space of the app even though we only use a tiny part of it.

**Comment by leematos** [comment]
@laurent22 I won't be able to remove 'aws-sdk' unless I replace all the calls with aws-sdk-v3 (with is also designed to be modular to solve this size problem.) 

If I built s3 specific integration tests for each platform would you feel comfortable providing a "style/sytnax" review? 

I'm going to whip up the quick hack version now so you can review and we can figure out how to proceed for an api upgrade.

**Comment by laurent22** [comment]
> If I built s3 specific integration tests for each platform would you feel comfortable providing a "style/sytnax" review?

I'm more concerned about adding another AWS package, since the one we have is already taking so much space. Is the aws-sdk-v3 package compatible with the one we currently use? Or would switching to it requires significant refactoring?

**Comment by leematos** [comment]
@laurent22 

> Is the aws-sdk-v3 package compatible with the one we currently use? 

they both can work along side of each other if we call them appropriately, but there are some subtle configuration differences that make the new package not a drop in replacement, but it's not hard to drop in as I already have 😸 

> Or would switching to it requires significant refactoring

The refactoring is probably about 10 api calls (I think less actually) and I don't expect any other refactoring needed as the rest of the core logic remains the same once joplin has the data.

**Comment by leematos** [comment]
the refactoring is basically:

`this.api().headObject({`

to

`this.api().send(new HeadObjectCommand({`
				
For each type of request, and confirming that the output is formatted the same with the new API.

**Comment by leematos** [comment]
This is closed because I need to fix my branches on my fork. Still working towards a fix 😄

**Comment by leematos** [comment]
@laurent22 the plot thickens.

So, in attempting to write the simple error handling version I could not trigger the XMLError in my env. This is when I realize my current env is based on latest dev.

I re-built against the latest iOS release commit bddbc0b54e1849ce0e5905bd34f9844eeb09a54e, re-ran pod install and npm install, and the problem gets triggered.

So, this is "technically" fixed in dev already? I assume some package somewhere that was actually causing the problem got updated.  I've considered hunting it down, but an easier (for me 😛) case would be a released package based on current dev.

Would you be able to release a new iOS build (maybe pulling in https://github.com/laurent22/joplin/pull/4506 as a reason for the build) and then I can confirm on my device if the problem persists?

**Comment by leematos** [comment]
Errr, I went to test this with a clean built and it looks like ^ the above is wrong, dev still has the error. Ugh. These build envs...

Going to make the simple error handling version now.

**Comment by leematos** [comment]
so last night I made the simple error handling version and there were two side effects:

- The try and repeat logic would get triggered a few times (I assume because it thinks there is an error)
- The XML error cropped up now in s3ListObjects (which does return XML so, interesting) but again, on requests that "error" we get a valid response:

`[Sun Jul 11 2021 22:11:30.900]  LOG      {"CommonPrefixes": [], "Contents": [{"ETag": "\"749ccbf0c0a49f3fb13f1d9265425333\"", "Key": "locks/sync_mobile_76b61336f401436a83d7327883575416.json", "LastModified": 2021-07-12T02:11:07.008Z, "Size": 83, "StorageClass": "STANDARD"}], "Delimiter": "/", "IsTruncated": false, "KeyCount": 1, "MaxKeys": 1000, "Name": "joplin-test", "Prefix": "locks/"}
[Sun Jul 11 2021 22:11:30.920]  ERROR    22:11:30: [XMLParserError: Non-whitespace before first tag.
Line: 0
Column: 1
Char: T]
`

It's possible in the log I'm miss-attributing what request is generating the error, but it seems the simple hack fix may have worse side effects.

If I have some time tonight I'm going to put together a full v3 api replacement as it seems like the right option, and we'd just need to decide how to test/review it.

**Pull request closed without merging**
