### PR TITLE
show correct date/time for cli command `ls`

### PR DESCRIPTION
**Pull request by tessus**
This change will allow the correct date/time to be shown when running the CLI app and when running the command directly (e.g.: `joplin ls -l`).

See also #729

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the PR, but it would be better to load this setting during application initialisation to avoid code duplication in the command files. If you set it in BaseApplication.js::start(), probably where setLocale is called it should work. Could you give this a try and see if it works?

**Comment by tessus** [comment]
I looked at the commands and only `tag` and `ls` would have needed those 2 lines. But I agree, adding them to the init code for all commands makes more sense.

I'll test it this evening and adjust the PR accordingly.

**Comment by tessus** [comment]
> Could you give this a try and see if it works?

Yep, works. New commits have been pushed (I squashed, rebased, ...).

**Comment by laurent22** [comment]
Looks good, thanks!

**Pull request merged**
