### PR TITLE
Desktop: Resolves #10194: Notebook disappears on typing

### LINKED ISSUE #10194: Focus is lost and notebook disappears
### Operating system

Windows

### Joplin version

3.0.2

### Desktop version info

Joplin 3.0.2 (prod, linux)

Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: a59ad20

Backup: 1.4.0

### Current behaviour

1. Select "All notes" in the left pane.

Screenshot from 2024-03-24 09-03-15

2. Select a note and then type any letter in the note. The focus is lost, the notebook is not shown in the list anymore and the second notebook in the list is shown.

It only happens when "All notes" is selected and not an individual notebook.

### Expected behaviour

Keep focus in the note and show the notebook on top in the list.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Aitchessbee**

### CODE REVIEW

**Comment by Aitchessbee** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Aitchessbee** [comment]
Any idea why the tests are failing?

**Comment by laurent22** [comment]
> Any idea why the tests are failing?

The failures seem related so you might want to investigate this. Simply run `yarn test` from the relevant package on your computer

**Comment by Aitchessbee** [comment]
Just checked, yarn test in the dev branch is also failing...

**Comment by Aitchessbee** [comment]
The tests were failing because this branch was not up to date with the latest dev... We can close this branch as there is a PR with a better solution for this...

**Pull request closed without merging**
