### PR TITLE
Clipper: Adding a footer to include the URL clipped

### PR DESCRIPTION
**Pull request by izmagik**
Adding a footer to include the URL clipped.

The footer looks like:

```
----------------------------------
clipped from : https://www.mozilla.org/fr/privacy/firefox/
```

@laurent22

### CODE REVIEW

**Comment by CalebJohn** [comment]
You can already access the url by clicking 
image
this button.

Is there a reason to add the source url twice?

**Comment by izmagik** [comment]
I was not aware of that feature :).
But I think it will be more convient to have it also at the bottom.

**Comment by CalebJohn** [comment]
[You can usually check these things on the forum first](https://discourse.joplinapp.org/search?q=clipper%20url).

Looks like your check failed because you didn't install the pre-commit hook. You have linting issues.

Thanks for helping improve Joplin. But I don't think this is something that will likely be merged since it doesn't provide much change from a usability perspective. Feel free to correct me if you feel like you can make a strong case.

**Comment by laurent22** [comment]
As CalebJohn said, this is already supported in the Info dialog.

**Pull request closed without merging**
