### PR TITLE
Desktop : Prevent overflow on small window size

### LINKED ISSUE #2917: Desktop: White margin on small window size
## Environment

Joplin version: 1.0.195
Platform: Linux Desktop
OS specifics: Ubuntu 19.10

## Steps to reproduce

1. Make the window size small (about 1/4 of the screen size on my 1366x768 display seems to trigger it)
2. Create a new note / paste a long note / paste a long title 
3. White margin is created due to title input overflowing

## Describe what you expected to happen

Title field should not overflow

# Screenshot

titleOverflow

### PR DESCRIPTION
**Pull request by anihm136**
Fixes #2917 
Added rule to prevent overflow of title input field

### CODE REVIEW

**Comment by anihm136** [comment]
@PackElend please label me for GSoC

**Comment by CalebJohn** [comment]
I don't see any harm in adding this line, but I also can't reproduce the issue you have. Can you give more instructions to reproduce this?

**Comment by anihm136** [comment]
ezgif com-optimize

I hope this clarifies it?

**Comment by CalebJohn** [comment]
Thanks, that indeed did help, I wasn't shrinking the window far enough.

LGTM

**Pull request merged**
