### PR TITLE
added incomplete Malay translation

### PR DESCRIPTION
**Pull request by potateros**
Started adding Malay translation, but it is not yet complete (35% complete), hopefully someone can also help check my translations. I have finished this much before suddenly getting too busy.

### CODE REVIEW

**Comment by laurent22** [comment]
Thank you for the pull request but I'm not sure if that can be merged? Are you going to add more to the translation?

**Comment by potateros** [comment]
I would like to make a new branch for this instead, but I'm not sure how. This is my first public pull request for hacktoberfest, and I wanted to help contribute to something I use :smile: Advice on how to proceed with this? I don't want to lose my translation work, and was hoping others would help improve my translations

**Comment by laurent22** [comment]
This is fine and that's the right way to contribute. The only issue is that at 35% the pull request cannot currently be merged, but we can leave it open for now to see if someone else would like to contribute. I'd say it would need to be completed at around 80% to be merged.

**Comment by laurent22** [comment]
Closing this pull request for now. Please re-create one once the translation is more complete.

**Pull request closed without merging**
