### PR TITLE
Displaying the notebook's name in the Note toolbar when search is act…

### PR DESCRIPTION
**Pull request by zblesk**
This PR adds a single feature: when Search is active, each note's parent notebook is displayed in the note's toolbar, so you can tell where it belongs.

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pull request. Is it possible to make the folder item look different so that it doesn't look like a clickable button? Or maybe it could go to the left of the title input box as a simple label? eg with something like "`coding > [joplin     ]`"

Also regarding this:

    title: _(this.state.folder.title),

The `_()` is to mark a string as translatable and it should only go around raw strings (not variables). In that case anyway the folder title is not translatable since it's user-specified.

**Comment by zblesk** [comment]
Sure, I'll give it a try. Thanks.

**Comment by zblesk** [comment]
I like the idea of a simple text label a lot less; I like the clear visual indication of the notebook (since the icon is used to denote them in 2 separate places on the screen already.) 

I opted for keeping it in the toolbar, but it no longer behaves as a button - no hover highlights or clicking. 

I've added a new component to facilitate this; I've noticed you already switch between 'button' and 'text' items in the toolbar, but the latter branch looks just like a placeholder and I'd found no suitable component. So I've added a new one. ToolbarLabel is almost the same as ToolbarButton, however I didn't want to add it as a specilal case to ToolbarButton, since then the name semantics would be confusing. 

What do you think?

**Comment by zblesk** [comment]
It just occurred to me that the notebook info would also be interesting when browsing tags. Added.

**Comment by laurent22** [comment]
Sorry to be picky but I'm not a fan of the ToolboxLabel component as it's essentially a duplicate of ToolboxButton. Instead, how about adding a "disabled" property to ToolboxButton button and, if it's true, the button won't be clickable and won't have hover state? That will reduce the amount of duplicate code and make long term maintenance easier.

Also could the label be something like "In: <notebook name>" (in your example "In: coding") to make it a bit clearer what it is?

**Comment by zblesk** [comment]
Sure.

**Comment by zblesk** [comment]
Okay, done as you asked. If code deduplication is a higher priority than class name semantics, that's reasonable. 
Since the button already has a 'disabled' option, I've just used that one for now. 
Any more suggestions?

**Comment by laurent22** [comment]
That looks good thanks. Code deduplication is indeed higher priority as it keeps things simple over time. Ideally we could have refactored a bit by having for example ToolbarButton and ToolbarLabel share the style, etc. but for now this is fine.

For the translatable strings, they shouldn't be concatenated as in `_("In") + ": " + this.state.folder.title,` but written using the printf syntax `_("In: %s", this.state.folder.title)` so that translators can also change the space before the ":". For example in French it would be `"Dans : %s"` and some languages could have the words in a different order.

Anyway I will merge for now and will fix this later. Thanks for the pull request!

**Pull request merged**
