### PR TITLE
Desktop: Fixes #4697: Prevent Goto anything from changing context

### LINKED ISSUE #4697: Goto Anything jumping away from "All notes" notebook
Selecting a Note by using "Goto Anything" functionality while viewing your notes through "All notes" triggers a Notebook change. 

- This is inconsistent with directly clicking on a note while in the same "All notes" notebook view.
- It loses user's current working context (visible list of all notes).

## Environment
Joplin version: 1.7.11 and earlier.
Platform: Linux (possibly All)

## Expected behavior
Triggering "Goto Anything" and selecting a note shouldn't change Notebook selection if currently focused on "All notes". Selected notebook should remain "All notes".

When viewing all notes, possibly sorted by most recently updated first, jumping through notes via "Goto Anything" shouldn't force the user to click back on "All notes" to regain visibility of full list after navigation.

### PR DESCRIPTION
**Pull request by jalajcodes**
Prevent Goto Anything from changing folders when "All Notes" is selected.

Fixes #4697

### CODE REVIEW

**Comment by laurent22** [comment]
No test units, no explanation why they are missing, and state handling should be done in the reducer.

**Comment by jalajcodes** [comment]
@laurent22  can you please elaborate on what do you mean by handling state in reducer, I am just dispatching the correct action when the condition is met...Is there something wrong with this? 

I couldn't find any tests for this file in the codebase, that's why there are no tests. It is a plugin basically, Should I write test for this plugin from scratch?

**Comment by jalajcodes** [comment]
Oh I see, all the state handling logic should live inside the reducer.

**Comment by laurent22** [comment]
The component logic was already correct - when a note is selected, we want to display that note and open the containing folder. If the All Notes filter is active however we don't want to change that, but that's not specific to Goto Anything as it should apply to every component that does something similar.

It's about application state basically and that's why it should be in the reducer. Patching one component one by one duplicates the business logic all over the codebase and makes it hard to maintain it and test it.

As for the test units, this is what the guidelines says:

> All pull request must have test units. If for some reason it is not possible to add tests, please let us know and explain why. In that case, you'll need to tell us what steps you followed to manually test your changes.

Is there something ambiguous about "please let us know and explain why"?

**Comment by jalajcodes** [comment]
> something ambiguous about "please let us know and explain why"?

Totally my fault, won't happen again. 


Thanks for explaining.

 I'll create another PR soon, ofc after reading the guidelines again.

**Pull request closed without merging**
