### PR TITLE
Create install_ubuntu.sh

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by laurent22** [comment]
I think the `rm -r ~/.joplin` would be a problem if someone only want to update their installation (they won't want to lose their data). I think we only need to delete the .desktop file.

Also should there be a `set -e` on top to stop the script in case of an error somewhere (eg couldn't not retrieve version number, could not download file, etc.).

**Comment by tanrax** [comment]
How do you work `set -e`? Just add that at the beginning?

**Comment by tanrax** [comment]
I was thinking of deleting the folder so that there would be no previous versions. Another option is to rename the file to `joplin.AppImage` without the version. Only that file and the `joplin.desktop` would be deleted.

**Comment by tanrax** [comment]
The folder would no longer be deleted, only the AppImage

**Comment by tanrax** [comment]
I take this opportunity to ask: you want a pull request to integrate it with Homebrew (mac os)?

**Comment by laurent22** [comment]
Thanks for the pull request! As for Homebrew there is already a package for it (I think someone has setup a script to auto-update it)

**Pull request merged**
