### PR TITLE
Desktop: Fixes #8159: Set minimum search/sort bar width

### LINKED ISSUE #8159: Buttons so large they occlude Search
As mentioned in [the forum](https://discourse.joplinapp.org/t/whats-new-in-joplin-2-10/30716/3?u=zblesk), for my sidebar width I get big New Note/To-do buttons and tiny search I can barely see.

image

Laurent asked in the thread above whether I have any custom CSS: No, I don't. 
(Well, technically: yes I did, but only for changing colors and the like. I did try deleting the contents of userchrome.css and restarting the app without styles; the issue persisted without any changes.)

## Environment

Joplin 2.10.18 (prod, win32)

Client ID: bee3eb494cf64baa81d038c29abc497f
Sync Version: 3
Profile Version: 42
Keychain Supported: No

Revision: c67f5fa

Link Graph UI: 1.5.0
Markdown Table: Sortable: 1.2.2
Menu items, Shortcuts, Toolbar icons: 1.1.0
Note Link System: 0.8.0
Note overview: 1.6.0
Outline: 1.5.9
Persistent Editor Layout: 2.2.0
Random note: 1.0.3
Rich Markdown: 0.13.2
Rubi and Furigana: 1.1.0
Simple Backup: 1.2.2
Tagging: 1.0.1
Templates: 2.3.0

## Steps to reproduce

1. Open app

## Describe what you expected to happen

Tiny 'new' buttons, usable search bar width

## Logfile

N/A

### PR DESCRIPTION
**Pull request by rio-codes**
### Problem:
When changing the note list panel to a certain width, the search bar becomes so small that it is unusable before flowing to the next line.

### Solution:
Change the flex-basis CSS property of the first-row search and sort bar to 60%, rather than auto. This ensures that the search bar will never become too small.

### CODE REVIEW

**Comment by rio-codes** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
That's a good start, but it needs to work with all languages, and for example it doesn't with French:

image

**Review by rio-codes — COMMENTED** [review]
fix: account for lang differences

edit - sorry, meant this to be the commit message. I'm changing the flex-basis property to Md since that is already calculated based on word length to account for language differences. I tested it in 6 different languages and it looks to be fine.

**Comment by tomasz1986** [comment]
Can you include a screenshot of how this looks when using a different layout, e.g. note list on top?

**Comment by laurent22** [comment]
Yes please provide a video. I've just spent 10 minutes testing this and I see no differences. As far as I can see "Md" is not even a valid property so your code is ignored and it reverts back to the previous behaviour.

Is this pull request for GSoC or other open source program?

**Comment by rio-codes** [comment]
Yes, I just noticed that Md does not work, I'm so sorry about that. Setting it to 50% rather than 60% seems to do the trick though.

## Issue behavior

issue_behavior

## Fixed behavior - English

fiixed_behavior_english

## Fixed behavior - French

fiixed_behavior_french

I'm sorry you wasted your time testing it, I was in the process of fixing it and recording gifs. I can submit another commit. This is not for any program, I am just new to contributing. Thanks for your patience with me.

**Comment by laurent22** [comment]
No problem, and thanks for recording the videos. It indeed looks better and as long as it looks good on the most common languages (those with higher % of translation) that should be fine.

**Comment by rio-codes** [comment]
I tried it with German, Spanish, French, and a few others. Seems to work fine. I committed and pushed the change just now.

**Comment by rio-codes** [comment]
fixes #8159

**Comment by laurent22** [comment]
Looks like it's working well. Thanks a lot for fixing this @rio-codes!

**Pull request merged**
