### PR TITLE
Mobile: Resolves #8611: Synchronization panel now can be hidden

### LINKED ISSUE #8611: Add a button to hide the synchronisation panel
It should be a button with a down arrow. Clicking on it hides the panel, then the button becomes an "up" arrow. Clicking on it again, will show the panel.

It should be hidden by default.

image

### PR DESCRIPTION
**Pull request by beonma**
Feature #8611 is now implemented, allowing the synchronization view to be collapsible. This enhancement has been successfully tested on Android API 26, although testing on iOS remains pending. Please don't hesitate to inquire further if additional adjustments are deemed necessary.

## Screenshots
Capture
Capture1

### CODE REVIEW

**Comment by beonma** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mybeon** [comment]
recheck

**Comment by mybeon** [comment]
recheck

**Comment by laurent22** [comment]
Sorry this ticket was created to address a regression, but it seems it's no longer necessary, so for now I prefer to close this PR. Thanks anyway for looking into it

**Comment by beonma** [comment]
Thank you for the update! If you have any future issues or questions, please feel free to reach out.

**Pull request closed without merging**
