### PR TITLE
Highlight notebooks based on depth

### PR DESCRIPTION
**Pull request by CalebJohn**
I added the depth color to theme.js with the anticipation that in the future there will be more (potentially more colorfull) themes.

Example
image
image

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for looking into it! For info the original post is there: https://discourse.joplinapp.org/t/theme-request-subnotebook-shading/1596/4

I think the way you did it is fine but I'd limit to three levels of shading (one colour for the root, then two more for two levels down) as otherwise it might look a bit busy and we'll run out of colours anyway.

On the dark theme, I think we need to make the currently selected notebook a different colour, maybe some blueish colour so that it's still visible among the other grey colours.

**Comment by CalebJohn** [comment]
I've updated based on your suggestions. Take a look.
image

image

**Comment by CalebJohn** [comment]
Just a thought, should we make this toggle-able in the settings? There are always a few users that hate visual changes.

**Comment by laurent22** [comment]
Looks good, thanks @CalebJohn! For now, let's not make it toggle-able and we'll see what feedback we get.

**Comment by v-marinkov** [comment]
Hi, I just updated to 1.1.4 and noticed the hierarchical highlights are gone. Was this intentional and why? How can I bring them back?

**Comment by CalebJohn** [comment]
Hi @v-marinkov , The highlights were removed based on community feedback. Fortunately we left the css classes responsible for styling in so you restore the behaviour with a userchrome.css file. You can see my instructions [here](https://github.com/laurent22/joplin/issues/3767#issuecomment-696404246)

**Comment by v-marinkov** [comment]
Thanks @CalebJohn, it seems like a neat solution.

**Pull request merged**
