### PR TITLE
All: Translation: Update zh_CN.po and zh_TW.po

### PR DESCRIPTION
**Pull request by HOLLYwyh**
zh_CN.po ---Correct a translation error and optimize some expressions
zh_TW.po ---Add some translations , correct some errors, optimize some translations

### CODE REVIEW

**Comment by tessus** [comment]
Thanks for the update.

Don't those 2 locales use different writing? Simplified vs Traditional?

**Comment by HOLLYwyh** [comment]
> Thanks for the update.
> 
> Don't those 2 locales use different writing? Simplified vs Traditional?

zh_CN uses Simplified  Chinese and zh_TW uses Traditional Chinese

**Comment by tessus** [comment]
Ok, let me re-phrase. It is rather unusual that someone works on both locales.

Take the German they speak in Germany and the one they speak in Austria. They use different words, even within the respective countries. French in France and here in Canada. English in Canada and the US. There are terms that mean the exact opposite (e.g. "to table a discussion").

What I wanted to ask is, whether you are sure that the translations for both are correct. I'm sorry if this is an unfair question, but it's the first time you are submitting a translation.

**Comment by HOLLYwyh** [comment]
I'm sure that the translations are correct. Different from English in Canada and US, simplified Chinese and troditional Chinese are both in China,maybe like French and English in Canada. The words in zh_CN and zh_TW are just written differently,but they always have the same meanings. As a chinese person, I think I translate them correctly.

**Comment by tessus** [comment]
Thank you.

**Pull request merged**
