### PR TITLE
Desktop: Resolves #4827,#5652: Fix and improve laggy scroll fix

### LINKED ISSUE #4827: Laggy Scrolling in Viewer
Scrolling through the Markdown viewer is quite laggy and not as smooth as it should be.

https://user-images.githubusercontent.com/78950242/114266474-31c5c480-9a14-11eb-876c-4a397f3f2f3d.mp4

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Linux Mint 19.3, AppImage

## Steps to reproduce

1. Open a note. 
2. Scroll through the note with the _Viewer_.

## Describe what you expected to happen
Scrolling should be smooth and seamless without 'breaking' in the middle.

### PR DESCRIPTION
**Pull request by ken1kob**
This PR fixes and improves the previous PR #5496 on the issue [#4827 "Laggy Scrolling in Viewer"](https://github.com/laurent22/joplin/issues/4827#issuecomment-925593345).

Bug Fix:
- In the previous PR, page-wise wheel scrolling was not supported. It can be configured in OS setting (ex. in Win10, at Control Panel > Mouse > Wheel > Vertical > Vertical Scrolling, select `One screen at a time`). If it was set, scrolling was very slow.
- This PR fix the bug.

Improvements:
- Since workaround for laggy scroll is only needed if zoom factor is not 1, native scroll functionality (including smooth scrolling) is used when zoom factor is 1, for safety.
- For non-1 zoom factor, compact and standalone custom smooth scrolling is implemented, for user's comfort.

By integrating this PR, user's UX is the same with before when laggy scroll does not occur (zoomFactor == 1). And, user's UX is almost the same with non-laggy scroll at the case that laggy scroll had occurred (zoomFactor != 1).

### CODE REVIEW

**Comment by ken1kob** [comment]
> I feel it's getting out of hand in terms of custom code that needs to be added to simulate something as simple as scrolling.

I had the same concern as you. So, I prepared one option in this PR. Before explaining it, I'll answer your questions.

> And is there an upstream bug?

[As I stated in the issue #4827](https://github.com/laurent22/joplin/issues/4827#issuecomment-925593345), there are many relevant issues in Chromium. One of them is [890345 - Can't set scrollTop value precisely if zoom setting is not 100% - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=890345&q=zoom%20%20%20scrolltop&can=2).

As stated in the Chromium issue, Chromium dev team doesn't think it is important, and it wouldn't be fixed near future.

> If it affects all Electron apps perhaps there's a library we can use to fix this? Or just some generally accepted fix?

Let me conclude first. I can find nothing.

Chromium dev team thinks the bug is minor, and it does not actually have a large impact on other projects. Because most of popular projects use a reliable underlying library (such as CodeMirror and TinyMCE) having independent scrolling capability and are free from the bug. It is a rare case that such a large project like Joplin uses a bare scrolling feature of Electron as it is.

When I searched small solutions and fixes specific to the bug before, I couldn't find them.

Though there are some smooth scrolling libraries (ex. [10 Best Smooth Scroll Libraries In Pure JavaScript (2021 Update) - CSS Script](https://www.cssscript.com/10-best-smooth-scroll-javascript-plugins/)), they are too rich and over-featured. I think you want to keep note-viewer/index.html compact, so these fat ones might be inappropriate.

Therefore, If smooth scrolling is needed, implementing the code by ourselves is only the way, I think. The code I wrote in the PR is compact, standalone and free from any copyright problems.

**Comment by ken1kob** [comment]
Then, I'll talk about the option in this PR. If you think smooth scrolling is not needed, it can be easily disabled or removed.

The smooth scrolling provided in the PR can be disabled by simply changing the code  `customScroll(e, true)` to  `customScroll(e, false)`. You can easily try them and look at the difference between with-smooth-scroll and without-smooth-scroll. I think you will find it comfortable to have a consistent UX in all situations. I would like to hear various opinions from many people on this matter.

I summarize the effects of this PR(#5606) and the previous PR(#5496) here. 

|PR|Laggy scroll|Smooth scroll (zoomFactor==1)|Smooth scroll (zoomFactor!=1)|Page-wise wheel scroll support|
|:-:|:-:|:-:|:-:|:-:|
|-|**OCCURS**|yes|yes, but **LAGGY**|yes|
|#5496|resolved|**NO**|**NO**|**NO**|
|#5606|resolved|yes|yes|yes|
|#5606 without smooth scroll|resolved|yes|**NO**|yes|

@laurent22, you have three options: 1) not take this PR, 2) take it with smooth scroll, and 3) take it without smooth scroll.

**Comment by ken1kob** [comment]
The commit c4d1c27 supports horizontal scrolling and fixes #5652, which happens because the previous PR #5496 only supports vertical scrolling.

**Comment by laurent22** [comment]
Thanks for clarifying @ken1kob. I guess it bothers me that in 2021 we need some much custom code to simply scroll a view, like you'd think that would be a solved problem by now. But it is what it is, and your code is indeed quite self-contained.

I think we can merge then but would you mind just adding a comment above your code block to explain in particular the variables "zoomFactorIsNotOne" and "remainedXx"? And a short description of the function below (and add a link to here for more info).

**Comment by ken1kob** [comment]
> I think we can merge then but would you mind just adding a comment above your code block to explain in particular the variables "zoomFactorIsNotOne" and "remainedXx"? And a short description of the function below (and add a link to here for more info).

Finished.

**Comment by laurent22** [comment]
Thanks @ken1kob, we can merge then.

**Pull request merged**
