### PR TITLE
Fixed the mermaid graph width 

### LINKED ISSUE #3109: Desktop : Mermaid Diagram background not rendering properly (Dark Themes)
## Environment

Joplin version: 1.0.201
Platform: Desktop
OS specifics: macOS

## Steps to reproduce

1. Switch to any dark theme (i.e. Dark, Solarised Dark, Dracula, Node, Aritim Dark)
2.  Write the below lines in the note body 
```
```mermaid

graph TB;
    Kombinatorik-->Alle;
    Alle-->leer1-->id1[Mit Wiederholung ja]--- id11([F1]):::fuellungrot;
    Alle-->leer2-->id4[Mit Wiederholung nein]--- id12([F2]):::fuellungrot;
    
    Kombinatorik-->Auswahl;
    Auswahl-->id7[Reihenfolge wichtig ja];
    Auswahl-->id8[Reihenfolge wichtig nein];
    id7[Reihenfolge wichtig ja]-->id2[Mit Wiederholung ja] --- id13([F3]):::fuellungrot;
    classDef fuellungrot fill:#f96;
    id7[Reihenfolge wichtig ja]-->id5[Mit Wiederholung nein]--- id14([F4]):::fuellungrot;
    id8[Reihenfolge wichtig nein]-->id3[Mit Wiederholung ja]--- id15([F5]):::fuellungrot;
    id8[Reihenfolge wichtig nein]-->id6[Mit Wiederholung nein]--- id16([F6]):::fuellungrot;
    
```
2. Now scroll the rendered mermaid graph horizontally.

## Describe what you expected to happen
The whole background of graph should be of similar colour instead.

## GIF of issue
Screen-Recording-2020-04-21-at-4

### PR DESCRIPTION
**Pull request by Rahulm2310**
Fixes #3109 

**Before changes:**

memaidissue

**After changes:**

mermaidwidthsolve

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@PackElend label me please

**Comment by laurent22** [comment]
The graph appearance have changed though - now there's a lot of white space within each box. I don't know what's the fix for this, but we can't merge it as it is.

**Comment by Rahulm2310** [comment]
Ok I will try to fix the white spacing

**Comment by laurent22** [comment]
Thanks @Rahulm2310, your fix makes sense.

**Pull request merged**
