### PR TITLE
Server: Remove node user and install gosu

### PR DESCRIPTION
**Pull request by ifurther**
Setting up storage using binding volume had error for permission denied because the joplin user is noraml user.
This request removes node user, and add entrypoint script to read environment value which is `USER_UID` and ` USER_GID ` and change the user ` joplin` uid/gid.  The script can read [the page](https://github.com/laurent22/joplin/tree/dev/packages/server#setting-up-storage-on-a-new-installation) setting value `Path`, and change the binding volume owner.

If using the joplin/server:latest contianer and binding volume, it could show this error.
擷取
I used it in docker compose, and setting volume.
`        volumes:            
            - ./joplin-data:/home/joplin/data
`

### CODE REVIEW

**Comment by laurent22** [comment]
I mean with so many changes we need more than one line of explanation.

**Comment by tessus** [comment]
Can you please explain in a few sentences why you are doing this change? What is the advantage over the current implemention.

**Comment by tessus** [comment]
@ifurther ^^^

**Comment by laurent22** [comment]
@ifurther, I think the keyword you missed in tessus' answer is "why". You've described "what" your change does, but not **why** it's needed. What problem does it solve, etc. We need to know that before we can consider your changes.

**Comment by ifurther** [comment]
Using the setting binding volume having error for permission denied, so the request should try resolve this

**Comment by tessus** [comment]
I am still not entirely sure I understand. So....

1. Does it run without issues when you run it as your supposed to?
2. Why do you want to run it differently, when what is provided works?

**Comment by ifurther** [comment]
>     1. Does it run without issues when you run it as your supposed to?
Yes, it dose run correctly, and it can write in binding volume.
>     2. Why do you want to run it differently, when what is provided works?
The joplin is non privileged user, so the node can't write data in binding volume. The entrypoint is running using root user to change joplin uid and gid to read binding data.

**Comment by ifurther** [comment]
@tessus If I ran the joplin/server, it has this error
擷取

**Comment by laurent22** [comment]
Sorry I will have to close this pull request for now, since I don't think anybody quite understand what it does. And we can't have code that's not understood in such a critical part of the server, if only for security reasons.

**Pull request closed without merging**
