### PR TITLE
Show geolocation info on save

### PR DESCRIPTION
**Pull request by marcosvega91**
I fix the issue that not shown geolocation info when the user saved a new note.
I have added <code>await</code> to <code>updateGeolocation</code> and then I've set the note object to state

### CODE REVIEW

**Comment by laurent22** [comment]
Hi, the reason there was no `await` on `Note.updateGeolocation` is because I want it to happen in the background (it can be very slow if there's no network or the GPS doesn't work well).

In theory it should update the geolocation and then call `Note.save`, which should update the state (via `NOTE_UPDATE_ONE`), including the UI.

If it's not happening, there might be a bug somewhere in the reducer or elsewhere (maybe the view that displays the metadata is not properly connected to the state), which is what we should try to fix.

**Comment by marcosvega91** [comment]
Yes, you're right. The problem is that <code> NOTE_UPDATE_ONE</code> reducer doesn't update any state parameter that is injected into the note screen, so when you call <code>updateGeolocation</code> the UI will not refresh

**Comment by marcosvega91** [comment]
To solve the problem I want to add the method below and call it instead of `Note.updateGeolocation`. What do you think?

```javascript
shared.updateGeolocation= async function(id,comp){
	const note=await Note.updateGeolocation(id);
	const stateNote = comp.state.note;
	if(note){
		stateNote.latitude=note.latitude;
		stateNote.longitude=note.longitude;
		comp.setState({
			lastSavedNote: Object.assign({}, note),
			note: note,
		});
		comp.refreshNoteMetadata();
	}

}
```

**Comment by laurent22** [comment]
That looks like the right approach, though I'll need to double-check since I think it's code shared by the desktop and mobile app

**Comment by laurent22** [comment]
I've ended up implementing this in a slightly different way in this commit - https://github.com/laurent22/joplin/commit/138ad9fcadc9203c1b5ddbdbf498bbcbd941f421

**Pull request closed without merging**
