### PR TITLE
change geolocation service to freegeoip.app

### LINKED ISSUE #2469: find a good geolocation service (https)
Joplin curently uses ip-api.com (80) as the geolocation service. Additionally it uses api.ipify.org (443) to retrieve the IP address, which is then fed into ip-api.com (80).

There were reports that the geolocation service does not always provide accurate results.

This change involves 2 parts:

- use a more accurate API, which is free and uses https
- maybe get rid of the separate request to api.ipify.org (443)

The files involved are:

```
ReactNativeClient/lib/geolocation-node.js
ReactNativeClient/lib/net-utils.js
ReactNativeClient/lib/shim.js
```

### PR DESCRIPTION
**Pull request by tessus**
Change geo-location service to `freegeoip.app` (https).

removed unnecessary request to `api.ipify.org`

closes #2469

### CODE REVIEW

**Comment by laurent22** [comment]
I feel the extra setting is not really necessary. If freegeoip.app is secure and works well can we simply switch to it, without the settings?

**Comment by tessus** [comment]
Hmm, yes and no. If I could be sure that freegeoip.app was as accurate as the other one, I would agree. The problem is that I just don't know. I can't go for a 72h drive to South America and check its accuracy. ;-) Until we can be sure, we should have the option. If after a while people don't complain, we can remove the old one. But it's up to you.

**Comment by tessus** [comment]
@laurent22 Please let me know how to proceed. I'm ok with removing the options or make them not public. The fact is that we don't really know how accurate the new provider is, so my initial thought was to provide users a choice in case they are not happy with it.

**Comment by laurent22** [comment]
If there's a problem with the new provider, it's still a problem whether it's optional or not. If we're reasonably confident it's better than the previous one, then let's use it (with no option, hidden or not). And if we get any feedback about it in the forum, we can always change it.

**Comment by tessus** [comment]
Ok, I'll make the option hidden... At least for now, thus we'll have an easier way to deal with new providers in the future.
I can always delete the option code later.

**Comment by tessus** [comment]
Done and tested.

**Comment by laurent22** [comment]
Sorry I should have been clearer. I meant I don't want an option because once an option is added, there's no mechanism to remove it (so everybody will have it, forever, even though it's not really used).

So if you could simply hardcode whatever URL is best that would be great. And if it turns out there are problems with it, we can change it later on.

**Comment by tessus** [comment]
Ok, will do when I'm home

**Comment by tessus** [comment]
Done.

**Comment by laurent22** [comment]
Perfect, thank you!

**Pull request merged**
