### PR TITLE
Mobile: Fixed notebook text overflow

### LINKED ISSUE #2875: Mobile: If the title of the notebook is too big, the note-list screen misbehaves.
On mobile, When I use too big a title for notebooks or paste a very big text by mistake, I see this screen and there is no button to go back and delete it. Even when the app restarts, this screen is there. So, there should be a limit to the title of the notebook.

Screenshot_1584988959

### PR DESCRIPTION
**Pull request by ishantgupta777**
closes #2875 
I fixed the issue and now only the limited characters of the title are shown, which is the ideal case.
@PackElend  please label my PR.
Screenshot_1584993002

### CODE REVIEW

**Comment by laurent22** [comment]
Can you post a screenshot of before/after? I think a hard limit of 100 character (or any hard limit) is not so good, especially on tablet. Before I believe the title was simply cropped which seems like a better solution. Or if you can find a way to display "...", but only at the place where the text would be cropped.

**Comment by ishantgupta777** [comment]
> Can you post a screenshot of before/after? I think a hard limit of 100 character (or any hard limit) is not so good, especially on tablet. Before I believe the title was simply cropped which seems like a better solution. Or if you can find a way to display "...", but only at the place where the text would be cropped.

Sir, I am sorry  to say but before, nothing was cropped and navbar would increase to take the full width, These are some screenshots of before. 
Before:
Screenshot_1584988894

**Comment by laurent22** [comment]
As for the note title PR, could you limit the folder title to one line max? And add ellipsis for any truncated text?

**Comment by ishantgupta777** [comment]
> As for the note title PR, could you limit the folder title to one line max? And add ellipsis for any truncated text?

Done Sir. Some screenshots in mobile and tablets:
Screenshot_1585165307
Screenshot_1585164609

**Comment by laurent22** [comment]
Thanks for looking into it, but it seems a bit imprecise as a title like "mmmmmm" might overflow while a title like "iiiiii" would be truncated too early. The Text component as an ellipsizemode prop, did you look at it? https://reactnative.dev/docs/text#ellipsizemode

**Comment by ishantgupta777** [comment]
> Thanks for looking into it, but it seems a bit imprecise as a title like "mmmmmm" might overflow while a title like "iiiiii" would be truncated too early. The Text component as an ellipsizemode prop, did you look at it? https://reactnative.dev/docs/text#ellipsizemode

Thanks Sir, that's a really great way of handling this. I will fix this will these changes.

**Comment by ishantgupta777** [comment]
Done Sir, Please have a look. I specified number of lines and It worked, and regarding that ... (three dots) in the end, It automatically added in the end. You can see in the screenshot. But if you want I can still specify ellipsizemod. 
Screenshot_1586783651

**Comment by laurent22** [comment]
That looks good, thanks @ishantgupta777!

**Pull request merged**
