### PR TITLE
All: Translation: Add Finnish fi_FI.po

### PR DESCRIPTION
**Pull request by mrkaato**

### CODE REVIEW

**Comment by laurent22** [comment]
Is that the Finnish translation?

**Comment by mrkaato** [comment]
Yes, this is a Finnish translation.

**Comment by tessus** [comment]
That's great.

@laurent22 I can move it to the correct location, but since I'm still using gettext <0.22 I can't do any test or build the translations.

**Comment by laurent22** [comment]
@tessus, that's fine, for now let's merge the translations anyway unless there's some obvious mistake with them (or a translation-related error in CI). Later, I will run the build-translation tool from my Mac as it has the latest version of gettext. By the way, test units are getting more stable so hopefully the CI will be more useful to know about translation errors.

**Comment by laurent22** [comment]
Thanks for the translation @mrkaato!

**Comment by tessus** [comment]
@laurent22 thanks for running the translation script for now. Btw, I tried to run the tests locally and I always get errors. I haven't had a clean test run yet. But splitting them into smaller groups will help.

**Comment by laurent22** [comment]
Yes the tests have been troublesome lately but it's getting better. We had the first successful dev commit the other day, but looks it's back to not working due to a timeout issue. What errors did you get locally?

**Comment by tessus** [comment]
e.g.

```
$ npm run test

> joplin@1.5.0 test /Users/tessus/data/work/joplin/packages/app-cli
> jest --config=jest.config.js --bail --forceExit

 PASS  tests/services_InteropService_Exporter_Md.js (11.317 s)
 PASS  tests/models_Note.js (13.103 s)
 FAIL  tests/services_InteropService.js (13.735 s)
  ● services_InteropService › should export and import tags

    Cannot find "/Users/tessus/data/work/joplin/packages/app-cli/tests/export/test.jex".

      273 |
      274 | 	async import(options: ImportOptions): Promise<ImportExportResult> {
    > 275 | 		if (!(await shim.fsDriver().exists(options.path))) throw new Error(_('Cannot find "%s".', options.path));
          | 		                                                         ^
      276 |
      277 | 		options = {
      278 | 			format: 'auto',

      at InteropService.<anonymous> (../lib/services/interop/InteropService.ts:275:60)
      at fulfilled (../lib/services/interop/InteropService.js:13:24)

Summary of all failing tests
 FAIL  tests/services_InteropService.js (13.735 s)
  ● services_InteropService › should export and import tags

    Cannot find "/Users/tessus/data/work/joplin/packages/app-cli/tests/export/test.jex".

      273 |
      274 | 	async import(options: ImportOptions): Promise<ImportExportResult> {
    > 275 | 		if (!(await shim.fsDriver().exists(options.path))) throw new Error(_('Cannot find "%s".', options.path));
          | 		                                                         ^
      276 |
      277 | 		options = {
      278 | 			format: 'auto',

      at InteropService.<anonymous> (../lib/services/interop/InteropService.ts:275:60)
      at fulfilled (../lib/services/interop/InteropService.js:13:24)


Test Suites: 1 failed, 2 passed, 3 of 58 total
Tests:       1 failed, 38 passed, 39 total
Snapshots:   0 total
Time:        14.198 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! joplin@1.5.0 test: `jest --config=jest.config.js --bail --forceExit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the joplin@1.5.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tessus/.npm/_logs/2020-12-02T20_47_46_628Z-debug.log
```

the second time I get more passed tests, but still fails:

```
$ npm run test

> joplin@1.5.0 test /Users/tessus/data/work/joplin/packages/app-cli
> jest --config=jest.config.js --bail --forceExit

 PASS  tests/services_InteropService_Exporter_Md.js (9.569 s)
 PASS  tests/models_Note.js (11.339 s)
 PASS  tests/services_InteropService.js (12.029 s)
 PASS  tests/services_KeymapService.js
 PASS  tests/services_SearchEngine.js (13.985 s)
 PASS  tests/Synchronizer.e2ee.js (14.618 s)
 PASS  tests/reducer.js (16.071 s)
 PASS  tests/Synchronizer.resources.js (16.641 s)
 PASS  tests/services_Revision.js (17.419 s)
 PASS  tests/models_Folder.js (5.497 s)
 PASS  tests/services_rest_Api.js (18.699 s)
 PASS  tests/services_PluginService.js
 PASS  tests/Synchronizer.basics.js (19.637 s)
 PASS  tests/services_CommandService.js
 PASS  tests/services_EncryptionService.js (6.087 s)
 FAIL  tests/services_SearchFilter.js (20.681 s)
  ● services_SearchFilter › should support filtering by created date

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      358 |
      359 | 		rows = await engine.search('created:20200520');
    > 360 | 		expect(rows.length).toBe(1);
          | 		                    ^
      361 | 		expect(ids(rows)).toContain(n1.id);
      362 |
      363 | 		rows = await engine.search('created:20200519');

      at Object.<anonymous> (tests/services_SearchFilter.js:360:23)

  ● services_SearchFilter › should support filtering by between two dates

    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

      382 |
      383 | 		rows = await engine.search('created:20200101 -created:20200220');
    > 384 | 		expect(rows.length).toBe(2);
          | 		                    ^
      385 | 		expect(ids(rows)).toContain(n1.id);
      386 | 		expect(ids(rows)).toContain(n2.id);
      387 |

      at Object.<anonymous> (tests/services_SearchFilter.js:384:23)

  ● services_SearchFilter › should support filtering by updated date

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      500 |
      501 | 		rows = await engine.search('updated:20200520');
    > 502 | 		expect(rows.length).toBe(1);
          | 		                    ^
      503 | 		expect(ids(rows)).toContain(n1.id);
      504 |
      505 | 		rows = await engine.search('updated:20200519');

      at Object.<anonymous> (tests/services_SearchFilter.js:502:23)
          at runMicrotasks (<anonymous>)

Summary of all failing tests
 FAIL  tests/services_SearchFilter.js (20.681 s)
  ● services_SearchFilter › should support filtering by created date

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      358 |
      359 | 		rows = await engine.search('created:20200520');
    > 360 | 		expect(rows.length).toBe(1);
          | 		                    ^
      361 | 		expect(ids(rows)).toContain(n1.id);
      362 |
      363 | 		rows = await engine.search('created:20200519');

      at Object.<anonymous> (tests/services_SearchFilter.js:360:23)

  ● services_SearchFilter › should support filtering by between two dates

    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

      382 |
      383 | 		rows = await engine.search('created:20200101 -created:20200220');
    > 384 | 		expect(rows.length).toBe(2);
          | 		                    ^
      385 | 		expect(ids(rows)).toContain(n1.id);
      386 | 		expect(ids(rows)).toContain(n2.id);
      387 |

      at Object.<anonymous> (tests/services_SearchFilter.js:384:23)

  ● services_SearchFilter › should support filtering by updated date

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      500 |
      501 | 		rows = await engine.search('updated:20200520');
    > 502 | 		expect(rows.length).toBe(1);
          | 		                    ^
      503 | 		expect(ids(rows)).toContain(n1.id);
      504 |
      505 | 		rows = await engine.search('updated:20200519');

      at Object.<anonymous> (tests/services_SearchFilter.js:502:23)
          at runMicrotasks (<anonymous>)


Test Suites: 1 failed, 15 passed, 16 of 58 total
Tests:       3 failed, 254 passed, 257 total
Snapshots:   0 total
Time:        21.298 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! joplin@1.5.0 test: `jest --config=jest.config.js --bail --forceExit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the joplin@1.5.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tessus/.npm/_logs/2020-12-02T20_48_56_991Z-debug.log
```

I never had a clean run.

**Comment by laurent22** [comment]
Hmm, yes I can't make sense of these test errors and they don't happen for me.

**Comment by tessus** [comment]
Unfortunateklt they also happen in the CI pipeline: https://travis-ci.org/github/laurent22/joplin/jobs/747942378

**Pull request merged**
