### PR TITLE
Desktop: fixes long lines warpped

### PR DESCRIPTION
**Pull request by amitsin6h**
**"Desktop" for the Windows/macOS/Linux app (Electron app)**
- This change allows warping long lines in the view area of note editor.
- Reference of the issue #2170

### CODE REVIEW

**Comment by amitsin6h** [comment]
@PackElend @tessus please review this updated PR

**Comment by PackElend** [comment]
I'm on mobile but I see only a single line added:question:
Moreover Travis failed, not to be resolved before PR

**Comment by amitsin6h** [comment]
@PackElend adding the `word-wrap: break-word;` fixes the issue of long lines wrap

**Comment by PackElend** [comment]
OK
But Travis CI failed???

sent from a fair mobile

**Comment by amitsin6h** [comment]
@PackElend I don't why it happened, due think is there something wrong?

**Comment by PackElend** [comment]
I cannot check I'm on the move.
I use only FastHub to check the PR history and that does not tell me that
much, Uou have to check it yourself

sent from a fair mobile

**Comment by tessus** [comment]
The Travis CI error has nothing to do with your PR:

```
/Users/travis/build/laurent22/joplin/CliClient/tests/models_Note.js

  120:53  error  A space is required before '}'  object-curly-spacing

/Users/travis/build/laurent22/joplin/ElectronClient/app/ElectronAppWrapper.js

  127:1  error  Trailing spaces not allowed  no-trailing-spaces
```

@laurent22 how is this possible? shouldn't the linter only check the staged files?

**Comment by laurent22** [comment]
I don't know, but it looks good so let's merge. Thanks @amitsin6h!

**Comment by amitsin6h** [comment]
Thanks :+1:

**Comment by amitsin6h** [comment]
@PackElend label me, please

**Pull request merged**
