### PR TITLE
Doc: Fix typo in docs

### PR DESCRIPTION
**Pull request by luzpaz**
Fixes a typo in the source comment texts.

### CODE REVIEW

**Comment by laurent22** [comment]
Those files are dynamically generated

**Comment by laurent22** [comment]
And we don't participate in Hacktoberfest

**Comment by luzpaz** [comment]
This isn't hacktoberfest related.

**Comment by laurent22** [comment]
Ok, in any case fixing this typo requires digging in the build process to see where the source is, so it is more work than is worth doing, but thanks anyway for giving it a try.

**Pull request closed without merging**
