### PR TITLE
Desktop: Fixed the 'Edit in external editor' menu item

### LINKED ISSUE #2762: When the editor is in Viewer mode, enable "Open in external editor" menu item
This item was recently disabled in a pull request, but it should always be enabled in all views.

Forum thread: https://discourse.joplinapp.org/t/external-editor-shortcut-available-in-any-layout-view-mode/6958?u=laurent

### PR DESCRIPTION
**Pull request by Rahulm2310**
Because the implementation is so sloppy it sometimes works, sometimes doesn't. For example if you go to the setting, then back to the notes, "Edit in External Editor" is enabled. If you toggle between notes however it is disabled.
This PR enables the "Edit in external editor" menu item in all modes.

Before:
pr3-1

After:
pr3-2

fixes #2762

### CODE REVIEW

**Comment by laurent22** [comment]
Ok let's merge this. I think the whole logic should be rewritten but at least external editing would work now.

**Comment by laurent22** [comment]
Actually there are test unit errors. Could you rebase on latest master please?

**Comment by Rahulm2310** [comment]
Ok great!

**Comment by Rahulm2310** [comment]
After rebasing on latest master, should I push it to master ?

**Comment by tessus** [comment]
I think the implementation in #2765 is cleaner.

**Comment by Rahulm2310** [comment]
@laurent22 PR is fixed and ready to be merged.

**Comment by tessus** [comment]
I'm still not sure, why the change needs a few lines, while all that is needed is to remove one item from an array.

**Comment by laurent22** [comment]
I'm going to close the pull requests related to this issue. My plan is to rollback the pull request that introduced the bug, then at a later time I'll need to look at all this properly. Right now, I have no idea what's the correct way to implement this.

**Pull request closed without merging**
