### PR TITLE
API: Fixes #4575: Set the value of filename while creating a resource

### LINKED ISSUE #4575: resource api get filename is empty
image

image

## Environment

Joplin version: 1.7.11 dev win32
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Open Joplin Clipper Service
2. Use Data api to get information about a single resource
3. See that the `filename` obtained is an empty string

## Describe what you expected to happen

Get the filename of the attachment resource correctly

### PR DESCRIPTION
**Pull request by nishantwrp**
Fixes #4575.

### CODE REVIEW

**Comment by nishantwrp** [comment]
I had one doubt, I did set the value of `filename` but I couldn't see any place where the filename property is used. Is this field 
actually required in the database?

**Comment by roman-r-m** [comment]
> I had one doubt, I did set the value of `filename` but I couldn't see any place where the filename property is used. Is this field
> actually required in the database?

I distinctly remember using it in the mobile app when showing long-press menu but went to check and found it's `file_name`, not `filename`. Was there a bug all along? I'll check.

**Comment by roman-r-m** [comment]
Please take a look a the comments in the related issue. I think it's not entirely clear what the result should be here. At least it's obvious that what you have right now is not what @rxliuli had in mind when raising the issue.

**Comment by laurent22** [comment]
@roman-r-m, should we close this pull request then? I wonder if we should get rid of the "filename" resource field because as far as I can see it's never used. Its value is either empty or the same as the resource title.

**Comment by roman-r-m** [comment]
> I wonder if we should get rid of the "filename" resource field because as far as I can see it's never used. Its value is either empty or the same as the resource title.

Yes, I think it does make sense. In theory a resource could have a separate title, similar to this in HTML:
```
 <a href="file://<resource name here>">Resource Title</a> 
```
but in practice it's not used. So probably best to remove to avoid confusion.

**Comment by nishantwrp** [comment]
Oh okay. Removing that field looks a good option. Can I try to do that?

**Pull request closed without merging**
