### PR TITLE
Desktop: Added dracula theme

### PR DESCRIPTION
**Pull request by domgoodwin**
To expand the themes available and since brace supports it I thought I'd add the dracula theme to the editor, from: https://draculatheme.com/

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks. Would it be possible to see a screenshot of it?

**Comment by domgoodwin** [comment]
Sure. I tried to map up other dracula editor themes with this one as much as possible. Only one I couldn't change is the one that comes from the brace package `require('brace/theme/dracula');`
Happy to update any of the colours as needed.

Screenshot 2019-10-01 at 09 43 47

**Comment by laurent22** [comment]
Thanks, that looks good. Could you remove package-lock.json from the pull request please? And then we're good to merge.

**Comment by domgoodwin** [comment]
@laurent22  That's been done now, thanks

**Comment by laurent22** [comment]
Brilliant, thanks @domgoodwin!

**Pull request merged**
