### PR TITLE
CLI: Fixes #4808: Fixed spacebar turning non-todo note into todo

### LINKED ISSUE #4808: Note converts to todo note when toggling complete/incomplete
Note converts to todo note when toggling complete/incomplete.

## Environment

Joplin version: joplin 1.7.0
Platform: Linux terminal
OS specifics: Manjaro

## Steps to reproduce

1. Select non-todo note
2. press space bar
3. 

## Describe what you expected to happen
Either no action, since the note is not a todo list, or for multiple presses of the spacebar to convert it back into the non-todo note.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6253431/log.txt)

### PR DESCRIPTION
**Pull request by axtyax**
Fixes #4808.

### Changes
Simply removes logic in `command-todo.js` which sets `node.is_todo` to true if executed on a non-todo note.

### CODE REVIEW

**Comment by laurent22** [comment]
CI is failing

**Comment by lkiThakur** [comment]
> Simply removes logic in `command-todo.js`

also consider viewing/changing the [command description](https://github.com/laurent22/joplin/blob/30fab85caa5b6462cd096a63508ecc168ff99bf5/packages/app-cli/app/command-todo.js#L14)
ps:I'm sorry if i was not supposed to comment here

**Comment by axtyax** [comment]
> > Simply removes logic in `command-todo.js`
> 
> also consider viewing/changing the [command description](https://github.com/laurent22/joplin/blob/30fab85caa5b6462cd096a63508ecc168ff99bf5/packages/app-cli/app/command-todo.js#L14)
> ps:I'm sorry if i was not supposed to comment here

Thanks for letting me know, will do.


> CI is failing

I'm looking into it, I'll look into writing a (or modifying an existing) unit test.

**Comment by tessus** [comment]
I think there's a problem.

You just removed the possibility to convert a note to a todo.

**Comment by laurent22** [comment]
Hmm, yes I missed that. I think it's not good that pressing space change a note into a to-do, however the behaviour of the "todo" is fine and should not be changed. I think we're going to leave it as it is then, as I can't think of a simple way to make the space bar do something, and the "todo" command do something else.

**Comment by laurent22** [comment]
Hmm, yes I missed that. I think it's not good that pressing space change a note into a to-do, however the behaviour of the "todo" is fine and should not be changed. I think we're going to leave it as it is then, as I can't think of a simple way to make the space bar do something, and the "todo" command do something else.

**Comment by axtyax** [comment]
I see where you're coming from. I just remember using the Cli for the first time and not understanding why my notes were becoming todo and I couldn't switch them back.

**Comment by tessus** [comment]
@laurent22 can you point me to the code where hitting space is calling the todo command? Maybe I get an epiphany.

**Comment by laurent22** [comment]
I just had a quick look but can't even find it. I would assume it calls the "todo" command somewhere when pressing "space".

**Comment by tessus** [comment]
No worries. Thanks for looking. I'll find it eventually.

**Comment by lkiThakur** [comment]
> @laurent22 can you point me to the code where hitting space is calling the todo command? Maybe I get an epiphany.

May be  [this](https://github.com/laurent22/joplin/blob/f62bfbb85361ab21cb8df3cd7e3913f98de5cf57/packages/app-cli/app/app.js#L331) is the line

**Pull request closed without merging**
