### PR TITLE
Docs: GSoC 2022 - Add settings sync idea

### PR DESCRIPTION
**Pull request by Daeraxa**
Add settings sync idea to GSoC ideas - discussed previously:

> The plugin ecosystem at this point is starting to become fairly essential to the way that people use Joplin so having to mirror settings over 2 or more devices can start to become a chore - particularly things like notebook sorting orders let alone the myriad of plugin settings.
> So basically an option to sync the settings (and the client info with it would be a bonus) rather than having to keep doing the same setup multiple times.

### CODE REVIEW

**Comment by laurent22** [comment]
Yes I think we'll need that eventually and that would make a good GSoC project.

**Comment by roman-r-m** [comment]
Perhaps it's worth adding that settings sync should use the existing sync mechanism (it should, right?) or people will start coming up with weird ideas just to sync settings.

**Comment by Daeraxa** [comment]
Good point, I did kind of assume that the existing sync target mechanism would be a given.

**Comment by roman-r-m** [comment]
Ha! You'd be surprised
I'm pretty sure even if we do say it should use the existing mechanism, a fraction of proposals will have something else.

**Pull request merged**
