### PR TITLE
Cli: Change Joplin Cloud login process

### PR DESCRIPTION
**Pull request by pedr**
Feature is based on this PR: https://github.com/laurent22/joplin/pull/9445

Relevant file while the base PR hasn't been merged:
https://github.com/laurent22/joplin/blob/ec9adafa305b8d2a85ed67be09b0ce13b3d36c6a/packages/app-cli/app/command-sync.ts#L92-L119

Changes the Joplin Cloud login process to make the user authorize the use of application credentials over the browser.

<details><summary>Images</summary>

Screenshot from 2024-01-15 03-03-35

Screenshot from 2024-01-15 03-04-14

Screenshot from 2024-01-15 03-03-03

Running the synch in the shell:

image

</details> 

### How it works

1. User uses the `:sync --target 10` command
2. "To allow Joplin to synchronise with Joplin Cloud, open this URL in your browser to authorise the application:"
3. User authorizes use in Joplin Cloud
4. "Did you already authorized login in Joplin Cloud?"
5. app-cli client requests to Joplin Cloud if the authorization is complete

### To do

- [ ] Is it possible to identify that it is app-cli (update ApplicationType and ApplicationPlatform value).

### CODE REVIEW

**Comment by pedr** [comment]
- TEST command: yarn start sync --target 10
    UI comment: Is "Did you already authorized login in Joplin cloud?" a prompt to press y after the user has:
    Opened the Joplin Cloud link
    Signed in

    If so, After signing in with the above URL, press <enter> or Have you signed in with the above URL? might make more sense (i.e. directly connecting the prompt to the URL).

**Comment by pedr** [comment]
I changed the prompt message to be more clear to what the user should do (access the above URL and authorize the login)
image

**Comment by laurent22** [comment]
@pedr, I merged the desktop pull request so could you update this one please? At the moment it has some desktop-related changes which I guess is because it was based on the desktop pr

**Comment by pedr** [comment]
@laurent22 PR is updated and ready to review/merge again

**Comment by laurent22** [comment]
That looks good!

**Pull request merged**
