### PR TITLE
correcting and expanding the markdown instructions for a link

### PR DESCRIPTION
**Pull request by taw00**
- "some content" in `[some content](https://somelink/)` is called the
    content of an entity (or alt text for an image link)
- "some title" in this example is the the title element of the
    entity: `[some content](https://somelink/ "some title")`

### CODE REVIEW

**Comment by taw00** [comment]
Note, @laurent22 -- this is my second go around with this documentation patch. I nuked the first one that clobbered your change and then resubmitted.

**Comment by tessus** [comment]
I'm not sure if we need the word 'some' in there at all.

I think the following sounds better:

```
And this is a link anchoring text content:

And this is a link, with a title, anchoring text content:
```

**Comment by taw00** [comment]
Would you like me to commit a new change to this branch? Or do another PR.

**Comment by tessus** [comment]
@taw00 you can just create another commit in this branch. We'll squash them anyway, so don't worry about the git history.

**Pull request merged**
