### PR TITLE
Desktop: Fix errors found by automated accessibility testing

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request:
1. Sets up automated accessibility scanning with `@axe-core/playwright` ([docs](https://playwright.dev/docs/accessibility-testing)).
   - For now, this scans the "General" and "Plugins" tabs of the settings screen and the main screen with an open note.
2. Fixes WCAG errors found by the scan.

> [!NOTE]
>
> This pull request includes code from https://github.com/laurent22/joplin/pull/11218.

# Change summary

- Missing `lang` attribute on `HTML`.
    - Fixed by merging https://github.com/laurent22/joplin/pull/11218 into this branch.
- Avoid empty `aria-label`s:
    - Fixed by using `aria-hidden={true}` instead.
- Missing `role='main'` and `role='navigation'` elements.
    - Fixed by adding `role='navigation'` to the sidebars and `role='main'` to the note editor.
    - The two `role='navigation'` elements are distinguishable by their different `aria-label`s.
- `aria-details={id}` sometimes points to an ID that isn't in the document.
    - Fixed by ensuring that the details element always exists. Previously, it was only created if it had content.
- `aria-setsize` on unsupported element.
    - Removed `aria-setsize` from the note list and sidebar content containers. (`aria-setsize` is already correctly present on children of the sidebar and note list).
- Missing label for note viewer.
    - Added `aria-label` to the note viewer.
- Missing label for the Markdown editor's content.
    - Added `aria-label` to the Markdown editor's content.
- Contrast issues:
    - Made `colorFaded` and `color3` darker in the light theme.
    - Previously, the following elements had contrast issues in light mode:
        -  Setting labels (3.18:1, expected 4.5:1)
            - **Before**: image before of a settings extended description
            - **After**: image after of a settings extended description with slightly darker text
        - Plugin version text (3.47:1, expected 4.5:1)
            - **Before**: screenshot before of plugin version number
            - **After**: image
        - Toolbar text labels (e.g. the language code for the spellchecker toolbar item), (3.79:1, expected 4.5:1)
            - **Before**: screenshot before of spellchecker button, slightly lighter text
            - **After**: screenshot after with slightly darker text

Additionally, while running tests in dark mode (currently disabled because of contrast issues not included below):
- Improved contrast of the "Plugins" settings sidebar divider.

### CODE REVIEW

**Comment by personalizedrefrigerator** [comment]
CI errrors in [this CI run](https://github.com/laurent22/joplin/actions/runs/11483276254/job/31958354367?pr=11246) should be fixed by https://github.com/laurent22/joplin/pull/11224.

**Comment by laurent22** [comment]
Conflict on styles/index.scss

**Comment by personalizedrefrigerator** [comment]
The Android APK build failure should be fixed by https://github.com/laurent22/joplin/pull/11294.

**Comment by laurent22** [comment]
Sorry, more conflicts now. Other than that it's ready to merge

**Pull request merged**
