### PR TITLE
Desktop: Change Toolbar Layout

### LINKED ISSUE #1944: Make the info dialog more visible
There are lots of important info in there and many users don't know it exists.

Maybe it should be made a collapsible panel on the right side, which would be consistent with the mobile app. Opened by default.

### PR DESCRIPTION
**Pull request by rabeehrz**
Resolves #1944 

- [x] Rearrange the toolbar items to improve visual hierarchy.
- [x] Move the note properties icon to right under date/time to improve visibility.

## Before
Screenshot 2020-04-06 at 3 05 01 PM

## After

Screenshot 2020-04-14 at 12 46 42 PM

Modified the ToolBarButton component so that it accepts custom styles.

### CODE REVIEW

**Comment by rabeehrz** [comment]
@PackElend label me, please.

**Comment by laurent22** [comment]
We discussed this and agreed it should be on the right, but you put it somewhere in the middle? Any reason for that?

**Comment by rabeehrz** [comment]
> We discussed this and agreed it should be on the right, but you put it somewhere in the middle? Any reason for that?

Nope. A bit of mishap from my part.

**Comment by tessus** [comment]
Hmm, I'm not sure, if this makes this button more visible. One also has to move the mouse cursor across the entire screen now, which is not that great.

But let's hope that does the trick. I still wished we had a shortcut for note properties, which is why I can't wait to get custom keyboard shortcuts.... ;-)

**Comment by rabeehrz** [comment]
> Hmm, I'm not sure, if this makes this button more visible. One also has to move the mouse cursor across the entire screen now, which is not that great.

It does look better this way imo. Also [this](https://github.com/laurent22/joplin/issues/1944#issuecomment-609706065)



> But let's hope that does the trick. I still wished we had a shortcut for note properties, which is why I can't wait to get custom keyboard shortcuts.... ;-)

Yepp. 😄

**Comment by tessus** [comment]
Ah, ok. I didn't follow the other conversation. But, if people are used to that from other apps, then it will certainly help.

**Comment by laurent22** [comment]
Thanks for the update @rabeehzr.

It looks so ugly though, although not your fault obviously. I wonder if it could be improved, as currently the title, date and now info button all have different heights and style. Do you have Bear, Evernote or similar app to see how they make it look?

**Comment by laurent22** [comment]
Perhaps the date/time should be removed from there?

**Comment by tessus** [comment]
> Perhaps the date/time should be removed from there?

I think the date/time should stay there, but since the title is now bigger, maybe the data/time  should be 50% bigger as well. Then we could make the info button the same height as date/time or even as big as the title. Date/time however, should not be as big as the title.

**Comment by rabeehrz** [comment]
> Do you have Bear, Evernote or similar app to see how they make it look?

Joplin is the first note-taking app I've used. I'll check out Bear and Evernote.

> I think the date/time should stay there, but since the title is now bigger, maybe the data/time should be 50% bigger as well. Then we could make the info button the same height as date/time or even as big as the title. Date/time however, should not be as big as the title.

Okay, I'll do some research and make it look good. Thank you so much for the input.

**Comment by rabeehrz** [comment]
I checked out Bear. They seem to have the info icon tucked away in the top right corner and made it barely visible. I don't think they intend to showcase that feature.

**Comment by rabeehrz** [comment]
> maybe the data/time should be 50% bigger as well

That makes it look really bad.

Screenshot 2020-04-09 at 10 04 10 PM

**Comment by rabeehrz** [comment]
What if we move the date and time inside the note properties, and just leave the icon there?

Screenshot 2020-04-09 at 10 07 45 PM

**Comment by laurent22** [comment]
Hmm, not sure, but it would indeed look better without the date there. Perhaps could you ask on the forum to see what other people think? If there's no opposition to it I guess we can indeed get rid of it.

By the way, this is how it looks in Evernote:

image

But they have one extra line on top (where the tags are) to work with, so it's easier to make it work.

**Comment by tessus** [comment]
> What if we move the date and time inside the note properties, and just leave the icon there?

I am defenitely against this. So here's my take:

For me it was perfectly fine until now. Then somebody decides that we have to change it, but the result is not that great and the new feature might actually remove functionality (in case you move the date/time to the note properties dioalog).
I'm sorry to be blunt, but this is just idiotic. 
- Adding a second line and more unnecessary clutter? 
- Removing the data/time from the UI so that you have to click a button that is now way off the toolbar?

Currently all solutions just look like a trade off instead of an enhancement. This is not a very convincing argument for doing this.

So either one can make the info button look good next to the date/time, or we forget about the whole thing and leave it like it is. If people don't recognize an (i) as the info symbol, moving it might not be very successful to begin with. If you want to underscore it, why don't you move it to the end of the toolbar?

image

**Comment by laurent22** [comment]
I think the toolbar has a problem because it mixes editor-level options (text formatting, etc), and note-level options (info, word count, etc).

Those are different concepts and it's not logical that they are mixed together, and also it means there are many toolbar buttons in there, which is not good ux.

So I think it would make sense to investigate ways to clarify this part of the UI, though of course it needs to be done in a way that improves the UI and no make it worse. I don't really have any ideas at the moment but will think about it. In the meantime any suggestion is welcome.

**Comment by tessus** [comment]
In which case we can move all non-editor buttons to the right side of the toolbar. It can't be more obvious that that. Currently they are also the right most icons. I don't understand why this isn't logical for some people, but ok. Moving them to the right border of the app makes that distinction certainly more prominent. But in that case the (i) button is one again amongst others, so same issue as before. Unless you make it a different color or background color (in which case don't forget to add a class so that people can modify it).

**Comment by rabeehrz** [comment]
> In which case we can move all non-editor buttons to the right side of the toolbar. It can't be more obvious than that.

I think this is something that could work. I also created a [forum topic](https://discourse.joplinapp.org/t/increasing-visibility-of-note-info-properties/7788) for the discussion.

**Comment by rabeehrz** [comment]
I've moved the button to the right, under the date/time as Tessus asked and updated the PR post.

**Comment by tessus** [comment]
@rabeehrz this was just a suggestion. I don't make any decisions. Laurent is the one who does.

**Comment by rabeehrz** [comment]
> I don't make any decisions. Laurent is the one who does.

Yep. Let's see what he thinks.

**Comment by rabeehrz** [comment]
Made changes as per Tessus's [suggestions](https://discourse.joplinapp.org/t/increasing-visibility-of-note-info-properties/7788/17). It looks better now. I've renamed the PR and updated the PR post.

**Comment by rabeehrz** [comment]
I don't know why my tests failed. All the tests passed on my machine. Also, I believe I didn't change anything that affects the tests.

**Comment by Rishgod** [comment]
I guess it's Travis ci fault, try re-running the travis ci build, (you can do that by pushing a dummy commit like a white space or close this pr and re-open this pr it will cause the travis ci to rebuild again

**Comment by rabeehrz** [comment]
> I guess it's Travis ci fault, try re-running the travis ci build, (you can do that by pushing a dummy commit like a white space or close this pr and re-open this pr it will cause the travis ci to rebuild again

Alternatively, You can create empty commits

`git commit --allow-empty -m "Message"`

And then push or rebase/squash that commit.

**Comment by rabeehrz** [comment]
Anything I should change?

**Comment by laurent22** [comment]
@rabeehrz, thanks for the change, but since then the note editor has been refactored and the toolbar buttons moved to a different location (to the left of the title input field). It's not ideal but will stay like that for now, till we redesign the whole UI.

**Pull request closed without merging**
