### PR TITLE
Doc: Add libvips dependency for Apple Silicon build instructions

### PR DESCRIPTION
**Pull request by nickhobbs94**
Thanks to [this thread](https://discourse.joplinapp.org/t/unable-to-build-on-macos-apple-silicon/22624/4) for solving my issue. I figured this should be in the build instructions.

### CODE REVIEW

**Comment by tessus** [comment]
Isn't the module installing the library? e.g. like `7zip-bin-linux` and `sqlite3`, ...

**Comment by nickhobbs94** [comment]
Looks like a later version of sharp is needed if we want it to fetch prebuilt binaries.

> Prebuilt sharp and libvips binaries are provided for macOS on ARM64 from sharp v0.29.0.
> Prebuilt libvips binaries were provided for macOS on ARM64 from sharp v0.28.0.

Source: https://sharp.pixelplumbing.com/install

There's a couple versions listed in the `yarn.lock` file but no later than v0.26.3.

**Comment by laurent22** [comment]
Not sure we should add this for now, because then we'll have to remember to remove it when we upgrade Sharp. Or should we upgrade sharp now? Would there be any breaking changes?

**Comment by laurent22** [comment]
Ok let's merge, thanks for the info @nickhobbs94.

**Comment by BalanaguYashwanth** [comment]
hey i am getting this issue when running desktop app in mac with Apple silicon m1

`Uncaught Error: Cannot find module '/Users/yashwanth/other-projects/open-source/joplin/packages/app-desktop/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node'`

Any solution ?

**Comment by BalanaguYashwanth** [comment]
I guess found solution - https://github.com/TryGhost/node-sqlite3/issues/1538#issuecomment-1037839683

If any alternative solutions are there please comment it below👇

**Pull request merged**
