### PR TITLE
Translation: Update vi.po 

### PR DESCRIPTION
**Pull request by ddtuan99**
- Fix some minor typo
- Change some translated line
- Add some line that wasn't translated
from line 2567 to end.

### CODE REVIEW

**Comment by laurent22** [comment]
Your file is not valid, please use poEdit to make changes.

**Comment by tessus** [comment]
@ddtuan99 are you going to work on the requested changes or shall I close the PR?

**Comment by ddtuan99** [comment]
@laurent22 @tessus Hi, thanks for your consideration. I'm still working on it but it may be slow, I think there are many lines i need to add/fix and i will use poEdit, too. 
Is there any inconvenient to keep this PR open until i finish or i just close it and make other pull when it done?

**Comment by tessus** [comment]
No, all good. But without a response it was hard to determine whether or not  you had abandoned the PR.

Now we know you are working on it...

**Comment by laurent22** [comment]
Thank you for your pull request. As currently it cannot be merged, please resubmit a pull request once you have updated the file using poEdit.

**Pull request closed without merging**
