### PR TITLE
Desktop: Add type 'info' and 'OK' button to update dialog when version up-to-date

### PR DESCRIPTION
**Pull request by matsest**
This removes a minor issue (not found Issues) where the text in the check for update messagebox is automatically selected. It adds a 'OK' button and makes the messagebox consistent with other boxes (type 'info'). This is only for the dialog when the version is up-to-date.

* Tested on Linux (Ubuntu 18.04 running under Unity)

## Issue

Current behavior when pressing check for update:
screenshot from 2019-01-25 12-37-22

Text is automatically selected in lack of a button. ESC must be pressed to exit the window.

## Fix

With this PR:
screenshot from 2019-01-25 12-36-57

OK is automatically selected, icon is shown. ESC or Enter (for 'OK') can be pressed to exit the window.

### CODE REVIEW

**Comment by matsest** [comment]
Should probably be tested on Mac/Windows as well.

**Comment by tessus** [comment]
On macOS it looks like this:

image

I don't know, if I want to have an info icon shown instead of the Joplin icon.

**Comment by matsest** [comment]
I'm not sure..

As long as you state the type (for the logo) and buttons explicitly, it should anyways look similar on all platforms :)

**Comment by laurent22** [comment]
What's the standard for message boxes on Linux? Maybe if the Electron team didn't put the OK button is because it's more normal on Linux not to have one?

In any case, if we make this change, we should probably change `showMessageBox` so that it applies to all message boxes and not just this one. I prefer not to have icons either, because for some reasons they look quite ugly on all platforms (that's why I wasn't using any).

**Comment by matsest** [comment]
Based on the documentation for Electron I thought that it automatically added 'OK' to Windows, but it indeed seems like this default action happens for MacOS as well - but not for Linux (as shown in my initial screenshot). There's not a coherent standard for Linux AFAIK, it's likely different in different distros and graphical environments. But not having a button does not look good and does not cohere with the general design in the application IMO.

To suppress the default icon action, adding `icon: "none"` should be sufficient? 

When I took another look at the code I see that using showmessagebox directly is not recommended:
https://github.com/laurent22/joplin/blob/8ff2418b028f9f5fe40ccbdb6ffc122c684e4164/ElectronClient/app/bridge.js#L65-L67
so perhaps `showInfoMessageBox` from `bridge.js` should be used instead?
https://github.com/laurent22/joplin/blob/8ff2418b028f9f5fe40ccbdb6ffc122c684e4164/ElectronClient/app/bridge.js#L90-L97

It's only in `checkForUpdates.js` this is used directly, so if changes would to be made on other boxes they should be changed in the definitions in `bridge.js` instead.

**Comment by laurent22** [comment]
Thanks @matsest, I think this is fine. I might be difficult to use functions from bridge from that script, so let's keep that way.

**Pull request merged**
