### PR TITLE
Desktop: Fixed color with higher contrast to enhance readability in oled dark theme

### LINKED ISSUE #9453: Desktop: Note list: Highlighted note barely visible in "OLED Dark" theme
### Operating system

Windows

### Joplin version

2.13.8

### Desktop version info

Joplin 2.13.8 (prod, win32)

Client ID: 25d9dae7661c4d5a9611082882a41044
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 604dcbc

Freehand Drawing: 2.5.0
RevealJS Integration: 0.6.0

### Current behaviour

To reproduce:
1. Enable the "OLED Dark" theme in settings
2. Open a note

### Expected behaviour

The selected note's background should have higher contrast with the surrounding notes.

### Screenshot

screenshot: Low contrast

### PR DESCRIPTION
**Pull request by Harshiths1**
Fixes : #9453 
Higher contrast color is now used which is energy-efficient and won't emit as much light, helping to save battery life on OLED screens and enhance the readability.

### CODE REVIEW

**Comment by Harshiths1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
Please provide a screenshot before / after the change

**Comment by Harshiths1** [comment]
> Please provide a screenshot before / after the change
Before
image



After
image

**Comment by laurent22** [comment]
I don't get how this works. `codeBorderColor` is not used for the note selection background?

**Comment by Harshiths1** [comment]
> I don't get how this works. `codeBorderColor` is not used for the note selection background?

I know changing the selectedColor to '#B9B9B9' also works but i got to review why as to this too is working on my device

**Comment by laurent22** [comment]
There are too many issues for such a simple PR, so I'd rather close. We don't participate in GSoC by the way

**Comment by Harshiths1** [comment]
Thank you anyway , this was my first ever PR so I did not expect much and purposely chose such a simple issue to familiarize. 
Appreciate that you gave inputs really helped .

**Pull request closed without merging**
