### PR TITLE
Desktop: Fix Goto scrolling (#2122)

### PR DESCRIPTION
**Pull request by rccavalcanti**
Fix issue #2122

### CODE REVIEW

**Comment by laurent22** [comment]
The original code makes sense to me: if the note is already visible, there's no need to scroll. So I don't think we can remove this part but rather we should find out why a valid index if outside of bounds. @rccavalcanti, do you know what could be the issue?

**Comment by rccavalcanti** [comment]
I dove a bit more on that line and I found it just has a problem in the boundaries.
1 - If the 1st visible item was selected, it didn't return (it should).
2 - If the 1st invisible item was select, it did return (it shouldn't).
This second problem caused #2122.

So I brought it back and fixed the issue.

**Comment by rccavalcanti** [comment]
Great! Just don't merge yet. I'm working in a better fix.

**Comment by rccavalcanti** [comment]
So previously, I found that `bottom` and `top` were 1-based, while `itemIndex` was 0-based. This ultimately caused the boundary problem. I solved it in 62674dc, resting 1 from them.

However, I thought this was probably unintended and all values should be 0-based. So I went to investigate further.

It turns out that I found 2 different bugs in the class that caused the 1-based index:
- for `bottom`, it was in the definition of `bottomItemIndex` 
- for `top`, it was in its own definition 

So I fixed both and kept the line of conditional return unchanged. 

I think this is much cleaner and probably the final solution. Sorry for the multiple iterations!

**Comment by tessus** [comment]
@laurent22 is anything still missing?

**Comment by laurent22** [comment]
Perfect thanks @rccavalcanti and @tessus!

**Pull request merged**
