### PR TITLE
Mobile: Resolves#7675 Fix ViewPropType error in react-native-camera

### PR DESCRIPTION
**Pull request by vikneshwar**
- This change includes patch-package as dependency to apply the patch to react-native-camera package. The patch imports ViewPropType from deprecated-react-native-prop-types instead of directly importing from react-native
- More context can be found at #7675

Testing instructions:
 - Follow the instructions [here](https://github.com/laurent22/joplin/blob/dev/BUILD.md#testing-the-mobile-application) to build and start the mobile app
 - Once app shows up in the device/emulator, create a new note
 - From the top right menu option --> Attach
 - Confirm that camera opens up

### CODE REVIEW

**Comment by vikneshwar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vikneshwar** [comment]
recheck

**Comment by laurent22** [comment]
recheck

**Comment by laurent22** [comment]
We use `yarn patch` for patching

**Comment by vikneshwar** [comment]
@laurent22 oh, got it ! Let me patch it using `yarn patch`

**Comment by vikneshwar** [comment]
@laurent22 update the pr to use `yarm patch`

**Comment by laurent22** [comment]
CI is broken

**Comment by vikneshwar** [comment]
Hi @laurent22, I can see the message `The lockfile would have been modified by this install, which is explicitly forbidden` , so should I remove `yarn.lock` from the commit ? Other than that I don't see any explicit error message, am I missing something here ? 

Screenshot 2023-02-18 at 3 41 44 PM

**Comment by laurent22** [comment]
run yarn install, git add, git commit, git push

**Comment by vikneshwar** [comment]
Thanks @laurent22, I have updated it.

**Pull request merged**
