### PR TITLE
macOS: make the menu more like a macOS menu

### PR DESCRIPTION
**Pull request by tessus**
/ref https://discourse.joplin.cozic.net/t/another-detailed-features-put-preferences-in-the-right-menu/1854/

Screen Shot 2019-03-16 at 18 19 39

Screen Shot 2019-03-16 at 18 19 59

### CODE REVIEW

**Comment by laurent22** [comment]
To avoid duplicate code even more, why not put each item that might move in a variable, and then insert it at the right location?

For example:

```
const syncStatusItem = {
	label: _('Synchronisation status'),
	click: () => {
		this.dispatch({
			type: 'NAV_GO',
			routeName: 'Status',
		});
	}
}
```

and then insert `syncStatusItem` at the relevant place. What do you think?

**Comment by tessus** [comment]
> What do you think?

Great idea. My bad that I missed this in the first place. I will change it accordingly. Oh, one more thing, there was a request to move some of the items to a File menu on macOS. Please see the following [comment](https://discourse.joplin.cozic.net/t/another-detailed-features-put-preferences-in-the-right-menu/1854/14?u=tessus) in the forum. Let me know, if you want to do this or not.
(Since I'm already playing around with this, I might as well do that too.)

**Comment by laurent22** [comment]
Yes I saw this comment, if you can do this as part of the pull request too that would be perfect.

**Comment by tessus** [comment]
I will look at it tonight.

**Comment by tessus** [comment]
image

image

**Comment by laurent22** [comment]
Perfect, thanks @tessus!

**Pull request merged**
