### PR TITLE
Desktop: Fix focus on GotoAnything and Layout Switching

### LINKED ISSUE #3066: Focus on note body after "Goto Anything" or "Toggle editor layout"
## Rationale

I'd like to use Joplin while using the mouse as little as possible. The current focus behavior makes this difficult.

### Expected / Desired

If I'm in an "editing" layout already, here's what I'd like:

1. `ctrl-g` + type note name + `enter`
2. Start editing the note

### Currently

1. `ctrl-g` + type note name + `enter`
2. Use mouse to click in note body editor
3. Start editing the note

Instead of step 2, I could also use the `tab` key, but the focus is on the top-level window, so it requires 13 tabs to get to the note body.

At the very least, I believe the focus should be changed in the same way that it would if the note had been clicked on, which would require just two tabs to get to the note body.

## For Ctrl-L (Toggle editor layout)

Similarly, if I toggle to an editor layout, I'd like the focus to be automatically moved to the note body.

### Expected / Desired

1. `ctrl-l`
2. Start editing the note

### Currently

1. `ctrl-l`
2. Use mouse to click on note body
3. Start editing the note

If I navigated to the note originally using the mouse, then the note (but not the note body) is in focus, so using `tab` at step 2 is not too bad, requiring just two tabs.

However, if I navigated to the note using `ctrl-g`, then the focus is still on the top-level window after `ctrl-l`, so tabbing to the note body is not a good option.

## Environment

Joplin version: 1.0.200
Platform: Linux
OS specifics: Fedora

## Related

Issue #2960 is describing the same desired behavior but got derailed by a separate issue. The description here is more precise and complete.

### PR DESCRIPTION
**Pull request by rabeehrz**
Fixes #3066 and #2960 

## Before

before

vim-before

## After

after

vim-after

### CODE REVIEW

**Comment by rabeehrz** [comment]
@PackElend label me, please.

**Comment by laurent22** [comment]
Do we definitely want this feature though? Changing the focus is what some users will expect, but other maybe will not like that (and, no, we won't add an option for it), so how to know?

**Comment by rabeehrz** [comment]
I think this feature would be great addition.

From a UX point of view, when a user searches for a note using GotoAnything, They either type on the note or they just navigate elsewhere. If they decide to navigate, they would have to click somewhere or bring up the GotoAnything menu again. And I think most users would type on the note right away and avoids the need for an extra click. The same thing for Layout Editor as well.

Also, there are 2 issues addressing this feature. So IMO, it helps the users who wants this feature and the ones that don't expect this, no harm will be done. 😅

**Comment by walkie** [comment]
Thanks, @rabeehrz!

@laurent22, is there a rationale/use case for the current behavior? It seems that at the very least, shifting focus to the note after Goto Anything is logical and consistent with clicking on the note.

I think changing focus to the note body in both of these scenarios makes sense. Opening a note or changing the layout is an action that the user is taking for a specific reason. I'm struggling to think of a reason for taking that action where the top-level window is the place to be, and I believe that for a majority of those reasons, the note body is a very useful place to be.

1. When changing the layout from a non-edit mode to an edit mode, 100% of the time I am doing so to edit the note body. It is annoying to have to fix the focus since I already indicated that "I'm about to change the note" by changing the layout to an edit mode.

2. When opening a note while in an edit mode, sometimes I'm doing so to edit the new note (e.g. paste some information I've copied from the current note), in which case I would again like to already be focused on the note body.

3. When opening a note while in edit mode, other times I'm just jumping into the new note to briefly look something up before jumping back to the original note to resume editing. In this case, focusing on the body of the note I briefly jumped to does no harm, and is definitely a more useful place to be than the top-level window for any action I might want to take. For example, I can more easily scroll with the keyboard and copy text from there.

As an aside, in Scenario 3, when I jump back to the original note, I have to change the focus *again* (and also scroll back to where I was... it would be great if Joplin remembered my cursor location, but I realize that's a trickier feature to add).

I tend to do a lot of jumping back and forth, moving things between notes (e.g. I dump ideas in one "Inbox" note, then batch sort them into other notes). Joplin's keyboard shortcuts for jumping to notes and switching between view and edit modes *almost* makes this very easy to do quickly, but changing focus back to the note body after every single jump kills it.

(I realize a pull request discussion isn't the best place for this, but I would like to say that besides this focus issue, I've found Joplin really fantastic to use. I tried it out in 2018 and bounced off, but it's evolved into a really great application since then. I've been using Dynalist for the last couple years but have spent this week using Joplin since I'd like to move back to an open source solution for note tracking. I started porting some of my essential notes from Dynalist today, so I think I'm here for good. Thank you.)

**Comment by laurent22** [comment]
I thought after Ctrl+G, it would focus whatever was previously focused, but looks like it's not what it does. In that case, focusing on the note is definitely improvement.

**Comment by walkie** [comment]
Returning focus to the last interface element that was focused after `Ctrl-G` would also be a fine solution for me since the most painful situation is switching between notes while in an editing mode. If the focus stayed in the note body window after the switch (and even better, remembered the cursor position when I switch back), that would be great.

I still think it makes perfect sense to move the focus to the note body after `Ctrl-L` to an editing mode, but that's based on how I'm using Joplin. I'm not sure if there are other ways people are using it where this would make less sense.

**Comment by rabeehrz** [comment]
Any changes need to be made?

**Comment by rabeehrz** [comment]
@bedwardly-down Thought on this?

**Comment by JusteUnSinge** [comment]
This behavior is also missing when adding a tag via CTRL+ALT+T.

**Comment by rabeehrz** [comment]
> This behavior is also missing when adding a tag via CTRL+ALT+T.

I can see what you mean, but I'm unsure whether it is really necessary from a UX perspective. We'll have to see what Laurent thinks. If it is okay with him, It can be added.

**Comment by laurent22** [comment]
Thanks @rabeehrz. I've merged the Goto Anything change as there's no problem with this one. For the layout switching however, the focus call should be done from the middleware, so that if that particular reducer action is called from elsewhere, the focus is also done. But that requires more changes, which could be made in a different PR if necessary.

**Comment by rabeehrz** [comment]
I'll look into it when I get time.

**Pull request merged**
