### PR TITLE
add shortcut to duplicate line to CodeMirror

### PR DESCRIPTION
**Pull request by tessus**
/ref https://discourse.joplinapp.org/t/duplicate-line-command/12650/15

### CODE REVIEW

**Comment by CalebJohn** [comment]
I think `duplicateLine` should probably be added as a joplin command, that way users will be able to remap it. 
I've made an example of what it takes to add a new command via the command system. You can see it [here](https://github.com/CalebJohn/joplin/commit/40ffff6549e559c4b9ac60ad601694cf07a089e4)

**Comment by tessus** [comment]
Sure, sound like a good idea. You can close my PR and create a new one, since you already wrote the code....

**Comment by tessus** [comment]
@CalebJohn What do you want to do?

**Comment by CalebJohn** [comment]
@tessus right, sorry about the delay. I'll open a PR.

**Comment by tessus** [comment]
No worries, just wanted to know if I can do anything.

**Pull request closed without merging**
