### PR TITLE
Desktop: Pre-fill “goto anything” list with recently updated notes

### PR DESCRIPTION
**Pull request by shawnaxsom**
This comes from this idea on the forum: https://discourse.joplinapp.org/t/improvement-idea-pre-fill-goto-anything-list-with-recently-updated-notes/4002

GoTo Anything currently initializes with no search results. This changes simply runs an initial search without a filter on loading the dialog, or again when removing all search terms in the dialog previously entered.

On updateList, the GitHub view of the diff obscures the change. I just removed the if block.

### CODE REVIEW

**Comment by laurent22** [comment]
Hmm, I don't know, do we actually want to see the latest modified notes by default? I feel it adds more complexity and it's not clear to me that it's what the GotoAnything dialog is for. It's more like custom behaviour that would be more suitable as a plugin.

**Comment by shawnaxsom** [comment]
Hmm it is behavior I'd expect would be built in. Most applications I use with jump-to behavior show results by default: Evernote shows most recently updated notes or notebooks. Visual Studio Code shows most recently viewed files. Bitwarden shows matches for the current site. Dynalist shows most recently viewed nodes.

The behavior is very useful. I might want to return to the note I was working on yesterday when I reopen the app in the morning. Or I might want to juggle between editing two notes. Or let's say I'm taking notes in a meeting, then I want to search for some information, and once finished searching other notes I want to jump back to the meeting notes I was just updating.

It seems like very little complexity to me (it's just a six line change, if you view the diff with "Hide whitespace changes" enabled), for a lot of utility. The only complexity or risk I see would be performance-wise, if someone has an overwhelming amount of notes, though I have thousands and it is instantaneous for me, and it would be simple still to add a TOP XXX limit.

**Comment by laurent22** [comment]
You make a good point. I don't use this recent item feature in my editors and disable it when I can, but it's true it's often present and can be useful.

In terms of complexity, I didn't mean in terms of added code (I had already checked the diff with hidden whitespaces) but in terms of added features. As an example, we had support for vim input in the text editor, which was added simply by setting "mode=vim" on the component. Just one attribute. But now that we've switched to a new (better) editor, people are asking to restore complex vim behaviour that was auto-implemented by the previous editor. So my point is that the amount of code change is not a big factor - whether we add a feature or not is, because it needs to be maintained afterwards through code refactoring and rewrites.

That being said, I agree this particular feature would be useful and I'm happy to merge. Could you fix the conflict please (which I suspect is large because of the indent level change), then I'll test it and merge if eveything's ok.

**Comment by shawnaxsom** [comment]
Sure thing! I've rebased in the latest changes in dev, it should be ready to go.

That does make sense regarding complexity. I know minor changes can become tough calls when maintaining a large and growing open source project.

Thanks for all your work on Joplin! It's always interesting to see the differences in use cases and user experiences. Features like this might seem minor to some, but it is essential to others, and it has kept me going back to Evernote or FSNotes. I prefer Joplin by and large, but it's rough when my boss jumps on a call with me and I'm fumbling trying to pull up recent notes when he asks questions as if I had a photographic memory :)

**Comment by laurent22** [comment]
I've installed the feature and looked again as I couldn't understand how it worked at all, but I see a few problems now:

- It relies on the fact that empty search queries returns something. Normally, empty queries are handled at UI level to return nothing. What it returns for empty queries is undefined behaviour and might be changed later on to return nothing.

- It relies on the fact that empty queries return all notes sorted by last updated time. As we are making changes to the sorting algorithm, that might change later on.

- It's loading all the notes in GotoAnything, it would have to be limited to 10-20 notes.

- Finally, while it makes sense to show the last changed notes, it would also make sense to show the last viewed notes. For example, if I look at a note 10 times a day, I might want to see it before some note I modified one week ago.

It works a bit by chance now, and it's not clear to me that we want to see the last modified notes or last viewed ones or a combination of both (there was some discussion about this a while ago to keep track of most viewed notes but it wasn't implemented), so I think the feature would have to be discussed further, better in the forum, and there would be more work to be done.

**Comment by shawnaxsom** [comment]
Yeah definitely, I agree with that. I opted for most recently updated as that was the idea tbergeron presented in the forum, and for the sake of complexity (I don't think we keep track of views yet). As a user, I do prefer to base this type of behavior on views.

I'll close this PR, but I'm happy to help with whatever is decided.

**Pull request closed without merging**
