### PR TITLE
[Desktop]: Resolves #3491 : Added  keyboard shortcuts to icon in menu tooltip

### LINKED ISSUE #3491: [Feature Request] Add keyboard shortcuts to icon and menu tooltips
### Operating System

- Windows
- macOS
- Linux

### Application

- Desktop

---

### 1. Markdown Editor Icons

Currently, if I place the pointer over one of the markdown editor icons, for instance, the one for inserting a hyperlink, I get a tooltip which says `Hyperlink`.

I propose displaying a more helpful tooltip such as `Hyperlink (Ctrl+K)`. Currently, it's hard to find the keyboard shortcuts for these icons. For example, I do not know the actual shortcut for inserting a hyperlink (it's not Ctrl+K).

NB: For reference, Github's markdown editor has implemented this feature.

### 2. Notebook Menu Bar

The same feature should be there for the toolbar right below the menu bar. For example, the tooltip for the button to create a new note currently only says `New Note`. It would be more useful if it said `New Note (Ctrl+N)`.

---

I am creating this Issue since https://github.com/laurent22/joplin/issues/1403 and https://github.com/laurent22/joplin/issues/1559 were marked as stale and closed.

### PR DESCRIPTION
**Pull request by aashimawadhwa**
Added  keyboard shortcuts in editorCommandDeclaration.ts 
Resolves issue #3491

### CODE REVIEW

**Comment by roman-r-m** [comment]
Your PR contains lots of unrelated changes, please review.
The list of commits also does not look right - there are commits from other people, these commits should not be included.
And finally - these shortcuts must not be hardcoded as they can be changed by the user.

**Comment by aashimawadhwa** [comment]
Is this issue not valid then?

**Comment by roman-r-m** [comment]
It is valid, I mean that you have hard-coded, e.g. copy to be Ctrl+C but the user might change it to something else and then with your change the tooltip becomes incorrect.

**Comment by aashimawadhwa** [comment]
I will fix it soon , working on it.

**Comment by aashimawadhwa** [comment]
Can you help me in fixing commits from other people.

**Comment by roman-r-m** [comment]
> Can you help me in fixing commits from other people.

I recommend you read about interactive rebase in git. However in this case it may be easier to just start over since host of the changes in the PR are not correct.

**Comment by laurent22** [comment]
For information, keyboard shortcuts are defined by creating commands (if they don't already exist) and by setting a shortcut on the KeymapService for that command.

**Comment by aashimawadhwa** [comment]
I am having trouble in passing the defaultKeymapItem .accelerator in  editorCommandDeclaration.ts file . can you guide me for same?

**Comment by laurent22** [comment]
I don't know what needs to be done without looking at the code. It might be easy to add or it could be difficult, I really don't know at this point.

**Comment by tessus** [comment]
How to creare a PR: https://discourse.joplinapp.org/t/how-to-create-a-pull-request-pr/15052?u=tessus

**Comment by laurent22** [comment]
I will close this pull request for now, but feel free create a new one if you solve issue. For support please use the forum

**Pull request closed without merging**
