### PR TITLE
Updating translation of "da_dk.po"

### PR DESCRIPTION
**Pull request by Mustafa-ALD**
Updating the translation file for danish.

### CODE REVIEW

**Comment by tessus** [comment]
@laurent I'm currently unable to build translations or run any tests in that regard. My gettext version is 0.19.8.1 and MacPorts still haven't updated their package to 0.21

Maybe I'll build a newer version this weekend.

**Comment by laurent22** [comment]
@tessus, yes same for Ubuntu, it seems everything is still on v0.19 even though it's very buggy for JavaScript. I got v.21 from Homebrew.

**Comment by laurent22** [comment]
@Mustafa-ALD, it seems the change was done on an old version of Joplin. The new location of this file in is in packages/tools/locales

**Comment by Mustafa-ALD** [comment]
okay, thank you, I will delete this request and just make a new one with the new version 🙂

**Pull request closed without merging**
