### PR TITLE
Added quick linking to the list of GSoC ideas.

### PR DESCRIPTION
**Pull request by joshsweaney**

### CODE REVIEW

**Comment by joshsweaney** [comment]
Added the functionality requested in #1449 to the GSoC ideas page.

**Comment by tessus** [comment]
Did you discuss this with Laurent? I think it's a good idea,, especially since I would like to see this feature as well.
But I'm not quite sure, if it really fits the requirements for GSoC. Parts of this enhancement are already implemented (e.g. the search algorithm for listing notes - in the goto anything code).
But if Laurent thinks this is ok for GSoC I'm all for it!

**Comment by joshsweaney** [comment]
Laurent seemed keen in the forum post here: https://discourse.joplinapp.org/t/internal-url-hyperlink/4435/7

I think maybe the difficulty could be reduced to "Easy" if lots of the work has already been done. No reason you couldn't combine multiple smaller features into one bigger GSoC submission.

**Comment by tessus** [comment]
@laurent22 I think you have to decide if we add this to GSoC. I'm all for it.

**Comment by laurent22** [comment]
I think that can be done in one or two days, while GSoC projects need to provide enough work for a month or so, but perhaps @PackElend can confirm. Also the spec would need to be changed because many users won't want a popup to show up when they type `[`.

**Comment by tessus** [comment]
> because many users won't want a popup to show up when they type `[`

I totally agree and IMO it shouldn't. At least not at the first `[`. It is rather unlikely for someone to enter 2 though. So I'd suggest to go with `[[`. I don't know, if this is possible in Electron, but the popup should be just a small live search box (with results attached to it - similar as with the goto anything) next to the cursor.
The second `[` will start the popup, but must be removed as soon as a selection is picked.

**Comment by PackElend** [comment]
> I think that can be done in one or two days, while GSoC projects need to provide enough work for a month or so, 

yes, they don't earn little money doing it and you expect some major improvements joining GSoC, don't you? 

it may can be combined in UI/UX improvment package

**Comment by joshsweaney** [comment]
You're right, ```[[``` seems more appropriate. I think #1449 suggested that too, and I know Confluence also supports that. If this isn't appropriate for GSoC is there way to get this into the feature list queue or something so that somebody can start working on it?

**Comment by tessus** [comment]
@PackElend 
> it may can be combined in UI/UX improvment package

There's no UI/UX improvement idea for GSoC

@joshsweaney there's already the issue on github, so somebody only has to implement it. nobody has picked it up so far...

**Comment by tessus** [comment]
@joshsweaney you can add the text you wrote (or at least parts of it) to #1449 
I have already marked it as `GSoC` so hopefully a candidate will pick it up.

**Comment by laurent22** [comment]
That should be part of a wider discussion before making it look too official. I wouldn't someone to start working on it and to tell them the spec was not actually final.

**Comment by tessus** [comment]
Someone has to pick it up first. So I guess until the point when this is happening the specs are hopefully fleshed out.
Either way, what are you saying? Shall I remove the GSoC label from 1449?

**Comment by joshsweaney** [comment]
Is somebody free to start working on #1449 and then submit a pull request? Or is more discussion needed on the forum?

I really think it is quite a simple feature. It is basically a clone of the same feature on Confluence which also deals with pages and linking. A stripped down version of Confluence is actually quite similar to Joplin in some ways, but with more features (WYSYWIG editing, macros). Unfortunately it is also very bloated (and isn't open source). But I think getting inspiration from there for some useful features in Joplin is worthwhile (such as this one). 

You're basically just spawning a search box at the cursor when you type ```[[```, then you can use the up/down arrows to pick a page, hit enter, and a Markdown link to that page is inserted. I use the feature all the time in Confluence and have seen it in Wiki-style editors. Super fast way to build up a collection of linked knowledge if you want to reference another part of your journal quickly.

**Comment by laurent22** [comment]
> Either way, what are you saying? Shall I remove the GSoC label from 1449?

Yes I think so. It unnecessarily restricts the issue anyway, because someone who sees the label might think it's reserved for GSoC, when it's not. And someone who wants to participate in GSoC can pick up any issue in the first phase, and not necessarily those tagged with GSoC.

I guess we only need to tag with that label once a student has declared they want to work on an issue in the context of GSoC.

**Comment by laurent22** [comment]
As for this pull request, I don't see how to make it work as a one month project for GSoC. Maybe as part of another project, as PackElend mentioned, but what project I don't know. So I'll close PR until this is clarified.

**Comment by PackElend** [comment]
> Either way, what are you saying? Shall I remove the GSoC label from 1449?
if it is really only 
> I think that can be done in one or two days,
than it might be a "good first project"?

**Pull request closed without merging**
