### PR TITLE
All: Resolves #3871 Interpret only valid search filters

### LINKED ISSUE #3871: Search with colons will confuse search
## Environment

Joplin version: `1.1.4`
Platform: Linux
OS specifics: doesn't matter

## Steps to reproduce

1. search for `https://github.com`, `ActiveSupport::Duration` or any other thing with colons

## Describe what you expected to happen

Finding only my notes with the terms `https://github.com` or `ActiveSupport::Duration`. But the search will simply show some notes that don't contain the term.

### PR DESCRIPTION
**Pull request by JackGruber**
If a `:` is used in the search, the word before it is interpreted as a search filter, even if this filter does not exist.

### Before the change:

The search `https://github.com` throws an error `Invalid filter: https`.

### After the change:

The search `https://github.com` is not parsed as a filter `https`, insteand a phrase word search is performed.

The whole thing could also be avoided by searching with semicolons `"https://github.com"`.
But from a user-friendliness point of view, I think the optimisation is an advantage.

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pull request. It makes sense but on the other hand doesn't it mean we've disabled error checking on the filters? Like if make a typo and type `noteboook:something`, it will literally search for `noteboook:something` instead of showing an error about the filter name, is that correct?

**Comment by JackGruber** [comment]
Yes, this is correct, before an [error was thrown](https://github.com/laurent22/joplin/blob/8b81da6cebd6b08233c5a7d297c40ce8b50f973b/packages/lib/services/searchengine/filterParser.ts#L82-L84) and the search has returnd all notes. 

Should I extend the whole thing so that the message is output as an error?

**Comment by laurent22** [comment]
Yes I guess it would be good to output the actual error. Also, maybe we could have a special rule for certain prefixes. For example if it's "http" or "https" we assume the user actually want to look for this and run the search with your fix, without throwing an error?

**Comment by JackGruber** [comment]
When we leave the current behaviour except for a few specific key words, such as `http`, `https`, `ftp`, `sftp`, `ssh`, `mqtt`, ...  then in the mentioned issue, one example would work and one would produce the same error as currently, return all notes sorted by BM25 and output only an error in the debugging console which are not easily seen. 
I do not find this behaviour is consistent. 

I would either use only valid filters and use all others as search words, or continue to throw the error for non-valid ones and mention the behaviour in the documentation and note at the issue as designed. 

But I can also implement the middel way you have suggested.

**Comment by laurent22** [comment]
Hmm, yes that makes sense. Showing all the notes on error is not by design but probably because we're not handling the error. And I don't think we have anything to display the error (an alert would be too disruptive and anything else would require quite a bit of UI work). So your current approach indeed sounds like the best solution.

Could you maybe make a note of this behaviour in README.md?

**Comment by JackGruber** [comment]
>And I don't think we have anything to display the error

A status bar at the bottom or something similar would be useful from time to time, also for plugins :)

>Could you maybe make a note of this behaviour in README.md?

Sure

**Comment by JackGruber** [comment]
Is the info OK like that?

**Comment by laurent22** [comment]
Yes it's good now, thanks!

**Pull request merged**
