### PR TITLE
All: Resolves #3934 fix notebook filter

### LINKED ISSUE #3934: Search "Any" operator can not be separated
## Environment

Joplin version: Windows 1.2.6, Android 1.2.1
Platform: Android, Windows
OS specifics: Android 9, Windows 10

## Steps to reproduce

1. Task: we are trying to find any notes in a notebook with tag B or C.
2. Create the query notebook:A any:1 tag:B tag:C
3. Will be filtered all notes with notebook A or tag B or tag C. So it might be notebook Z if note has tag B or C. Or it might be any note from notebook A with any tags. It is wrong behaviour.
4. There is no way now to find any notes in notebook A with tags B or C. Or find any notes with ((tag D and B) or (tag D and C)). In short, where D is obligatory and B and C interchangeable.

## Describe what you expected to happen

On the step 2, everything before "Any" operator has AND logic, everything after "Any" operator has OR logic.
So it would work:
notebook:A any:1 tag:B tag:C = (notebook:A)AND((tag:B)OR(tag:C))

Another solution is to implement brackets () as it made in Evernote.
So it would work:
notebook:A (any:1 tag:B tag:C) = (notebook:A)AND((tag:B)OR(tag:C))

### PR DESCRIPTION
**Pull request by naviji**
#3934 

The notebook should not be included in the "union" created by the "any:" operator

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the fix @naviji. Could you remind me if there's somewhere where the filter operators are documented?

So far I think there's this:

- "notebook" filters have an implicit "AND" between them
- "tag" filters have an implicit "OR" between them
- The notebook is not included in the "union" created by the "any:" operator.

Is there anything more you can think of? I'll put all this in a spec so that we can know if something is working as specified or if it's really a bug.

**Comment by naviji** [comment]
The documentation page in the forum has some additional details (like default connective of notebook) that are missing in the version available on the website.
https://discourse.joplinapp.org/t/search-syntax-documentation/9110



> "notebook" filters have an implicit "AND" between them

It's acutally connected by OR. The reason being that no note can be in multiple notebooks at once.

> "tag" filters have an implicit "OR" between them

No, there's no such rule. The tag filter behaves just like the other filters (except notebook) with their connective changing between AND/OR depending upon **any**. Default is AND.

> The notebook is not included in the "union" created by the "any:" operator.

This rule was not documented anywhere. Everything else is specified in the doc in the forum.

**Comment by tessus** [comment]
> Could you remind me ...

I really don't want to say _I told you so_, but it's certainly a usability problem, if one has to study the handbook for half an hour before being able to do a search.

When I asked about boolean operators I was told they are not necessary. I still agree to disagree.

**Comment by laurent22** [comment]
Thanks for the bug fix @naviji, much appreciated!

**Pull request merged**
