### PR TITLE
Desktop: Added Nord Theme

### PR DESCRIPTION
**Pull request by Kullsno2**

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pr. Could you post a screenshot of it please? Also the code doesn't build now so you might want to check on Travis.

**Comment by Kullsno2** [comment]
Instructions for local setup and testing please?

**Comment by laurent22** [comment]
It's in BUILD.md

**Comment by Kullsno2** [comment]
> It's in BUILD.md

Looking at it.

**Comment by laurent22** [comment]
Hello, another user submitted and completed a pull request for the Nord theme, so I'm going to close this PR in favour of the other one.

Closed in favour of #1946

**Pull request closed without merging**
