### PR TITLE
Esperanto language 51% completed

### PR DESCRIPTION
**Pull request by martonpss**

### CODE REVIEW

**Comment by tessus** [comment]
@laurent22 I'm not sure, if I shall merge this, because the PR includes adding a language and updating a language. Please advise.

**Comment by tessus** [comment]
If you need help, here's how to do it:

- create a new branch (from master)
- cherry pick 79969a92a3d4d9124af05690c39dede4706a0b2a
- create new PR for pt_PR.po update
- switch back to this branch
- do a hard reset HEAD^1 and force push

**Comment by tessus** [comment]
@martonpss or I can do this, if you don't have time. Just let me know.

**Comment by tessus** [comment]
I did it myself. 

Next time, please create on PR language. 
Also, it is good practice to use a branch and not master.

**Comment by martonpss** [comment]
Thanks! I will follow the instructions next time.

**Comment by tessus** [comment]
@martonpss no worries. A PR should include just one fix, or one feature, or one update. It makes reviews easier and keeps the history in order.
Using a separate branch makes your life a lot easier, because we usually squash commits, thus you won't be able to use your master branch again, thus you'd have to delete your repo and fork it again to submit a new PR.

Thanks for the new language and for the update!

**Pull request merged**
