### PR TITLE
Desktop: Use the strongly recommended asar packing on linux and macOS

### PR DESCRIPTION
**Pull request by R-L-T-Y**

### CODE REVIEW

**Comment by laurent22** [comment]
Does it build?

**Comment by R-L-T-Y** [comment]
Of course it builds and works fine on my machine.

The CI seems to be not functioning and stuck on the same error for different PR.

**Comment by laurent22** [comment]
It used to not work. Since you didn't exclude any of the native modules, did you test that they work? Did you run `yarn dist` to actually build the executable? on which OS? We don't massive changes to the build like that with no comment and no information on what tests have been done.

**Comment by R-L-T-Y** [comment]
I have tried both yarn dist to generate AppImage and electron-builder on latest Arch Linux, no issue either way. With my half a day of usage, it suggest no error on debug mode.

I don't see how I can offer extensive tests for diverse Linux distros.

**Comment by tessus** [comment]
I also tested this with macOS (I had to set asar to true for mac) and it seems to work.

**Comment by laurent22** [comment]
Ok it's possible they fixed asar packing then. It's been "strongly recommended" for a while, even when it was obviously broken.

How about resources like icons, fonts and CSS files? Is Katex and Mermaid rendering still working?

**Comment by R-L-T-Y** [comment]
Resources and all the themes looks fine. Katex works and I don't think Mermaid is in master branch.

**Comment by tessus** [comment]
Yes, Katex and Mermaid work too.

**Comment by laurent22** [comment]
Thanks for checking all this @R-L-T-Y and @tessus, it looks like we can use asar then. Please @R-L-T-Y could you fix the conflict? Then we can merge.

**Comment by tessus** [comment]
@laurent22 this PR only changes the asar flag for linux.

**Comment by R-L-T-Y** [comment]
Since macOS version has been tested and that should yield a more consistent result, I propose the change made on macOS as well.

**Comment by laurent22** [comment]
I've also added it to Windows then. I guess it should work too but I'll test later. Thanks for the PR @R-L-T-Y!

**Pull request merged**
