### PR TITLE
Mobile: Fix issues with development environment

### PR DESCRIPTION
**Pull request by xuhcc**
1. https://github.com/mikehardy/jetifier

Without this package installed, `react-native run-android` command fails:

```
> Task :@react-native-community_slider:compileDebugJavaWithJavac FAILED
/home/xuhcc/Documents/coding/joplin/ReactNativeClient/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java:11: error: package android.support.v7.widget does not exist
import android.support.v7.widget.AppCompatSeekBar;
                                ^
/home/xuhcc/Documents/coding/joplin/ReactNativeClient/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java:23: error: cannot find symbol
public class ReactSlider extends AppCompatSeekBar {
```

2. https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows/44476757

Added note about this bug to BUILD.md, because it seems to be a common problem.

### CODE REVIEW

**Comment by tessus** [comment]
> Added note about this bug to BUILD.md, because it seems to be a common problem.

The problem is that the solution I used in the discussion [here](https://discourse.joplinapp.org/t/unable-to-build-mobile-application/2951/5?u=tessus) is not a solution. The command: `react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` creates a release build, which is not wanted during development.

We need to find a real solution to the issue, but even though I followed every single advice and even though my server is running on the correct port, I still get the "unable to load from script" error message.

**Comment by xuhcc** [comment]
Running `react-native bundle --platform android ...` is inconvenient, but it makes development possible, so I think we can add a note to help new contributors.

I suspect that it is indeed a bug in React Native CLI.

**Comment by tessus** [comment]
Apparently @laurent22 does not have this problem, so maybe it's just my dev env, which I do not understand either, because it worked on my other MacBook (which I don't have anymore) and I setup both the same way. Very strange.

In any case, I'm more than ok to update the doc, but it's not my decision. Let's wait for Laurent's comment.

**Comment by xuhcc** [comment]
Fix for [1] was added in ba5c636dda6598bd9fc21b43496342cdc8921bf2, so only BUILD.md change remains here.

**Comment by laurent22** [comment]
Thanks for the PR but indeed the main part has already been fixed in another commit. The Readme update is not specific to Joplin but to React Native development in general so I'd rather not add it.

**Pull request closed without merging**
