### PR TITLE
Desktop: Make table in HTML format horizontally scrollable

### PR DESCRIPTION
**Pull request by wljince007**
# Summary
Make table in HTML format horizontally scrollable by give table a div parent, so the width of the table is limited to the screen width.
See   [Mobile, Desktop: Make table horizontally scrollable by give table a div parent, so the width of the table is limited to the screen width.] : #10161 

# Test
## Test on Desktop
https://github.com/user-attachments/assets/3871db8a-93ed-4dea-a75e-f260bd923743

## Test on IOS Mobile

https://github.com/user-attachments/assets/7c8ffe82-9d07-41c3-b589-67430ab11f80

### CODE REVIEW

**Comment by wljince007** [comment]
When GitHub displays an HTML table, it also moves the table left and right to keep it within the screen range. During dragging, the content is not allowed to shake from side to side.



https://github.com/user-attachments/assets/82b48111-9f1e-4132-a47c-999bda1aa7bf

**Comment by laurent22** [comment]
There are still many websites that have their layout done using tables within tables. Isn't this change going to interfere with this by making all tables scrollable?

**Comment by wljince007** [comment]
1. Clipping from web or modified will add only one `<div class="joplin-table-wrapper">` before the most outside table:

https://github.com/user-attachments/assets/2f9b36d9-a888-40e8-b6db-4b25f88bc182

2. Display on Mobile:

https://github.com/user-attachments/assets/d37c4462-3b4b-4eb8-af75-0de4787fca84

3. test html:
```
<style type="text/css">
  .seasons1987 table {
      border-top-width: 0px;
      border-right-width: 0px;
      border-bottom-width: 0px;
      border-left-width: 0px;
  }
  </style>
  <table width="600" border="1" cellpadding="0" cellspacing="0" class="seasons1987">
    <tr>
      <td width="200"><table width="200" border="1" cellspacing="0" cellpadding="0">
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
      </table></td>
      <td width="200"> </td>
      <td width="200"><table width="200" border="1" cellspacing="0" cellpadding="0">
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
      </table></td>
    </tr>
    <tr>
      <td> </td>
      <td><table width="200" border="1" cellspacing="0" cellpadding="0">
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
      </table></td>
      <td> </td>
    </tr>
    <tr>
      <td><table width="200" border="1" cellspacing="0" cellpadding="0">
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
      </table></td>
      <td> </td>
      <td><table width="200" border="1" cellspacing="0" cellpadding="0">
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
      </table></td>
    </tr>
  </table>


asdlfkjasldfj asdflj asdflkj asdflkj asdflkj asdfljk asdlfkj asdlfj asdflkjasd fkljasdflkj asdlkfj asdlfkj asdflkj asdlkfj asdlfkj asdlfkj asdflkj asdlfkj asdflkj asdlfkj asdflkj asdflkj asdflkj asdflkj asdflkj asdflkj asdflkj asdflkj asdfljk asdfljk asdflkj asdfljk asdflkj asdflkj asdflkj asdfljk asdflkj asdflkj asdfljk asldfkj asldfj alsdjf
```

**Comment by wljince007** [comment]
Give me some example websites，I can test.

**Comment by laurent22** [comment]
Ok I think that makes sense, thank you for implementing this @wljince007!

**Pull request merged**
