### PR TITLE
Updates: Updated README.md

### PR DESCRIPTION
**Pull request by rt-oliveira**
This pull request contains the commits already made in pt_BR.po (made in the previous pull request), as well as updates in README.md (which are actually the new changes made).

I don't know if I could change README.md, but I had seen that it was out of date, especially in the pt_BR translation percentage.

I already apologize in advance for two things:
1- By the level of English I have.
2- Through the pull request process that is being done, I am still learning how to do this.

### CODE REVIEW

**Comment by tessus** [comment]
Thanks for your contribution.

Please do not update the README.md. This is automatically done by scripts. Even though the translation in the code tree might be having a higher translation percentage, the currently released app might still not have those changes....

Anyway, since you are the last translator you should change the 

```
"Last-Translator: XXXXXXX\n"
```

entry in the .po file. This entry will be used for updating the README.md.

**Comment by rt-oliveira** [comment]
I just updated the Last-Translator field.

**Comment by tessus** [comment]
Yep, looks good. If you can now revert the changes you made to the README.md, I can merge it.
As mentioned before, please do not update the README.md file.

You can use `git revert` like this:

```
git revert 7cbc17d39f3fa802b5e90e9ff55a1556fa00083b
git revert 3c1b6541d79b54479029154e5e7142801a5e1f62
```

**Comment by tessus** [comment]
Hmm, wait. I think you made a slight mistake here. You are using the same branch that you used for your last PR.

**Comment by tessus** [comment]
Ok, here is how it works:

Every time you want to create a new PR, you also have to create a new local branch.
So I suggest you do the following. You checkout the master branch, do a git pull from upstream (this repo) and then you create a new local branch. eg `update-last-translator`.
Then you make the same change as you did in your last commit and create a new PR.

**Comment by rt-oliveira** [comment]
Oh. About the use of the same branch: I'm sorry.
I'm still learning about pull requests.

**Comment by rt-oliveira** [comment]
I'll do that

**Comment by tessus** [comment]
Don't worry about it. We all have to start somewhere. I'm here, if you need help.

**Comment by rt-oliveira** [comment]
Ok.

**Comment by tessus** [comment]
Closing this one.

**Pull request closed without merging**
