### PR TITLE
Merge request for displaying notes count to the side of folder name in electron.

### PR DESCRIPTION
**Pull request by ghost**
1. Added the element to SideBar.jsx for displaying the notes count present in that particular folder.
2. Created a file called note-count-utils.js which is used for updating the notes count when ever there is action done on notes like adding a note, deleting a  note.
3. Calling a notes count refresh method from NoteList when the note is deleted.
4. Calling a notes count refresh method from Mainscreen when a new notebook is added.
5. Assigning the store dispatch to note-count-utils dispatch from BaseApplication.js.
6. Added a new action type FOLDER_COUNT_UPDATE_ALL in the reducer and modified FOLDER_UPDATE_ALL action type to save folder count to new state.

This is a PR for enhancement of https://github.com/laurent22/joplin/issues/518 in electron.

Please see the below image with enhancement

notes-count-electron

### CODE REVIEW

**Comment by foxmask** [comment]
look nice !

**Comment by laurent22** [comment]
There are issues with white spaces here too unfortunately. Please limit the commit to only the code changes.

Otherwise, I wonder about the performance of this change? It seems it's looping through all the folders to count the notes every time it needs to be refreshed. Shouldn't there be instead just one SQL query to get all the data in one go?

Should the data be cached?

Also it seems `NoteCountUtils.refreshNotesCount()` is manually called everywhere the note count might change, but there are other ways in which the note count can change, such as via sync, with the web clipper or when a note is moved to a different notebook. I think this `refreshNotesCount()` should be called based on events, either in the Redux middleware or by creating a service a bit similar to `ResourceService` which would loops through the recent changes in `item_changes` and update the note count accordingly.

**Comment by foxmask** [comment]
that'd be cool if the same was applied for tags :)

**Comment by laurent22** [comment]
Closed abandoned pull request.

**Comment by tessus** [comment]
@laurent22 dumb question, but why was this closed? The second commit (at least from the commit message) addressed your comments.

**Comment by laurent22** [comment]
The person who started the PR is gone, and I can see there's still work to do but unfortunately noone to do it.

**Comment by tessus** [comment]
Ah, ok. Too bad.

**Pull request closed without merging**
