### PR TITLE
Doc: Unformatted text -> Verbatim text

### PR DESCRIPTION
**Pull request by CyrusYip**
I think "verbatim" is clearer than "unformatted".

### CODE REVIEW

**Comment by laurent22** [comment]
How is usually called in other Markdown implementations?

**Comment by CyrusYip** [comment]
The following code is called indented code block in CommonMark, Github Flavored Markdown and Pandoc's Markdown:

```
    This text will not be formatted:

    Robert'); DROP TABLE students;--
```

**Comment by tessus** [comment]
I think the word `verbatim` is better, because it means `as is`. I think it's closer to the truth than "unformatted". The text in a code block is in fact not unformatted. It is formatted as a code block with a monospaced font.

**Comment by laurent22** [comment]
I got Unformatted Text from Microsoft Word, while Verbatim seems to be Latex terminology. I feel it's one of those things that are fine either way so don't need to be changed. "Indented code block" though is definitely not good because code should go in fenced sections, where it will be properly highlighted.

**Comment by laurent22** [comment]
Closing as per the explanation above.

**Pull request closed without merging**
