### PR TITLE
Update on Persian Language

### PR DESCRIPTION
**Pull request by mmahmoudian**
I have myself now switched to Persian translation for the time being to make sure what I translated are suitable when it is in context, therefore had to modify some of the existing translations and also added few more.

### CODE REVIEW

**Comment by tessus** [comment]
@mmahmoudian you should start with a new branch every time you submit a new PR.
The problem now is that the first 2 commits have already been applied.

I suggest you do a pull on master, create a new branch, and cherry-pick https://github.com/laurent22/joplin/pull/1590/commits/82bfb1c293304415c1b10a6dd18c85103ce21873 and create a new PR.
Oh wait, not possible. You already have a messed up master branch.

Never, ever make changes in the master branch!!!

Ok, here is how you fix this:

1. Save your current .po file.
2. Go to a directory where joplin has not been checked out  e.g. your current joplin dir is /Users/xxx/work/joplin -> go to /Users/xxx/work2/
3. delete your fork
4. fork joplin again
5. git clone <your fork>
6. git checkout -b translation
7. cp /Users/xxx/work/joplin/CliClient/locales/fa.po /Users/xxx/work2/joplin/CliClient/locales/
8. commit and create PR

**Comment by tessus** [comment]
@mmahmoudian or I can do this for you this time. just let me know.

Whatever you decide, always start with a new branch. You can also use the same name, but in that case, you will have to delete the local **and** remote branch first.

**Comment by tessus** [comment]
Btw, the conflict was not resolved correctly.

It should read `msgid "Fetching resources: %d/%d"`

**Comment by mmahmoudian** [comment]
no worries, reject this pull request, I'll make a new one. The issue is that there was no way that I could pull changes from origin to my Github fork. so I tried what people have suggested [here](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) and [here](https://gist.github.com/CristinaSolana/1885435).

To me it sounds stupid that I cannot pull all changes from the original repo in Github (or Gitlab as far as i checked today), and that caused lots of confusion and messy git log. I'll clean up everything and try again. Ignore this pull request for the time being.

Btw, thanks for the educational comments.

**Comment by tessus** [comment]
@mmahmoudian as I mentioned, I can do this (in a few seconds), and if this makes your life easier, I'm more than happy to do this. after this is done it's easier for you to start from scratch.

**Comment by tessus** [comment]
@mmahmoudian ok, I tried but found so many issues that you really better start from scratch

- you actually removed valid message ids from the file
- there are 3 occurrence where the diff shows weird data:

```
 msgid "Current version is up-to-date."
-msgstr ""
+msgstr "ورژن فعلی به<U+200C>روز است."

 msgid "Tags"
-msgstr ""
+msgstr "برچسب<U+200C>ها"

 msgid "Checkbox"
-msgstr ""
+msgstr "گزینه (چک<U+200C>باکس)"
```

- I noticed that you added `fuzzy` to some of your translations, which means they will not show up

This is currently not usable, no cherry-picking or merging will fix this. Sorry, I thought it was just a git issue, but it's definitely more than that.

**Comment by mmahmoudian** [comment]
@tessus The weird data you are referring to is [zero-width non-joiner (ZWNJ)](https://codepoints.net/U+200C?lang=fa) and is an essential character is many languages. It is one form of [Non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) can be replaced by any of the [other various types that are not full-length space](https://en.wikipedia.org/wiki/Whitespace_character#Spaces_in_Unicode). Suggest me what is the optimum replacement and I will apply it on the whole file.

Regarding the "fuzzy" marking, I can remove it, but those translations need confirmation from others users since English language structure does not easily applied on other languages and I'm not a professional translator, plus I should always consider the character count different between the English version and the Persian one since longer translation can affect the aesthetic of the software.

Regardless, I will do it the dumb way since Gihub have not implemented a nicer way to adopt latest changes from the original repo :(
1. remove the fork
2. create a new fork
3. apply the changes
4. create new pull request

P.s: Thank you for being descriptive and educational. I appreciate it.

**Comment by tessus** [comment]
@mmahmoudian By weird I meant the `<U+200C>`. Usually I wouldn't see something like this but the unicode character (which is basically a shorter space). The fact that I didn't was a bit puzzeling, but maybe my terminal has an issue. Weird, because I can see all other unicode characters...
Anyway, I've already merged your new PR. Thanks again!

**Comment by mmahmoudian** [comment]
@tessus Thank you for being patient despite of my n00b actions.

**Pull request closed without merging**
