### PR TITLE
Clipper: Resolves #123: Added script to build a directory that contains the extension's files to install the extension in development mode

### PR DESCRIPTION
**Pull request by bytrangle**
## What do these changes do
1. Add an npm script that creates a directory at `app-clipper/dev` which contains the extension's files. This directory can then be loaded in development mode on the Extension Management page.
2. When running the script, it will do the following:
- Delete the `app-clipper/dev`. It silently quit if the directory doesn't exist.
- Create a brand new directory `app-clipper/dev`.
- Create two sub-directories named `chrome` and `firefox` inside `dev`.
- Copy the following files and directories from `app-clipper` to `app-clipper/dev`:
   - manifest.json
   - background.js
   - content_scripts
   - popup/build
   - icons 
- The manifest files for Chrome and Firefox at this point contain a key that won't be accepted by either browser. Chrome doesn't recognize `applications: gecko: id` key and Firefox doesn't accept `persistent: false` key. The script will remove those keys.
3. Now, when one makes a change to files inside `app-clipper`, run  the script above again, then go to the corresponding Extension Management page and click *Reload* button to see the changes in the locally installed extension.

### CODE REVIEW

**Comment by roman-r-m** [comment]
Minor thing but: 

> Resolves #123

Pretty sure it doesn't, that issue is closed long ago

**Comment by bytrangle** [comment]
> Minor thing but:
> 
> > Resolves #123
> 
> Pretty sure it doesn't, that issue is closed long ago

I don't know where to find it, but when I opened the PR, there was a premade template that says to write **Resolves #123** if adding a new feature.

**Comment by laurent22** [comment]
> Now, when one makes a change to files inside app-clipper, run the script above again, then go to the corresponding Extension Management page and click Reload button to see the changes in the locally installed extension.

You can already do this more easily by running `npm run watch` from the popup directory, so I don't think this new script is needed.

**Comment by bytrangle** [comment]
> You can already do this more easily by running `npm run watch` from the popup directory, so I don't think this new script is needed.

I've tried that `watch` script, but I have two questions remain:
- Does it watch changes to `content_scripts` or `background.js`? It only runs when I made changes inside`popup` directory.
- Where does it output the content of the extension? Unless I'm missing something, if I simply load `joplin/app-clipper` into the Extension Management page, then it will be rejected by both Chrome and Firefox because the manifest file contains keys that are not recognized for either extension.

I know that my script may be redundant, and I will close it if it turns out to be the case, but it was written to get around the issue above, unless I'm missing something.

**Comment by laurent22** [comment]
> Does it watch changes to content_scripts or background.js? It only runs when I made changes insidepopup directory.

It doesn't need to since they are JS files that don't need to be rebuilt.

> Where does it output the content of the extension? Unless I'm missing something, if I simply load joplin/app-clipper into the Extension Management page, then it will be rejected by both Chrome and Firefox because the manifest file contains keys that are not recognized for either extension.

They output a warning but the extension should load fine. You still need of course to reload the extension from the browser whenever you make a change.

**Comment by laurent22** [comment]
Thanks for the script, but it's not clear that it's actually needed, so I'll close the pull request for now.

**Pull request closed without merging**
