### PR TITLE
Android: Make app movable to SD card again

### PR DESCRIPTION
**Pull request by Atrate**
Follow-up on pull https://github.com/laurent22/joplin/pull/787

Fixes regression introduced by https://github.com/laurent22/joplin/commit/cb3e1cf1e956e9921cc698b510eed3ac5500d402#diff-60aa334fa21790107dce7a4dd1b69c087282a1d24f2eac559fa0c031af429425

Signed-off-by: Atrate <Atrate@protonmail.com>

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks, I indeed missed that in the recent React Native upgrade. I will merge it in the next version, 1.4

**Comment by laurent22** [comment]
@Atrate, your change is good but please could you fix the conflict? It means moving your change to the new location in packages/app-mobile

**Comment by Atrate** [comment]
Force push — ready for review

**Comment by laurent22** [comment]
Perfect, thanks @Atrate!

**Pull request merged**
