### PR TITLE
ALL: Added Slovak translation

### PR DESCRIPTION
**Pull request by dodog**
Added Slovak language translation

### CODE REVIEW

**Comment by dodog** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tessus** [comment]
Thanks for the translation. May I ask how this was done? I'm asking this because we had people submit automated translations and a lot of the translations won't be correct without knowing the context.

**Comment by dodog** [comment]
I translated everything by myself. I use Joplin on my computer and iPhone with its own Joplin server. I really like the app and wanted to contribute my bit. I only tested the translation strings visually because I was not able to load the translation file to the app and test it that way. If there is some simple way to do this, please let me know.

**Comment by tessus** [comment]
Awesome, thanks for the info.

@laurent22 I can't recall, whether we have to do something in particular for new translations. But I believe no extra steps have to be taken, correct? There were extra steps way in the past, but now I think we should be good. am I correct?

**Comment by laurent22** [comment]
No it should just work if we add a language file, there's not special script to run

**Comment by tessus** [comment]
Thanks a bunch for your contribution @dodog. Must have been a lot of work.

**Comment by dodog** [comment]
@tessus I think some extra steps should have been taken after all, because the json files were not generated and the language is not available to select in menu.

**Comment by tessus** [comment]
Hmm, I thought that creating the translation files was added to the CI workflow at one point. But maybe not.

**Pull request merged**
