### PR TITLE
All: Bump KaTeX to 0.13.3

### PR DESCRIPTION
**Pull request by roman-r-m**
I reviewed the commits between the current version 0.12.0 and the latest 0.13.3. Does not seem to have any breaking changes. A few simple formulas seem to render ok.

For reference, here's how I obtained the list of changes (run from a local copy of the repo obviously):
```
git log --pretty=oneline v0.12.0..v0.13.3 | grep -v chore | grep -v docs | grep -v "build(" | grep -v "ci(" | grep -v "build:" | grep -v "ci:"
```

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for looking into it. I think you also need to run `npm run buildAssets` to compile the assets for the various platforms.

**Comment by roman-r-m** [comment]
> Thanks for looking into it. I think you also need to run `npm run buildAssets` to compile the assets for the various platforms.

Tried that but nothing changes:
```
roman@mrr:~/dev/joplin/packages/renderer$ npm run buildAssets && git diff

> @joplin/renderer@1.8.1 buildAssets /home/roman/dev/joplin/packages/renderer
> node Tools/buildAssets.js

warning: LF will be replaced by CRLF in packages/renderer/assets/highlight.js/atom-one-dark-reasonable.css.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in packages/renderer/assets/highlight.js/atom-one-light.css.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in packages/renderer/assets/katex/katex.css.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in packages/renderer/assets/mermaid/mermaid.min.js.
The file will have its original line endings in your working directory
```

**Comment by laurent22** [comment]
This script normally should take the file from node_modules and move it to the asset directory, so if the package has been updated there should be changes. Or is it the LF/CRLF warning that's hiding the changes?

**Comment by roman-r-m** [comment]
Ok, looks like it worked now; not sure what went wrong the 1st time. Updated the assets.

**Comment by laurent22** [comment]
Looks good now, thanks!

**Pull request merged**
