### PR TITLE
Updated translation

### PR DESCRIPTION
**Pull request by githubaccount073**
Added missing translations
Made adjustments to previous translations.

### CODE REVIEW

**Comment by tessus** [comment]
Thanks for the update.

**Comment by laurent22** [comment]
This translation is invalid so I've reverted it in 554c46182a6e88ba1d452a4d037afb1dfdad101f

```
Error: Command failed: msgfmt -v "CliClient/locales/sv.po"
CliClient/locales/sv.po:1067:44: syntax error
CliClient/locales/sv.po:1067: keyword "s" unknown
CliClient/locales/sv.po:1191: keyword "Alla" unknown
CliClient/locales/sv.po:1191:42: syntax error
CliClient/locales/sv.po:1192: end-of-line within string
```

Please do not manually edit .po files - you will make mistakes and break the build process. In the coming version, invalid translations will trigger a CI error so that we know earlier about it.

**Comment by tessus** [comment]
@laurent22 sorry, I usually run the `build-translation.js` locally to check for any issues, even, if I don't commit the changes. I forgot to do it this time.

**Comment by laurent22** [comment]
@tessus, no worries, I'm not as careful as you actually and just merge translation PR directly without checking so I would have been caught too. Adding this check to CI will make it easier for us to spot these issues.

**Comment by tessus** [comment]
@laurent22 adding this check to CI is definitely a good idea.

**Pull request merged**
