### PR TITLE
All: Resolves #8728: Bump mermaid version to 10.4.0 to support new chart types

### LINKED ISSUE #8728: Mermaid quadrantChart (and experimental charts) are not working
Both examples are from the Mermaidjs website (https://mermaid.js.org/syntax/quadrantChart.html) but don't work in the Joplin Android app.

```mermaid
quadrantChart
  x-axis Urgent --> Not Urgent
  y-axis Not Important --> "Important ❤"
  quadrant-1 Plan
  quadrant-2 Do
  quadrant-3 Delegate
  quadrant-4 Delete
```

and 

```mermaid
quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    Campaign A: [0.3, 0.6]
    Campaign B: [0.45, 0.23]
    Campaign C: [0.57, 0.69]
    Campaign D: [0.78, 0.34]
    Campaign E: [0.40, 0.34]
    Campaign F: [0.35, 0.78]
```

Result in "Syntax error in graph
mermaid version 9.2.2".

I also noticed that other experimental charts like Timeline and Mindmaps don't work in Joplin but I guess those are simple not available yet in Joplin. It would be great if we could enable experimental support for Mermaid in the app too.

## Environment

Joplin version: 2.11.32 (db v42)
Platform: Android
OS specifics: OxygenOS (OnePlus)

### PR DESCRIPTION
**Pull request by oj-lappi**
A bump from 9.2.2 to 10.4.0 adds at least the following chart types:
 - timeline chart
 - quadrant charts
 - Sankey diagrams (flow from one set of elements to another set, e.g. used in budget analysis)

Browsing through the forums I noticed some old topics on previous updates to the mermaid dependency. 

https://discourse.joplinapp.org/t/upgrading-mermaid/10140/8
>laurent, Jun '21:
>Normally it's easy and [even documented 30](https://github.com/laurent22/joplin/tree/dev/packages/renderer#updating-a-markdown-it-plugin) but I guess no-one took the time to do it. Often we only update when there's a bug or significant improvement in the library.

I've tested, and bumping the version number gives us all the implemented chart types out of the box (which I think counts as a significant improvement).

This would of course be a major version bump, but I can't comment on the breaking changes for v10, it seems to work fine, but I don't have the perspective that regular contributors do. The breaking changes for mermaid v10 are listed here:
https://github.com/mermaid-js/mermaid/blob/master/CHANGELOG.md#1000

Fixes #8728, #8701, #6769

### CODE REVIEW

**Comment by oj-lappi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by oj-lappi** [comment]
Related to #7629

**Comment by oj-lappi** [comment]
Can confirm that mindmap charts work after this update as well.

**Comment by oj-lappi** [comment]
Fixes/resolves #8728, #8701, #6769

**Comment by wh201906** [comment]
It seems the mermaid team has added the CJS support back, that's why bumping the version works
https://github.com/mermaid-js/mermaid/commit/04305bdddcda6970301dd7961b1d0c31997132f1

**Comment by wh201906** [comment]
@oj-lappi I found that @tessus changed more files than this PR when bumping the mermaid version. Would you please check the related files?
#5831 #6039 #6849 #7330

**Comment by oj-lappi** [comment]
Ah, I had missed the postinstall step. I'll update tomorrow. 

Is there a way to user test the mobile version on desktop btw? I've only tested the desktop app.

**Comment by tessus** [comment]
> Is there a way to user test the mobile version on desktop btw? I've only tested the desktop app.

Yep, https://github.com/laurent22/joplin/blob/dev/BUILD.md#testing-the-mobile-application

**Comment by jasonwilliams** [comment]
Great work @oj-lappi 
Do you know if the update resolves any of the issues mentioned in the master issue?

https://github.com/laurent22/joplin/issues/7629#issue-1535353471

**Comment by oj-lappi** [comment]
Just reran everything the way tessus outlined it, so now the mobile assets should all be there. I'll now try to test the mobile version, but I don't have the environment set up yet, so this may take a while.

**Comment by oj-lappi** [comment]
> Great work @oj-lappi Do you know if the update resolves any of the issues mentioned in the master issue?
> 
> [#7629 (comment)](https://github.com/laurent22/joplin/issues/7629#issue-1535353471)

Yup, out of the documented issues, both are solved (#6769, #6711)

Of the undocumented issues, the ones below with checked boxes are resolved afaict (tested on desktop):
- [X] Mindmaps don't work
- [X] tooltips don't work
 - tooltips give me the title of the charts. On 9.2.2 some charts, like the flowchart, didn't recognize titles, but titles as tooltips work even on 9.2.2 for me for e.g. the Gantt chart or Pie chart
- [ ] fa icons
 - fa icons show up in the rich text editor, but not in the markdown editor. In the rich text editor, the width of the fa icon is not used to calculate the width of the box its in, leading to part of the text being clipped off
- [ ] support dark mode
 - the images drawn by mermaid still appear with a white background

**Comment by oj-lappi** [comment]
Tested on a Pixel 7 AVD, all the charts tested render on android as well (timeline, mindmap, quadrant, Sankey). The font-awesome icons do not render on android, which makes sense since this was pretty much what I saw on desktop (fa icons only rendered in the rich text editor on desktop).

charts_0


image


Afaict, everything seems to work just fine.

**Review by jasonwilliams — APPROVED** [review]

**Comment by jasonwilliams** [comment]
I've tested these changes (on desktop), I can see the mermaid diagrams are still working. I can also see:
- Mindmap
- Timeline
- Sankey
- Quadrant

all working fine.

I can see https://github.com/laurent22/joplin/issues/6769 is fixed in this PR.
I can also see https://github.com/laurent22/joplin/issues/6711 is fixed in this PR.

@laurent22 you will nee to approve the workflow so it can run.
I've approved these changes but @tessus may also want to look.

**Review by tessus — APPROVED** [review]
LGTM

**Comment by laurent22** [comment]
That's great, thanks guys for looking into this!

**Pull request merged**
