### PR TITLE
All: Fixes #6956: set updated_time when a note's custom sort order is updated, so it syncs 

### LINKED ISSUE #6956: Custom sort order not synchronized
## Environment
_Platform_: 
Windows + Android

_Windows_:
Joplin version: Joplin 2.8.8 (prod, win32)
Sync-Version: 3
Profil-Version: 41
Revision: c2a6a13
Platform: 
OS specifics: 

_Android_:
Joplin version: 2.8.1
Database version: 41

## Steps to reproduce

1. create notebook on Windows
2. create some tasks in the notebook
3. set sort order to custom
4. move tasks to desired order
5. sync to Android (in my case via filesystem on both systems, filesystem folder synced via syncthing)
6. open notebook on Android
7. make sure custom sort order is selected (not sure if this setting itself is synced?)
8. => sort order is not the same as on Windows

## Expected: 

Sort order should be the same for the notebook on both Windows and Android after synching (when custom sort order is selected in both - ideally the selected sort order should be synced, too).

This is especially frustrating when trying to create a todo list of tasks with prioritized order...

### PR DESCRIPTION
**Pull request by TaoK**
As detailed in issue #6956, when you reorder notes according to a custom sort, and don't make any further updates to those notes, the sort order does not propagate to other synchronized clients.

This commit fixes this, by ensuring the update_time, used for synchronization,
*is* updated even though the update is made with "autoTimestamp: false".

### CODE REVIEW

**Comment by TaoK** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
updated_time is already updated in the save() call

**Comment by TaoK** [comment]
(moving comment to the pull request - I had previously put it in the issue)

In defense of this "set updated_time" change, a search for `autoTimestamp` in the codebase yields a reasonably even division between two types of usecases:

* Places where we are trying to preserve user_updated_time, and we explicitly set updated_time as in this change:
  * `NotePropertiesDialog.jsx#closeDialog()`
  * `Note.ts#moveToFolder()`
  * `RevisionService.test.ts#'should preserve user update time'`
  * `notes.ts#POST`
  * `ShareService.ts#shareNote()`
* Places where we are performing import-related activities, and explicitly want to preserve both `user_updated_time`, **and** `updated_time`

So it looks like not setting `updated_time` in `Note.ts#updateNoteOrder_()` was a simple oversight, and this change is a simple bugfix.

**Comment by laurent22** [comment]
That looks like the right fix, thank you for looking into it. Could you add a test for it please?

**Comment by TaoK** [comment]
@laurent22 test added, thx!

**Comment by laurent22** [comment]
Thanks for the fix @TaoK!

**Pull request merged**
