### PR TITLE
Android: Prevent Joplin from crashing when downloading large files

### PR DESCRIPTION
**Pull request by roman-r-m**
Fixes https://github.com/laurent22/joplin/issues/2424
Fixes https://github.com/laurent22/joplin/issues/2943
Not exactly fixes but makes obsolete https://github.com/laurent22/joplin/issues/3107

Calling text() on a response object returned by RNFetchBlob (in case it's a blob that's been written to a file) will cause rf-fetch-blob to read the file, encode it in base64 and send over the RN bridge. This is often enough to crash the application with OutOfMemoryError.

When downloading resources it seems we do not care about the response anyway to it seems safe to return an empty json:
https://github.com/laurent22/joplin/blob/ac2635a3632a2bd75caa9eabe97695042c51defb/ReactNativeClient/lib/services/ResourceFetcher.js#L172-L178 .

TODO
- [x] Check OneDrive
- [x] Check WebDAV / NextCloud
- [x] Test
- [ ] (Optional) disable max resource size limit

### CODE REVIEW

**Comment by roman-r-m** [comment]
OneDrive apparently does not allow uploading files > 4mb so no issue here.

**Comment by laurent22** [comment]
Very good catch, thanks for looking into it. Have you confirmed that the app no longer crashes with this fix? If we add this, we should also add a comment over the line to explain why we return an empty response.

Also doesn't the WebDAV API have the same issue?

**Comment by roman-r-m** [comment]
Yes this changes fixes the crash for Dropbox - I was able to sync a 60mb file that was crashing the app before.

WebDAV definitely has the same issue. I was testing with Nextcloud and could reproduce the crash itself but could not get the same stacktrace with OutOfMemoryError. In fact from a quick glance I could not see the reason for the crash. But in any case a similar fix worked there.

This is still WIP - I need to test more with different combinations of sync methods and encryption on/off

**Comment by roman-r-m** [comment]
So I've tested WebDAV and the fix works there as well so I moved it to the shared file.

Still could not see that same OutOfMemoryError and without root on my device I could not quite figure out the reason for the crash. I suspect the app gets killed by the system OOM killer as I can see in log that a lot of processes die at the same time, not only Joplin. Not sure why the difference compared to Dropbox.

**Comment by roman-r-m** [comment]
Not sure why tests are failing, seems like a false alert.

**Comment by kowalskidev** [comment]
> So I've tested WebDAV and the fix works there as well so I moved it to the shared file.
> 
> Still could not see that same OutOfMemoryError and without root on my device I could not quite figure out the reason for the crash. I suspect the app gets killed by the system OOM killer as I can see in log that a lot of processes die at the same time, not only Joplin. Not sure why the difference compared to Dropbox.

You don't need to root your device you can check log in terminal. Try to run `npm start` command in ReactNativeClient folder in Visual studio code terminal and use Android Studio to build the app and run app from android studio it will open emulator where you can use Joplin app and all log can be seen in your terminal. 

@roman-r-m  If you stuck somewhere please don't hesitate to ask me I would love to help you.

**Comment by roman-r-m** [comment]
@kowalskidev that's just to view log - that does not require root indeed (I normally use `adb logcat`). I was talking about getting a crash dump from `/data/anr` which is not accessible without root.

I actually later found a way to extract it but there was nothing related to my crash there, it was some older log.

**Comment by kowalskidev** [comment]
> if you have time - try it out and see if you can spot anything there.

Yea Sure. I would to try out! I'll ping you if anything popups..

**Comment by laurent22** [comment]
> Still could not see that same OutOfMemoryError and without root on my device I could not quite figure out the reason for the crash. 

Even without root you can export a log from the dev options, and it should include a stack trace. https://joplinapp.org/debugging/ I expect we can merge your PR but just to be sure could you check the crash log?

**Comment by roman-r-m** [comment]
Got the report but still can't see the reason for the crash. This seems relevant:
```
05-02 14:29:06.113  1319  2292 I WindowManager: WIN DEATH: Window{a05ff99 u0 net.cozic.joplin/net.cozic.joplin.MainActivity}
05-02 14:29:06.122   584   584 I Zygote  : Process 12762 exited due to signal (9)
05-02 14:29:06.306  1319  6006 I ActivityManager: Process net.cozic.joplin (pid 12762) has died: fore TOP 
```

I do see lots of apps being killed at the same time and there are lines like these
```
05-02 14:28:23.611  1319 13110 I ActivityManager: Killing 13444:com.android.calendar/u0a12 (adj 902): iAwareF[LowMem](cch-empty)
...
05-02 14:29:58.828  1822  1822 I PGApp   : onLowMemory...
```
This all leads me to believe this was an OOM killer at work. I know in Linux it prints to `dmesg` when an app is killed but dmesg is not accessible without root and in any case I am not sure Android works the same here.

**Comment by laurent22** [comment]
That seems like a good change, and it's well explained in the code comments so let's merge. Thank you for looking into this @roman-r-m!

**Pull request merged**
