### PR TITLE
All: Resolves #5808: Remove patch for multimd, and update package instead

### LINKED ISSUE #5808: New Sync-Scroll out-of-sync case.
Hello,
I have a note  that go crazy with the new Sync-Scroll.

It is a table, a very long table (but I made also a textbench file for debug), with some empty row at the end (I use to add empty lines at the end and populate it when necessary).

It happens with Joplin 2.6.2 (prod, win32).
With the old 2.5.12 the behavior was "normal", but with 2.6.2 this note is TOTALLY out of sync; I should scroll all the viewer pane before the editor moves.

## Environment

Joplin version:  Joplin 2.6.2 (prod, win32) Revisione: 5a82f5d  - Portable package
Platform: Windows
OS specifics: Windows 10 Pro 1903

## Steps to reproduce

1. Import and open the note  "file_per_bug_sync-scroll.md" attached
image

2. Add some lines  like in the pictrure (I copy and paste the selected lines)
image

3. Scroll the editor pane and the viewer pane

The effect is much more evident with the second file, "Diario  - 2021 (working copy).md"; if you scroll a little in the editor pane
 the preview pane scroll to the end, and the table is very long! 

[Diario  - 2021 (working copy).md](https://github.com/laurent22/joplin/files/7627171/Diario.-.2021.working.copy.md)
[file_per_bug_sync-scroll.md](https://github.com/laurent22/joplin/files/7627172/file_per_bug_sync-scroll.md)

### PR DESCRIPTION
**Pull request by CalebJohn**
Version 4.1.2 was release 10 days ago, making our patch unnecessary. 

The disturbing thing, is that apparently the [patch didn't work](https://github.com/laurent22/joplin/issues/5808#issuecomment-1021342244) when releasing the code. We'll have to keep that in mind for next time we patch (maybe that's why patching was removed in the first place?).

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pull request and indeed I'm not sure why it didn't pick up that patch. Also looks like you need to update the Dockerfile: https://github.com/laurent22/joplin/runs/4940887819?check_suite_focus=true#step:6:4956

**Comment by CalebJohn** [comment]
Thanks for patching that up @tessus!

**Comment by tessus** [comment]
You're welcome.

**Comment by laurent22** [comment]
Thanks for the update, let's merge then.

**Pull request merged**
