### PR TITLE
Desktop : Adding the title option in the url promt

### LINKED ISSUE #1731: Add title to hyperlink
It would be great, if the title of a website can be automatically queried with a web request and inserted as text, if a new hyperlink is added with the hyperlink button.

image
image
image

**Bonus**
An even enhanced version: Just paste a hyperlink into the Joplin editor and Joplin will automatically convert the hyperlink to a markdown link including the website title as description. This could be an option, that this behavior can be enabled or disabled if desired.

### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

### PR DESCRIPTION
**Pull request by Rishgod**
fixes #1731 

The previous dependency we were using, namely Smalltalk had this bottleneck for only one one user input prompt, so I tried to use a different dependency on the suggestion of @laurent22  

Anyway tell me if this is useful and if we can also add auto extraction of tittle (by using regexp on the URL)

@PackElend @tessus @laurent22  @Perkolator any inputs

# Before

Adding tiitle

# After

Adding tiitle-solve

### CODE REVIEW

**Comment by Rishgod** [comment]
I have doubts about how this will pass the build test since I added new dependencies(i updated the package.json file so there should not be any conflict), @laurent22 can please clarify that

**Comment by Rishgod** [comment]
@PackElend label me please

**Comment by laurent22** [comment]
Closing this for now as the point of the initial issue was to automatically add the title, which this PR doesn't do.

**Comment by Rishgod** [comment]
> Closing this for now as the point of the initial issue was to automatically add the title, which this PR doesn't do.

Okay 🥺

**Comment by PackElend** [comment]
I reckon Laurent had something like https://meta.discourse.org/t/rich-link-previews-with-onebox/98088 in mind.
You may can rewrite your code?

**Pull request closed without merging**
