### PR TITLE
Fix issues with webDAV sync against Cyrus IMAP

### PR DESCRIPTION
**Pull request by hattne**

### CODE REVIEW

**Comment by laurent22** [comment]
Hmm, thanks for the pull request but I'm not sure accepting 403 should be ok. That's what's returned for invalid credentials and we want to notify users about this, not silently ignore it.

Also why is the Content-Type needed?

Are there no config options that can be set on Cyrus to fix these issues?

**Comment by hattne** [comment]
> Hmm, thanks for the pull request but I'm not sure accepting 403 should be ok. That's what's returned for invalid credentials and we want to notify users about this, not silently ignore it.

Yes, that had me baffled too.  So I looked it up (https://tools.ietf.org/html/rfc4918#section-9.3.1), and while I still think it makes more sense to return 405, I don't know that returning 403 is violating the RFC.  I'll take this to the Cyrus list to see what they say.

Given that there seems to be some disagreement among webDAV servers on what to return when  the collection exists, maybe a sane approach is to PROPFIND if MKCOL fails.  If PROPFIND succeeds, we're all good no matter how MKCOL failed.

Regarding notifying users about wrong credentials: would this not become apparent before the MKCOL is run?

> Also why is the Content-Type needed?
> 
> Are there no config options that can be set on Cyrus to fix these issues?

As far as I understand the standard, clients must supply the content type, but I have only skimmed through the relevant documentation for now.

**Comment by hattne** [comment]
> > Hmm, thanks for the pull request but I'm not sure accepting 403 should be ok. That's what's returned for invalid credentials and we want to notify users about this, not silently ignore it.
> 
> Yes, that had me baffled too. So I looked it up (https://tools.ietf.org/html/rfc4918#section-9.3.1), and while I still think it makes more sense to return 405, I don't know that returning 403 is violating the RFC. I'll take this to the Cyrus list to see what they say.

After a bit more of skimming, a 403 response is making more and more sense to me: the server forbids the request to create the resource—the reason the server chooses to do so may be given in the response.  If the user is not authorized to create the resource, I would expect a 401 response instead.

**Comment by tessus** [comment]
@hattne please keep use apprised of Cyrus' answer. IMO it is a bad idea to silently ignore 403 unless you guard it against Cyrus IMAP servers only or check the response for the proper reason.

**Comment by hattne** [comment]
> @hattne please keep use apprised of Cyrus' answer. IMO it is a bad idea to silently ignore 403 unless you guard it against Cyrus IMAP servers only or check the response for the proper reason.

The thread on info-crus starts here: https://lists.andrew.cmu.edu/pipermail/info-cyrus/2019-November/041053.html; there haven't been any replies yet, but I'll make sure to report back whatever comes out.  In case nothing comes out, I'll read those RFC:s myself in an attempt to sort this out.

I agree: in general, silently ignoring error messages is no good.  However, it seems Joplin will attempt to create this resource whether it exists or not, so there will be an error, and it will have to be ignored.  Checking for existence before the MKCOL is a bit of wart because it creates a race condition.  So I think you're right in that the correct solution is to determine whether the error is indeed due to the existence of the collection prior to MKCOL.  Alternatively, an easier (but maybe not quite as correct) solution: check whether the collection exists after MKCOL fails, regardless of the kind of error returned (after all, if it exists the purpose of the MKCOL has been fulfilled).  I could revise the patch thusly, if you think it'd be worthwhile.

**Comment by laurent22** [comment]
The best option is to check first for existence and then run MKCOL if the dir doesn't exist but as you point out there would be a race condition.

Checking after is not an option because that would mean 2 requests for each MKCOL, which would slow down the sync process startup too much.

Let's wait a bit for their answer, as Joplin works with many WebDAV servers as it is, and it seems Cyrus are the only ones doing this.

**Comment by laurent22** [comment]
Closing inactive PR. Feel free to comment here if there's any news from Cyrus.

**Pull request closed without merging**
