### PR TITLE
Desktop: Fixes long lines wrapped issue

### PR DESCRIPTION
**Pull request by amitsin6h**
#### "Desktop" for the Windows/macOS/Linux app (Electron app)
- This change allows warping long lines in the view area of note editor.
- Reference of the issue https://github.com/laurent22/joplin/issues/2170

### CODE REVIEW

**Comment by amitsin6h** [comment]
@PackElend @tessus please review and please help me in resolving the conflict.

**Comment by tessus** [comment]
I'm not sure how you can have a conflict when creating a branch from upstream master. 

Did you pull the latest changes from upstream?

**Comment by tessus** [comment]
I think something similar happened with your other PR. 

It seems you cloned the project a while ago and never pulled the latest changes from upstream.

**Comment by tessus** [comment]
This PR can't be used. The file you have changed does not even exit anymore.

So here is how it works:

```
git remote add upstream https://github.com/laurent22/joplin.git
git checkout master
git pull upstream master
git checkout -b your-new-branch
```

**Comment by amitsin6h** [comment]
Thanks @tessus for helping me out.

**Comment by tessus** [comment]
You are welcome.

If you have additional git questions, please ask them in the [Development](https://discourse.joplinapp.org/c/development/6) category in the foum. This way others will benefit from the answers as well.

**Comment by amitsin6h** [comment]
Updated PR https://github.com/laurent22/joplin/pull/2447

**Pull request closed without merging**
