### PR TITLE
feat: basic minio support

### PR DESCRIPTION
**Pull request by matchett808-gh**

### CODE REVIEW

**Comment by matchett808-gh** [comment]
Consider this a WIP

**Comment by matchett808-gh** [comment]
2 issues from this PR being elsewhere:
- If I were to click on Check synchronization configuration it would error TypeError: options.endpoint is not a function.
- If I synced my files to S3, then delete my local files on ~.config/joplindev-desktop, and try to sync back all the files from S3. It would error UriParameterError: Expected uri parameter to have length >= 1, but found "" for params.Bucket and not sync.

first one is done, not sure what to do about the 2nd one
There's a change in here I don't recognise (possibly made by the linter)

**Comment by laurent22** [comment]
Is the pull request not currently working? If so, would you mind if I close it for now and you re-open once it's working?

**Comment by laurent22** [comment]
Closing for now, but you're welcome to re-open once it's complete.

**Pull request closed without merging**
