### PR TITLE
Navigating through the search Results

### LINKED ISSUE #6352: Desktop: Navigate through the Search Results
## Environment

Joplin version: Joplin 2.7.15 (prod, darwin)
Platform: macOS
OS specifics: Monterey Version 12.3 (M1)

## Steps to reproduce

1. Search For a word in the search bar
2. It will show all the found results.
3. Try to use enter or arrow keys to navigate to the next result

## Describe what you expected to happen
When clicked enter or arrow keys, it should navigate through all the founded results

## Logfile
No Logs

### PR DESCRIPTION
**Pull request by kamalbuilds**
Resolves #6352 

- Desktop , MacOS : navigate through all the founded results , When up and down arrow keys are clicked.

Fixes Bug

Gist of solution :- When Up and down keys are pressed , Callback function is fired which helps in navigating the results.

### CODE REVIEW

**Comment by laurent22** [comment]
There's something wrong with your PR as it has 132 changed files.

**Comment by laurent22** [comment]
But anyway this is not a valid issue. See https://joplinapp.org/gsoc2022/pull_request_guidelines/

**Comment by kamalbuilds** [comment]
this was a bug but i suppose u are reffering to this -> issues with labels such as "high", "medium" or "enhancement as valid ones right?

**Comment by kamalbuilds** [comment]
description-> There are not multiple changes , they have occured automatically. My changes could be found in the commits list.

**Comment by Daeraxa** [comment]
Did you do a `git add .` or something? There is tons of stuff in there that simply shouldn't be committed or has been changed.

**Pull request closed without merging**
