### PR TITLE
All: Translation: Update sr_RS.po

### PR DESCRIPTION
**Pull request by Vaso3**
Updated Serbian translation.

### CODE REVIEW

**Comment by laurent22** [comment]
Validation failed: https://github.com/laurent22/joplin/pull/5218/checks?check_run_id=3117931967#step:8:555 You should use PoEdit to avoid errors as these po files aren't meant to be edited manually with a text editor.

**Comment by tessus** [comment]
@Vaso3 did you see Laurent's comment?

**Comment by Vaso3** [comment]
Yes, sorry. If I open it in PoEdit and save it, would that fix the problem?
I'm not sure what is the problem here, is it CRLF?

**Comment by tessus** [comment]
>  If I open it in PoEdit and save it, would that fix the problem? 

I can't say. Try to save it and push another commit. In that case we can see if that fixed it.

**Comment by Vaso3** [comment]
Alright, will do that.

**Comment by tessus** [comment]
Thanks, apparently this fixed it.

**Pull request merged**
