### PR TITLE
Desktop: Updated Linux icon based on GNOME design guidelines

### PR DESCRIPTION
**Pull request by elsiehupp**
The fill and glyph are identical to the pre-existing JoplinIcon.svg, scaled and cropped using the GNOME icon template. This preliminary icon does not include any 3D styling, but it could easily be added in the future. GNOME encourages the use of SVG icons, but I exported PNG icons in all the existing resolutions because I don't know how Joplin packages icons for Linux.

### CODE REVIEW

**Comment by elsiehupp** [comment]
I added an alternate icon based on the GNOME Contacts icon:

https://gitlab.gnome.org/GNOME/gnome-contacts/-/blob/master/data/icons/hicolor/scalable/apps/org.gnome.Contacts.svg

I didn't export it as the various sizes of PNG, but it should be fairly straightforward for you to do so if you choose to use this variant.

**Comment by laurent22** [comment]
Can we see the icons before and after, side by side?

**Comment by elsiehupp** [comment]
> Can we see the icons before and after, side by side?

Here are comparisons with other GNOME icons in my GNOME dock:
existing_icon
gnome_icon
book_icon

To be clear, circular and oblong-rectangular icons are not uncommon in GNOME. Just the only one I have in my dock at the moment is Firefox. The Discord icon has slightly nonstandard corner radii, but it's barely noticable.

Again, this is the GNOME outline template (with the blue line representing the minimum recommended resolution of detail):

template

Icons with Apple-style outlines are not exactly uncommon, but they look increasingly out of place. (FWIW KDE doesn't seem to have any icon guidelines, because KDE is a free-for-all.)

**Comment by laurent22** [comment]
Is that the first or second one that you've created? We can't really use the third one for now as, although I think it looks nice, it should be part of a wider discussion.

Also I forgot about this, but we don't manually create images. Instead they must be generated dynamically generated using "generate-image.js". So you would create a base file, probably a high resolution of the icon, and you would generate dynamically the other resolutions. I would suggest not to have both SVG and PNG files, just one or the other, so probably only keep the PNG because that's easier to dynamically generate.

**Comment by elsiehupp** [comment]
The first image is the existing icon (which is roughly iOS-style); the second image is the icon with a square GNOME-style outline; and the third image (of course) is the icon mashed up with the GNOME Contacts icon.

GNOME specifically states that SVG icons should be used for superior scalability. According to the KDE documentation, they follow the freedesktop icon specification, which allows either SVG or PNG (or XPM, which is deprecated), with PNG allowing greater backwards compatibility than SVG.

https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

KDE's icon design guidelines are largely equivalent to GNOME's, with the main difference being that they strongly encourage otherwise flat icons to use a beveled bottom edge (which you can see in the calendar and terminal icons in my screenshot). They also encourage subtle gradients and foreground shadows, though the exact type of shadow is somewhat peculiar.

https://develop.kde.org/hig/style/icons/colorful/

I could update the roundrect version of the icon to match the additional KDE recommendations, but in the case of the notebook version it's probably better without the foreground shadow.

Looking at the GNOME guidelines again, the sharp 45º shadow doesn't feature in any of them, so it may be preferable to do without it for the roundrect icon, too.

https://developer.gnome.org/hig/stable/icon-design.html.en

As far as icon formats go, I would recommend keeping the SVG as the "source" for the icon in the repository even if it doesn't make it into the built version. And in general scaling down large PNGs seems to have safe visual results, since that's what Apple does in most circumstances (even though they require multiple resolutions).

**Comment by elsiehupp** [comment]
Another thing to clarify: I more or less used the existing file organization, but it might make sense to move, say, the PSD files and some of the SVG files (which exist as fully editable "source" files but aren't directly used in the end product) to a separate folder, such as [Assets / ImageSources](https://github.com/laurent22/joplin/tree/dev/Assets/ImageSources), or something similar. In general it would be nice if the organization of the Assets folder were more clearly documented, however you prefer to do so.

**Comment by MrCarroll** [comment]
I've accepted @elsiehupp 's PR for the snap build, making this the default desktop icon for now
image

I'll push this to users for the 1.7 release, since snaps update automatically it makes it a decent avenue for collecting feedback and adapting to it if needs be, I don't feel it misrepresents Joplin branding so I'm hopeful @laurent22 is happy with me testing it. 

I think overall the changes are subtle but positive, if you'd like me to do the same trial by fire on the AppIndicator icons that were proposed I think these would be very much appreciated by the community, since they're noticably more aligned with the majority of themes and the difference is immediately noticable when seen side by side.

**Comment by laurent22** [comment]
No problem with the icon @MrCarroll, thanks for letting me know.

**Comment by laurent22** [comment]
As I understand this pull request can now be closed since the icon can be added directly to the Linux package? In general I would indeed prefer this approach: we provide one Linux icon, then individual packages or distros are free to change it to something else.

**Comment by elsiehupp** [comment]
> As I understand this pull request can now be closed since the icon can be added directly to the Linux package?

Yes and no. If you approve of this icon, ideally it would be used uniformly by the AppImage, Snap, Flatpak, etc., for consistency. I say "if you approve" because you seem to be the final authority on Joplin as a brand. The main reason to use the version of the icon I created (or something similar) is that it more closely aligns with the GNOME and KDE icon design guidelines.

**Comment by laurent22** [comment]
I'm afraid we're going to keep the default Linux icon as it is, but I give my permission to package maintainers to use whatever icon they want as long as the overall look is similar to the original icon.

**Pull request closed without merging**
