### PR TITLE
Desktop: Disable Toggle Editor Layout Shortcut and Button in Empty Notebook

### LINKED ISSUE #2608: ctrl + L and  toggle editor layout button is not disabled in empty notebook
## Environment

Joplin version: Joplin 1.0.178
Platform:  Windows
OS specifics: Windows 10

I'm not sure if this was deliberately designed to do this,  **but ctrl + L and  toggle layout button is not disabled in an empty notebook** (notebook without notes), the Pane toggle icon is disabled when a notebook is empty and i believe this should also apply to the shortcut associated with this functionality. 

## Steps to reproduce

1. Create an empty note
2. On the menu, go to **views**
3. click on  **Toggle editor layout** or type CTRL + L
4. Go to an existing notebook (or create one) with notes and you'll notice that the layout changes.

## Describe what you expected to happen
1. Create an empty note
2. Go to **views**
3. **Toggle editor layout** and CTRL + L should be disabled like the toggle layout icon

### PR DESCRIPTION
**Pull request by Runo-saduwa**
fixes #2608 

 This PR causes the toggle editor layout shortcut and button (ctrl+l/cmd+l) to be disabled in an empty notebook (notebook without notes) just like the toggle editor layout icon. I still don't know if its done by design, but it doesn't seem right, so figured out i just solve it

**BEFORE**
joplin-toggle-error

**AFTER**
joplin-toggle-fix

### CODE REVIEW

**Comment by Runo-saduwa** [comment]
@PackElend Please label me, Thanks.

**Comment by tessus** [comment]
This brought something else to my attention. If you select multiple notes, it is still possible to use the `Layout` toolbar button. This has nothing to do with this PR, but should be fixed as well.

**Comment by tessus** [comment]
In the future, please use the github way to link issues. Don't write `This is a fix for ...`.

Write in a separate line: `fixes #2628` or `closes #2628`

**Comment by Runo-saduwa** [comment]
> This brought something else to my attention. If you select multiple notes, it is still possible to use the Layout toolbar button. This has nothing to do with this PR, but should be fixed as well.

Noted. i'll look into it and fix it

**Comment by Runo-saduwa** [comment]
> Write in a separate line: fixes #2628 or closes #2628

Oh, i'll do this next time. thanks

**Comment by mic704b** [comment]
> Oh, i'll do this next time. thanks

@Runo-saduwa Tessus means to update the first PR post in this thread, adding the comment `fixes #2628` or `closes #2628`.   You can edit it and do it this time.

It is important to do it, because if/when this PR is merged, github will look for that text in your PR, and automatically close the associated issue. If you don't, it will have to be done manually.

Just to be clear, he doesn't mean to add this to the code.  Issue numbers should nearly almost never appear in the code.

**Comment by Runo-saduwa** [comment]
@mic704b thanks for the clarification, I’ve done that. I never know that was how GitHub closes issues.

**Comment by laurent22** [comment]
Looks good, thanks @Runo-saduwa.

**Pull request merged**
