### PR TITLE
Script to install on Ubuntu with Gnome Shell

### PR DESCRIPTION
**Pull request by tanrax**
Add script to install on Ubuntu or Debian with Gnome Shell Icon

### CODE REVIEW

**Comment by laurent22** [comment]
This is very useful, especially the desktop shortcut, but obviously it only works for v106. I wonder if it could be made into a shell script that we add to the repo? Then we could just add the instructions `wget https://.../install_ubuntu.sh && chmod 755 install_ubuntu.sh && ./install_ubuntu.sh`.

**Comment by tanrax** [comment]
Now admits the latest version

**Comment by tanrax** [comment]
Do I create a script file?

**Comment by laurent22** [comment]
Yes if you could put all this in a Bash file that would be great.

**Comment by tanrax** [comment]
To test it, both pull must be integrated.

**Pull request merged**
