### PR TITLE
mermaid version update

### LINKED ISSUE #11327: Add Support for Mermaid 11.4.0
### Operating system

macOS

### Joplin version

3.1.20

### Desktop version info

Joplin 3.1.20 (prod, darwin)

Client ID: 1dfa99475d17480db74956dc092b7dfc
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 8199362

Backup: 1.4.2
Combine notes: 1.2.2
Draw.io: 2.2.0
Embed Search: 2.0.0
Freehand Drawing: 2.11.0
Inline tags: 1.3.0
Insert Date: 1.0.1
Note Tabs: 1.4.0
Quick Links: 1.4.1
Rich Markdown: 0.15.0
Templates: 2.4.0
Time Slip: 0.2.0

### Current behaviour

Joplin is using Mermaid 10.9.1.  

### Expected behaviour

Newer Mermaid releases have added a number of new diagram types. 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by LEVIII007**
fixes : #11327 
Platform:
All: Applicable to all platforms supporting the Joplin application.
Summary:
This PR updates the mermaid dependency to version 11.4.0 to support new features and improvements, including enhanced diagram types, updated class diagram rendering, and bug fixes.

Key Changes:
Upgraded mermaid from 10.9.1 to 11.4.0.
Introduced support for new diagram types and features:
Kanban board diagram : A new type of diagram added for better project management visualization.
Class diagram enhancements :
New unified rendering for class diagrams.
Introduction of a "classBox" shape for more versatile diagrams.

Benefits:
Enables the use of the latest diagrams and features introduced by Mermaid.

References:
Version Update: [mermaid@11.4.0](https://github.com/mermaid-js/mermaid/releases/tag/mermaid%4011.4.0)
Impact:
No breaking changes anticipated.
Enhances Joplin's diagram capabilities by leveraging new features provided by the latest Mermaid release.

After the changes  :
Screenshot from 2024-11-09 13-16-52

Before :
Screenshot from 2024-11-09 14-51-33

### CODE REVIEW

**Comment by LEVIII007** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
Please check previous Mermaid updates, there's a script to run to update all assets

**Comment by LEVIII007** [comment]
@laurent22  will do that!

**Comment by LEVIII007** [comment]
recheck

**Pull request merged**
