### PR TITLE
PDF Viewer: embedded viewer options

### PR DESCRIPTION
**Pull request by asrient**
This is a subset of the previously opened PR: https://github.com/laurent22/joplin/pull/6740

## Features added to the viewer

- Print pdf.
- Download pdf.
- Current active page indicator.

## Screenshot

Screenshot 2022-08-14 at 9 59 48 PM

## Notes

I have kept option as text buttons for now for simplicity, will discuss the UI in forum and add support for icons if needed.

### CODE REVIEW

**Comment by laurent22** [comment]
No idea what you're doing here. It contains some of the same code as in the other two PRs.

**Comment by asrient** [comment]
> No idea what you're doing here. It contains some of the same code as in the other two PRs.

Actually the next 2 PRs have code changes that depends on some refactoring done in #6747, I will update these 2 PRs once the 1st one is merged or else I have to make redundant changes now.

**Comment by CalebJohn** [comment]
@asrient You can change the "base" branch of the PRs so that they point to the same branch as #6747 (asrient:pdf-scroll-progress). This will make it so that Github only shows how this branch is different from the other. Once #6747 is merged GitHub will automatically change the base branch of this PR to laurent22:dev.

**Comment by asrient** [comment]
> @asrient You can change the "base" branch of the PRs so that they point to the same branch as #6747 (asrient:pdf-scroll-progress). This will make it so that Github only shows how this branch is different from the other. Once #6747 is merged GitHub will automatically change the base branch of this PR to laurent22:dev.

Hi, this sounds like a good idea, will do that. Thanks.

**Comment by asrient** [comment]
@CalebJohn I was trying this out, I took a pull from `asrient:pdf-scroll-progress` and fixed the merge conflicts but when I tried changing the base branch I realised I couldn't since `pdf-scroll-progress` branch does not exist on `laurent22/joplin`. 
I can only create such a PR on my forked copy. Is there any flaw in my understanding? Any articles to refer on this?
Screenshot 2022-08-17 at 11 18 45 PM

**Comment by CalebJohn** [comment]
@asrient It appears to be a limitation of GitHub. Sorry, I should have checked before letting you know about the feature.

**Comment by asrient** [comment]
> @asrient It appears to be a limitation of GitHub. Sorry, I should have checked before letting you know about the feature.

No issues CalebJohn.

**Comment by laurent22** [comment]
@asrient, please fix the conflicts and rebase your branch so that it can be reviewed.

**Comment by asrient** [comment]
> @asrient, please fix the conflicts and rebase your branch so that it can be reviewed.

I will update this once #6748 is merged, since #6748 introduces fontawesome icons and it will be utilized here too.

**Comment by laurent22** [comment]
That other PR is now merged, please have a look at the conflicts and rebase.

**Comment by asrient** [comment]
Yes I will update it soon.

**Comment by laurent22** [comment]
> Yes I will update it soon.

How soon? Because it's been 5 days

**Comment by asrient** [comment]
> How soon? Because it's been 5 days

Sorry for this, I was bit stuck with some full-screen viewer bugs, I was holding on to this update because I thought the bug might be a part of this change.
I have posted a new PR for this now: https://github.com/laurent22/joplin/pull/6800.

**Pull request closed without merging**
