### PR TITLE
add option to show line numbers in editor

### PR DESCRIPTION
**Pull request by tessus**
This also allows code folding in the editor.

The editor options `showLineNumbers` and `showFoldWidgets` are `true` by default.
But they only show up, if the gutter is displayed, which is explicitly disabled in Joplin.
Therefore this change only toggles the gutter.

see https://discourse.joplinapp.org/t/feature-request-folding-sections-of-text/5752?u=tessus

### CODE REVIEW

**Comment by tessus** [comment]
I can also create 2 options: one for line numbers and the other for folding marks. But I thought it's not unreasonable to combine them.

**Comment by laurent22** [comment]
I feel this feature is incomplete if what's shown in the text editor is not reflected in the viewer pane, and doing so would be very hard to implement. So we would have to leave as it is, which for me looks a bit broken.

**Comment by tessus** [comment]
If you take the code folding alone, I agree. But I think that many people would just be able to show line numbers (in which case the folding marks are just a bonus).

Showing line numbers in an editor is a fundamental editor feature. I haven't done any research about the statistics. I couldn't live without ine numbers in Sublime Text. Not sure how important it is in Joplin. But hey, if people want it, why not? It's not really my place to tell them they don't need it in Joplin.

**Comment by tallguyjenks** [comment]
i want this feature very badly, not just line numbers but also relative line numbers. like all my editors vscode/rstudio/vim etc. i use the vim keys mode and having the relative line numbers help with navigation through the text and in the desktop version this is more difficult than the CLI version. it would be great if desktop had at least line numbers to start if not relative line numbers as a toggle-able option

**Comment by tessus** [comment]
Using relative line numbers is not possible. react-ace uses brace which in turn uses an ace version that is several years old (1.2.9). The dev of brace seems to have abandoned the project, so that's that.

**Comment by tessus** [comment]
@laurent22 what are we going to do with this? Some people like line numbers, others don't. So an option makes sense. But if you don't want this in the code, we can close it to make the list of PRs shorter.

**Comment by laurent22** [comment]
I wonder what's the use case for the line numbers? Just for the vim users?

As for folding marks, I'd prefer if we disable them as we can't make this work with the preview and I'm sure half of users who'll use this will ask in the forum why is the preview not updated.

**Comment by tessus** [comment]
> I wonder what's the use case for the line numbers? Just for the vim users?

Not necessarily. I know people who like line numbers in their editor. I couldn't live without them in Sublime Text. But as I mentioned before, I can't say how important they are in Joplin.
But for vim users line numbers makes their lives a lot easier.

> As for folding marks, I'd prefer if we disable them as we can't make this work with the preview and I'm sure half of users who'll use this will ask in the forum why is the preview not updated.

Makes sense. On the other side, I've noticed that it is a very convenient way to jump to the next section in the text (especially if your sections are long). You just hit the folding mark et voilà - you are at the next section. But I get it that you don't want to open a can of worms.

**Comment by tessus** [comment]
Either way, I can remove the cold folding marks in a few seconds, if you still consider merging this.

**Comment by laurent22** [comment]
I'd prefer to put this change on the side for now as I feel there's not enough demand for the line numbers. Collapsing sections would be useful if it can work with the preview, but that would be a different PR. So if you don't mind I'd prefer to close this pull request.

**Comment by rickythefox** [comment]
An optional line number feature would be very useful for vimers. =)

**Comment by amandamcg** [comment]
I would love the folding in the markdown side, with or without line numbers, and would not expect to be affecting the preview. Maybe this is a good candidate for a very simple plugin?

**Comment by jayhill** [comment]
Give us the gutter — please! 🙏

**Comment by philippludwig** [comment]
Since this got not merged, is there any possibility that I can apply this myself? I would love to have the folding feature, the plugin does not enable this.

**Comment by roman-r-m** [comment]
I think there was a plugin for this.

**Pull request closed without merging**
