### PR TITLE
Desktop: allow scrolling past end in Ace editor

### LINKED ISSUE #3147: Scroll Past End in Editor
This is more of a feature request than a bug, but would you consider setting this option to a value that would give some bottom padding to the Ace editor used in Joplin?

`scrollPastEnd: number|boolean`

https://github.com/ajaxorg/ace/wiki/Configuring-Ace

I'm not sure if it's possible to include this as a setting in Joplin's settings. That would be even better.

### PR DESCRIPTION
**Pull request by tessus**
follow-up to #3156
fixes #3147

/ref https://discourse.joplinapp.org/t/scrolling-past-end/5043

### CODE REVIEW

**Comment by tessus** [comment]
The CI build will fail, b/c my linter fix is not yet in master.

**Comment by laurent22** [comment]
Does the viewer also scroll past end?

**Comment by tessus** [comment]
No. The other PR didn't mention anything about the viewer.

**Comment by laurent22** [comment]
We had this discussion for CodeMirror as Caleb made it scroll past end, but the viewer doesn't and to me it looks a bit strange. Like it seems there's more content past the end of the viewer when there isn't.

We discussed various option like having a shared scrollbar, etc. but not sure what's best.

**Comment by tessus** [comment]
Ah, ok.

Didn't one of the css modifications (I think by Amanada) actualy add a margin at the bottom?

**Comment by laurent22** [comment]
As we are going to switch to CodeMirror I think this pull request is no longer needed.

**Pull request closed without merging**
