### PR TITLE
Desktop: Resolves  #11478 - Bold or italic text in markdown viewer

### LINKED ISSUE #11478: Desktop: Bold or italic text in checklists have weird formatting in markdown viewer
### Operating system

Windows

### Joplin version

3.2.3

### Desktop version info

Joplin 3.2.3 (prod, win32)

Client ID: 6cfb4e5a34d04a73aeea629e561b4dd6
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 1993d30

Backup: 1.4.2

### Current behaviour

When bold or italic text is included in a checklist item, the formatting looks weird in the markdown viewer
bug1

This is not the case in the rich text editor
bug2

### Expected behaviour

The formatting of the markdown view should look the same as on the rich text editor for the checklist item

### Logs

_No response_

### PR DESCRIPTION
**Pull request by RajwardhanSinghUmath**
…matting in markdown viewer

Fixes the issue with bold and italic text in markdown viewer which is addressed in the issue #11478

### CODE REVIEW

**Comment by RajwardhanSinghUmath** [comment]
recheck

**Comment by RajwardhanSinghUmath** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by RajwardhanSinghUmath** [comment]
recheck

**Comment by personalizedrefrigerator** [comment]
Resolved in https://github.com/laurent22/joplin/commit/9373c334b3b1b9481710d2e9189639c664472077

**Pull request closed without merging**
