### PR TITLE
All: Translation: Update zh_CN.po

### PR DESCRIPTION
**Pull request by whriedplanck**
Update zh_CN.po

P.S. I would like to ask, do `AWS key` and `AWS secret` refer to `Access Key ID` and `Secret Access Key` respectively?
(Because I haven't used AWS, I checked it online, but I'm not sure.)

### CODE REVIEW

**Comment by tessus** [comment]
I think your intrepretation of the strings are correct. 

@alexchee wrote the AWS code and he would be able to tell you what he used the short string versions for.

**Comment by alexchee** [comment]
Yes, that's correct.

**Comment by whriedplanck** [comment]
@tessus @alexchee  OK, thank you!~

**Comment by tessus** [comment]
Are you going to push another commit?

**Comment by whriedplanck** [comment]
> Are you going to push another commit?

Yes. I'm very sorry for the delay, because I've been a bit busy recently at work and haven't had time to commit. Thank you very much again for your help ~ :D  I will push the last commit soon so that you can merge this PR.

**Comment by whriedplanck** [comment]
I have given the specific name of AWS secret and AWS key in the translation.
Because I read the official documents of several local cloud service providers in China, and asked a few people who use these services, and then found that these cloud service providers all use English to express similar concepts.  And the official AWS China seems to be the same (I don’t know why the exact information I found on the Internet seems a bit outdated, so I'm not quiet sure). I think the current translation should enable Chinese readers to better understand the specific meaning of these two words. ~

**Comment by tessus** [comment]
Don't worry about it. I only asked, because I wanted to know, whether I should merge or wait...

Thanks for the update!

**Comment by whriedplanck** [comment]
Thank you, too. :D

在 2020/7/24 下午11:57, Helmut K. C. Tessarek 写道:

**Pull request merged**
