### PR TITLE
Desktop: #11073: Fix directory being considered unsafe because of naming

### LINKED ISSUE #11073: Unknown file type warning for folders with a dot
### Operating system

Windows

### Joplin version

3.0.15

### Desktop version info

Joplin 3.0.15 (prod, win32)

Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 598677b

### Current behaviour

1. ALT-Drag-drop a folder into a note, folder name has a dot like "my folder.nice"
2. Ctrl-click on folder in note
3. Warning pops up about unknown file type ".nice"

### Expected behaviour

At step 3, Joplin should understand this is a folder so extensions are irrelevant, and open the folder with no warning

### Logs

_No response_

### PR DESCRIPTION
**Pull request by pedr**
Fixes https://github.com/laurent22/joplin/issues/11073

# Summary

When the user tries to open a link to a folder path with dot on its name it shows the warning message about being an unknown type file.

I'm not sure if there is a security concern here, but I guess if the system recognizes the path being to a directory/folder it is probably safe to open.

### CODE REVIEW

**Review by personalizedrefrigerator — CHANGES_REQUESTED** [review]
Thank you for working on this!

I've left feedback on the internal Discord.

**Comment by pedr** [comment]
- [x] Add comment on why the conditional is there

**Comment by pedr** [comment]
.

**Comment by pedr** [comment]
Add comment to new warning message

**Comment by laurent22** [comment]
@pedr, for this issue I've ended up adding a simple comment here: a4be89144e3dce403f56713bc140ced0a1a3e575 There's no easy way to address this issue

**Pull request closed without merging**
