### PR TITLE
Added auto complete

### PR DESCRIPTION
**Pull request by gabcoh**
Inteligent command based autocompletion (i.e. autocompleting notes for `rmnote`)  is not yet implemented. This will require knowledge of the command, and it's parameters. The autocomplete feature is pretty powerful however, so this should not be very difficult to add. But I think this is still better than nothing!

### CODE REVIEW

**Comment by laurent22** [comment]
> This will require knowledge of the command, and it's parameters.

Yes the issue is that if a user type for example "rmnote" followed by "r" and type TAB, that will result in "rmnote rmnote", which would be confusing. I'd rather have either:

- Auto-completion for only the command name (so pressing tab after the first word won't do anything)

- Or full auto-completion for both command name, flags and positional arguments.

But something hybrid would be confusing.

Before there was no GUI and auto-completion was supported in shell mode. The code is still in the repo and could probably be re-used:

https://github.com/laurent22/joplin/blob/5492e715f86eb52777998ecd4790428a4af6d9fe/CliClient/app/autocompletion.js#L68

Likewise there could be a function that takes a partial command line and return the list of autocompletion words. For example:

function handleAutocompletion(line) { ... }

Calling `handleAutocompletion('rm')` would return `[rmbook, rmnote]`

Calling `handleAutocompletion(['rmnote', 'my'])` could return `['my note', 'my note 2]`, etc.

**Comment by gabcoh** [comment]
Right. I only implemented autocomplete for the command name. After you type in the command name it won't autocomplete anything else.

**Comment by gabcoh** [comment]
I am going to work on adapting the old autocompletion.js script to work now.

**Comment by laurent22** [comment]
Indeed I missed that it would only auto-complete the first word, so that's already a pretty good improvement as is. If you need some more info on adapting the old autocompletion script let me know.

Also by the way, for consistency please use tabs instead of spaces.

**Comment by gabcoh** [comment]
Ok. I just made the autocomplete smarter. It should be able to autocomplete notes, notebooks, todo commands, tags, tag commands, and command names. It might have some bugs because I haven't tested it against every command. Also what do you think about having the autocomplete menu? That's the little menu that shows up on the bottom of the screen when you have multiple potential autocompletes.

**Comment by laurent22** [comment]
Great, I've just checked the code for now, which looks good. I didn't know that terminal-kit could take a callback for autocompletion, which makes it even more flexible. I'll test this within the next few days and will let you know.

**Comment by laurent22** [comment]
I've done a few tests with this and noticed these few issues:
- `tag` command does not complete the sub-commands. If I type `tag ad` it doesn't autocomplete `tag add`
- `todo` command autocomplete a note name in second position instead of the todo-command. For example `todo t` would complete `todo testnote` instead of `todo toggle`
- `rmnote` doesn't autocomplete note title (not sure if implemented)
- I didn't test but items titles should have quotes around them, in particular they have spaces in them.
Otherwise other commands I've tested seemed to work fine. Command names and flags for instance are autocompleting correctly.

**Comment by laurent22** [comment]
> Also what do you think about having the autocomplete menu? That's the little menu that shows up on the bottom of the screen when you have multiple potential autocompletes.

Yes that would be useful as it would show the available options. I guess when the menu shows up it would push the UI up, so we'd just need to make sure it goes back down when the menu closes.

**Comment by gabcoh** [comment]
Thanks for checking the code! I'll work on fixing that, but also I was wondering if I could add unit tests to it?

**Comment by laurent22** [comment]
Currently there's nothing to test UI code, but for functional code you could use the existing test units in CliClient/tests. It's used to test the synchronisation and encryption backend at the moment.

Simply add a file in there, for example "autocompletion.js" and add Jasmine tests to it.

Here's an example of a minimal test unit:

```
require('app-module-path').addPath(__dirname);

const { setupDatabase, setupDatabaseAndSynchronizer, db, synchronizer, fileApi, sleep, clearDatabase, switchClient, syncTargetId, encryptionService, loadEncryptionMasterKey } = require('test-utils.js');
const Folder = require('lib/models/Folder.js');
const Note = require('lib/models/Note.js');

process.on('unhandledRejection', (reason, p) => {
	console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
});

jasmine.DEFAULT_TIMEOUT_INTERVAL = 15000; // The first test is slow because the database needs to be built

describe('Example', function() {

	beforeEach( async (done) => {
		await setupDatabaseAndSynchronizer(1);
		await switchClient(1);
		done();
	});

	it('should create notes and folders', async (done) => {
		let folder = await Folder.save({ title: "some folder" });
		await Note.save({ title: "some note", parent_id: folder.id });

		const allFolders = await Folder.all();
		const allNotes = await Note.all();

		expect(allFolders.length).toBe(1);
		expect(allNotes.length).toBe(1);
		
		done();
	});

});
```

Basically change what's in `it('should create notes and folders'` making sure you call `done()` at the end. And use `expect(x).toBe(y)` for assertions.

Once it's done, add the script to `run_tests.sh`, eg `(cd "$ROOT_DIR" && npm test tests-build/autocompletion.js)`

**Comment by gabcoh** [comment]
I think I fixed all of the issues. This should now properly autocomplete everything and also properly handle quotes and spaces. I think the reason it wasn't autocompleting `rmnote` was because it doesn't autocomplete anything if there are multiple potential options. If `autoCompleteMenu` is enabled in the StatusBarWidget it will give you a list of the potential options but it is sort of ugly because it does not just list what would be added to the current line, it lists the entire line.

**Comment by gabcoh** [comment]
Also, I'll work on adding some unit tests later for some of the utility functions I use.

**Comment by laurent22** [comment]
Seems to work very well on all the commands I tried. I actually like it with the `autoCompleteMenu` option, and by calling `this.root.invalidate();` at the end, it redraws the GUI properly.

I wonder if there's any option to display only the word being auto-completed rather than the whole line? @cronvel do you know if there's a way to do this with the current version of terminal-kit?

**Comment by cronvel** [comment]
@laurent22 It's possible, if you write your own auto-completer. The array to be returned by the auto-completer should be what is displayed, the array should have a property *.prefix* that will be inserted at the beginning of all values.

Look at the implementation of a file input in `lib/fileInput.js`.
You can test it if you run `./sample/file-input-doc1.js` (use `tab` when you are inside multiple sub-directories).

**Comment by gabcoh** [comment]
Now the autocomplete menu just shows the word that's going to be added but I don't know where I should put `this.root.invalidate`

**Comment by laurent22** [comment]
Great, thanks a lot @cronvel for the help, and thanks @gabcoh for this useful improvement! I've added the invalidate line and I'll merge this and release a version with it later today.

**Comment by laurent22** [comment]
Ok it's on version 0.10.84 on npm and seems to work fine, thanks again for your work!

**Comment by cronvel** [comment]
@laurent22 You're welcome! ;)

**Comment by gabcoh** [comment]
Cool! Glad to help

**Pull request merged**
