### PR TITLE
Desktop: Enhance notelist focus behaviour

### PR DESCRIPTION
**Pull request by mic704b**
This PR contains two enhancements to focus behaviour in the note list:

## Focus following delete
1. Delete a note from the note list (eg using `Delete` key or context-menu)
2. Use `Up` or `Down` key to select the next note

Expected: the next note is selected, the user can continue navigating with the keys
Actual: nothing, the note list does not respond to the navigation keys anymore

## Focus when navigating "away" from multiple-note selection.

1. Select multiple notes in the note list (eg Ctrl-A, or using mouse)
2. Use `Up` or `Down` key to select the next note

Expected: the next note is selected, and the previous notes are deselected
Actual: nothing, the note list does not respond to navigation keys anymore

This fix also fixes another issue discussed in [forum](https://discourse.joplinapp.org/t/please-help-test-the-new-desktop-pre-release) as a side effect.

### CODE REVIEW

**Comment by laurent22** [comment]
Just need to fix the conflict and we can merge. (The "app" folder was removed so you will need to move your file one level down)

**Comment by mic704b** [comment]
I'm going to postpone this for now, until I get a chance to look at it.

It works for note delete, but breaks new note behaviour.

**Comment by mic704b** [comment]
Fixed and ready for review.

**Comment by mic704b** [comment]
Fixed and ready for review.

**Comment by tessus** [comment]
I'd like to merge this. Is there anything left to do? @laurent22 you already gave the ok to merge, but there were a few changes after your comment. Please advise.

**Comment by laurent22** [comment]
Looks good but I didn't test, however if you guys think it's ready to merge, please go ahead.

**Comment by tessus** [comment]
Oh, yes, I forgot to add the `PR-tested` label. I actually did test this.

**Pull request merged**
