### PR TITLE
Open in external editor mode state fixed #2762

### LINKED ISSUE #2762: When the editor is in Viewer mode, enable "Open in external editor" menu item
This item was recently disabled in a pull request, but it should always be enabled in all views.

Forum thread: https://discourse.joplinapp.org/t/external-editor-shortcut-available-in-any-layout-view-mode/6958?u=laurent

### PR DESCRIPTION
**Pull request by Hardik500**

### CODE REVIEW

**Comment by PackElend** [comment]
1. can you explain what you did, PRs without any description, reviewers won't react to this PR .
1. How does this align with the issue history?

**Comment by Rahulm2310** [comment]
@PackElend I agree. Also, he is another who uses master branch for a pull request

**Comment by Hardik500** [comment]
Sorry about not writing a description.
In this I removed the 'commandStartExternalEditing' from the for loop of the code where the states are updating. Thus making it's state remain constant throughout.

**Comment by Hardik500** [comment]
I will close this one since I created a new pull request with a different branch from master.

**Pull request closed without merging**
