### PR TITLE
Added .idea and other IDEs and editors in .gitignore

### PR DESCRIPTION
**Pull request by sealch**
Also created some hierarchy in .gitignore file and removed redundant files covered by ignoring node_modules

### CODE REVIEW

**Comment by tessus** [comment]
I'm sorry, we cannot merge this. You removed some files from the list without any explanation and added.
If you want to exclude files in your local repo, you can either use:

- `.gitignore_global`
- `.git/info/exclude`

**Comment by sealch** [comment]
> I'm sorry, we cannot merge this. You removed some files from the list without any explanation and added.
> If you want to exclude files in your local repo, you can either use:
> 
> * `.gitignore_global`
> * `.git/info/exclude`

Hey, Tessus, thanks for your comment. I noticed that my IDE (WebStorm) creates .idea folder that shouldn't be committed and decided to add IDE and editors section in gitignore file where I listed all possible unwanted files that various IDE's generate.

**Comment by sealch** [comment]
@tessus 
As for Makefile, .swp and .map WebStorm says they are already ignored when including other files and paths in gitignore but I returned them in the second commit just in case

**Comment by tessus** [comment]
As you can see, Laurent commited a Sublime file to the code tree, thus adding this to .gitignore is a bad idea.

These are mostly your IDE files, so this PR might not be very helpful.

Just add the files to the file `.git/info/exclude` in your repo.

**Comment by sealch** [comment]
> As you can see, Laurent commited a Sublime file to the code tree, thus adding this to .gitignore is a bad idea.
> 
> These are mostly your IDE files, so this PR might not be very helpful.
> 
> Just add the files to the file `.git/info/exclude` in your repo.

I haven't added extra sublime files, *.sublime-workspace was already here. I think this PR still might be useful if someone also uses IntelliJ family IDE or VScode as I added files that could be generated.

**Comment by tessus** [comment]
Well, let's see. Laurent will have to decide.

But I think, if you really only excuded any IDE files, the chances are good that it's merrged.

**Comment by sealch** [comment]
@PackElend please label me

**Comment by laurent22** [comment]
I'm unable to review this to be honest. I don't know what problem it solves, and I don't think it's wise to add many entries in .gitignore without knowing what they are exactly.

I'd be fine if someone adds an entry or two to make it work with their editor, but not this. With that in mind I'd prefer to close the PR.

**Pull request closed without merging**
