### PR TITLE
Server: Load environment values from files for Docker Secrets/Configs

### PR DESCRIPTION
**Pull request by ChaosExAnima**
This PR adds support for loading environment settings from paths. This allows native integration of [Docker Secrets](https://docs.docker.com/engine/swarm/secrets/) or [Docker Configs](https://docs.docker.com/engine/swarm/configs/), which allows keeping sensitive data outside of a Compose file or script.

Please let me know if you need any changes! 🙂

### CODE REVIEW

**Comment by laurent22** [comment]
Hmm, but we can already load the env variables from a file using the `--env-file` flag. Doesn't Docker Secrets or similar integrate with this?

**Comment by ChaosExAnima** [comment]
> Hmm, but we can already load the env variables from a file using the `--env-file` flag. Doesn't Docker Secrets or similar integrate with this?

No, unfortunately. `env-file` loads env vars from a file on the host, which is then loaded into the env of the running container, and I believe is exposed when the container is inspected. Environment vars generally aren't a good place to store sensitive information like passwords, imo.

Secrets are not stored inside a file but in an encrypted system internal to Docker, accessible only inside the container _after_ it starts running. And while you can load a bunch of env vars from a single Secret, it makes more sense to split them up into individual vars to allow resharing. For instance, on my setup I have a secret named `joplin-postgres-pass` that isn't accessible anywhere except inside the Joplin container and my Postgres install at `/run/secrets/`. That lets me do things like rotate the DB password easily- just stop the containers, delete and recreate the secret, and start it up again.

Right now I hack around it via a custom `entrypoint`, but it'd be really nice to have things integrated like this!

**Comment by laurent22** [comment]
Thanks for the pull request but I would prefer to close it for now, as I prefer not to add too much complexity to the configuration, and I'm not sure if loading the env in that way is a common use case.

**Comment by Enissay** [comment]
@laurent22, passing secrets this way is quite common as It allows to not store them in plain text. Instead you create a secret in docker and it is then mounted to all the target containers where you just have to reference it `/run/secrets/my_top_secret`

In most popular projects, they always accept two exclusive variables to handle this use case, eg: `PASSWORD=plain_text_psw` and `PASSWORD_FILE=/run/secrets/my_top_secret`

See official doc here: https://docs.docker.com/compose/use-secrets/

Also since you use PG as a database, they have that as well: 
- Joplin Compose: https://raw.githubusercontent.com/laurent22/joplin/dev/docker-compose.server.yml
- PG secret variable: https://github.com/docker-library/docs/blob/master/postgres/README.md#docker-secrets

**Comment by Jip-Hop** [comment]
Instead of implementing this in the Joplin server, this can be accomplished with an entrypoint script instead.

Simplified example for a single variable based on [the immich set-env.sh file](https://github.com/immich-app/base-images/blob/d218673b8e4254574d0ed9b922c80e72cc5e1bb6/postgres/set-env.sh):

```sh
#!/usr/bin/env bash

read_env_or_file() {
    local var_name="$1"
    local file_var_name="${var_name}_FILE"

    if [[ -n "${!file_var_name}" && -f "${!file_var_name}" && -s "${!file_var_name}" ]]; then
        cat "${!file_var_name}"
    else
        echo "${!var_name}"
    fi
}

: "${POSTGRES_PASSWORD_FILE:=${DB_PASSWORD_FILE}}"

POSTGRES_PASSWORD=$(read_env_or_file "POSTGRES_PASSWORD")

: "${POSTGRES_PASSWORD:=${DB_PASSWORD}}"

unset POSTGRES_PASSWORD_FILE

export POSTGRES_PASSWORD
```

The benefit is that this pattern would allow using either a POSTGRES_PASSWORD or a POSTGRES_PASSWORD_FILE environment variable, just like postgres recommends for their images as pointed out by @Enissay. When using the POSTGRES_PASSWORD_FILE env var, the secret value doesn't show up as plain text in e.g. docker inspect as the env var is exported once the container is running. And it doesn't add complexity to the Joplin server code itself. The feature is exclusive to the docker image.

@laurent22 Would it be acceptable to introduce an entrypoint script with this logic?

**Pull request closed without merging**
