### PR TITLE
Desktop: Resolves #4911: Adding a tag in all notes leads to select first note

### LINKED ISSUE #4911: Adding a tag in all notes leads to select first note
If you add a tag to a note in the `All notes` view, the first note from the `All notes` nootbook will be selected after saving the tag.

H3CLa5tvQl

## Environment

Joplin 1.8.2 (prod, win32)

Client ID: 8d4ac0fa4a1840acb6db8ac8be29d7ce
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 2531e8945

## Steps to reproduce

1. Select `All note` nootebook
2. Select a note, but not the first one
3. Click on Tags
4. Add a Tag and click on OK
4. Selected note jumps to the first note from the `All note` nootebook

## Describe what you expected to happen

The selected note should not be changed.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6410855/log.txt)
[console.log](https://github.com/laurent22/joplin/files/6410856/console.log)

### PR DESCRIPTION
**Pull request by Aksh-Konda**
Fixes #4911

### Problem:
When "All notes" is selected and a tag is added to a note from the note list. whatever the currently focused note be, it's changing to the first note in the list.

### Solution:
Basically the [parentItem()](https://github.com/laurent22/joplin/blob/dev/packages/lib/reducer.ts#L267) function in reducer.ts is not checking for the noteParentType to be "SmartFilter" and returning a null. The function [lastSelectedNoteIds()](https://github.com/laurent22/joplin/blob/dev/packages/lib/reducer.ts#L277) which is checking for the parent using the above function and returning an empty array in case of parent being null.

which is affecting the [BaseApplication.ts](https://github.com/laurent22/joplin/blob/dev/packages/lib/BaseApplication.ts#L341) re-focusing the last selected note after a refresh of the note list.

### Manual Test to check if the focus is preserved to the note selected:

1. Select the "All notes" option from the sidebar.
2. Open a note which is not the first one in the note list.
3. Add tags by selecting the option at the bottom of the main screen.
4. After adding the tags the focus should remain on the same note rather than focus being shifted to the first note in the list.

below is the demo of the same: 

https://user-images.githubusercontent.com/63443657/118864497-adf9d480-b8fd-11eb-9147-e7710261baa2.mp4

### CODE REVIEW

**Comment by roman-r-m** [comment]
Looks like there are already tests for this file, can you add one or more test cases for your change?

**Comment by laurent22** [comment]
The parentItem logic is quite tricky and used in many cases, so I suspect you broke something. You should try many actions: for example, opening a tag, then searching, then closing the search, jumping to a note from GotoAnything, etc. The logic is how it is now to take into account all these cases and more.

**Comment by Aksh-Konda** [comment]
> Looks like there are already tests for this file, can you add one or more test cases for your change?

Sorry, I couldn't figure out what to test. StateUtils or the reducer. As it is a bug generated by the refreshNotes() function of BaseApplication.ts (there is a lot going on in the function). I got stuck. Could you please guide me?

**Comment by roman-r-m** [comment]
> > Looks like there are already tests for this file, can you add one or more test cases for your change?
> 
> Sorry, I couldn't figure out what to test. StateUtils or the reducer. As it is a bug generated by the refreshNotes() function of BaseApplication.ts (there is a lot going on in the function). I got stuck. Could you please guide me?

It seems StateUtils is just an implementation details of the reducer so it's the reducer that should be tested. There are some tests for the reducer in `packages/app-cli`. I suggest you check which reducer actions are affected by your change and try to add tests for these actions where possible.

**Comment by Aksh-Konda** [comment]
shouldn't the [selectedNoteIds](https://github.com/laurent22/joplin/blob/dev/packages/lib/reducer.ts#L117) prop of defaultState also contain SmartFilter ? as it contains similar things like Search and Tags.

**Comment by roman-r-m** [comment]
> shouldn't the [lastSelectedNoteIds](https://github.com/laurent22/joplin/blob/dev/packages/lib/reducer.ts#L117) prop of defaultState also contain SmartFilter ? as it also contains similar things like Search and Tags.

I suppose best way to answer this is to see where and how this prop is used and from there figure out if we're missing anything by not having SmartFilter in there. Maybe it was forgotten, maybe it genuinely not needed, hard to say.

**Comment by roman-r-m** [comment]
Also, with regards to tests for the reducer -- note that Laurent has just moved these tests from `app-cli` to `lib`, if you haven't started on it yet, update the repo or you'll have to deal with merge conflicts later.

**Comment by Aksh-Konda** [comment]
> > shouldn't the [lastSelectedNoteIds](https://github.com/laurent22/joplin/blob/dev/packages/lib/reducer.ts#L117) prop of defaultState also contain SmartFilter ? as it also contains similar things like Search and Tags.
> 
> I suppose best way to answer this is to see where and how this prop is used and from there figure out if we're missing anything by not having SmartFilter in there. Maybe it was forgotten, maybe it genuinely not needed, hard to say.

I think it might be forgotten, as the Smart_Filter is considered everywhere else(in [getContextFromHistory()](https://github.com/laurent22/joplin/blob/dev/packages/lib/reducer.ts#L530), [defaultNotesParentType()](https://github.com/laurent22/joplin/blob/dev/packages/lib/reducer.ts#L438)) which rely on the parenType and these are used in managing the history. also, I feel that Smart_Filter is important in case of storing multiple selectedNoteIds when All notes filter is on and the parentType should only be Smart_Filter.

> The parentItem logic is quite tricky and used in many cases, so I suspect you broke something. You should try many actions: for example, opening a tag, then searching, then closing the search, jumping to a note from GotoAnything, etc. The logic is how it is now to take into account all these cases and more.

Yes, and I see it is mainly used for history to store the parent-related details of a note.

**Comment by Aksh-Konda** [comment]
I pushed the merge commit too. I'll make another pull request. is it ok @laurent22?

**Comment by roman-r-m** [comment]
> should I make another pull request? or is this okay to merge?

I do not see any conflicts so yes

**Comment by laurent22** [comment]
The manual tests are not enough at the moment. Because we don't have automated tests for all possible cases you would need to manually test what I mentioned above and probably more. I'm, let's say, 90% sure you broke something with this change.

**Comment by laurent22** [comment]
What would you like to do about this pull request @Aksh-Konda?

**Comment by Aksh-Konda** [comment]
I added few tests And also did the manual tests as you suggested. But as you were sure that this change might have broke some operation... I wasn't sure what to do next...

**Comment by laurent22** [comment]
Yes most likely something is broken but we don't have enough unit tests to find out, and if you can't do the manual tests I've suggested let's close it.

**Pull request closed without merging**
