### PR TITLE
add support for webp images

### LINKED ISSUE #848: Please add support for webp images
Some websites use ".webp" images, "Joplin Web Clipper" saves these images but the client seems unable to display this type of images. So we have to manually convert them to supported formats, which is tedious. It would be great if Joplin can support ".webp" images!

### PR DESCRIPTION
**Pull request by tessus**
fixes #848

### CODE REVIEW

**Comment by laurent22** [comment]
Nice, so it works in all devices without additional changes?

**Comment by tessus** [comment]
I could only test with the electron application.

I'll try to get the mobile dev stack running in the afternoon. At one point I have to get it working anyway.

**Comment by laurent22** [comment]
I guess what would need to be tested is whether images can be attached to notes. When attaching images, they are down-scaled so the module that does this needs to support webp.

**Comment by tessus** [comment]
This is what I did: I took a random webp image from the net. Attached it to a note and added the following: ``.

I'm now trying to compile the Android app...

**Comment by tessus** [comment]
I was finally able to run `react-native run-android`.

However, I've encountered several issues along the way. I can't start the emulator from the command line, even though all ENV vars are set correctly. There is no AVD manager in `Tools > Android > AVD Manager` in Android Studio. I could only start it with the icon in the icon toolbar.

After starting the emulator, the `react-native run-android` worked.

Anyway, I cannot attach any other file than a `.jpg`. Whenever I try to add another file via `Attach any file`, Joplin dies. I tried `.pdf`, `.ogg`, `.webp`. Nothing works.

(This entire dev env seems a bit flaky. Even when I create an empty project with no activity, Android Studio downloads and syncs a load of crap which takes a long time....)

There are also warnings in the Joplin app.

<details>
<summary>click me to see screenshot</summary>

screenshot_1538846756

</details>

**Comment by tessus** [comment]
That is all that is in the debug log:

```
10-06 14:10:53.822  4550  4577 I ReactNativeJS: 2018-10-06 14:10:53: "Setting up recurrent sync with interval 300"
10-06 14:10:53.822  4550  4577 I ReactNativeJS: 2018-10-06 14:10:53: "Recurrent sync operation DISABLED!!!"
10-06 14:10:57.004  4550  4577 I ReactNativeJS: 2018-10-06 14:10:57: "Reducer action", "NOTE_UPDATE_ALL"
10-06 14:10:59.204  4550  4577 I ReactNativeJS: 2018-10-06 14:10:59: "Got file: content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fexample.ogg"
10-06 14:10:59.204  4550  4577 I ReactNativeJS: 2018-10-06 14:10:59: "Got type: application/ogg"
10-06 14:10:59.351  4550  4577 I ReactNativeJS: 2018-10-06 14:10:59: "Reducer action", "NOTE_UPDATE_ALL"
10-06 14:10:59.613  4550  4577 I ReactNativeJS: 2018-10-06 14:10:59: "Reducer action", "NOTE_UPDATE_ALL"
10-06 14:11:00.038  4550  4550 D ReactNative: ReactInstanceManager.detachViewFromInstance()
```

crash here

after restarting Joplin:

```
10-06 14:13:20.316  4928  4928 D ReactNative: ReactInstanceManager.ctor()
10-06 14:13:20.413  4928  4928 D ReactNative: ReactInstanceManager.createReactContextInBackground()
10-06 14:13:20.413  4928  4928 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
10-06 14:13:20.415  4928  4928 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
10-06 14:13:20.418  4928  4928 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
10-06 14:13:20.419  4928  4928 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
10-06 14:13:20.523  4928  4951 D ReactNative: ReactInstanceManager.createReactContext()
10-06 14:13:20.847  4928  4951 D ReactNative: Initializing React Xplat Bridge.
10-06 14:13:20.852  4928  4951 D ReactNative: Initializing React Xplat Bridge before initializeBridge
10-06 14:13:20.862  4928  4951 D ReactNative: Initializing React Xplat Bridge after initializeBridge
10-06 14:13:20.862  4928  4951 D ReactNative: CatalystInstanceImpl.runJSBundle()
10-06 14:13:20.863  4928  4959 D ReactNative: ReactInstanceManager.setupReactContext()
10-06 14:13:20.863  4928  4959 D ReactNative: CatalystInstanceImpl.initialize()
10-06 14:13:20.868  4928  4959 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
10-06 14:13:21.538  4928  4958 W ReactNativeJS: Require cycle: node_modules/react-native-fetch-blob/index.js -> node_modules/react-native-fetch-blob/polyfill/index.js -> node_modules/react-native-fetch-blob/polyfill/Blob.js -> node_modules/react-native-fetch-blob/index.js
10-06 14:13:21.538  4928  4958 W ReactNativeJS:
10-06 14:13:21.538  4928  4958 W ReactNativeJS: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
10-06 14:13:21.542  4928  4958 W ReactNativeJS: Require cycle: node_modules/react-native-fetch-blob/index.js -> node_modules/react-native-fetch-blob/polyfill/index.js -> node_modules/react-native-fetch-blob/polyfill/XMLHttpRequest.js -> node_modules/react-native-fetch-blob/index.js
10-06 14:13:21.542  4928  4958 W ReactNativeJS:
10-06 14:13:21.542  4928  4958 W ReactNativeJS: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
10-06 14:13:21.544  4928  4958 W ReactNativeJS: Require cycle: node_modules/react-native-fetch-blob/index.js -> node_modules/react-native-fetch-blob/polyfill/index.js -> node_modules/react-native-fetch-blob/polyfill/FileReader.js -> node_modules/react-native-fetch-blob/index.js
10-06 14:13:21.544  4928  4958 W ReactNativeJS:
10-06 14:13:21.544  4928  4958 W ReactNativeJS: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
10-06 14:13:21.545  4928  4958 W ReactNativeJS: Require cycle: node_modules/react-native-fetch-blob/index.js -> node_modules/react-native-fetch-blob/polyfill/index.js -> node_modules/react-native-fetch-blob/polyfill/Fetch.js -> node_modules/react-native-fetch-blob/index.js
10-06 14:13:21.545  4928  4958 W ReactNativeJS:
10-06 14:13:21.545  4928  4958 W ReactNativeJS: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
10-06 14:13:21.602  4928  4958 W ReactNativeJS: Require cycle: node_modules/react-native-popup-menu/src/index.js -> node_modules/react-native-popup-menu/src/Menu.js -> node_modules/react-native-popup-menu/src/index.js
10-06 14:13:21.602  4928  4958 W ReactNativeJS:
10-06 14:13:21.602  4928  4958 W ReactNativeJS: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
10-06 14:13:21.610  4928  4958 W ReactNativeJS: Require cycle: node_modules/react-native-popup-menu/src/index.js -> node_modules/react-native-popup-menu/src/Menu.js -> node_modules/react-native-popup-menu/src/logger.js -> node_modules/react-native-popup-menu/src/index.js
10-06 14:13:21.610  4928  4958 W ReactNativeJS:
10-06 14:13:21.610  4928  4958 W ReactNativeJS: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
10-06 14:13:21.834  4928  4958 I ReactNativeJS: Running application "Joplin" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
10-06 14:13:21.862  4928  4958 I ReactNativeJS: OPEN database: log.sqlite
10-06 14:13:21.977  4928  4958 I ReactNativeJS: 2018-10-06 14:13:21: "===================================="
10-06 14:13:21.977  4928  4958 I ReactNativeJS: 2018-10-06 14:13:21: "Starting application net.cozic.joplin-mobile (dev)"
10-06 14:13:21.983  4928  4958 I ReactNativeJS: OPEN database: joplin-68.sqlite
10-06 14:13:22.055  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Database was open successfully"
10-06 14:13:22.064  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Checking for database schema update..."
10-06 14:13:22.134  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Current database version", "12"
10-06 14:13:22.216  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Database is ready."
10-06 14:13:22.219  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Loading settings..."
10-06 14:13:22.264  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "SETTING_UPDATE_ALL"
10-06 14:13:22.272  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Setting up recurrent sync with interval 300"
10-06 14:13:22.273  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Recurrent sync operation DISABLED!!!"
10-06 14:13:22.277  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Sync target: 2"
10-06 14:13:22.290  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Trying to load 0 master keys..."
10-06 14:13:22.291  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Loaded master keys: 0"
10-06 14:13:22.293  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "MASTERKEY_REMOVE_NOT_LOADED"
10-06 14:13:22.295  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Scheduling sync operation..."
10-06 14:13:22.300  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Trying to load 0 master keys..."
10-06 14:13:22.303  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Loaded master keys: 0"
10-06 14:13:22.307  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Loading folders..."
10-06 14:13:22.366  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "FOLDER_UPDATE_ALL"
10-06 14:13:22.384  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "TAG_UPDATE_ALL"
10-06 14:13:22.399  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "MASTERKEY_UPDATE_ALL"
10-06 14:13:22.449  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "FOLDER_SET_COLLAPSED_ALL"
10-06 14:13:22.454  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "NAV_GO, Notes"
10-06 14:13:22.457  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Setting up recurrent sync with interval 300"
10-06 14:13:22.458  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Recurrent sync operation DISABLED!!!"
10-06 14:13:22.461  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Scheduling sync operation..."
10-06 14:13:22.464  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Application initialized"
10-06 14:13:22.466  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "APP_STATE_SET"
10-06 14:13:22.541  4928  4958 E ReactNativeJS: 'Warning: Component %s declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?', 'DialogBox'
10-06 14:13:22.807  4928  4958 I ReactNativeJS: 2018-10-06 14:13:22: "Reducer action", "NOTE_UPDATE_ALL"
10-06 14:13:23.306  4928  4958 I ReactNativeJS: 2018-10-06 14:13:23: "DecryptionWorker: starting decryption..."
10-06 14:13:23.307  4928  4958 I ReactNativeJS: 2018-10-06 14:13:23: "Reducer action", "DECRYPTION_WORKER_SET"
10-06 14:13:23.367  4928  4958 I ReactNativeJS: 2018-10-06 14:13:23: "DecryptionWorker: completed decryption."
10-06 14:13:23.368  4928  4958 I ReactNativeJS: 2018-10-06 14:13:23: "Reducer action", "DECRYPTION_WORKER_SET"
10-06 14:13:32.483  4928  4958 I ReactNativeJS: 2018-10-06 14:13:32: "Preparing scheduled sync"
10-06 14:13:32.501  4928  4958 I ReactNativeJS: 2018-10-06 14:13:32: "Could not run background sync:"
10-06 14:13:32.502  4928  4958 I ReactNativeJS: 2018-10-06 14:13:32: "Error: Error: Directory could not be created. Path:
10-06 14:13:32.502  4928  4958 I ReactNativeJS: Code: EUNSPECIFIED
10-06 14:13:32.502  4928  4958 I ReactNativeJS: fsErrorToJsError_@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:183680:31
10-06 14:13:32.502  4928  4958 I ReactNativeJS: mkdir$@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:183948:45
10-06 14:13:32.502  4928  4958 I ReactNativeJS: tryCatch@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:21522:23
10-06 14:13:32.502  4928  4958 I ReactNativeJS: invoke@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:21695:32
10-06 14:13:32.502  4928  4958 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:21565:30
10-06 14:13:32.502  4928  4958 I ReactNativeJS: tryCatch@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:21522:23
10-06 14:13:32.502  4928  4958 I ReactNativeJS: invoke@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:21598:30
10-06 14:13:32.502  4928  4958 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:21610:21
10-06 14:13:32.502  4928  4958 I ReactNativeJS: tryCallOne@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:20851:16
10-06 14:13:32.502  4928  4958 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:20952:27
10-06 14:13:32.502  4928  4958 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:22274:26
10-06 14:13:32.502  4928  4958 I ReactNativeJS: _callTimer@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:22163:17
10-06 14:13:32.502  4928  4958 I ReactNativeJS: _callImmediatesPass@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:22199:19
10-06 14:13:32.502  4928  4958 I ReactNativeJS: callImmediates@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:22418:33
10-06 14:13:32.502  4928  4958 I ReactNativeJS: callImmediates@[native code]
10-06 14:13:32.502  4928  4958 I ReactNativeJS: __callImmediates@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2755:35
10-06 14:13:32.502  4928  4958 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2592:34
10-06 14:13:32.502  4928  4958 I ReactNativeJS: __guard@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2738:15
10-06 14:13:32.502  4928  4958 I ReactNativeJS: flushedQueue@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2591:21
10-06 14:13:32.502  4928  4958 I ReactNativeJS: flushedQueue@[native code]
10-06 14:13:32.502  4928  4958 I ReactNativeJS: invokeCallbackAndReturnFlushedQueue@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2584:33
10-06 14:13:32.502  4928  4958 I ReactNativeJS: invokeCallbackAndReturnFlushedQueue@[native code]"
10-06 14:13:32.503  4928  4958 I ReactNativeJS: 2018-10-06 14:13:32: "Setting up recurrent sync with interval 300"
10-06 14:13:32.504  4928  4958 I ReactNativeJS: 2018-10-06 14:13:32: "Recurrent sync operation DISABLED!!!"
10-06 14:13:32.505  4928  4958 I ReactNativeJS: 2018-10-06 14:13:32: "Updating all notifications..."
10-06 14:13:32.507  4928  4958 I ReactNativeJS: 2018-10-06 14:13:32: "Garbage collecting alarms..."
10-06 14:13:33.514  4928  4958 I ReactNativeJS: 2018-10-06 14:13:33: "DecryptionWorker: starting decryption..."
10-06 14:13:33.516  4928  4958 I ReactNativeJS: 2018-10-06 14:13:33: "Reducer action", "DECRYPTION_WORKER_SET"
10-06 14:13:33.580  4928  4958 I ReactNativeJS: 2018-10-06 14:13:33: "DecryptionWorker: completed decryption."
10-06 14:13:33.580  4928  4958 I ReactNativeJS: 2018-10-06 14:13:33: "Reducer action", "DECRYPTION_WORKER_SET"
10-06 14:13:52.469  4928  4958 I ReactNativeJS: 2018-10-06 14:13:52: "ResourceService::indexNoteResources: Start"
10-06 14:13:52.660  4928  4958 I ReactNativeJS: 2018-10-06 14:13:52: "ResourceService::indexNoteResources: Completed"
10-06 14:13:52.671  4928  4958 I ReactNativeJS: 2018-10-06 14:13:52: "ResourceService::deleteOrphanResources:", "[]"
```

**Comment by tessus** [comment]
Btw, this issue has nothing to do with this change.

I get the same behavior on master.

**Comment by laurent22** [comment]
Not sure but it might be this bug, at least that's the crash I'm getting: https://github.com/joltup/rn-fetch-blob/issues/79

**Comment by laurent22** [comment]
Ok that should be fixed in this commit: https://github.com/laurent22/joplin/commit/44986a35a4861ac6dfe38df2c27c160f73240ba4

I think Android sends back paths in a format that's not understood by react-native-fetch-blob so I've switched to copying the file using react-native-fs (all files operations should actually use this module which is much more reliable).

**Comment by tessus** [comment]
Hmm, after doing a rebase I got the following....

screenshot_1538982182

**Comment by tessus** [comment]
Ok, I now got it working. The app doesn't crash anymore when adding a file and the webp file is shown correctly.

However, I still see warnings when starting Joplin.

<details>
<summary>Screenshot</summary>

screenshot_1538982654


</details>

**Comment by laurent22** [comment]
Yes these are expected warnings. We'll need to wait for the third-party modules to fix them.

**Comment by tessus** [comment]
ok, in that case this PR should be ok.

**Comment by laurent22** [comment]
Thanks!

**Pull request merged**
