### PR TITLE
Windows: Fixes #11508: Prevent installer from recognizing itself as a running instance of Joplin

### LINKED ISSUE #11508: Cannot install Joplin 3.2 on Windows
> I cannot install 3.2.4 - I get "Joplin cannot be closed. Please close it manually and click Retry to continue." But I did close it manually before installing 3.2.4. I looked through the Task Manager (I'm on Windows 10) and do not see any Joplin processes. I also tried rebooting and running the 3.2.4 install first thing before starting anything else, same result. Any suggestions?

Ref: https://discourse.joplinapp.org/t/desktop-pre-release-v3-2-is-now-available-updated-12-12-2024/41898/23?u=laurent

I think it may be due to this issue? https://github.com/electron-userland/electron-builder/issues/8131

Which has a fix here:

https://github.com/electron-userland/electron-builder/pull/8133

But for now only available on an alpha version. Maybe we can try to use yarn patch to fix this?

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request may fix #11508. It re-applies an `electron-builder` patch that seems to have been lost [when upgrading Electron (in 2023)](https://github.com/laurent22/joplin/commit/17831bf87ad657e391c13227b450c10bc2f566af#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR12213). For additional details, see [the pull request in which the patch was originally added](https://github.com/laurent22/joplin/pull/8451#issue-1798623763).

If the patch does fix the issue, I plan open an upstream pull request with the change.

# Testing plan

> [!NOTE]
>
> I haven't been able to reproduce #11508 on my Windows 11 development virtual machine. The below steps are primarily to test for regressions.

**Windows 11**:
1. Build `Joplin Setup 3.2.5.exe` using `yarn dist` from `packages/app-desktop`.
2. Start Joplin if not already running.
3. Run `Joplin Setup 3.2.5.exe`.
4. Start installing Joplin for the local user.
5. Verify that a "Joplin is running. \ Click OK to close it." dialog is shown.
6. Click "OK".
7. Verify that Joplin is closed.
8. Wait for installation to complete.
9. Leave "Run Joplin" checked.
10. Click "Finish".
11. Verify that Joplin starts.

### CODE REVIEW

**Comment by laurent22** [comment]
Now that https://github.com/laurent22/joplin/pull/11541 has been merged, should we close this one?

**Comment by personalizedrefrigerator** [comment]
Yes. Let's close this pull request.

**Comment by mess-maker** [comment]
hi same issue on 3.2.6

**Comment by manderss99** [comment]
3.2.6 has same problem win11, cannot install.

**Comment by laurent22** [comment]
Please try manually uninstalling and installing again

**Comment by mess-maker** [comment]
3.2.10 installed (without prior uninstall)
had an error message saying that it cannot uninstall previous version, selected continue there, and the install has completed

**Pull request closed without merging**
