### PR TITLE
Desktop: (linux) created and adding high contrast icons

### PR DESCRIPTION
**Pull request by taw00**
They are needed for a complete linux desktop experience (accessibility).

The desktop standard for Linux requires both hicolor and highcontrast icons that eventually land in (via packaging) directory structures that look like this:
```
/usr/share/hicolor/WxH/apps/joplin.png
/usr/share/hicolor/scalable/apps/joplin.svg
/usr/share/HighContrast/WxH/apps/joplin.png
/usr/share/HighContrast/scalable/apps/joplin.png
```
When someone needs high contrast on their system, usually for accessibility reasons, they switch to that in their desktop settings and the menu icon will change accordingly.

I try to ensure all the stuff I package has both a breadth of icon sizes as well as both hicolor (the normally branded icons) and high contrasting icons (starker and simpler coloration and generally outlined in heavy white).

You will see if you look at the icons I have provided that joplin already has a favorable color scheme (there is argument that one could darken the blue for the high contrast icons), but I also shrunk the J a smidgen to pull it away from the edges and encircled the icon in a thick white perimeter.

I hope that all makes sense. Have a lovely day. -todd

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks, but I don't quite understand:

- How are they connected to the application? I don't think they will be packaged with the app just because they are in this folder, or am missing something?

- What's the difference between these icons and the regular icons (for me they look the same but I didn't put them side by side)? I think the current one is already quite high contrast so I'm not sure these are necessary?

**Comment by taw00** [comment]
On a linux desktop ...

The why: The hicolor and HighContrast trees are supposed to be populated if a desktop application is to check all the boxes for a "correctly packaged application".

How are they different?: HighContrast have to have highly contrasting colors and a stand-out border. White is, more or less what it should be. If you use a linux machine, switch to high contrast and look at how all the icons change. That will illustrate it better than I can.

You also need a `joplin.appdata.xml` file included in any packaged linux desktop application for it to be complete, but... that is a different issue that I have not filed yet (just look under `/usr/share/metadata/` to see what I mean) because I want to make sure whatever I submit is generic enough (Ubuntu, Fedora, etc. etc.)

The RPMs I have building for some time -- https://github.com/taw00/joplin-rpm -- have been filling in some of these gaps on RPM-based machines.

**Comment by laurent22** [comment]
Since the icons are specific to the RPM package, shouldn't they be part of that package instead? What I mean is that this PR simply drop icons in a directory, but that directory is not used by anything. When the app is built, then won't be packaged with the app.

Also that's 12 more icons to maintain, even though they aren't very different from the original ones. Can't they be dynamically generated from the original ones? In that case, we could add the script that generates them to the repo.

**Comment by taw00** [comment]
Nothing is specific to RPM in these Icons and how they are to be deployed. It is part of the standard expectations of a desktop application on Linux. It is expected that sets of varying resolutions and a scalable vector graphic populate the `/usr/share/icons/hicolor/` and `/usr/share/icons/HighContrast/` trees.

RPM packages. DEB packages. Etc. For desktop applications these are supposed to be provided.
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

The spec documents are difficult to parse, but the various package building documentation help to summarize. Additionally, just looking at other applications helps, though many break the guidelines.

Up to you. I figured I would just provide them since I was providing them in my RPM building endeavors. Joplin is also missing a `joplin.appdata.xml` file which is supposed to land in `/usr/share/metainfo/joplin.appdata.xml` -- I need to dig in a bit deeper with that to see if mine is truly properly formatting. Plus, I don't know if it is more dynamic than I made mine. Anyway. I digress.

**Comment by laurent22** [comment]
I'm hoping to write a script at some point that will dynamically generate all the icons Joplin needs (there are already many of them), so when it's done we can revisit this issue.

**Pull request closed without merging**
