### PR TITLE
Desktop: Resolves #6035: Fix global search causing text overwriting

### LINKED ISSUE #6035: Global search focuses text in notes so that edits overwrite highlighted text
I have noticed recently that when doing a global search, and choosing a note from the note list, the found text is highlighted in the note. So far so good. But when I click into the note (e.g. at the end to append something) the cursor jumps _after the first character_ to the highlight and Joplin starts to over-write this text.

I've attached a short video to explain more clearly!

https://user-images.githubusercontent.com/1671065/149974279-7f5c02fd-0ed5-4ba4-87cc-c970c3d35d9a.mp4

## Environment

Joplin version: 2.7.7 (although I think this happened on at least the few recent releases of the 2.7 series)
Platform: linux
OS specifics: ubuntu 20.04

## Steps to reproduce

1. Create a note with given text
2. Search for this text in the global search
3. Select the created note from the list
4. Click at the end of the note to position the cursor to append some text
5. Start tying
6. Note that the _first_ character is correctly placed, but that subsequent characters overwrite the "found" text in the note

(note that I have tested this in safe mode - as in the video - to make sure it was not due to a plugin)

## Describe what you expected to happen
Regardless of the search highlighting, edits should occur where the cursor is positioned.

### PR DESCRIPTION
**Pull request by CalebJohn**
As briefly mentioned in a [comment in the report thread](https://github.com/laurent22/joplin/issues/6035#issuecomment-1016231963), this bug was the nasty combination of 2 changes. One which made the highlight also select, and the other which ensured that the scroll-to functionality would happen even for searches with a single result. The selection works perfectly fine, but when combined with a bug in the second change (the scroll-to became not discriminant enough and was called frequently) it caused this more visible bug. This is a fix for the frequent scroll/selection issue, the selection code is left unchanged.

The previous fix was to always jump if there's only a single result but this combined with the change to make searches selected meant that many users were accidentally deleting text when it was re-selected.
This commit fixes that problem by replacing the simple single-result-fix with one that observes the last search time to decide when to jump.

b98e64c can be restored after this change.

### CODE REVIEW

**Comment by laurent22** [comment]
@CalebJohn @ken1kob could you confirm what would need to be merged to fix this issue? Are your two pull requests related or would they conflict with each others?

Or maybe could we create just one pull request that has all the required changes, including any commit that needs to restored?

**Comment by ken1kob** [comment]
> @CalebJohn @ken1kob could you confirm what would need to be merged to fix this issue? Are your two pull requests related or would they conflict with each others?

I tried PR #6038 (mine) to v2.7.6 and then PR #6037 (@CalebJohn's). They don't conflict, and things go fine.

**Comment by laurent22** [comment]
But the two pull requests both fixing the same bug, but in a different way? Do we need both fixes?

**Comment by ken1kob** [comment]
> But aren't the two pull requests both fixing the same bug, but in a different way? Do we need both fixes?

Yes. The two PRs fix different causes respectively. Either of them can suppress the symptom, but the both are desirable to completely solve the problem.

**Comment by CalebJohn** [comment]
> But aren't the two pull requests both fixing the same bug, but in a different way? Do we need both fixes?

I agree with @ken1kob here, both PRs are useful and focus on different aspects of the problem. 
This PR fixes the [bug recently noted in the original thread](https://github.com/laurent22/joplin/issues/6035#issuecomment-1016910542). This fixes the original bug because it prevents the query from being re-selected on every edit.
@ken1kobs PR fixes the bug by disabling the selection behaviour when using the global search. This is an important usability fix, even when not considering this big report.

So both are fixing the original bug report and a little bit extra. You can really view it as both fixing different issues that happen to fix the reported issue.

I can wrap these commits up into a PR that restores the previous commit if you'd like. I'll do it after dinner.

**Pull request closed without merging**
