### PR TITLE
CLI: Fixes #4808: Fixed spacebar turning non-todo note into todo

### LINKED ISSUE #4808: Note converts to todo note when toggling complete/incomplete
Note converts to todo note when toggling complete/incomplete.

## Environment

Joplin version: joplin 1.7.0
Platform: Linux terminal
OS specifics: Manjaro

## Steps to reproduce

1. Select non-todo note
2. press space bar
3. 

## Describe what you expected to happen
Either no action, since the note is not a todo list, or for multiple presses of the spacebar to convert it back into the non-todo note.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6253431/log.txt)

### PR DESCRIPTION
**Pull request by lkiThakur**
## Changes
Declared a new command toggleTodo and assigned it to spacebar.
this new command only works on todos and keeps notes unaffected.

I also noticed that this command is not getting suggested when user starts typing `todo toggle` which is a desired behaviour in my opinion; since primary purpose of this command is to handle `spacebar` keypress.
## Manual test
In the video below ; look at the bottom panel (where commands are executed) to know when spacebar was pressed
terminalFix

 
> I was not able to provide automated tests because of not being able to figure out the way to implement them here.

### CODE REVIEW

**Comment by lkiThakur** [comment]
@laurent22  @tessus   since you had already reviewed a PR on same issue can you please review this pull request

**Comment by laurent22** [comment]
I would suggest you read the pull request guidelines again, in particular:

> All pull request must have test units. If for some reason it is not possible to add tests, please let us know and explain why. In that case, you'll need to tell us what steps you followed to manually test your changes.

> Please do not @mention contributors and mentor and do not ask for pull request reviews. Sometimes it takes time before we can review your pull request or answer your questions but we'll get to it sooner or later. @mentioning someone just adds to the pile of notifications we get and it won't make us look at your issue faster.

**Comment by lkiThakur** [comment]
I'm sorry for not sticking to the guideline ; adding tests for this PR seemed impossible to me and i mentioned that in my first comment .
I used `@ ` mention so that the people who already reviewed similar PR get the information about it and other mentors are not needed to start from the beggining .
I'm sorry for these and I will not repeat this behaviour in future.

**Comment by laurent22** [comment]
Adding tests is not impossible, you'd just need to instantiate the class and call `action()` with the right arguments. Taking the time to setup tests for the CLI tool is something that would be very useful. On the other hand, the provided fix is a bit weird to be honest - `todo toggleToDO` is like every effort is made to make the command as confusing as possible. Repeating "todo" but with seemingly random casing, and no explanation to the user why they should choose this instead of "todo toggle".

**Comment by lkiThakur** [comment]
> Adding tests is not impossible, you'd just need to instantiate the class and call `action()` with the right arguments. Taking the time to setup tests for the CLI tool is something that would be very useful.

I'm trying to add them ASAP.

> no explanation to the user why they should choose this instead of "todo toggle".

Actually I thought users will not have any situation where they need to invoke this command by typing it; I only wrote it to bind it with `spacebar` key. however **if there're possible cases where users have to use this command by typing then I should also make changes to autocomplete.js so that users can get autocompletion on this command.**
>Repeating "todo" but with seemingly random casing,

Sorry for that ; i changed it to toggleTodo in next commit

**Comment by laurent22** [comment]
Feel free to look into it but I can't promise I'm going to merge. I think someone needs to think through it properly and comes up with a solution. Or maybe there's no solution and it should just stay as it is.

**Comment by laurent22** [comment]
Thanks for looking into it but I'm not convinced we should make this change, so I'm closing the PR for now.

**Pull request closed without merging**
