### PR TITLE
Desktop: Fixed top margin of toolbar

### LINKED ISSUE #2824: Desktop: Upper border of selected icon outline is not inline with gray menu border
When hovering over any icon in app, outline is few pixels higher than it should be

Screenshot 2020-03-21 at 00 01 15

image

## Environment

Joplin version: v1.0.194
Platform: macOS
OS specifics: 10.15

## Steps to reproduce

1. Open Joplin app
2. Hover over any icon

## Describe what you expected to happen
Icon outline was expected to be inline with gray border

### PR DESCRIPTION
**Pull request by coderrsid**
Platform: macOS
Fixes #2824 

## Before
image

### After
image
image

### In detailed view
image  image

### CODE REVIEW

**Comment by coderrsid** [comment]
Label me @PackElend

**Comment by laurent22** [comment]
Looks good, thanks @coderrsid.

**Comment by coderrsid** [comment]
Great !! Thanks.

**Comment by Perkolator** [comment]
Is it intended that on Windows now with this modification the button outline top border is not on the title box horizontal line anymore?

button

(Man I hate that new BIG TITLE box, stupid change in Joplin)

**Comment by laurent22** [comment]
Please be nice. We're all trying to improve the app here, and changes can be undone or improved if there are good reasons for it, but calling people's work stupid is not helpful.

**Comment by coderrsid** [comment]
Hey @Perkolator, we believe there should be a sense of difference between 2 components, that's why it's done and yeah as laurent said you can be a little more polite. 🙍

**Comment by Perkolator** [comment]
But you fail to see that there's now (still) difference how that button outline is shown in Windows vs. Mac. On Mac the top line is on the horizontal line while on Windows it's 1 pixel below.

**Comment by coderrsid** [comment]
Oh wow, i guess that's bothering so much of your important work right?

**Comment by Perkolator** [comment]
You tell me to be polite and you start behaving this way?! I don't understand.

Is not my observation a valid question? I'm just trying to make Joplin better.

**Comment by rabeehrz** [comment]
> Is not my observation a valid question? I'm just trying to make Joplin better.

Hey @Perkolator, Thank you for noticing that issue. On Mac, It was off before. That's why this PR was done. It looks like this change affects the Windows version.

We will look into this. Meanwhile, can you try adding custom css to fix this:

```
.editor-toolbar {
	margin-top: 3px;
}
```

The selector is editor-toolbar. And the styles is margin-top. Maybe that could solve your problem? Can you please check?

**Comment by Perkolator** [comment]
I don't have a "problem" with that button outline. I just thought that maybe the goal should have been a parity of the visual representation on different platforms. I wondered that maybe it wasn't thought out that this change would affect other platforms as well.

**Comment by rabeehrz** [comment]
Usually, styles works on both platforms. But I guess we found an exception or something. Maybe it has to be tested on every platform now. 😅

**Comment by Perkolator** [comment]
The [linked issue](https://github.com/laurent22/joplin/issues/2824) already established that the problem was not on Windows, but on Mac.

**Comment by coderrsid** [comment]
@rabeehrz That's a great suggestion. I guess we can add multiple tests for the build of the application or we can assign some contributors or members to test on various platforms and provide. A little tedious on the second option but could be acceptable.

**Comment by coderrsid** [comment]
And perkolator, Thanks for suggesting i'll try to add some code for the test of the platform before rendering these styles ASAP.

**Comment by Perkolator** [comment]
I hope this problem with different visual rendering on different platforms doesn't end up with writing code like this:

```
if "mac" then
    marginTop: 4
elseif "windows" then
    marginTop: 3
elseif "xyz" then
    marginTop: 5
...
```

... and possibly updating those if something changes with the rendering on some platform.

**Pull request merged**
