### PR TITLE
Avoid updating if this is the latest version.

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by laurent22** [comment]
Hi, sorry there have been some confusion with these installation scripts. In particular I've just [merged this](https://github.com/laurent22/joplin/pull/841) which renames your file. Please could you take a look at the latest changes and see if you can integrate yours?

**Comment by tanrax** [comment]
The merge code is integrated and comments have been added to make each section clearer.

**Comment by tanrax** [comment]
Is there any way to prevent linux from asking for the creation of the icon? It generates a double icon with a lower quality.

**Comment by tessus** [comment]
wasn't this file replaced with https://github.com/laurent22/joplin/blob/master/Joplin_install_and_update.sh ?

**Comment by laurent22** [comment]
Yes it was. Any new change should be applied to this other file.

**Comment by tessus** [comment]
In this case this PR should be closed, shouldn't it?

**Comment by tessus** [comment]
@tanrax I think you are missing the point. This script does not exist anymore in the repo. if you want this functionality, you will have to add it to the script that replaced this one.

**Pull request closed without merging**
