### PR TITLE
Welcome: french translation 1 - Welcome!

### PR DESCRIPTION
**Pull request by semiopat**
Here is the french translation of the first Welcome file: 1. Welcome to Joplin!
[1_welcome_to_joplin.fr.txt](https://github.com/laurent22/joplin/files/3593975/1_welcome_to_joplin.fr.txt)

### CODE REVIEW

**Comment by tessus** [comment]
I am going to close this PR, because it's a total mess. Unfortunately I will be away the next few days and I have to go to bed now.
Otherwise I would explain how to use git and create a proper  PR.

If you can wait a few days, I can walk you through it.

**Comment by semiopat** [comment]
I understand it the moment I click to submit. I can wait and I would be thankfull for some explanations.

**Comment by tessus** [comment]
I’ll be back Thursday evening (UTC-4). I’ll write a short guide and send it to you on Thursday or Friday. Then we can either use PMs in the forum or email. Or we could use discord, if you rather chat.

**Comment by tessus** [comment]
@semiopat there's no email address in your profile, so how should I send you the info?
what's your forum username? Is it `pat3`? I just want to make sure that I don't PM the wrong person.

**Comment by semiopat** [comment]
Yes, it is pat3, and I make my address visible in my profile.

**Pull request closed without merging**
