### PR TITLE
API: Fixes #4655: Don't compress image when resource is added through api

### LINKED ISSUE #4655: Created image resource via API is scaled / reduced
When a new image is created as a resource (JPG, PNG, ...) via API, the file is automatically scaled and not the original file is attached as a resource. 

## Environment

Joplin 1.7.11 (prod, win32)

Client ID: fea0ba97613b45d8b1c8ee33e9f08413
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)

## Steps to reproduce

1. Create a image resource via API in a Plugin or with a web request
```
await joplin.data.post(
	["resources"],
	null,
	{ title: "test.jpg" }, // Resource metadata
	[
		{
			path: "/path/to/test.jpg", // Actual file
		},
	]
);
```

2. Check file in `.config\joplin-desktop\resources`

## Describe what you expected to happen

The original file should be uploaded, or there should be an parameter for scaling the image.

### PR DESCRIPTION
**Pull request by nishantwrp**
Fixes #4655.

### CODE REVIEW

**Comment by nishantwrp** [comment]
@laurent22 please review.

**Comment by laurent22** [comment]
Is it in the context of GSoC? If so, please read the pull request guidelines: https://joplinapp.org/gsoc2021/pull_request_guidelines/ In particular, please don't `@mention` us and please include test units.

**Comment by nishantwrp** [comment]
Oh, ok. I'll take care from next time about the guidelines. Added the unit tests.

**Comment by nishantwrp** [comment]
I have a doubt, for testing I've added a large image file randomly from the internet. Are there any rules on which image file should I use?

**Comment by laurent22** [comment]
Good question, we don't want to use any large image because it's going to unnecessarily make the repo larger. I've attached a simple 2500x2000 png to this which you can use. It's just a white image so it doesn't take much space.

[large-image](https://user-images.githubusercontent.com/1285584/111039142-6f8af980-8424-11eb-8183-ad3ca62e8b5d.png)

**Comment by nishantwrp** [comment]
done.

**Comment by laurent22** [comment]
Ok looks good now, thank you for the pull request!

**Pull request merged**
