### PR TITLE
[WIP] Use material design to style main screen

### PR DESCRIPTION
**Pull request by xcffl**
Current progress:
Screenshot_20190410_131034

Note that it's still broken and WIP.

### CODE REVIEW

**Comment by laurent22** [comment]
Hi, thanks for your efforts so far. Because it's such a big change, I think there should be some kind of discussion about it on the forum (or here) and basically try to reach a consensus on whether it should be done and how.

For me these are the pros and cons:

# Advantages

- We can add existing themes easily (I guess?)
- The UI will look nicer (but again, there should be some discussion about this and find out if we actually want the Material design look)

# Disadvantages

- The main one I see is that we are now tied to a framework for the UI. Before everything was done around standards button/input/select, etc. that everybody knows. This framework will make it harder to contribute (even for myself!) since there will now be a new framework to learn.
- Is there any impact on performance?

Also, another question - can't most of it be done using plain CSS (instead of custom components)?

Personally I don't currently have time to review and test the pull request, but if enough people are interested, we could consider it.

**Comment by subi54** [comment]
Care about the performance than UI. Current app UI is good enough, just need performance and editor improvements.

**Comment by xcffl** [comment]
Certainly it can be done via pure CSS (since it's a CSS framework that also provides CSS compiling). However, it's a more reactive and centralized way to put the theming into React.js part.

As for the learning curve, actually it's pretty straight forward -- just replace the tag with one having initial caps (the corresponding component in the framework). And the core of the framework is maintained by Google, so it may not be deprecated so soon.

Besides, for my personal experience, this framework brings responsive and elegant UI with neglect performance penalty.

**Comment by tristil** [comment]
@xcffl Would you provide screenshots in the main description?

**Comment by xcffl** [comment]
Screenshot_20190410_130745


> @xcffl Would you provide screenshots in the main description?

Sure. Updated.

**Comment by tessus** [comment]
IMO the design is lacking. The toolbar buttons are too far apart and the main icons have no text (`New note`, `New notebook`, ...). I also don't like that they are all cramped to the right edge of the screen.
Date and time should be next to each other and not on 2 lines.
When I look at the mockup I find it isn't clearly arranged - and it looks like an ad from a candy store, it's too playful.
I like the current look much better - it looks a lot more professional. Just my 2 cents.

P.S.: Working on the react native interface would be much better received. e.g. getting rid of this extremly unnecessary (and annoying) Welcome screen (as soon as there is one notebook).

**Comment by tessus** [comment]
In my opinion this should be approached differently. I would suggest to create a framework to allow different themes as plugins. e.g. put a theme in a subdirectory and reference it in the code.
Then people can actually choose. In this case, between the `Classic` look and this `Material` design. I certainly woudn't want Joplin to look like this PR suggests, but others might like it.
In the future somebody else might create another theme and boom, we can choose between 3 different themes.

**Comment by kexirong** [comment]
Boostnote's design is clear . 
https://github.com/BoostIO/Boostnote

**Comment by xcffl** [comment]
I agree with @tessus. 
I suppose RMWC would do the trick. Material design is simply the vallina variant. It's highly customizable.

But regarding the use cases, I've already move to another note taking app, and may not be able to help with this.
Hope someone else will look into it.

**Pull request closed without merging**
