### PR TITLE
Desktop: Fixes #9130: Add Electron `--disable-gpu` flag to known flags

### LINKED ISSUE #9130: Joplin desktop does not accept `--disable-gpu` flag
**Joplin desktop does not accept Electron `--disable-gpu` flag.**

At some point I encountered GPU rendering errors on Linux with most Electron applications. And while every other application could be started with `--disable-gpu` flag Joplin desktop refused to accept this flag so I couldn't use it anymore.

I guess this flag is important and desktop app should accept it.

## Environment

Joplin version: latest
Platform: all

I've made a patch for myself.

[Git patch](https://gist.github.com/orl0/6a5e8f46acb000fa1cc33a9b4b2434aa)

I can make a PR if you want.

### PR DESCRIPTION
**Pull request by orl0**
Add Electron `--disable-gpu` flag to known flags in `packages/lib/utils/processStartFlags.ts`

Issue #9130

### CODE REVIEW

**Comment by orl0** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by tessus — APPROVED** [review]
LGTM

**Comment by laurent22** [comment]
@orl0, the flags have been moved to a different file so there's a conflict. Would you mind moving the change to that new file?

**Comment by orl0** [comment]
> @orl0, the flags have been moved to a different file so there's a conflict. Would you mind moving the change to that new file?

Sure thing, new PR is #9179

**Pull request closed without merging**
