### PR TITLE
Update Joplin_install_and_update.sh

### PR DESCRIPTION
**Pull request by zero77**
Start Joplin after the update or installation has finished.

### CODE REVIEW

**Comment by tessus** [comment]
I don't think that starting the app should be part of the install/upgrade script. Maybe it can be added with an option, but not by default. But maybe I'm alone with my opinion.

**Comment by zero77** [comment]
@tessus 
It be great to have Joplin start automatically after updates is this the script that takes care of that or is that some thing else https://github.com/laurent22/joplin/issues/1270.

**Comment by tessus** [comment]
@zero77 the dev has not marked #1270 as a bug, so I'm not sure what you really want to accomplish.
You think that it should be restarted, open an issue and write a PR that fixes your "bug".

Noone has yet established though, if this is the expected and wanted behavior or not.

Maybe you should ask @laurent22 what he thinks of it. (I've already expressed my opinion, but I don't make the descisions.)

**Comment by laurent22** [comment]
I indeed don't think it's standard to auto-start applications after having installed them from the command line. Brew casks for example don't do this. I don't mind if the feature is added via a parameter though, something like `./Joplin_install_and_update.sh --auto-launch-app`

**Comment by tessus** [comment]
@zero77 what's the status of this?

**Comment by zero77** [comment]
@tessus 
I haven't had the time to work on this lately.

But, i would like to implement a complete seamless update/install process.
> kill Joplin > update/install > start Joplin 

But, with parameter so users dont have to do this unless they want to.

**Comment by tessus** [comment]
Ok, sounds like a plan. If you are not able to work on it, maybe we should close this PR and you open a new one (referencing this one) when it is ready.

**Comment by zero77** [comment]
@tessus @laurent22 
What would be the best way to kill Joplin be for doing the update.

**Comment by tessus** [comment]
@zero77 as mentioned before, the following would work:

```
for PID in `ps -ef |grep -e "Joplin" |grep -v "Helper" |grep -v grep |awk '{print $2}'`
do
  kill $PID
done
```

I will add my comments from #1270 here for completeness:

The problem is rather restarting the Joplin processes. It won't be an issue, if only one process was running without any paramters. But if there were several processes you would have to retrieve the start parameters somehow and store them, so that you can start all the instances with the correct parameters.

The kill, upgrade, and restart are the main steps, but you have to figure out all the possibilities and edge cases. (e.g. that several Joplin instances are running). Because if you want to kill all Joplin instances, you also have to restart all of them - otherwise where's the point?
Then you have to make sure that all commands you are using like `grep`, `awk`, `ps` are available and work the same way on the target platforms (which should be the case on Linux boxes).

**Comment by zero77** [comment]
@tessus 
Thanks, i will use that for killing Joplin.
Also, would something like this work for starting Joplin.
> "/home/user/.joplin/Joplin.AppImage" &

**Comment by tessus** [comment]
@zero77 I think you are missing the point where you have to backup the arguments of the joplin processes that are running. You will have to start them with the same arguments again.

e.g.: One Joplin instance was started by clicking on the icon. Another one by passing `--profile /path/to/profile`, ...
So you have to start all of them with the correct arguments again.

As I mentioned before, this is way more complex than killing a process and starting it again. But you wanted this, so you will have to find a way to make it work. IMO it's more trouble than it's worth.

**Comment by zero77** [comment]
@tessus 
Starting the process after update sounds like it will be a lot of work, and i don't currently have the time to research and implement this.

But, i have already created the code that will give users the option to kill Joplin first and then update, and this is implemented using parameters. 

So, would you accept a PR for this and then another separate PR for starting Joplin after the update or install.

**Comment by tessus** [comment]
Laurent will have to answer this. Joplin is his project.

**Comment by laurent22** [comment]
> But, i have already created the code that will give users the option to kill Joplin first and then update, and this is implemented using parameters.

Yes this is fine, feel free to update your PR with this.

**Comment by laurent22** [comment]
Could a Linux user confirm this is working as expected?

**Comment by tessus** [comment]
@laurent22 I don't think this code works - at least no how it might have been intended. If you run it w/o any argument, you will get 2 messages: `Unknown Parameter`. Why? This makes no sense. I should be able to run the script w/o any arguments.
The arguments are also inconsistent. One is `--Kill-Joplin`, the other one `--auto-launch`. 

Also, every time you start the script you get usage information how to use these 2 arguments.

I am very sorry, but this is not how shell scripting is done.

**Comment by laurent22** [comment]
Hmm ok, the script indeed needs to work as it does now without arguments. I think there should be two modes:

- No arguments: the script works as it does now.
- With an argument (like "--start-app"), which starts the app after the install script. If you have something that can kill the running app and restart it with the same param then even better.

**Comment by zero77** [comment]
@tanrax @laurent22 
Thanks for testing this.
The `Unknown Parameter` is meant for when a user types the argument incorrectly but, i forgot to test it with our using any argument at all, i will fix this.

> The arguments are also inconsistent. One is --Kill-Joplin, the other one --auto-launch.

yes, one is meant to kill Joplin first before starting an update and the other is meant to start Joplin after an update or install has finished.
I created these separately incase users only want to do one or the other and not both, this way they have the option to do either.

**Comment by tessus** [comment]
@zero77 by inconsistent I mean that one used capitalized letters, the other one does not. Pick one. Long arguments are usually lowercase.

Also, when I run the script I do not want to see any help information. Help information is supposed to be displayed when using `-h`, `-?`, and `--help`.

Maybe you should use getopt for parsing arguments.

**Comment by zero77** [comment]
@tanrax @laurent22
Ok, i will make some amendments based on both your suggestions.

**Comment by laurent22** [comment]
Sorry as well for the lack of answers here as well.

I don't think it makes sense to have two options to handle all this. Can we merge the auto-launch and kill-joplin options under "auto-restart"? If that option is set, the app is killed and then auto-restarted.

**Comment by tanrax** [comment]
There wouldn't be any problem implementing it. I can do some testing.

**Comment by tessus** [comment]
> If that option is set, the app is killed and then auto-restarted.

The test case would be as follows:

Start Joplin with `--profile <non-standard-profile-dir>` and then check after the restart, if was restarted with the proper argument.

**Comment by zero77** [comment]
I have made some amendments, now the arguments are either -h or --help for the help message.

Also, i have made one argument called --update that covers the full update procedure including killing Joplin and automatically starting it after the update.

**Comment by laurent22** [comment]
@tessus, it's up to you. If you think the changes are good now feel free to merge.

**Comment by tessus** [comment]
I'm not really sure. Currently only terminating Joplin is implemented, so it's not really complete.
As mentioned before, the startup parameters should be saved in an array and applied when starting joplin again, otherwise you could also do this manually.
I never really understood why this functionality should even be in the update script.

But I can try to improve upon it, if this is really wanted/requested by a lot of people.

I'd not merge the PR as it currently is. The OP can use his own script locally, but I don't think this should be shipped in this state.

**Comment by benallan** [comment]
Hi, I also don't think this is something that's really needed for most users, but just in case it's useful for the OP or anyone else in future I made an attempt at doing this a bit more cleanly:
https://github.com/benallan/joplin/blob/install-script-auto-restart/Joplin_install_and_update.sh

There's a single `--auto-restart` parameter as suggested above, and that interface should hopefully behave properly. 

However it still won't work in lots of cases: I'm still not sure how to reliably get the PIDs of the proper Joplin processes without catching any false positives. Just greping for "Joplin" will match other processes with Joplin in the path, and on my Ubuntu 18.04 system the process seems to be called "joplin" or maybe "Joplin.AppImage". For some reason I also don't see any processes with "Helper" on Ubuntu, while I did see them on my mac. The killing and restarting worked when I tested it, but I'd recommend tuning the `JOPLIN_PROC_NAME` so that it properly finds the right processes on your system.

To be honest, if this feature were to be added I think the cleanest way to do it might be for Joplin to write it's running pid(s) to a file, maybe under .config/joplin, which could then be read by the installer script and ensure we don't get false positives. 

But that's a lot of hassle for very little gain, so I'd just leave it.

**Comment by benallan** [comment]
Here's the updated script just in case it's easier:

```bash
#!/bin/bash
set -e
# Title
echo "     _             _ _       "
echo "    | | ___  _ __ | (_)_ __  "
echo " _  | |/ _ \| '_ \| | | '_ \ "
echo "| |_| | (_) | |_) | | | | | |"
echo " \___/ \___/| .__/|_|_|_| |_|"
echo "            |_|"
echo ""
echo "Linux Installer and Updater"

#-----------------------------------------------------
# Variables
#-----------------------------------------------------
COLOR_RED=$(tput setaf 1)
COLOR_GREEN=$(tput setaf 2)
COLOR_RESET=$(tput sgr0)

# Check and warn if running as root.
if [[ $EUID == 0 ]]; then
  if [[ $* != *--allow-root* ]]; then
    echo "${COLOR_RED}It is not recommended (nor necessary) to run this script as root. To do so anyway, please use '--allow-root'${COLOR_RESET}"
    exit 1
  fi
fi

#-----------------------------------------------------
# Parse arguments
#-----------------------------------------------------
AUTO_RESTART=0
process_cmds=()

USAGE="Usage: Joplin_install_and_update.sh [--auto-restart]"

OPTS=$(getopt -o h --long help,auto-restart -- "$@")
if [[ $? -ne 0 ]]; then
  echo >&2 "Invalid options"
  echo >&2 "${USAGE}"
  exit 1
fi

eval set -- "$OPTS"
while true; do
  case "$1" in
    -h | --help)
      echo "${USAGE}"
      exit 0
      ;;
    --auto-restart)
      AUTO_RESTART=1
      echo "Any running Joplin processes will be killed and restarted after upgrade."
      shift
      ;;
    --)
      shift
      break
      ;;
  esac
done

# Check for any leftover non-option args
if [[ $# -gt 0 ]]; then
  echo >&2 "Invalid options: $*"
  echo >&2 "${USAGE}"
  exit 1
fi

# Get the latest version to download
version=$(wget -qO - "https://api.github.com/repos/laurent22/joplin/releases/latest" | grep -Po '"tag_name": "v\K.*?(?=")')

# Check if it's in the latest version
if [[ ! -e ~/.joplin/VERSION ]] || [[ $(<~/.joplin/VERSION) != "$version" ]]; then

  #-----------------------------------------------------
  # Kill running Joplin processes
  #-----------------------------------------------------
  if [[ "$AUTO_RESTART" -eq "1" ]]; then
    JOPLIN_PROC_NAME="Joplin\|joplin"
    # JOPLIN_PROC_NAME="Joplin.AppImage\|/usr/bin/joplin"
    for PID in $(ps -ef | grep -e "$JOPLIN_PROC_NAME" | grep -v "Helper" | grep -v grep | awk '{print $2}'); do
      # TODO check the parent PID of each process here?
      # If the ppid = 1, then it's probably the master joplin process
      cmd="$(ps -p "$PID" -o args=)"
      process_cmds+=("$cmd")
      echo "Killing process $PID: $cmd"
      kill "$PID"
    done
  fi

  #-----------------------------------------------------
  # Download Joplin
  #-----------------------------------------------------

  echo 'Downloading Joplin...'
  # Delete previous version (in future versions joplin.desktop shouldn't exist)
  rm -f ~/.joplin/*.AppImage ~/.local/share/applications/joplin.desktop ~/.joplin/VERSION

  # Creates the folder where the binary will be stored
  mkdir -p ~/.joplin/

  # Download the latest version
  wget -nv --show-progress -O ~/.joplin/Joplin.AppImage https://github.com/laurent22/joplin/releases/download/v$version/Joplin-$version-x86_64.AppImage

  # Gives execution privileges
  chmod +x ~/.joplin/Joplin.AppImage

  echo "${COLOR_GREEN}OK${COLOR_RESET}"

  #-----------------------------------------------------
  # Icon
  #-----------------------------------------------------

  # Download icon
  echo 'Downloading icon...'
  mkdir -p ~/.local/share/icons/hicolor/512x512/apps
  wget -nv -O ~/.local/share/icons/hicolor/512x512/apps/joplin.png https://joplinapp.org/images/Icon512.png
  echo "${COLOR_GREEN}OK${COLOR_RESET}"

  # Detect desktop environment
  if [ "$XDG_CURRENT_DESKTOP" = "" ]; then
    desktop=$(echo "$XDG_DATA_DIRS" | sed 's/.*\(xfce\|kde\|gnome\).*/\1/')
  else
    desktop=$XDG_CURRENT_DESKTOP
  fi
  desktop=${desktop,,} # convert to lower case

  # Create icon for Gnome
  echo 'Create Desktop icon.'
  if [[ $desktop =~ .*gnome.*|.*kde.*|.*xfce.*|.*mate.*|.*lxqt.*|.*unity.*|.*X-Cinnamon.* ]]; then
    : "${TMPDIR:=/tmp}"
    # This command extracts to squashfs-root by default and can't be changed...
    # So we run in in the tmp directory and clean up after ourselves
    (cd $TMPDIR && ~/.joplin/Joplin.AppImage --appimage-extract joplin.desktop &>/dev/null)
    APPIMAGE_VERSION=$(grep "^X-AppImage-BuildId=" $TMPDIR/squashfs-root/joplin.desktop | head -n 1 | cut -d " " -f 1)
    rm -rf $TMPDIR/squashfs-root
    # Only delete the desktop file if it will be replaced
    rm -f ~/.local/share/applications/appimagekit-joplin.desktop

    # On some systems this directory doesn't exist by default
    mkdir -p ~/.local/share/applications
    echo -e "[Desktop Entry]\nEncoding=UTF-8\nName=Joplin\nComment=Joplin for Desktop\nExec=/home/$USER/.joplin/Joplin.AppImage\nIcon=joplin\nStartupWMClass=Joplin\nType=Application\nCategories=Application;\n$APPIMAGE_VERSION" >>~/.local/share/applications/appimagekit-joplin.desktop
    echo "${COLOR_GREEN}OK${COLOR_RESET}"
  else
    echo "${COLOR_RED}NOT DONE${COLOR_RESET}"
  fi

  #-----------------------------------------------------
  # Restart any previous Joplin processes
  #-----------------------------------------------------
  if [[ "$AUTO_RESTART" -eq "1" ]]; then
    echo "Restarting Joplin processes"
    for ((i = 0; i < ${#process_cmds[@]}; i++)); do
      echo "Attempting to relaunch process: ${process_cmds[$i]}"
      (${process_cmds[$i]} &)
    done
  fi

  #-----------------------------------------------------
  # Finish
  #-----------------------------------------------------

  # Informs the user that it has been installed and cleans variables
  echo "${COLOR_GREEN}Joplin version${COLOR_RESET}" $version "${COLOR_GREEN}installed.${COLOR_RESET}"
  # Add version
  echo $version >~/.joplin/VERSION
else
  echo "${COLOR_GREEN}You already have the latest version${COLOR_RESET}" $version "${COLOR_GREEN}installed.${COLOR_RESET}"
fi
echo 'Bye!'
unset version
```

**Comment by tanrax** [comment]
I understand what you mean, a multitude of threads are created.
Screenshot from 2019-08-08 08-21-45
The solution you propose is not very elegant ... but it is a possibility.
I have encountered 2 bugs:
1. After kill joplin the update does not continue, I must run it a second time.
2. After updating it does not launch Joplin again.

**Comment by benallan** [comment]
Right, it works on my mac, and on one of my linux machines but not on the third. So that's why I'm saying it's not usable as is. 

My guess is that the script's process itself (which contains the text "Joplin"...) was killed too! Hence why I'm saying we need a better way to identify which processes to kill. If you modify the search text in `JOPLIN_PROC_NAME` you might be able to get it to work, or maybe greping to remove the script:

```
    for PID in $(ps -ef | grep -e "$JOPLIN_PROC_NAME" | grep -v "Helper" | grep -v grep | grep -v Joplin_install_and_update | awk '{print $2}'); do
```

I'm not sure why the process isn't launching though.

**Comment by benallan** [comment]
Still no guarantees, but this updated script might work a bit better (works on both the linux machines I tried at least):
https://github.com/benallan/joplin/blob/e8a2c58a0296f51e21a784679a03421b1589ebcb/Joplin_install_and_update.sh

The problems are caused by those secondary helper processes, e.g. trying to kill them after their parent would cause the script to exit. And similarly trying to re-launch a process which was under `/tmp/` would probably fail. 

So yeah, I still can't see a robust way of doing this without having Joplin write its pid somewhere, since trying to figure it out in bash is always going to be flaky!

**Pull request closed without merging**
