### PR TITLE
Update de_DE.po

### PR DESCRIPTION
**Pull request by cedecode**
Minor changes, uniform translation from synchronisation to Synchronisation (no longer Synchronisierung)

### CODE REVIEW

**Comment by cedecode** [comment]
Should this be merged into release-3.0 or into dev?

**Comment by tessus** [comment]
> Should this be merged into release-3.0 or into dev?

I am not sure. afaik they should always go in dev, but maybe I am wrong. @laurent22 what's your take on this?

**Comment by laurent22** [comment]
Yes always in dev once the final stable release is out. After that we only merge security patches and critical bug fixes in the stable release

**Comment by tessus** [comment]
@cedecode can you please re-open the PR to merge into dev?

**Comment by cedecode** [comment]
I will make a new PR. Thanks @tessus and @laurent22.

**Pull request closed without merging**
