### PR TITLE
Mobile : The colour of the notes updated to OLED dark theme, instead of the dark theme

### LINKED ISSUE #2695: OLED dark theme on Android app using dark theme colour for note content instead of OLED dark theme colour (see screenshot).
OLED dark theme on Android app using dark theme colour for note content instead of OLED dark theme colour (see screenshot).
WhatsApp Image 2020-03-08 at 16 01 45
WhatsApp Image 2020-03-08 at 16 01 45(2)
WhatsApp Image 2020-03-08 at 16 01 45(1)

## Environment

Joplin version: 1.0.320
Platform: OnePlus 6
OS specifics: Android 10

## Steps to reproduce

1. Select OLED Dark theme in configuration options.
2. Open a note.

## Describe what you expected to happen
The colour of the notes should be OLED dark theme, but it's the dark theme instead.

## Logfile

[syncReport-1583683460348.txt](https://github.com/laurent22/joplin/files/4303473/syncReport-1583683460348.txt)

### PR DESCRIPTION
**Pull request by Rahulm2310**
Earlier, when we chose OLED dark theme on mobile, the note content in view mode (not in edit mode) had dark theme color instead of OLED dark theme color.This PR fixes that.

Before:
pr2-1

After:
pr2 -2

fixes #2695

### CODE REVIEW

**Comment by CalebJohn** [comment]
Hi @Rahulm2310, nice fix! But you have 2 files with whitespace changes that should not be in this pull request. Can you remove those files and then we'll merge.

**Comment by Rahulm2310** [comment]
Ok @CalebJohn I will fix that.

**Comment by CalebJohn** [comment]
@Rahulm2310 if you could also remove the package.json file then this will be ready for merging

**Comment by Rahulm2310** [comment]
> @Rahulm2310 if you could also remove the package.json file then this will be ready for merging

I m not getting why the package.json is showing those changes even when i didn't touch it.

**Comment by CalebJohn** [comment]
@Rahulm2310 it looks like you probably opened it and your editor made a line ending change for you. You will need to remove using [`git reset HEAD <file>`](https://docs.gitlab.com/ee/university/training/topics/unstage.html)

**Comment by Rahulm2310** [comment]
You will need to remove using [`git reset HEAD <file>`](https://docs.gitlab.com/ee/university/training/topics/unstage.html)

Nothing is changing and everything is up-to date

**Comment by CalebJohn** [comment]
Can you copy and paste your terminal input/output?

**Comment by Rahulm2310** [comment]
error

**Comment by CalebJohn** [comment]
I think since you already commited the file, you'll need to specify i different head something like  `git reset HEAD~7 <file>`

**Comment by Rahulm2310** [comment]
@CalebJohn all changes are fixed & PR is ready to merge.By the way, thanks for supporting man!

**Comment by laurent22** [comment]
Looks good now, thanks @Rahulm2310, and thanks @CalebJohn for reviewing.

**Pull request merged**
