### PR TITLE
Desktop: New search-result orderings

### LINKED ISSUE #1388: Feature request: option to sort search results by date
I believe this is the default for comparable programs like OneNote (or at least they put a weight on descending date). For my use case, this would be more useful than relevance and I'd prefer it to be the default, but I think it should at least be an option. Either through syntax in the search box or a menu option.

### LINKED ISSUE #2071: Order search results by "Last updated"

### PR DESCRIPTION
**Pull request by mic704b**
Resolves #2071 
Resolves #1388

# Changes
- Add menu item to allow user to select search-results order as
  - best match (current method),
  - updated time or
  - title
- Add menu item to allow user to reverse the search-results order
- Add setting to store the selections
- Modify search engine to support new ordering methods
- Add unit tests

search-order-menu

# Testing
- all unit tests pass (old and new) 
- manual testing of desktop app
  - check search results ordered by best match with/without reverse
  - check search results ordered by title with/without reverse
  - check search results ordered by updated time with/without reverse
  - check results list is updated when new selection is made
  - check new settings are saved and restored
  - check order notes behaviour is unaffected

# Comments
There is modified code in ReactNative however the changes are only visible in the desktop app. There is no change in behaviour for mobile and command-line apps.

### CODE REVIEW

**Comment by laurent22** [comment]
Hmm, unfortunately issue #2071 is just something I wrote quickly as a reminder, but the implementation details are missing.

What I had in mind is to improve the existing relevance-based results and give more weight to the "last updated" date. So if several results have a similar weight, those more recent go on top.

Plainly sorting by criteria is not something I'm sure I'd like to support. I think just improving the existing relevance-based results would go a long way. There are various ideas for GSoC: https://joplinapp.org/gsoc2020/ideas.html#7-search

Sorry about that, it's a good pull request but unfortunately not in the direction that I prefer.

**Comment by mic704b** [comment]
No worries, thanks @laurent22

**Comment by frogger72** [comment]
Curious as to why not add plain sort by date this option, so users can at least use it similarly to other notetaking apps? This is all that's stopping me from fully migrating to Joplin.

From a use case perspective, users tend to look for notes in the last a couple weeks (and often the most recent note), so one would type in a keyword and look for the most recent notes matching this. Using an algo to weight relevance and date doesn't address the use case when a user knows it's the last note with the keyword or it was in the last couple weeks.

**Comment by jrlacharnay** [comment]
Could it be integrated into a plugin?

**Pull request closed without merging**
