### PR TITLE
Desktop: Fixes todo-hover behaviour

### LINKED ISSUE #2830: Desktop: To-do in the list in not filled with blue completely on hover
When hovering over to-do item in the list it is not selected (filled with blue) completely

Screen Recording 2020-03-21 at 18 37 06

## Environment

Joplin version: v1.0.194
Platform: macOS
OS specifics: 10.15

## Steps to reproduce

1. Open Joplin app
2. Create new to-do if there are no existing
3. Hover cursor over to-do

## Describe what you expected to happen
To-do was expected to be filled with blue completely

### PR DESCRIPTION
**Pull request by coderrsid**
Fixes #2830 
Platform: macOS

## Before
before

## After
Screen-Recording-2020-03-22-at-1

### CODE REVIEW

**Comment by coderrsid** [comment]
@PackElend label me please!!

**Comment by coderrsid** [comment]
Hey @laurent22 . Are the build tests failing because of the `css-margin` changes ?

**Comment by laurent22** [comment]
@coderrsid, as this feature cannot be unit tested, please list the manual tests you performed to verify this feature. As a hint I can tell you broke something and you could have found that out with careful testing.

**Comment by Rishgod** [comment]
@coderrsid this is your error, 

Screenshot (7)


try adding a commit that does not change anything (a white space maybe) and see if it builds again, this happened to me too it probably a travis CLI glitch

**Comment by coderrsid** [comment]
@Rishgod are you suggesting to add another false commit which doesn't change anything in code to this branch? for this to build properly??

**Comment by coderrsid** [comment]
Hey laurent, now it has no build issues i guess this PR is also ready.

**Comment by laurent22** [comment]
@coderrsid, it's not ready, did you see my comment above?

**Comment by coderrsid** [comment]
Yeah i saw the comment, i am manually testing this feature in every way possible. Thank laurent!

**Comment by coderrsid** [comment]
Screen-Recording-2020-04-03-at-3

Hey laurent, now i've tested the changes in to-do for somedays now and i didn't find any problems
although the checkbox can be ticked and unticked and after ticking , the opacity of the whole to-do component is reduced to 0.5 which also makes the checkbox looks like disabled. I think a new user wouldn't think of unchecking it. Isn't it?

**Comment by laurent22** [comment]
The bug is that now you cannot tick a note without selecting it. Before you could, so that would need to be fixed.

**Comment by coderrsid** [comment]
Yeah i saw that. But we have to do add changes to style. I'll do it ASAP.

**Comment by coderrsid** [comment]
I guess this will work then!
Screen-Recording-2020-04-07-at-3

**Comment by laurent22** [comment]
Makes perfect sense, thanks for the fix @coderrsid.

**Comment by coderrsid** [comment]
Sure laurent. 🤟

**Pull request merged**
