### PR TITLE
Mobile: Resolves #1141: Create / move sub notebook

### PR DESCRIPTION
**Pull request by jki21**
Related to https://github.com/laurent22/joplin/pull/1141. Started from scratch as it should be easier than merging from 3000 commits behind.

Folder move is done in the side menu directly instead of re-using `Dropdown` for following reasons:
- Other folder operations such as rename and delete are also done there
- The dropdown could be confusing whether it is moving a folder or note

Move mode screen:
image

I also have to change the folder long press action to show a context menu as `Alert` could not show more than 3 buttons.

Any comments or advice are welcomed. Hope I didn't break any rules.

### CODE REVIEW

**Comment by tessus** [comment]
Resolves #1141

**Comment by tessus** [comment]
Did you test it on the simulators for Android and iOS?

My mobile dev env is currently slightly shot, but I will try to get it in order and run your code in the simulators.

A lot of people will be happy about this feature! Thank you for adding it.

**Comment by jki21** [comment]
haha I know because I'm one of those people.

> Did you test it on the simulators for Android and iOS?
Only for Android as I'm on Windows. Also I have just noticed that changes made to `root.js` were not committed due to gitignore settings. Will check-in the missed changes in `root.ts` after I figure out how build & test in typescript.

**Comment by laurent22** [comment]
I've tried to test the pull request from a new install, and I got this error when I've tried to create a new notebook:

image

**Comment by laurent22** [comment]
I'll close this for now as it's currently crashing, but feel free to let us know if you'd like to keep working on it.

**Pull request closed without merging**
