### PR TITLE
Translation: Hindi-India

### PR DESCRIPTION
**Pull request by hpnightowl**
*Hindi-indian Language

### CODE REVIEW

**Comment by hpnightowl** [comment]
I Will add more Whenever i will get time

**Comment by hpnightowl** [comment]
i will add more thanks for suggestion @subi54 and sorry but it is not a synonym it is adjective for your kind information.

**Comment by subi54** [comment]
Yes, it's an adjective. Bold and daring are synonymous to each other. Synonym is a word that means exactly or nearly same as another word.

What we are talking about here is Bold (noun): a bold typeface or letter.

**Comment by hpnightowl** [comment]
ok WILL FIX THAT @subi54 THANKS FOR INFO

**Comment by hpnightowl** [comment]
i will add more soon As i get time @subi54

**Comment by tessus** [comment]
Yea, context is very important, that's why machine translations won't always work.

**Comment by hpnightowl** [comment]
i will take care now every time i will do @tessus . you will push it ? or add me as a contributor in this repo i will work on translation in hindi. else i will do pull request only :)

**Comment by laurent22** [comment]
Is it an automated translation from Google Translate?

**Comment by subi54** [comment]
@laurent22 it does seem to be.

**Comment by laurent22** [comment]
Ok I should have mentioned it in the doc but at the moment we don't accept automated translations.

**Comment by hpnightowl** [comment]
not all are automated translation some are done by me also like joplin name and java script ones i will do future once by my self. @laurent22

**Comment by tessus** [comment]
What do you mean? Joplin is a product name and is not supposed to be translated.

I don't want to be rude, but it doesn't look like you have done translations for an application before. Since we can't verify what people translate, we have to trust that the translations are ok. I am sorry to say, but I'm not very confident that this PR is ok.

**Comment by hpnightowl** [comment]
ok then i will close that thanks for suggestion @tessus i will close this pr no trust so no work . :)

**Comment by tessus** [comment]
@hpnightowl I don't decide, if this gets merged. Laurent will have to do that. I'm just saying that according to the different comments I am not very confident - that's all.

**Comment by hpnightowl** [comment]
ok no issue @tessus its ok  i understand :)

**Pull request closed without merging**
