### PR TITLE
All: Bump @codemirror/view version.

### LINKED ISSUE #10043: iOS: Autocorrect inserts 2 line breaks.
### Operating system

iOS

### Joplin version

12.14.6

### Desktop version info

_No response_

### Current behaviour

When typing in the note editor and the last word on the line is spelled incorrectly (autocorrect) pressing return inserts 2 line breaks and does not autocorrect the word
Screen recording explains it better

https://github.com/laurent22/joplin/assets/50887230/c87bb682-e719-48d6-84de-7bd9ac9922da

### Expected behaviour

Instead of inserting 2 new lines it should autocorrect the word and insert 1 new line

### Logs

_No response_

### PR DESCRIPTION
**Pull request by itzTheMeow**
Fixes #10043. (i'm not aware of any other issues this affects)

Bumps the `@codemirror/view` version to [6.26.0](https://github.com/codemirror/view/releases/tag/6.26.0) for the editor.
> Avoid the editor getting confused when iOS autocorrects on pressing Enter and does the correction and the break insertion in two different events.

### CODE REVIEW

**Comment by itzTheMeow** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by itzTheMeow** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by personalizedrefrigerator** [comment]
Thank you for contributing!

Here are a few notes:
- Be sure to also update `yarn.lock` (e.g. by running `yarn install` and committing the result). 
- If tests fail after this, it may be necessary to remove all `@codemirror/` and `@lezer/` dependencies from `yarn.lock`, then re-run `yarn install`.

See also:
- The comment for the relevant regression test:
https://github.com/laurent22/joplin/blob/b29bf7de5d3b3a7469c488602d63782b9febc7c3/packages/editor/CodeMirror/createEditor.test.ts#L23-L31
- [A related thread on the CodeMirror forum](https://discuss.codemirror.net/t/how-to-upgrade-codemirror-past-0-19/5010/4).

**Comment by laurent22** [comment]
CI is passing now. Does that look good to you now @personalizedrefrigerator?

**Comment by personalizedrefrigerator** [comment]
> CI is passing now. Does that look good to you now @personalizedrefrigerator?

I haven't tested this locally, but since the automated tests are passing, this looks good to me!

**Comment by laurent22** [comment]
Great, let's merge then!

**Pull request merged**
