### PR TITLE
Desktop: Fixes #4769: Highlight existing text in the search bar on focus

### LINKED ISSUE #4769: highlight existing text in global search field
When using the shortcut (default: `CtrlCmd+Shift+F`) or the menu item `Edit > Search in all notes`, the focus is set to the global search field.

However, if there's already text in the field, the cursor is placed at the end and typing appends to the existing search term.

This change should highlight the current text, so that it will be replaced by the new search term.

/ref https://discourse.joplinapp.org/t/search-across-notes-selects-existing-search-terms/16252

# Before

gsf1

# After

gsf2

### PR DESCRIPTION
**Pull request by xUser5000**
# Description
Fixes the issue #4769

# What has been done
```
return {
    execute: async () => {
        if (searchBarRef.current) searchBarRef.current.select();
    },
};
```
# In action

# Tests
It would be very difficult to provide an automated unit test for the component because it is tightly coupled with React hooks and other modules. For that we would need a tremendous amount of mock objects in place. Accordingly, I had to do manual testing.
Steps to test the functionality manually:
- Type a query in the search bar
- Click on something else other than the search bar
- Edit -> Search in all notes (or Press F6)
If the previous query text was highlighted, the functionality is working correctly.

### CODE REVIEW

**Comment by CalebJohn** [comment]
Just FYI @xUser5000 this is a duplicate of #4773. Duplicates are not against the rules and so we will still consider this for the GSoC program. 
However, this does not seem to be the correct solution to the issue. From what I can see here, the text is selected whenever the search bar gains focus. The desired (and IMO better) behaviour is just when the text box is focused using a command.

**Comment by xUser5000** [comment]
@CalebJohn 
Oh, sorry! Didn't notice that

**Comment by xUser5000** [comment]
@CalebJohn @tessus
I've edited the PR a bit. Is it good now ?

**Comment by CalebJohn** [comment]
@xUser5000 it's looks good to me know. It is also now identical to #4773 so I think we should give priority to it because it was opened first.

**Pull request closed without merging**
