### PR TITLE
Updated Request to v2.88.0 to remove dependency on Outdated and Insecure Hawk and Cryptiles Dependencies

### PR DESCRIPTION
**Pull request by bedwardly-down**
The maintainer is no longer supporting any version of cryptiles before
v4.2.0 on npm; npm's older versions stop at 3.1.2 and a high security
vulnerability was thrown during a build on linux: https://npmjs.com/advisories/720

The maintainer still has 3.1.4 tagged in his repo and this commit
updates cryptiles to solve that issue without breaking compatibility
since it was primarily bug fixes for a code freeze.

EDIT: After talking a bit on here with both @laurent22 and @tessus and running basic tests on the app after building, it doesn't look like Request 2.88.0 breaks anything and they have dropped support for dependencies on Hawk and Cryptiles while also keeping the overall api the same.

### CODE REVIEW

**Comment by tessus** [comment]
I think you should open an issue with the maintainer of the package `hawk`. `Cryptiles` is used by `hawk` and thus should be fixed there.

**Comment by bedwardly-down** [comment]
@tessus thanks for the suggestion. This is my first time doing a pull request like this, so I'm still pretty wet behind the ears about it.

**Comment by tessus** [comment]
No worries. But IMO this should be fixed upstream. e.g. what happens, of you upgrade Cryptiles, but hawk does not support that version?

**Comment by bedwardly-down** [comment]
It's the same maintainer and he's not supporting before 7.1.0 on npm either: https://www.npmjs.com/package/@hapi/hawk?activeTab=versions

Cryptiles: https://www.npmjs.com/package/@hapi/cryptiles?activeTab=versions

**Comment by tessus** [comment]
ok, in that case you have to figure out which package requires `hawk` and then tell them to update `hawk`. I get it, it's a never-ending story, but not much we can do about it.
Update X, which then updates hawk, which in turn updates Cryptiles....

**Comment by bedwardly-down** [comment]
Thanks. Will do. 

Here's my [original post](https://discourse.joplinapp.org/t/trying-to-build-from-source-threw-a-security-advisory/5329) on the forums about it. I'll contact request and see what's up with that.

**Comment by bedwardly-down** [comment]
How is hawk used here and could it possibly be dropped from the dependencies and everything be fine with the code base? After version 2.86.0 of request, it is fully dropped as a dependency.

**Comment by tessus** [comment]
Which means, if we update request, hawk will be dropped automatically. The question now is, whether we can update `request` without breaking anything. 
Maybe there's a reason why Laurent didn't update request. I guess we need @laurent22's input.

**Comment by bedwardly-down** [comment]
Request 2.86.0 pulls in hawk 6.0.2 and cryptiles 3.1.4, both of which are the final releases of their respective versions. After that, Request 2.87.0 fully drops both. I have a request branch on my repo that I'm testing out 2.86.0 build on as we speak.

**Comment by laurent22** [comment]
I don't know anything about this. You'd need to understand how the dependency is used, in which apps, check the changelogs for breaking changes, maybe try to upgrade and test of it still works.

**Comment by bedwardly-down** [comment]
[Request branch](https://github.com/bedwardly-down/joplin/tree/request) pushed to my fork. It builds with no errors so far.

## What's Working So Far (on Desktop)

1. Syncing
2. Creating a new note
3. Moving notes around

**Comment by bedwardly-down** [comment]
Request is used for https calls as and hawk was used for authentication purposes. So far, from what I can tell, they just dropped the package as a dependency but the basic usage is still the same.

**Comment by tessus** [comment]
The Tools directory is only used for the internal infrastructure and building.

So, nothing you do here will change how Joplin behaves. You would have to change the 'package.json` files for all apps. However, `request` is only listed/used in the Cli terminal app and has been upgraded to 2.88.0 already. Not sure why the request package is not used for the desktop and mobile apps.

Anyway, since this change only affects the Tools, I think we are good to merge.

**Comment by bedwardly-down** [comment]
I see nothing related to https or authentication in ElectronClient or ReactNativeClient directories. I wonder if everything but the CliClient uses Tools for that? I've gotta go back to work but if omitting the request package will break syncing.

**Comment by bedwardly-down** [comment]
The only file in Tools that even calls the request module directly is `Tools/update-readme-contributors.js`. Is that what you're seeing? It's a bit tricky on phone to search through files but doable.

**Comment by tessus** [comment]
You misunderstood. None of the clients use the tools package.json file. That file in tools is exclusively for the scripts in the Tools dir.

**Comment by bedwardly-down** [comment]
Gotya. I did misunderstand. So, just plug it in to the other package.jsons and see if it breaks anything?

**Comment by bedwardly-down** [comment]
Sqlite3 requires request: https://www.npmjs.com/package/sqlite3?activeTab=dependencies

**Comment by tessus** [comment]
No, why would you add a package that isn't there already?

Let me try this again.

The CLI terminal client is the only client that lists the `request` package in the `package.json` file. And it is already on 2.88.0. Thus nothong to do there.

The desktop app and the mobile apps either do not use this package or it is pulled as a dependency by another package. If it's the latter, you will have to find the package and contact the maintaiers to update it so they pull in 2.88.0 as a dependency.

Ok, your update came in. So contact sqite maintainers and tell them to use 2.88.0.

**Comment by bedwardly-down** [comment]
Already beat you to the punch. Version 4.1.1 of sqlite3 uses version 2.88.0 of request, so no breakage there.

**Comment by tessus** [comment]
We are using 4.1.1 already so what do you want to do? There is nothing to do.
The only occurrence of the message you got was during install of the tools. And they have nothing to do with the Joplin code.
So after your PR is merged all is good.

**Comment by bedwardly-down** [comment]
I have no goals beyond that right now. I'm mainly just trying to get a feel for how this all works and getting a bit too excited about it. Haha. Thanks for the help, by the way. ☺️

**Comment by laurent22** [comment]
So are the scripts where this dependency is used still working? That's the only thing that matters to me. The security issue is not even one really because we aren't running a server.

**Comment by bedwardly-down** [comment]
The only place Request is used, from what i could tell, is to get the contributer list from Github in Tools and how it does it won't break from updating to a newer version of request and is wprking fine for me. Updating will at least keep people building the source code like i was from asking about it and panicking about security vulnerabilities even if they aren't actually applicable to. Updating will also allow Tools to be consistent with the rest of the code base since they are already using Request 2.87.0 (as an Sqlite3 dependency) or Request 2.88.0 (for CliClient).

In all honesty, if it doesn't break Sqlite3, would making Request 2.88.0 the version across all directories be a good oprolion anyways? 2.88.0 mainly was just bug fixes with very little if any major API changes.

**Comment by laurent22** [comment]
Ok if it doesn't break the script, then let's merge. For SQLite 3, we'll upgrade the package independently.

**Pull request merged**
