### PR TITLE
All: Sort search results by average of multiple criteria, including 'Sort notes by' field setting

### PR DESCRIPTION
**Pull request by shawnaxsom**
As discussed here:

https://discourse.joplinapp.org/t/improvement-idea-pre-fill-goto-anything-list-with-recently-updated-notes/4002/5

This is a work-in-progress. While I need to add/update tests and test various cases, it works well for me so far. Tessus suggested waiting for input from Laurent before it can be accepted.

**Use cases**

I have quite a few search use cases at my job that I'm sure are common, and Joplin returns very irrelevant (outdated) results with the current implementation.

I often will search for phrases like "one-on-one", or my bosses's name, or "interview", or "Recruiting meeting". I might be reviewing recent candidates, or pulling up notes from recent conversations I've had with my boss while talking with him, for example.

With the current search implementation, these results have rarely factored in last created or updated dates. It would pull up interviews I did at my previous companies years ago, or conversations I had with direct reports or my boss from last year, which are rarely the results I'm looking for. I found that this is because SearchEngine.processResults_() stops considering sorting criteria on the first difference it finds, and it rarely falls through to consider date.

**Intentions and changes in this PR**

Summary: Modify search to factor in all criteria in a weighted manner, and include the created/updated/title fields as factors if selected by the user.

- Change SearchEngine. Sort search results essentially using a weighted average to factor in all search results criteria, rather than just basing it off of the first criteria difference between two rows.
- In effect, this allows created/updated dates to be more of a factor. Last updated date was last in line, and it is rarely a factor in my data set as the slightest change in weight/fuzziness would overrule any difference in date.
- Additionally, it seems the user's "Sort notes by..." settings should be considered. They are now used to change which additional field is used in the sort criteria.

### CODE REVIEW

**Comment by laurent22** [comment]
I don't really have an opinion on this pull request to be honest. Search is complex and I think any change we make should be based on prior art, otherwise it's easy to make a change that will make results better in some cases, and worse in other cases.

As it is, I'm unfortunately unable to review the pull request. Perhaps @naviji would have a better idea about this?

**Comment by shawnaxsom** [comment]
The sentiment makes sense, but here is something to consider.

```
Checked user_updated_time in: 12 out of: 141 search results
Checked user_updated_time in: 10 out of: 107 search results
Checked user_updated_time in: 2 out of: 33 search results
Checked user_updated_time in: 166 out of: 238 search results
Checked user_updated_time in: 0 out of: 19 search results
Checked user_updated_time in: 8 out of: 41 search results
Checked user_updated_time in: 8 out of: 84 search results
Checked user_updated_time in: 80 out of: 334 search results
Checked user_updated_time in: 51 out of: 196 search results
Checked user_updated_time in: 4 out of: 130 search results


```

That doesn't seem like the behavior we'd want, does it? Should

**Comment by shawnaxsom** [comment]
Sounds good, I'd be curious what @naviji thinks.

I agree, any search changes could make some cases better and some cases worse, which is why I made the change based on the "Sort notes by..." configuration value (as a user, I was originally surprised that this setting had no impact on search results). We could consider other UI or other configuration settings rather than reusing that menu item setting.

With configuration, a user can choose between sorting more by content or time. Right now, users are stuck to use one search algorithm that doesn't factor in time often at all.

Some users may choose to configure to sort by title or content weight, but most of my search use cases are time-sensitive. Many are based on work discussions or meetings that are highly time dependent for relevancy. But even more evergreen searches phrases like "JavaScript" are often time sensitive, too: I update more important notes more often (like with "cheat sheets" notes), and older notes about subjects like technology are likely to be obsolete.

But users are stuck with the current algorithm, which is skewed heavily towards content weight, and totally disregards note dates/times in the majority of tests I ran:

I ran 14 common searches, and only 17% average (10% median) of the search results factored in "last updated date" at all.

The screenshot below is actually from the BEST case scenario, with the search term "one-on-one", in which search results factored in time with 166/238 of the search results.

Yet that is still 30% of results that aren't factoring in age of the note whatsoever. And when I'm searching for one-on-ones with my direct reports, it isn't ideal to have 9/24 of the search results be notes from 2014-2015. I can search by `one-on-one updated:year-1` or use notebooks/tags, but for me those are less convenient (especially when I'm trying to quickly look up information in the middle of a meeting).

Left: current Joplin implementation
Right: results from this pull request

CleanShot 2020-09-20 at 09 40 27@2x

**Comment by naviji** [comment]
Hi @shawnaxsom !

In general, I do like the idea of considering the "freshness" of a note when sorting. It is a fact that people are more likely to open and edit notes they've recently opened and edited.

Indeed, the current sorting rarely considers the updated time of a note. This is because, as you've mentioned,  two notes rarely have the same weight, so it rarely checks the updated time.

But fuzziness was never meant to be a widely varying value. In fact, if you search for a single word, the notes returned will only have 3 distinct values of fuzziness. This was supposed to ideally separate the search results into 3 broad groups. 
1. Notes with at least one exact match
2. Notes with at least one close match
3. Notes with only very fuzzy matches

And then to sort these groups by the relevance function.

But you just made me realize that I've made a mistake here. If there were multiple words, then fuzziness values *could* vary a lot. (3 distinct values for each search word). **This might make it so that it even hides the Okapi BM25 score!** I'll open a PR to fix this.

I think it's best to make minimal changes for now. But the staleness problem is worth fixing.

We could add an offset to the weight to consider updated time and keep everything else the same.
```
weight = weightBM25 + alpha * log(1 + 1/daysSinceLastUpdate)
```
If daysSinceLastUpdate is large, this will only consider the BM25 score. This should take care of the staleness problem, while still relying on prior art for sorting.

**Comment by shawnaxsom** [comment]
Hey @naviji, great idea! I think it is useful to keep the current logic in place, especially with how it ensures title matches to always get prioritized first.

I've replaced my previous changes with what I believe captures the intent of your message. I tried to pick an alpha that would help ensure notes updated in recent weeks are prioritized, but still frequently allow strong content matches to surface historically.

What do you think?

**Comment by naviji** [comment]
Seems good to me.

> I still at times will wish that I could toggle an option to sort purely by date

I agree. I was thinking of adding some sorting filters for this. 
`sort:updated latest meeting`
`-sort:created // for descending order`
`sort:updated sort:title // sort first by ascending updated time, then title`

Didn't get much attention from the community though. Seemed like it was not that important for most people.

**Comment by shawnaxsom** [comment]
Okay great, I'll update unit tests for this current PR then.


I'd be all for that sorting option. Another option is a button, maybe
similar to Obsidian, either approach works for me:

[image: CleanShot 2020-09-25 at 13.58.00@2x.png]

**Comment by laurent22** [comment]
Thanks @shawnaxsom and @naviji for looking into this. Would it be possible to have a spec of what was eventually implemented? Perhaps with an example of how it behaved before and how it behaves now.

Actually I've started adding technical specs in [this directory](https://github.com/laurent22/joplin/tree/dev/readme/spec), so if you could add your description there (for example as a file "search_sorting.md) as part of this pull request that would be even better.

**Comment by shawnaxsom** [comment]
Sure no problem, I've added a spec here: https://github.com/laurent22/joplin/blob/ffe380d9a706662fb395f6e9c71f645120cd43a2/readme/spec/search_sorting.md

I've copied a BM25 description from some unit tests from @naviji, and added some descriptions of the "fall-through" logic where only the first sorting criterion is used, and finally, I added information about how user_updated_time is added to the sorting weight.

**Comment by laurent22** [comment]
Brilliant, thank you for the spec as well as the comments in the code. I think that's a useful feature that's going to improve the search results further.

**Comment by gitterspec** [comment]
> Seems good to me.
> 
> > I still at times will wish that I could toggle an option to sort purely by date
> 
> I agree. I was thinking of adding some sorting filters for this.
> `sort:updated latest meeting`
> `-sort:created // for descending order`
> `sort:updated sort:title // sort first by ascending updated time, then title`
> 
> Didn't get much attention from the community though. Seemed like it was not that important for most people.

Wondering if anything like this got implemented - would be fantastic. Or the ability to do "updated:>YYYYMMDD" instead of a single date point. There are a bunch of issues linked to these kind of sort/filter by date requests, so I think people asking for these might have had some trouble finding relevant pull requests and discussion.

**Comment by lehelkeresztes** [comment]
Bump, I'd also love to be able to order the search results based on date created/updated. 
I've switched from evernote this week and this is one of the biggest pain points for me so far.

**Pull request merged**
