### PR TITLE
Server: Resolves #6096: Use apt to install tini to fix/enable multi-platform support

### LINKED ISSUE #6096: Latest Dockerfile.server breaks multi-platform support
## Environment

Joplin version: Joplin Server v2.7.4
Platform: Joplin Server
OS specifics: 

## Steps to reproduce

The latest changes to `Dockerfile.server` for `v2.7.4` breaks arm builds. This is due to the method of installing tini that breaks multi-platform support because it specifically downloads the amd64 version.

In the new Dockerfile.server, there is this line:

```bash
# Download the init tool Tini and make it executable for use in the final image
ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static /tini
```

This is a hard reference to the amd64 version of tini, which isn't compatible with arm64. Tini has arm64 builds though... So this should be an easy fix. I'm just trying to find the best way to do that without making drastic changes to the upstream Dockerfile.

## Logfile

Error when launching container on Raspberry Pi 4:
```
standard_init_linux.go:228: exec user process caused: exec format error
```

### PR DESCRIPTION
**Pull request by etho201**
Resolves https://github.com/laurent22/joplin/issues/6096

The way tini was being installed broke multi-platform (amd64, armv7, arm64) support.

```bash
# Download the init tool Tini and make it executable for use in the final image
ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static /tini
```

This is a hard reference to the amd64 version of tini, which isn't compatible with armv7 and arm64. Tini has builds for other platforms though... The easiest way to fix this is to simply use the apt package manager to install tini as that will result in retrieval of the correct binary.

### CODE REVIEW

**Comment by laurent22** [comment]
@whalehub, was there any particular reason you've installed tini this way? Just wondering if we aren't going to break something by changing the installation method.

**Comment by whalehub** [comment]
@laurent22 No, there was no reason in particular for installing it this way.  The Debian package installs both a dynamically and statically linked binary for Tini, so the only change I would recommend (@etho201) is to copy `/usr/bin/tini-static` instead of `/usr/bin/tini` from the build image to `/usr/local/bin/tini` in the final image.

**Comment by tessus** [comment]
@whalehub While I understand the usefulness of static binaries, I am still wondering why you prefer this one in the container. The container does have a libc (which should be the only dependency for tini), so I am not entirely sure. When you downloaded the file it made kind of sense. It could have been compiled against a libc version not available in the container. It's unlikely but possible, so I understood that move.

But when you install it via apt or any package manager, this problem does not exist. So why do you prefer the static binary?

**Comment by whalehub** [comment]
> But when you install it via apt or any package manager, this problem does not exist. So why do you prefer the static binary?

@tessus Initially, it's because I thought the `-slim` variant of the `node` image, which we use as a base for the final image, doesn't include `libc`, but turns out it does.

```
whalehub@pdh:~# docker run --rm -it node:16-bullseye apt list --installed | grep libc6
libc6-dev/now 2.31-13+deb11u2 amd64 [installed,local]
libc6/now 2.31-13+deb11u2 amd64 [installed,local]
```
```
whalehub@pdh:~# docker run --rm -it node:16-bullseye-slim apt list --installed | grep libc6
libc6/now 2.31-13+deb11u2 amd64 [installed,local]
```

It should be fine to use the dynamically linked binary in this case, especially since it weighs only 27KB compared to the static one at 719KB.

**Comment by tessus** [comment]
> Initially, it's because I thought the -slim variant of the node image, which we use as a base for the final image, doesn't include libc, but turns out it does.

Yep, this explain it.

> It should be fine to use the dynamically linked binary in this case, especially since it weighs only 27KB compared to the static one at 719KB.

It doesn't matter since apt installs both. ;-)

**Comment by whalehub** [comment]
> It doesn't matter since apt installs both. ;-)

@tessus Just a small nitpick: In this case, it does make a difference because only the dynamically linked binary is copied from the build stage (where apt is used to install Tini) to the final image. Of course, a difference of <1MB is basically meaningless since we're dealing with a 1GB+ Docker image.

**Comment by tessus** [comment]
True, I didn't think of that.

**Comment by laurent22** [comment]
Thanks everyone for looking into this. Looks like the change makes sense so let's merge.

**Comment by mikebgrep** [comment]
I open this question because I have problem today I install the Joplin sever on Raspberry Pi with v7 support and I got not supported system. Is this package tiny will fix this, and I can use the Joplin server

**Comment by fourstepper** [comment]
Yeah - I think it could now be possible to build multi-platform Docker images, however it's not actually done somewhere in the pipeline. 

I tried to find out where the Docker image is actually built and pushed upon release, however I wasn't unfortunately able to find it (in some reasonable amount of time), otherwise I would be happy to contribute the fix for this - should be relatively straightforward using `docker buildx`

**Comment by mikebgrep** [comment]
If you have capacity, please do it, and you can message here again if any image is available.

**Comment by fourstepper** [comment]
I don't, really, however the commit that reverted the multi-platform build efforts is [this revert](https://github.com/laurent22/joplin/commit/a661a73511c1446fd792a67bdd084b9b3a71a6e6) -- therefore, some variation of https://github.com/laurent22/joplin/commit/ab134807eae53b303fe8bb054ec5808543fa9624 could be the solution

**Pull request merged**
