### PR TITLE
All: Fix various CVE through upgrading lerna to latest

### PR DESCRIPTION
**Pull request by mhatvan**
Reported `npm audit` vulnerabilities for the root `package.json` went down from 65 to 7.

Breaking changes of lerna with v4 don't seem to impact this project, I tested a couple of npm scripts to verify that they behave as before.
 
If it is encouraged to get the dependencies up to date and fix CVE, then I would continue with the `/packages` directory as well in another PR.

### CODE REVIEW

**Comment by laurent22** [comment]
Audit fix has been ran not long ago. And we aren't going to upgrade to a v.0 for something has critical as Lerna.

**Comment by mhatvan** [comment]
So you rather stay on outdated dependencies? Some of them are 2 years or even older.

And this is not how you should treat new contributors imo, simply closing a PR without even checking if it is a viable addition. 

Eventually you will have to upgrade anyways, this or other deps.

However, I rather spend my time contributing to other projects then.

**Comment by laurent22** [comment]
I've checked and explained why it's not a viable addition.

Running `npm audit fix` without making completely sure that nothing has been broken is not something we're interested in. We can run it too, that's easy. What's trickier is to ensure that all apps and libraries still work properly on all operating systems. Then a few weeks later, when some difficult bug is found due to the package upgrade, we need someone to fix this, but usually the contributors who ran `npm audit fix` are nowhere to be found, and it's up to me to fix the bug they've introduced.

**Comment by mhatvan** [comment]
I never use `npm audit fix` since it just updates subdependencies (except with `--force` flag), I rather solve the issue at its root cause, in this case it was upgrading `lerna`.

I can't verify all the scripts using `lerna` because some involve publishing a new version. Apart from that you can never be 100% sure not to break something. Additionally, `lerna` is a dev dependency which is purged on the prod build, so the chance of it breaking something significant in production is lower in general.

> Then a few weeks later, when some difficult bug is found due to the package upgrade, we need someone to fix this, but usually the contributors who ran npm audit fix are nowhere to be found, and it's up to me to fix the bug they've introduced.

This is where I agree with you, it's unfortunate.

**Pull request closed without merging**
