### PR TITLE
Update nl_NL.po

### PR DESCRIPTION
**Pull request by metbril**

### CODE REVIEW

**Comment by metbril** [comment]
There are some menu item descriptions like `&File` that have an ampersand in the name. I did not know how to embed those properly in the translation. For now I have left the ampersand away. So `&File` becomes `Bestand` and NOT `&Bestand`. If there are any guidelines or instructions what the ampersand does, I can always add another commit to this PR.

**Comment by tessus** [comment]
Yes, the ampersands are there for a reason.

Due to an issue with Electron, the main menu items must include an ampersand to denote the shortcut. @laurent22 would be able to describe this better.

So in fact it must be `&Bestand` or whatever is the correct shortcut for this menu item in other apps.

Here's the explanation in the source code:

```
	/* `&` before one of the char in the label name mean, that
	 * <Alt + F> will open this menu. It's needed becase electron
	 * opens the first menu on Alt press if no hotkey assigned.
	 * Issue: https://github.com/laurent22/joplin/issues/934 */
```

Therefore, please add another commit to include the `&` for the menu items, but make sure that non use the same character. e.g.

msgid "&View"
msgstr "Beeld"

You can't use the B again, because you have already used it in `&Bestand`, thus I'd suggest to use the `B&eeld`. But you would know better, because you have been using menus in nl_NL, so you should know what the default shortcuts for these menu items are....

**Comment by metbril** [comment]
> Please add the `&` back.

Just to prevent misunderstandings, I did not remove it from a previous translation, but simply left it out for the mentioned reason. Those strings were not translated yet.

I'll have a look at other apps and come up with some proper suggestions through an additional commit.

**Comment by metbril** [comment]
Microsoft Word uses:

- File: `&Bestand`
- Edit: `Be&werken`
- View: `Beel&d`
- Tools: `E&xtra`
- Help: `&Help`

52791-sup-52605-002

Added commit.

**Comment by tessus** [comment]
Awesome, thank you for your contribution.

> Those strings were not translated yet.

Yep, but this means that the strings with the ampersands were used. After your change the ampersands were gone. Anyway, all good. Thanks again.

**Pull request merged**
