### PR TITLE
Onboard renovate

### PR DESCRIPTION
**Pull request by JamieMagee**
[Renovate](https://renovatebot.com/) is an automated dependency updater. This PR adds a config for renovate that includes all `package.json` files. In order to enable renovate, you'll have to [Install the GitHub App](https://renovatebot.com/docs/install-github-app/) (It's free for open source projects).

I think that renovate can help with the burden of keeping all 7 of your `package.json` files up to date (as well as your gradle dependencies, but I'll leave that for now).

### CODE REVIEW

**Comment by laurent22** [comment]
Is that to automatically upgrade packages? Because I don't do that since it can introduce unexpected bugs, but please confirm.

**Comment by JamieMagee** [comment]
Basically, yes. It won't automatically merge any changes for you with this configuration. It will just send out PRs with version upgrades. The PRs that it creates will have all the tests run automatically, which should give you some confidence in the changes. You can still checkout the branch, and build locally to test out major changes.

This has the advantage of being a 'push' system, instead of a 'pull' system. By that I mean that you're automatically notified of dependency updates, instead of having to go and search for dependency upgrades yourself.

**Comment by JamieMagee** [comment]
@laurent22 Have you given any more thought to this?

**Comment by laurent22** [comment]
As there's currently no automated tests for the GUI, I prefer not to have the dependencies automatically updated either. Let's get back to it maybe once we have the proper tests, but thanks anyway for looking into it.

**Comment by Dasymi** [comment]
OMG!

**Pull request closed without merging**
