### PR TITLE
Desktop: Resolves #9553: Added enter key support to navigate search results

### LINKED ISSUE #9553: Arrow keys cannot be used to navigate search results
### Operating system

macOS

### Joplin version

Joplin 2.13.9 (prod, darwin)

### Desktop version info

```
Joplin 2.13.9 (prod, darwin)

Client ID: 76122f1042cc4756b47308502b4b719d
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 1bbec44
```

### Current behaviour

1. Start a search by pressing ⌘⇧F.
2. Type a search query that appears in multiple notes (e.g. "the").
3. Try pressing the down arrow on your keyboard to go to the search results. 

[Here's a video recording of me trying this out](https://clips.twitch.tv/ConsiderateCrowdedBoarSwiftRage-XDKNLJOTZtSAkZia).

### Expected behaviour

I expected the focus to go down to the search results and optionally to preview the selected note (although I don't mind pressing enter at that point either).

I did see issue #6352, but it seems to have been closed with no resolution.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by njmulsqb**
Fixes https://github.com/laurent22/joplin/issues/9553

@PackElend label me please, apologies pre-commit hooks didnt execute on previous PR, it was some issue with my Windows machine, now creating this PR with macbook and pre-commits hook executed successfully

Introduction URL: https://discourse.joplinapp.org/t/introducing-najam/36216

With 💚 from Tecvity

### CODE REVIEW

**Comment by laurent22** [comment]
> it was some issue with my Windows machine

We have heard of this issue before but never been able to replicate it or fix it. Would you mind trying to commit again on your Windows machine and see what happens - is there any error or warning? Could you provide a screenshot if there's something?

**Comment by laurent22** [comment]
Also all the commits need to be under the same username for the CLA to be valid. So you might want to squash all the commits under the CLA name

**Comment by njmulsqb** [comment]
recheck

**Comment by njmulsqb** [comment]
> is there any error or warning? Could you provide a screenshot if there's something?

The pre-commit hook is failing on windows
image
I had to use `--no-verify` bypass in previous PR

**Comment by laurent22** [comment]
Thanks for checking. I'm not sure why `yarn updateIgnored` would fail here. Would you mind checking this?

- What version of yarn are you using? `yarn --version` should tell you
- And what if you run `yarn run updateIgnored`?

**Comment by njmulsqb** [comment]
>     * What version of yarn are you using? `yarn --version` should tell you

3.6.4
 
>     * And what if you run `yarn run updateIgnored`?

image

**Comment by laurent22** [comment]
Oh I see it now, that script should be executed from the root of the repository, so in your case from `C:\GitHub\joplin`. I will improve that error message to make that clearer

**Comment by laurent22** [comment]
Now the problem is that I'm not sure what should be implemented here. Feel free to participate in the discussion at https://github.com/laurent22/joplin/issues/9553 to figure this out

**Comment by laurent22** [comment]
Closing for now. We need to define what we want to implement (if anything)

**Pull request closed without merging**
