### PR TITLE
Desktop, Mobile: add typographer support

### PR DESCRIPTION
**Pull request by tessus**
New plugin `Enable typographer support`.

# disabled (default)

image

# enabled

image

### CODE REVIEW

**Comment by laurent22** [comment]
Looks good. Could you just add an entry about this plugin in readme/markdown.md please?

**Comment by tessus** [comment]
Sure. Will do in the next 30 minutes.

**Comment by tessus** [comment]
Done.

**Comment by laurent22** [comment]
Perfect, thanks for the PR!

**Pull request merged**
