### PR TITLE
All: Extension of the search filter by tododue and noteid

### PR DESCRIPTION
**Pull request by JackGruber**
Extension of the existing search logic by `tododue` and `noteid` filters.

Search querys testet on Windows and Android 10 (Virtual Device)

DB Upgrade testet with a copy of my own joplin-dekstop profile from DB version 34 to 35.

Some search examples:
Search a note by id: `noteid:ea6dee639783473eb4d594e6ded4607d`
Show all open todos with exceeded due date: `-tododue:day-0 iscompleted:0`
Show all open todos with no due date: `-tododue:19700102`
Show all open and upcomming todos for the next seven days: `-tododue:day+7 iscompleted:0`

### CODE REVIEW

**Comment by laurent22** [comment]
By the way, maybe the tododue filter could be called just "due"?

Also what's the use case for searching by note ID? "Searching" is a bit strange because by definition if you have the ID you've already found it.

**Comment by JackGruber** [comment]
>By the way, maybe the tododue filter could be called just "due"?

yes it is a good idea to shorten the filter name.

> Also what's the use case for searching by note ID? "Searching" is a bit strange because by definition if you have the ID you've already found it.

I had it a few times where I had the noteid in the logs but not the note name to search for it. In the forum is also a few times asked how to search for a noteid for the same reason.
You can search in the database, but it's easier for everyone that way.

**Comment by laurent22** [comment]
Ok that makes sense for the note ID. Actually since search is only for note, maybe we can name the filter just "id"?

Also you have a failing test: https://travis-ci.org/github/laurent22/joplin/jobs/768664744#L1037

**Comment by JackGruber** [comment]
ok, I don't quite get it yet, but the BM25 weight is suddenly the same for the test machtes.

**Comment by laurent22** [comment]
I don't remember this particular test being flaky. Is it possible that the changes you made to the FTS view can affect this?

**Comment by JackGruber** [comment]
Ok, I misinterpreted something in the code and thought I had to adjust the fts table as well. 
The todo_due date was not included in the BM25 weight calculation before and I don't think this needs to be added currently. 

I have reverted this change and made the adjustment to the filter names.

**Comment by laurent22** [comment]
All tests are passing now and the code looks good. Thanks @JackGruber!

**Pull request merged**
