### PR TITLE
Added 'Yandex Disk' to the list of WebDAV-compatible services known to work with Joplin.

### PR DESCRIPTION
**Pull request by teterkin**
Yandex Disk (cloud storage by Yandex) supports WebDAV access and is known to work with Joplin.

### CODE REVIEW

**Comment by tessus** [comment]
@teterkin are you still woring on this? I will close the PR otherwise.

**Comment by teterkin** [comment]
> @teterkin are you still woring on this? I will close the PR otherwise.
Sorry, I didn't answer in time.
Should I submit another PR now? (with the appropriate position)

**Comment by tessus** [comment]
@teterkin I've re-opened the PR. You can just add another commit.

**Comment by teterkin** [comment]
> Perfect, thanks for the update.

Thank you!
Actually it was fist in my life contribution to the open source project.
That's one small step for Joplin, one giant leap for me. 🙂

**Pull request merged**
