### PR TITLE
Mobile: added filter for notes  option

### PR DESCRIPTION
**Pull request by ishantgupta777**
I added a filter option on the mobile platform. Now, users can filter their notes and can only see their todos, completed todos, incomplete todos, and notes.  If admins allow this, I will add more filter options such as notes from the last 1 day, last 1 week, between two dates, etc.
@PackElend  please label this PR.

Screenshot_1584533996

### CODE REVIEW

**Comment by ishantgupta777** [comment]
@laurent22 sir, I've added many features and fixed bugs in Joplin mobile app and now I'm working on a new feature, but sir, many of my PR's haven't been reviewed. I'll be really thankful if you can have a look at my PR's, so that I can change if I need to in my code. Thanks
https://github.com/laurent22/joplin/pulls/ishantgupta777

**Comment by laurent22** [comment]
I really don't know about that. It wasn't asked by anyone, and there was no spec. And we don't have the resources to look into this properly at the moment so I prefer to close.

**Comment by ishantgupta777** [comment]
> I really don't know about that. It wasn't asked by anyone, and there was no spec. And we don't have the resources to look into this properly at the moment so I prefer to close.

Sir, I really think this will be a great feature. So to you, if the community wants this feature, can I ask  community in the group? Or like what should I provide you in detail, I personally love this feature.

**Comment by laurent22** [comment]
Feel free to ask on the forum, but can't promise anything regardless of the feedback you'll get.

**Comment by ishantgupta777** [comment]
> Feel free to ask on the forum, but can't promise anything regardless of the feedback you'll get.

Okay sir, thank you so much.

**Comment by PackElend** [comment]
> if the community wants this feature, can I ask community in the group?

btw, that is the normal way, now extension without conformation by the community in the forum

**Pull request closed without merging**
