### PR TITLE
Chore: Update MenuBar.tsx

### PR DESCRIPTION
**Pull request by eltociear**
becase -> because

### CODE REVIEW

**Comment by eltociear** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
Thanks for the fix! This pull request reminded me I need to setup cSpell so as to automatically detect those spelling mistakes

**Comment by laurent22** [comment]
Oh, and congratulation for getting pull request `#10000` :)

**Comment by eltociear** [comment]
@laurent22 Lucky!

**Pull request merged**
