### PR TITLE
Server: avoid new user's password to be hashed twice

### PR DESCRIPTION
**Pull request by MaySoMusician**
- Issues related: n/a

`joplin-server`, built with current source code, doesn't let us log in a newly-created user, providing error message `Invalid username or password`. This is certainly due to mis-matching of the hashes of the user password.

When adding an user through Admin UI, the password will get hashed unexpectedly *twice* before registering, first in `makeUser` function `src/routes/index/user.ts`, second in `UserModel.save()` function in `src/models/UserModel.ts`, that causes mis-matching of the hashes as I mentioned above.

~So, I fixed a conditional expression in the latter function which I thought is wrong.~

~As a result of a little closer inspect, the code I submitted first was totally meaningless, so I removed the entire line.~

### CODE REVIEW

**Comment by MaySoMusician** [comment]
Finally, I decided not to calculate the hash of the password on client side, as opposite to my first commit, because it is rather dangerous to directly store a hash calculated on client side, than to send a raw password to the server and create a hash there.
Instead, the server is now forced to calculate all of the sent password on doing `save()`, regardless of the account is newly created or already existed (i.e. when a user changes its password).

It may be possible to hash password *expectedly twice*, both on client side and on server side, both of a new account and of an existing one. That would require to rewrite all the unit test which currently pass raw passwords to `UserModel.save()` (e.g. `src/utils/testing/testUtils.ts` L171-178)

**Comment by laurent22** [comment]
Hmm, yes I think the issue is that the property currently is called "password" but really it should be called "password_hash" to avoid any ambiguity. Because of that, there's some magic happening when the user is saved and apparently this magic is not consistent.

Your fix would solve some of the issues, but I don't think it's a strong enough solution. For example, if I save a user twice and provide the password every time, the password would be hashed twice again with your implementation.

**Comment by MaySoMusician** [comment]
Sorry but I'm not sure when the password will be hashed twice again.
When an admin adds a new user in `/users/new` page, by clicking 'Create User' button, the new user data is POSTed to `/users`, apparently in the form of url-encoded. At this point the password isn't hashed yet (i.e. the raw password will be POSTed). Then the new user will be saved after replacing the password by its hash.
When a user profile is updated (by admins or the user itself) by clicking 'Update profile' button, the updated data is POSTed as well, with the new password *not* hashed. I think it doesn't matter how many times the profile is updated repeatedly, because the data sent to the endpoint always remains as we input into the text fields.

**Comment by laurent22** [comment]
> Sorry but I'm not sure when the password will be hashed twice again.

Code like this would hash the password twice:

```typescript
const user = await userModel.load('someid');
user.email = 'newemail@example.com'
await userModel.save(user);
```

The first call to `load` retrieves all the data including hash password. The call to `save` will save everything again, which is fine for all properties, except for the password which will get hashed again.

I'm not sure what's the best solution for this. Perhaps a specific function to change the password?

**Comment by MaySoMusician** [comment]
I get it now. I'm not a security specialist or backend engineer, I can't answer the solution right now. For me, your idea should go well, but I will check how other software deal with this if I have some time.

**Comment by MaySoMusician** [comment]
In WordPress, they provide a dedicated function to change the user's password ( [`wp_set_password`](https://developer.wordpress.org/reference/functions/wp_set_password/) ) taking a raw password and calculating a hash inside, as well as they let us change the password in [`wp_update_user`](https://developer.wordpress.org/reference/functions/wp_update_user/) just when we pass the new password via `user_pass` field of `$userdata` parameter.
The `wp_update_user` function updates the value of the field only we specified in `$userdata`. That is, in order to change, for example, the user's name and its password at the same time, we call that function as in `wp_update_user( { name: 'new_username', user_pass: 'new_password' } )` (notice: this is pseudocode. Actually we must use PHP in WP). On the contrast, to change only the user name, we simply call it passing just the new username field.

So, currently our `UserModel.save()` takes always the full user object. We should allow this to receive the Partial user object that specifies only the field we want to change.

We can see the implementation of `wp_update_user` [here](https://core.trac.wordpress.org/browser/tags/5.6.2/src/wp-includes/user.php#L2140). It's rather large because some of the field are separately checked to apply some particular processing.

**Comment by laurent22** [comment]
I had a look at it but eventually got to the same solution as your initial pull request. The auto hashing behaviour is not ideal so I've added a comment as a warning along with test unit. Eventually we'll see if a specialised function is needed but for now that will do. For info the commit is this one: 76c143e8b09f812562caf71d44d4780598d47035

Many thanks for bringing up this issue, it's quite a major one (and in fact I'm surprised we didn't get more bug reports about it).

**Pull request closed without merging**
