### PR TITLE
Optimizations & Dependencies Updates

### PR DESCRIPTION
**Pull request by xbdmHQ**
Updates Includes:

- Source Code Optimizations
- Harden Docker-Compose.yml File
- Example Nginx.conf File
- Dependencies Updates

### CODE REVIEW

**Comment by xbdmHQ** [comment]
> 

I have read the CLA Document and I hereby sign the CLA

**Comment by xbdmHQ** [comment]
@github-actions I have read the CLA Document and I hereby sign the CLA

**Comment by personalizedrefrigerator** [comment]
Thank you for your work!

As per [CONTRIBUTING.md](https://github.com/laurent22/joplin/blob/dev/CONTRIBUTING.md#contributing-to-joplins-code), keep pull requests small where possible. In this case, please create a separate pull request for each issue that is fixed. This helps us test each individual change.

For example, the changes to `docker-compose.server.yml` could be one pull request (make sure to describe the rationale for the change in detail!) and the changes to GitHub actions dependencies could be another.

**Comment by laurent22** [comment]
Also, any reason you change the project license? You'd think that's something worth mentioning since that would have switched even the proprietary parts of the project, such as Joplin Server, to open source.

**Comment by xbdmHQ** [comment]
> Also, any reason you changed the project license? You'd think that's something worth mentioning since that would have switched even the proprietary parts of the project, such as Joplin Server, to open source.

The AGPL is a great open-source license, and a lot of open-source developers can agree if you want to ask them. Here's more information about AGPL: https://fossa.com/blog/open-source-software-licenses-101-agpl-license/

**Comment by laurent22** [comment]
Ok, but as you can imagine changing the license of an open source project is not a small matter, not to mention you'd be open sourcing all our non-open-source stuff. By the way we already use AGPL for most of the project anyway.

**Comment by xbdmHQ** [comment]
> Ok, but as you can imagine changing the license of an open source project is not a small matter, not to mention you'd be open sourcing all our non-open-source stuff. By the way we already use AGPL for most of the project anyway.

Ah, yeah ok

**Pull request closed without merging**
