### PR TITLE
doc: add archlinux package for pre-release in docs

### PR DESCRIPTION
**Pull request by Alkindi42**
Hello,
I suggest you a PR to update the documentation and the readme. I would like to mention there an arch linux package to install the latest pre-release (cli and desktop).

### CODE REVIEW

**Comment by laurent22** [comment]
I'd rather not put that much information in there, as I guess all this is already detailed on the package homepage.

**Comment by Alkindi42** [comment]
I agree with you, there is a lot of informations. I just wanted to add the joplin-beta package for users wanting the pre-release. I can reduce the text, like it:

> You can install [joplin](https://aur.archlinux.org/packages/joplin/) package or if you are interested in [pre-releases](https://joplinapp.org/prereleases/) [joplin-beta](https://aur.archlinux.org/packages/joplin-beta)

What do you think?

**Comment by fabianski7** [comment]
@Alkindi42 joplin-beta is also in the chaotic-aur

**Comment by Alkindi42** [comment]
Yes, I know @fabianski7.
I think it's a good idea to highlight the pre-release. I updated my PR to show only the important information. 
That's just a suggestion, if you think it 's not a good idea, feel free to close my PR.

**Comment by laurent22** [comment]
Can you go back to the orignal text and only mention the pre-release package please? You've removed some important text, in particular the fact that we don't provide support for this package. Also please don't include the HTML file, it will be auto-generated.

**Comment by Alkindi42** [comment]
> You've removed some important text, in particular the fact that we don't provide support for this package.
We already have the information above the table.
```
Unsupported methods

There are other ways to install the terminal application. However, they are not supported and problems must be reported to the upstream projects.
```
Is it not sufficient?

**Comment by tessus** [comment]
> Is it not sufficient?

No, because people ignore it. If the info is duplicated several times, it might sink in at one point.

e.g. someone just posted a topic in the forum about a problem with a fork of the aur package. I mean seriously, how ignorant can one be?

Some packages even bundle the desktop and the CLI app. IMO this is a very bad idea. Either way, we don't support packages and it makes sense to mention it a few times.

**Comment by laurent22** [comment]
From this conversation, I think it would make sense to keep the text as it was, and simply mention the pre-release. If you're ok with that @Alkindi42 I can merge.

**Comment by Alkindi42** [comment]
> Either way, we don't support packages and it makes sense to mention it a few times.
I'm just surprised to see that the mention is only present for the **AUR** package. What about the **brew** package?

> From this conversation, I think it would make sense to keep the text as it was, and simply mention the pre-release. If you're ok with that @Alkindi42 I can merge.
I updated my PR, thanks.

**Comment by laurent22** [comment]
Looks good, thanks for the update @Alkindi42!

**Pull request merged**
