### PR TITLE
Italian translation Update

### PR DESCRIPTION
**Pull request by StarFang208**
Translated the remaining lines.

### CODE REVIEW

**Comment by tessus** [comment]
I'm not sure what you did, but when I diff your PR, I see the entire file and not just your changes. Something is off.

**Comment by tessus** [comment]
Your first commit is fine. The second one messed everything up.

**Comment by StarFang208** [comment]
Sorry, I thought I didn't push to the main git, so I copy pasted another file altogheter.

Only then I realized it was unnecessary, my bad.

**Comment by tessus** [comment]
Please delete the last 3 commits and force push.

**Comment by tessus** [comment]
No, you did not delete the last 3 commits.
You know what, let me fix that for you....

**Comment by StarFang208** [comment]
I'm terribly sorry, my ignorance on how to remove commits made things worse.

**Comment by tessus** [comment]
Thanks a lot for the translation update. 

If you want to learn more about git, you can have a look into topics like:

- rewrite git history
- deleting commits
- rebasing

Those are things that are often needed. The problem is, if you mess things up, you can lose your work, so you should really know how to use git.

**Pull request merged**
