### PR TITLE
Update zh_TW.po

### PR DESCRIPTION
**Pull request by bobchao**
Update/tweak the translation to the latest version.

### CODE REVIEW

**Comment by tessus** [comment]
Thanks for the update.

**Comment by laurent22** [comment]
I had to revert this pull request because it's invalid - https://travis-ci.org/github/laurent22/joplin/jobs/772889793#L1499 @bobchao, if you are not already doing so, you should use PoEdit to modify the po file otherwise you are likely to make a mistake at one moment or another.

**Comment by tessus** [comment]
@laurent22  that's interesting because one of the CI runs went through and passed.

**Comment by laurent22** [comment]
Yes, translation validation is done only on Linux since there's no need to run it on both macOS and Linux.

**Comment by tessus** [comment]
Oops, in that case I'm sorry that I missed that.

**Comment by bobchao** [comment]
@laurent22 Thanks for the suggestion; I revisited the file with POEdit and created another PR.

https://github.com/laurent22/joplin/pull/5039

**Pull request merged**
