### PR TITLE
Desktop: Code button now detects multiline

### LINKED ISSUE #1606: More intelligent behaviour of code and code-block markdown
I thought it would be tidier to lump these three minor things into a single issue as they are all interlinked:

### Operating system
- Windows

### Application
- Desktop (1.0.158)

I assume the behaviour is consistent on other platforms but I cannot test that.

---
## 1 - </> button behaviour
Current behaviour of the </> code button is to always use a single ` regardless of how many lines of text are selected. It would be great if:
* when a user has selected two or more lines of text
* and uses the </> button

the editor would instead use code block (```) around the selected text.

**Current behaviour:**
image

**Proposed behaviour:**
image

---
## 2 - Possible bugs
While experimenting I found some odd cases which seem like possible bugs. Examples 1 & 2 to me are expected behaviour but examples 3 & 4 are unexpected. To elaborate:

* Example 3 - the first line of the code block disappears from the rendered note.
* Example 4 - The terminating ``` don't work and so the code block remains unclosed.

image

I'm not sure what the authority for markup is but, Example 3's behaviour is contrary to examples given here:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

---
## 3 - Improving auto-complete
When simply trying to type a code block the auto-complete could be a little more helpful. Auto-complete seems to assume you are always trying to type a single line of code where:

* hitting \` once gives: \`|\` (where | is the location of the cursor).
* But hitting \` three times gives you: \```|` where I would expect the behaviour to be: \```|``` .

### PR DESCRIPTION
**Pull request by CalebJohn**
The new linter changed the string formatting a bit, but it still works.

fixes #1606 which was closed by the stale bot.

### CODE REVIEW

**Comment by tessus** [comment]
This is brilliant. Thank you. I was about to work on this myself, but you beat me to it.

However, there's a slight side effect that _could_ be problematic:

multiline

As you can see, not the entire text is selected after the action (contrary to the selected text for a single line code block).

**Comment by CalebJohn** [comment]
@tessus Thanks for taking a look so quickly! I never even considered the selection, I've pushed a fix for this.

btw what did you use to take a gif screenshot?

**Comment by tessus** [comment]
@CalebJohn 

> btw what did you use to take a gif screenshot?

A while back I was looking for a simple tool which allows me to create an animated gif automatically, because I was sick and tired to do it manually.

I found this: https://giphy.com/apps/giphycapture

(This tool even allows you to add multiple captions.)

**Comment by laurent22** [comment]
Thanks @CalebJohn and @tessus for the PR and review, it's good to merge.

**Pull request merged**
