### PR TITLE
Linux Installer: "-x86_64" is not part of the AppImage release name

### PR DESCRIPTION
**Pull request by carlbordum**
Just gives a 404 for me currently.

### CODE REVIEW

**Comment by CalebJohn** [comment]
Looks like this is a duplicate of #2321

**Comment by laurent22** [comment]
Ok let's merge this before we get a fourth pull request about it :)

**Comment by laurent22** [comment]
In fact we got a total of seven pull requests for this. It was time to merge 😄

**Comment by Erwyn** [comment]
At least we now know we are an active community :p. Sorry for the duplicate.

**Pull request merged**
