### PR TITLE
Update translations es_ES

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by tanrax** [comment]
Could you add the hacktoberfest tag?

**Comment by tessus** [comment]
@laurent22 are we particpating in Hacktoberfest? I think last year we didn't because too many people created BS PRs the year before.

**Comment by laurent22** [comment]
We aren't officially participating but if someone creates a good PR we can add the label if they want. I think we've done it for a few PRs last year.

**Comment by tessus** [comment]
@tanrax Laurent will have to decide if he wants to apply the `hacktoberfest` tag.

**Comment by tessus** [comment]
@tanrax Thanks for the update.

**Comment by laurent22** [comment]
@tessus, feel free to add it if someone asks, unless there's something obviously wrong with the PR, or if it's really low effort (such as a doc update that changes a word or two).

**Comment by tanrax** [comment]
> @tanrax Thanks for the update.

Thanks to you for the fantastic work. I have a lot of love for the project and from time to time I go through the Linux installer script to check that everything is OK. And of course the respective translation. Best regards and keep up the good work!

**Pull request merged**
