### PR TITLE
Add Arabic translation

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by laurent22** [comment]
Thank you for the translation, but please could you provide the .po file? As this is what is needed to update and maintain the file over time.

**Comment by atefBB** [comment]
Excuse-me! I see https://github.com/laurent22/joplin#localisation and I'm working on it.

**Comment by laurent22** [comment]
Hello, I will close this pull request for now but when the new translation is ready, please open a new one.

**Comment by atefBB** [comment]
Ok.

**Pull request closed without merging**
