### PR TITLE
Mobile：code block  default  line wrap

### PR DESCRIPTION
**Pull request by wljince007**
The display window on the mobile end is very small, and the code block does not Line wrap and word wrap automatically. It is troublesome to move left and right to see the code. Add a switch to control whether the code block displays Line wrap and word wrap. Please give the user a choice to decide whether the code block should wrap.(移动端的显示窗口很小，代码块不自动换行，要左右移动看代码很麻烦。加一个开关控制代码块是否自动换行显示。请给使用者一个决定代码块是否换行的选择。)

### CODE REVIEW

**Comment by wljince007** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
Could you provide a screenshot to demonstrate the issue before and after? I'm thinking that if it's bad enough we can make it the default instead of adding an option

**Comment by wljince007** [comment]
image
image

On the mobile end, the code block without line wrap and word wrap, we have to move left and right to see the complete code, that is inconvenient

**Comment by wljince007** [comment]
On the PC side, we can add CSS codes in userstyle.css:

```

Code{

White space: pre wrap;

}

```

, let the pdf display Line wrap and word wrap, but currently the mobile terminal cannot edit userstyle.css, so cannot do Line wrap and word wrap for code blocks.

**Comment by wljince007** [comment]
The above code has been compiled successfully on the PC side and the function Test effort works normally, but the mobile side has not been compiled successfully and the test has not been carried out.

**Comment by wljince007** [comment]
@laurent22  I think code block should not move left to right or move right to left on mobile app.

**Comment by wljince007** [comment]
Other mobile note taking apps seem to not allow the interface to move left or right.(其它移动端的笔记类软件好像都不让界面左右移动)

**Comment by laurent22** [comment]
> Other mobile note taking apps seem to not allow the interface to move left or right.(其它移动端的笔记类软件好像都不让界面左右移动)

Do you have example screenshots of other apps doing that?

**Comment by wljince007** [comment]
Evernote:

image

**Comment by wljince007** [comment]
@laurent22   Evernote do not allow the code block to move left or right. This way, dragging can only be move up and down, without the need to move left or right to view the complete content of the code block. The code Line wrap and word wrap in the code block reduces the operation of viewing the complete code and facilitates the user.

**Comment by laurent22** [comment]
Thanks @wljince007, how about we make it wrap by default then? I'm not so keen with adding an option for this

**Comment by wljince007** [comment]
We make it wrap by default is great too,  expect the new release version of mobile app. [ThumbsUp][ThumbsUp][ThumbsUp]

**Comment by laurent22** [comment]
Would you be able to make the required change?

**Comment by wljince007** [comment]
Sorry, in fact, I am not familiar with the syntax of CSS and typescript. Submitting a pull request is just to catch your attention. I only can find the way adding CSS can effectively break code blocks by debugging . I'm not sure where the CSS code above would be put more appropriate, and it's better for the author to add it.

**Comment by wljince007** [comment]
@laurent22  I am trying to change the required .

**Comment by laurent22** [comment]
You would modify this in packages/app-mobile/components/NoteEditor/CodeMirror/theme.ts

We can't give a default value to the custom CSS

**Comment by wljince007** [comment]
@laurent22  Thank you for your patient guidance. I have attempted to modify packages/app mobile/components/NoteEditor/CodeMirror/theme.ts , but I am not familiar with CSS. I compiled the mobile code completely but always made errors during runtime, so I did not verify it. If there are any errors, please provide more guidance. Thanks a lot.

**Comment by wljince007** [comment]
@laurent22 Thank you for your patient guidance. I have attempted to modify packages/app mobile/components/NoteEditor/CodeMirror/theme.ts :
```
'& .cm-codeBlock': {
...
			whiteSpace: 'pre-wrap',		
},
```
but this don't work, debug on Android and IOS , find out this only can affect edit view, not pdf view.

Expect your great work to implement code block wrap. Thanks a lot.

**Comment by laurent22** [comment]
@wljince007, if it's not working please create a bug report so that it can be part of the backlog

**Comment by wljince007** [comment]
@laurent22  I try create a bug repot at:  https://github.com/laurent22/joplin/issues/8517.

**Pull request closed without merging**
