### PR TITLE
Desktop: md importer handle special chars in linked image name

### PR DESCRIPTION
**Pull request by BartBucknill**
Currently fix is failing the corresponding test in the linux pipeline as it is not finding the file when the name has been decoded.
Fix for this issue: https://github.com/laurent22/joplin/issues/2334

### CODE REVIEW

**Comment by laurent22** [comment]
I think it's good but we need to fix the Linux issue.

In fact I'm not sure if it's really a Linux issue because your tests are running in random order and in parallel because you made them all async (and Jamine doesn't support async), so `beforeEach` is also called randomly.

To get what you want and run the tests sequentially, please use the `asyncTest` helper function. See for examples tests/EnexToMd to see how it's used.

Also please remove the console statements.

**Comment by BartBucknill** [comment]
@laurent22  Just double checked - Jasmine does support async/await
> async/await is supported by Jasmine 2.7 and later

[from jasmine official tutorials](https://jasmine.github.io/tutorials/async)

So I don't think there is any need to change this. 

The result of the debug logs I added show that `shim.fsDriver().stat(pathWithExtension);` is coming back null for the file with special characters in the linux pipeline. 
As I commented on the issue, I suspect this could be a cross OS encoding issue.
It would be good to test this out on linux, but I haven't got round to setting up a vm for this yet.

On the issue you mentioned that we could perhaps just skip this test in the linux pipeline - is that still an option?

**Comment by laurent22** [comment]
For this pull request, I think we should try to understand why it works on macOS but not on Linux, and whether it's possible to write a test that works on both. I don't know if you're still interested working on this. If not please let me know.

**Comment by BartBucknill** [comment]
@laurent22 Added the same file from Linux, and the tests now pass on both OS. It seems to be related to the encoding of the file name on mac vs linux as I mentioned on the issue - in the linux test it finds the file added on linux, in the Darwin test it finds the file added on mac.

Just need to remove debug logs etc and should be able to move this PR out of WIP.

**Comment by BartBucknill** [comment]
@laurent22 Test passing & removed logs, PR ready!

**Comment by laurent22** [comment]
Looks good, thanks @BartBucknill!

**Pull request merged**
