### PR TITLE
Mobile: Fixes #8017: Android sync crash fixed

### LINKED ISSUE #8017: App randomly crashes during sync
During sync, the app can randomly crashes with this error:

```
04-04 20:19:10.335  4092  4276 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-04 20:19:10.335  4092  4276 E AndroidRuntime: Process: net.cozic.joplin, PID: 4092
04-04 20:19:10.335  4092  4276 E AndroidRuntime: java.lang.ClassCastException: okhttp3.internal.http.RealResponseBody cannot be cast to com.RNFetchBlob.Response.RNFetchBlobFileResp
04-04 20:19:10.335  4092  4276 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlobReq.done(RNFetchBlobReq.java:594)
04-04 20:19:10.335  4092  4276 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlobReq.access$100(RNFetchBlobReq.java:72)
04-04 20:19:10.335  4092  4276 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlobReq$3.onResponse(RNFetchBlobReq.java:493)
04-04 20:19:10.335  4092  4276 E AndroidRuntime:        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
04-04 20:19:10.335  4092  4276 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-04 20:19:10.335  4092  4276 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-04 20:19:10.335  4092  4276 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
```

Android 13, Samsung Galaxy S22

Possible fix here: https://github.com/joltup/rn-fetch-blob/issues/490#issuecomment-990899440

Some additional info here: https://github.com/RonRadtke/react-native-blob-util/issues/88

Possible explanation here: https://github.com/joltup/rn-fetch-blob/issues/490#issuecomment-654326087

### PR DESCRIPTION
**Pull request by palerdot**
Fixes #8017 

### Problem

Android app randomly crashes during sync.

### Solution

Ref: https://github.com/joltup/rn-fetch-blob/issues/490#issuecomment-990899440
Following files in `node_modules/rn-fetch-blob` was manually edited as per the solution
- `packages/app-mobile/node_modules/rn-fetch-blob/android/src/main/java/com/RNFetchBlob/Response/RNFetchBlobFileResp.java` (https://github.com/laurent22/joplin/pull/8045/files#diff-096380626fe192da4c8a02f3127dd5f0efd9777024598115eb0983aaa003bf05R4095)
- `packages/app-mobile/node_modules/rn-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java` (https://github.com/laurent22/joplin/pull/8045/files#diff-096380626fe192da4c8a02f3127dd5f0efd9777024598115eb0983aaa003bf05R4082)

### Testing

Basic syncing testing was done in local android app and local joplin server setup. Was able to sync items locally (checked with fetching the synced items from desktop).

I was not able to reproduce this issue in my local android app setup and local server setup. I have just applied the changes via `patch-package` as per the solution.

### CODE REVIEW

**Comment by palerdot** [comment]
`react-native-paper` had to be upgraded to `v5.6.0` because of the following error in `v5.5.0`
```shell
error: SyntaxError: packages/app-mobile/node_modules/react-native-paper/src/utils/splitStyles.ts: Unexpected token (32:55)

  30 |   // `Object.entries` will be used to iterate over the styles and `Object.fromEntries` will be called before returning
  31 |   // Entries which match the given filters will be temporarily stored in `newStyles`
> 32 |   const newStyles = filters.map(returnEmptyArray<Entry>);
     |                                                        ^
  33 |
  34 |   // Entries which match no filter
  35 |   const rest: Entry[] = [];
```

**Comment by laurent22** [comment]
I don't get this PR, did you see the size of the diff? The original comment mentions two small changes in two files, but you have multiple changes in multiple files. No way we can merge this, since we have no idea what we're doing here.

Also did you even try? I'm pretty sure your patch does nothing since patch-package is not installed, and we use `yarn patch` for patching but the entry for that patch is not in package.json

Obviously we aren't going to upgrade rn-paper either, how could that be related? If there's something wrong with this package it should be updated in a different PR.

**Comment by palerdot** [comment]
>  I'm pretty sure your patch does nothing since patch-package is not installed

As per `README` this is not needed, since `patch-package` can be run globally. So, I went that way. I was under the wrong impression that all the files in `patches` folder would be applied. Didn't realise it has to be applied in a specific way based on how patches were created (patch-package, pnpm, yarn v2+ etc).

>I don't get this PR, did you see the size of the diff? The original comment mentions two small changes in two files, but you have multiple changes in multiple files. 

I don't understand the patch either. I just made those two changes. But running `npx patch-package` resulted in this huge patch. There are `--include` and `--exclude` flags, but there are no examples of how to use this switch. Maybe, we have to try this.

> Obviously we aren't going to upgrade rn-paper either, how could that be related? If there's something wrong with this package it should be updated in a different PR.

I agree. I was not able to run things locally because of this error, and I had to upgrade to run the setup locally. To make this work, first an upgrade for `rn-paper` has to made and then it has to be merged into this PR.

**Comment by palerdot** [comment]
`--include` flag had to be given for creating patches for specific files. Following command created current patch

```shell
npx patch-package rn-fetch-blob --include android/src/main/java/com/RNFetchBlob/
```

**Comment by palerdot** [comment]
I have reverted the `rn-paper` upgrade commit. As mentioned earlier, this branch cannot be run locally because build crashes because of `rn-paper` error. I will wait for `rn-paper` upgrade in master so that it can be merged into this branch.

Also, as mentioned earlier, I don't know much about patches, and I don't know how to check if the patches are applied cleanly. This error is not reproducible in my local in any case, and there is no way for me to confirm if patches were applied cleanly. If there is a way to check, please let me know.

**Comment by palerdot** [comment]
Closing in favour of https://github.com/laurent22/joplin/pull/8056

**Pull request closed without merging**
