### PR TITLE
Desktop: Performance: Reduces re-rendering of NoteEditor and loading of resourceInfo 

### PR DESCRIPTION
**Pull request by ken1kob**
This PR is one of PRs resolving issue #6386.

This PR suppresses redundant re-rendering of NoteEditor caused by ResourceInfos and redundant loading of ResourceInfos.

### Cause

When a new note is selected, a new FormNote instance is created. In NoteEditor/utils/useFormNote.ts, the following four parts have loading ResouceInfos and updating a useState variable.

- (a) FormNote initialization (in useEffect)
- (b) Change of FormNote.id (in useEffect)
- (c) Change of FormNote.body (in useEffect)
- (d) `onResourceChange` useCallback

When a new FormNote instance is initialized, (a), (b) and (c) are executed. So, two redundant loading happen, and caching doesn't work in (a) and (b). Besides, redundant re-rendering of NoteEditor possibly happens.

### Treatment

The belows are treatments to prevent redundant re-loading and re-rendering.
- id and body information (`resourceInfosDesc`) is tied to `resourceInfos`.
- (b) and (c) are merged into one useEffect.

### CODE REVIEW

**Comment by laurent22** [comment]
In order to contribute to the project, it is now required to sign a Contributor License Agreement (CLA) as described in this announcement: [Joplin is switching to the GNU Affero General Public License v3 (AGPL-3.0)](https://joplinapp.org/news/20221221-agpl/). Your contributions will remain open source and you only need to sign this document once. If you have any question about it please let me know.

**Comment by laurent22** [comment]
recheck

**Comment by ken1kob** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
See https://github.com/laurent22/joplin/pull/6446#issuecomment-1817817260

**Pull request closed without merging**
