### PR TITLE
Fix toolbar top-margin for Win and Mac Platform

### LINKED ISSUE #2824: Desktop: Upper border of selected icon outline is not inline with gray menu border
When hovering over any icon in app, outline is few pixels higher than it should be

Screenshot 2020-03-21 at 00 01 15

image

## Environment

Joplin version: v1.0.194
Platform: macOS
OS specifics: 10.15

## Steps to reproduce

1. Open Joplin app
2. Hover over any icon

## Describe what you expected to happen
Icon outline was expected to be inline with gray border

### PR DESCRIPTION
**Pull request by coderrsid**
Fixes #2824 for both windows and mac platform.

### CODE REVIEW

**Comment by coderrsid** [comment]
@Perkolator Can you or anyone please test the changes on windows platform and match if they resolves the problem https://github.com/laurent22/joplin/pull/2828#issuecomment-607155797?

**Comment by laurent22** [comment]
Why is there a difference between Mac and Windows? I'd rather we figure that out first, to know if it makes sense to start adding custom styles for each platform.

**Comment by coderrsid** [comment]
Laurent, on that we had a conversation in #2828 that the problem persists for different platforms

**Comment by tessus** [comment]
I will have a look at the changelog for Electron. Maybe something related shows up....

**Comment by coderrsid** [comment]
So what should be the approach here as there is no changelog related to this issue in Electron?

**Comment by laurent22** [comment]
If we don't know why there's a difference between platforms, I think we should close the pull request. We can't add platform specific code for tiny tweaks like this, especially since it's likely to break when we change something to the layout.

**Comment by coderrsid** [comment]
Sure, laurent. But we should know about this issue. As this can lead to
issues in future.

**Comment by laurent22** [comment]
As mentioned above, I prefer not to add platform specific styling at this point, as it makes it too complex. Also there's a plan to refresh the UI at some point so this style will be removed anyway.

**Pull request closed without merging**
