### PR TITLE
Android: Fixes #6732: Don't reload the application on screen rotation

### LINKED ISSUE #6732: Android: Note screen/settings screen resets on screen rotation change
## Environment

Joplin version: 03c3188a4a8e1aa0da9f3278c6e61f0f9d52258e
Platform: Android
OS Specifics: Android 12/Samsung

## Steps to reproduce

1. Open the note editor
2. Click 'edit'
3. Rotate the screen
4. Navigate to `configuration`
5. Toggle "Enable footnotes"  but don't click save.
6. Rotate the screen
7. Scroll down to "enable footnotes"

## Describe what you expected to happen

* Settings changed before rotating the screen should not be reset on screen rotation.
* The text editor should still be visible after rotating the screen.

# Log
<details>

```
info Reloading app...
 BUNDLE  ./index.js 

 LOG  Running "Joplin" with {"rootTag":21}
 INFO  19:13:04: ====================================
 INFO  19:13:04: Starting application net.cozic.joplin-mobile v2.8.1 (dev)
 INFO  19:13:04: Database was open successfully
 INFO  19:13:04: Checking for database schema update...
 INFO  19:13:04: Current database version {"table_fields_version": 41, "version": 41}
 INFO  19:13:04: Upgrading database from version 41
 INFO  19:13:04: New version: 41. Previously recorded version: 41
 INFO  19:13:04: Database is ready.
 INFO  19:13:04: Loading settings...
 INFO  19:13:04: KeychainService: checking if keychain supported
 INFO  19:13:04: KeychainService: check was already done - skipping. Supported: 0
 LOG  19:13:04: Setting up recurrent sync with interval 300
 INFO  19:13:04: Recurrent sync operation DISABLED!!!
 INFO  19:13:04: e2ee/utils: Trying to load 0 master keys...
 INFO  19:13:04: e2ee/utils: Loaded master keys: 0
 INFO  19:13:04: e2ee/utils: Master password is not set - trying to get it from the active master key...
 LOG  19:13:04: Scheduling sync operation... 10000
 INFO  19:13:04: models/Setting: Applying default migrations...
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 INFO  19:13:04: PluginAssetsLoader: Assets are up to date. Hash: ea13a22d0df59339b671f6b5700e2914
 INFO  19:13:04: Sync target: 0
 INFO  19:13:04: e2ee/utils: Trying to load 0 master keys...
 INFO  19:13:04: e2ee/utils: Loaded master keys: 0
 INFO  19:13:04: Loading folders...
 LOG  19:13:04: Setting up recurrent sync with interval 300
 INFO  19:13:04: Recurrent sync operation DISABLED!!!
 INFO  19:13:04: ResourceFetcher: Auto-add resources: Mode: always
 LOG  19:13:04: Scheduling sync operation... 1000
 INFO  19:13:04: RevisionService: runInBackground: Starting background service with revision collection interval 30000
 INFO  RSA Tests: Running integration tests...
 INFO  RSA Tests: Decrypting and encrypting using desktop data...
 INFO  19:13:04: ResourceFetcher: Auto-added resources: 0
 INFO  RSA Tests: Data could be decrypted
 INFO  RSA Tests: Data could be encrypted then decrypted
 INFO  RSA Tests: Decrypting and encrypting using mobile data...
 INFO  RSA Tests: Data could be decrypted
 INFO  RSA Tests: Data could be encrypted then decrypted
 INFO  RSA Tests: Decrypting and encrypting using local data...
 INFO  RSA Tests: Data could be decrypted
 INFO  RSA Tests: Data could be encrypted then decrypted
 INFO  19:13:05: Application initialized
 INFO  19:13:05: DecryptionWorker: cannot start because no master key is currently loaded.
 INFO  19:13:05: Preparing scheduled sync
 INFO  19:13:05: Sync cancelled - no sync target is selected.
 INFO  19:13:05: Updating all notifications...
 INFO  19:13:05: Garbage collecting alarms...
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 INFO  19:13:07: DecryptionWorker: cannot start because no master key is currently loaded.
 INFO  19:13:08: RevisionService: maintenance: Starting...
 INFO  19:13:08: RevisionService: maintenance: Service is enabled
 INFO  19:13:09: RevisionService: collectRevisions: Created revisions for 0 notes
 INFO  19:13:09: RevisionService: maintenance: Done in 236ms
 WARN  EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 WARN  EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 WARN  EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 LOG  Running "Joplin" with {"rootTag":31}
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 INFO  19:13:14: SearchEngine: Updating FTS table...
 INFO  19:13:15: SearchEngine: Updated FTS table in 35ms. Inserted: 0. Deleted: 0
 WARN  EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 WARN  EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 WARN  EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 LOG  Running "Joplin" with {"rootTag":41}
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 INFO  CodeMirror: Initializing CodeMirror...
 WARN  EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 WARN  EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 WARN  EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
 LOG  Running "Joplin" with {"rootTag":61}
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

```

</details>

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
 * This PR replaces `android:configChanges` with its value in a new-from-template `react-native` project. On my tablet, this resolves #6732.
 * The space-to-tab conversion on several lines is the result of opening `AndroidManifest.xml` in Android Studio.

# Testing plan
(On Android)
1. Deploy a copy of the app from AndroidStudio
2. Open a note
3. Enter edit mode
4. Rotate the screen

**On `origin/dev`**: On my tablet, after step 4, the app exits edit mode and scrolls to the top of the note (the app is partially reloaded). With this PR, the app stays in edit mode.

### CODE REVIEW

**Comment by laurent22** [comment]
Do you understand the reason why these parameters fix the issue? If so could you add a comment above the "android:configChanges" line please?

**Comment by personalizedrefrigerator** [comment]
Related:
 * https://github.com/flutter/flutter/issues/42963
 * https://github.com/facebook/react-native/issues/25040#issuecomment-515297669
 * https://github.com/facebook/react-native/commit/fc962c9b6c4bf9f88decbe014ab9a9d5c1cf51bc

I'm not entirely sure why these changes fixed the issue. I just tested `laurent22/dev` on an Android emulator and am not experiencing the issue. I think my (Samsung) tablet might be configured to treat orientation changes as window resizes.

According to the above links, `screenLayout` and `smallestScreenSize` are for multi-window/split screen layout changes. My tablet was operating in single-window mode.

**Comment by roman-r-m** [comment]
> I'm not entirely sure why these changes fixed the issue. 

From https://developer.android.com/guide/topics/manifest/activity-element

`android:configChanges` 
Lists configuration changes that the activity will handle itself. When a configuration change occurs at runtime, the activity is shut down and restarted by default, but declaring a configuration with this attribute will prevent the activity from being restarted. Instead, the activity remains running and its `onConfigurationChanged` method is called.

**Comment by roman-r-m** [comment]
I don't see how `smallestScreenSize` is relevant but having it won't hurt I guess

**Pull request merged**
