### PR TITLE
Mobile : Added an alert before exiting the app

### LINKED ISSUE #2807: Mobile: Pressing the back button exits the app without any alert
## Environment

Joplin version: 1.0.322
Platform: Mobile

## Steps to reproduce

1. Start the app
2. Press the back button 
3. App closes instantly without any alert

## Describe what you expected to happen
There should be a confirmation alert to ask the user if he/she really want to quit the app.

### PR DESCRIPTION
**Pull request by Rahulm2310**
The app closes instantly when back button is pressed.There should be a confirmation alert which asks user if he/she really want to quit the app.
This PR fixes that.

Before:

After:
exit-alert

fixes #2807

### CODE REVIEW

**Comment by PackElend** [comment]
personally I don't have a problem with that but I can imaging that there are situations in which you don't want that to happen.
As a compromise, can you make it optional?

**Comment by ishantgupta777** [comment]
> personally I don't have a problem with that but I can imaging that there are situations in which you don't want that to happen.
> As a compromise, can you make it optional?

I agree with you, I also don't like my apps asking me again and again for confirmation. I think what we can do is to just create a checkmark option of " Don't ask again", if user checks that, there won't be alert box again and again. What say?

**Comment by PackElend** [comment]
> Don't ask again", if user checks that, there won't be alert box again and again. What say?

is ok for me, but how can I revert it later?

**Comment by ishantgupta777** [comment]
> > Don't ask again", if user checks that, there won't be alert box again and again. What say?
> 
> is ok for me, but how can I revert it later?

We can just add a state variable and when the user chooses to not show that alert-box, we set that variable to false. And while showing alert-box, we just check that variable.

**Comment by PackElend** [comment]
> We can just add a state variable and when the user chooses to not show that alert-box, we set that variable to false.

how can change a standard user that variable? Any menu entry?

**Comment by ishantgupta777** [comment]
> > We can just add a state variable and when the user chooses to not show that alert-box, we set that variable to false.
> 
> how can change a standard user that variable? Any menu entry?

No sir, I mean just a boolean. It will be set as true initially, and there will be a checkmark on alert which will ask for ( not show this again ), and if user choose that option, it will set that variable to false, and there will be no alert after that. And if there is a issue of state variable getting reset on every applicaiton close of Joplin, we can store that variable in local storage.

**Comment by PackElend** [comment]
may I have to ask differently?

How will you allow standard users to revert this setting?

**Comment by ishantgupta777** [comment]
> may I have to ask differently?
> 
> How will you allow standard users to revert this setting?

We can add an option to somewhere in the settings page which will again change the value of thtat variable. And coz this is only mobile thing and variable is storing locally, I don't think there will be a problem in any syncing. We don't even have to touch those settings, just have to add an extra option to settings page.

**Comment by Rahulm2310** [comment]
@ishantgupta777 @PackElend thanks! I am working on it

**Comment by PackElend** [comment]
have a look in  #2327 too

**Comment by laurent22** [comment]
No sorry I don't think we need this. It's almost as fast to accidentally close the app an re-open it, than it is to answer to the alert dialog.

**Pull request closed without merging**
