### PR TITLE
Bump mermaid to 8.8.1

### PR DESCRIPTION
**Pull request by CalebJohn**
[reference](https://github.com/laurent22/joplin/pull/3745#issuecomment-701563953)

It's probably worth it even just for [this change](https://github.com/mermaid-js/mermaid/pull/1686) which removes a bunch of `console.log` statements from mermaid.

### CODE REVIEW

**Review by tessus — COMMENTED** [review]
I think we also have to put it in `ReactNativeClient/package.json` because of the electron builder bug.

**Comment by CalebJohn** [comment]
@tessus Thanks, that was missing in my previous pull.

**Comment by laurent22** [comment]
Thanks for the update. Also when updating a package, please run "npm install" in each relevant directory to update package-lock (it will eventually get updated anyway but in an unrelated commit so it's better to do it now). As we're quite close to the v1.2 release, I'll merge it in v1.3.

**Comment by laurent22** [comment]
Ok it's good to merge, thanks!

**Pull request merged**
