### PR TITLE
add katex font KaTeX_Size4-Regular.woff2

### LINKED ISSUE #2477: Katex: 3x3 and above matrices render with a break in the delimiters
Any 3x3 matrix or a higher order square matrix renders with a tiny break in the delimiters. This nit picky detail can be a bother when the matrix is viewed on a huge screen. Can this be fixed?
4x4

## Environment

Joplin version: 1.0.179
Platform: Linux
OS specifcs: Ubuntu 18.04.4 LTS

## Steps To Reproduce

1. Enter the following latex code in the markdown editor
```bash
$$
\begin{pmatrix}
    a & b & c\\
    a & b & c\\
    a & b & c\\
    a & b & c
\end{pmatrix}
$$
```

2. The matrix should appear in the preview pane or you could also try a PDF or an HTML export to view the issue.

# Describe what you expected to happen

When the above 4x3 matrix was rendered using the editor at https://katex.org/, the delimiters appear to be fine. So, it seems like the issue is not originating from the Katex engine. If you notice Joplin's render of the matrix above, the tapering of the delimiters towards the top and bottom seems a bit off, too. 
4x4_right

Thank you for considering my issue.

### PR DESCRIPTION
**Pull request by tessus**
fixes #2477

Laurent, I think we should add all `*.woff2` fonts.

### CODE REVIEW

**Comment by tessus** [comment]
I forgot to actually mention you @laurent22

Not sure, if you turned off all notifications.

**Comment by tessus** [comment]
@laurent22 I still think we should add all `*.woff2` fonts. They don't take a lot of space. Otherwise we'll create one PR after the other for every katex function someone uses.

**Comment by laurent22** [comment]
Yes, maybe, but is there any doc about what these extra fonts are for? We had the same four for a long time and it seems it's good enough, so I get the feeling the other ones aren't really needed for us.

**Comment by laurent22** [comment]
The extra font you've added also needs to be registered in katex.js. We don't load all the assets every time, only those relevant to the active plugins within the note, and so plugins need to tell the app what assets they need.

That makes me think that could actually be automated, but for now we need to do that manually.

**Comment by tessus** [comment]
Ok, I've registered the font in `katex.js`.

I've also opened an issue with katex to ask for a list/matrix of what the fonts are used for.
Although I seriously doubt they will reply with an explanation.
They probably tell me that if I wanted to use KaTeX properly, I'd have to load all the fonts because that's why they are there and that it was my fault by not using the entire katex package, but just a part of it.
TBH, I'm sure you would dismiss an error report, if a user had deleted a few files from the Joplin app.

I suspect they are just used for different aspects of KaTeX. e.g. if you use a function x,y,z, font A is used, and so on.

**Comment by tessus** [comment]
@laurent22 this one should also be ready. btw, I've added comments to make adding other fonts easier in the future. You will only have to uncomment the fonts and done.

**Comment by laurent22** [comment]
> I've also opened an issue with katex to ask for a list/matrix of what the fonts are used for.
> Although I seriously doubt they will reply with an explanation.
> They probably tell me that if I wanted to use KaTeX properly, I'd have to load all the fonts because that's why they are there and that it was my fault by not using the entire katex package, but just a part of it.

Hmm, yes that's a good point. I've also made some tests and I see that while having the fonts there would increase the package size, it shouldn't affect performances. So I'm ok with including all the fonts as you've prepared in the build script. If you could uncomment the code, we can merge this.

**Comment by tessus** [comment]
@laurent22 done

**Comment by laurent22** [comment]
Perfect, thanks!

**Pull request merged**
