### PR TITLE
Desktop: Resolves #468: Add ability to record audio and save it to a note

### LINKED ISSUE #468: [Feature Request] Audio notes
Recording voice notes and storing them in the cloud.

### PR DESCRIPTION
**Pull request by bryangerlach**
I added a microphone button to a note's edit toolbar that allows you to record audio and save it to the note as an attachment.

### CODE REVIEW

**Comment by Rishgod** [comment]
seems like there are linting issue 😕 

image

**Comment by Rishgod** [comment]
I found a bug that a voice memo is created even if you don't create one, have a look

audio-bug

**Comment by Rishgod** [comment]
Another small bug I found was, the modal does not close on clicking outside it(it should preferably), 
Plus the close button does not function properly so effectively there isn't any way of exiting the modal then saving it. Have a look

audio-bugII

**Comment by laurent22** [comment]
For new React normally it should be done in TypeScript and using React Hooks, as mentioned in contributing.md

**Comment by laurent22** [comment]
Also closing this pull request for the same reason.

**Pull request closed without merging**
