### PR TITLE
All: Translations: Update zh_TW.po and improve zh_CN.po

### PR DESCRIPTION
**Pull request by whriedplanck**
Update zh_TW.po and improve zh_CN.po

### CODE REVIEW

**Comment by whriedplanck** [comment]
Note: zh_CN.po has been updated before (#3430), this PR is mainly for updating zh_TW.po. But zh_CN.po has been slightly updated (improved) again : )

**Comment by tessus** [comment]
Can you please use a new branch. Never, ever re-use a branch after it has been merged. Also, please create one PR per language.

**Comment by whriedplanck** [comment]
> Can you please use a new branch. Never, ever re-use a branch after it has been merged. Also, please create one PR per language.

I'm so sorry for that. I always make mistakes since I'm not familiar with Git and GitHub. Sorry again for make you annoyed.

**Comment by tessus** [comment]
No worries. All good. I am not annoyed. Sometimes it takes a while to get used to the git workflow.

**Pull request closed without merging**
