### PR TITLE
All: Add SwissDisk sync target (based on WebDAV)

### PR DESCRIPTION
**Pull request by benmcollins**
One of the biggest support requests we get is "what's the WebDAV URL". This change aims to hide and hard code details that will never change so that SwissDisk users can have a simpler sync setup page.

Full disclosure, I own SwissDisk.

### CODE REVIEW

**Comment by benmcollins** [comment]
Screen Shot 2022-10-05 at 11 48 50 AM

**Comment by laurent22** [comment]
I don't think we'll add that as it's a lot of extra code to maintain, just to make it a bit easier for SwissDisk users.

Currently we have a Nextcloud sync target because it was planned to do something special for it (but that didn't happen), but any other generic WebDAV target should simply be WebDAV.

**Comment by benmcollins** [comment]
> I don't think we'll add that as it's a lot of extra code to maintain, just to make it a bit easier for SwissDisk users.
> 
> Currently we have a Nextcloud sync target because it was planned to do something special for it (but that didn't happen), but any other generic WebDAV target should simply be WebDAV.

I have some plans as well. For starters, SeissDisk allows creating public links through a propset. I’d like to extend that for Joplin’s share feature.

**Comment by laurent22** [comment]
Thanks but at this point I don't think we'll add this sync target, unless indeed it starts having special features and there's a demand from users.

**Pull request closed without merging**
