### PR TITLE
Update Joplin_install_and_update.sh

### PR DESCRIPTION
**Pull request by tanrax**
- Add argument: Mutes messages by console.
- Remove unset.
- Variables in capital letters.

### CODE REVIEW

**Comment by tanrax** [comment]
I replace print with echo because there is a function that I have called that way 'print()'. It will not work for you separate. I have done this in order to have control of when or not to mute the messages.

**Comment by tanrax** [comment]
Execute 

print() {
...}

print “hi”

🙂

**Comment by tanrax** [comment]
no problem, I make daily mistake much more stupid! 😂 Do you want me to make a change?

**Comment by foxmask** [comment]
It's look like there a party here as you seem to have fun 🤣

**Comment by laurent22** [comment]
That's a good change, thanks @tanrax!

**Comment by tanrax** [comment]
😉

**Pull request merged**
