### PR TITLE
Joplin server (WIP)

### PR DESCRIPTION
**Pull request by laurent22**
The short term goal is to develop a new type of sync target, like Dropbox, Nextcloud, etc. but specifically for Joplin. It will be an open source option that's more performant than Nextcloud (or WebDAV in general).

Once it's working it will allow implementing features that are currently missing in Joplin, in particular:

- Sharing a note with anyone, using a URL. When the note is changed, the content at the URL is changed too.

- Sharing a notebook with a user on the same Joplin Server instance. For example, if you share a notebook with another user, that user will see this notebook in their desktop or mobile app, and will be able to edit the notes, etc.

Although it's not really planned, if there's ever a Joplin web app, this server would be the starting point for it.

### CODE REVIEW

**Comment by tessus** [comment]
@laurent22 I would suggest to create a separate repo for the server. maybe you could already create it under the organization https://github.com/joplinapp, something like `joplinapp/server`.
At one point it could also help to create new repos like `tools` and `tests`, which can then be used as submodule in the repo `joplin`. This depends on your workflow, but in certain situations this could be an advantage.

**Comment by laurent22** [comment]
@tessus, I thought about it but a monorepo for this project is by far the simplest solution. There are dependencies between the server and the core Joplin lib, and as it develops there will be more and more.

**Comment by tessus** [comment]
@laurent22 it all depends on your workflow. e.g. if you used several branches with references to specific commit points, submodules can make your life a lot easier. if you just dump everything in one repo and don't have a real release pipeline, the overhead of using submodules is probably too much.
I only wanted to point out that iff you wanted to change your workflow, now would probably be the best time. ;-)

P.S.:  I do understand the attraction of having only one repo. it's just that I've learned from experience that at one point it might not be that awesome anymore and changing it at that point will be hard and complicated.

**Comment by laurent22** [comment]
Closing this for now while evaluation other possible options.

**Comment by laurent22** [comment]
Re-opening for reference.

**Comment by tessus** [comment]
May I ask what the server database can be? I saw a commit about Postgres and now sqlite3.
sqlite3 is pefectly fine as a client and single user database.

On the server sqlite3 is rather a bad idea. I would only allow MySQL and Postgres. I'm sure there's some sort of abstraction layer library in js that allows to use both.

**Comment by laurent22** [comment]
It's sqlite3 for the test units and of course Postgres for the server. There's indeed a layer of abstraction which allows using one or the other.

**Comment by tessus** [comment]
Thanks for the info. But I rather meant allow MySQL and Postgres. A lot of people only have MySQL and thus requiring to install a second rdbms might be too much.
Personally I prefer Postgres, but I have already IBM DB2 and MySQL running on my server. I doubt I would install Postgres as well. Especially since my server has an uptime of more than 5 years, thus you can imagine how old the base system is.
(I most likely would have to compile postgres myself.)

**Comment by laurent22** [comment]
It's unlikely that MySQL will be supported although you might be able to get it working by changing the config (which in your case would be easier than having to compile Postgres).

**Comment by tessus** [comment]
Is there an architecture document (+ specs and reqs) for the server code?

**Comment by laurent22** [comment]
No, at the moment there's only the readme.

**Comment by shelumiel** [comment]
It would be great if the Joplin server could also be provided as a Docker image, for a novice like me.

**Comment by Grithubber** [comment]
Hi there!

I'm confused. Is there a centralized Joplin Server in existence that I can target? Or do I have to host it?

Thanks!

**Comment by Heston-in-Mtl** [comment]
> Hi there!
> 
> I'm confused. Is there a centralized Joplin Server in existence that I can target? Or do I have to host it?
> 
> Thanks!

It would be self-hosted.  There is no "public" Joplin Server hosted by the devs.  However, you can use something like Dropbox or Nextcloud as a sync target.

**Comment by shelumiel** [comment]
> Hi there!
> 
> I'm confused. Is there a centralized Joplin Server in existence that I can target? Or do I have to host it?
> 
> Thanks!

There is a docker image named “Joplin Server,” which has been provided since January, and it needs to be self-hosted. I remember the developer also considers offering a centralized server in the future.

For the self-hosted Joplin Server, refer to the following: 

https://discourse.joplinapp.org/t/joplin-server-pre-release-is-now-available

https://hub.docker.com/r/joplin/server

**Pull request merged**
