### PR TITLE
WIP - Fold/unfold Notebook/Tag trees

### PR DESCRIPTION
**Pull request by Abijeet**

### CODE REVIEW

**Comment by tessus** [comment]
This PR looks a bit off. Why are there past commits from a previous PR?

Can you checkout/pull the master of jopiln, make your changes, and create a PR?

**Comment by tessus** [comment]
I'm not sure, if I understand. How would you lose your contributions? They are already commited to joplin (minus the current change). Are they not?
Usually when you fork a project and start contributing you create a branch. You change into that branch, do your code changes, commit them, and create a PR. After the PR is merged, you can delete that branch.
And then you start all over again with a new branch for your next contribution(s).

Commits in a fork do not count as contributions. They only count, when they are merged. And then they are counted from the original repo and not the fork. (That's why you can delete your branch in the forked repo).

I think the problem is that you messed up your own master branch somehow. (Never, ever commit changes to a forked master, unless you really know what you are doing.)

**Comment by tessus** [comment]
One way to fix it (if you don't have any other new code or changes in your repo):

- Save your changes (`ElectronClient/app/gui/SideBar.jsx` and `ReactNativeClient/lib/models/Setting.js`) into a temporary directory (outside the repo).
- Delete the repo
- fork joplin again
- create branch `whatever-name-you-like`
- change into the new branch
- copy the saved files back to their respective locations
- commit
- create PR

**Comment by alexdevero** [comment]
@Abijeet another option is removing those wrong commits manually from git history, keeping only the commit for folding, and then rebasing your branch with master.

**Comment by Abijeet** [comment]
@alexdevero and @tessus  - Thank you for the suggestions. I think I will avoid updating forked master from now onwards.

To fix this problem, here's what I've done for now.

1. Created a new branch from `upstream/master` - `git checkout -b toggle-menu upstream/master`
2. Cherry-picked the two necessary commits - `git cherry-pick <<commit-id>>` 

I've created a new WIP PR here - https://github.com/laurent22/joplin/pull/1002

**Pull request closed without merging**
