### PR TITLE
Mobile: Resolves #9258: Add more space between settings title and description

### LINKED ISSUE #9258: Add more space between setting title and description
Add 3 or 4 more pixels between the setting title and description as it's a bit narrow at the moment.

image

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Adds additional space between the section headers and descriptions in the mobile settings screen.

Resolves #9258.

# Screenshots

screenshot: Before and after. Shows section list, with more space between titles and descriptions after than before

# Notes

With this change, the description text seems a bit too close to the next heading in some cases.

### CODE REVIEW

**Comment by laurent22** [comment]
> With this change, the description text seems a bit too close to the next heading in some cases.

Yes actually it looks a bit better in the previous version because of this. How difficult would it be to limit the description text to just one line and truncate with ellipsis?

**Comment by personalizedrefrigerator** [comment]
> Yes actually it looks a bit better in the previous version because of this. How difficult would it be to limit the description text to just one line and truncate with ellipsis?

That should (hopefully :) ) be a one-line change.

**Comment by personalizedrefrigerator** [comment]
> > With this change, the description text seems a bit too close to the next heading in some cases.
> 
> Yes actually it looks a bit better in the previous version because of this. How difficult would it be to limit the description text to just one line and truncate with ellipsis?


With this change:

screenshot: Just one line of description below each section

**Comment by laurent22** [comment]
Perfect, thanks!

**Pull request merged**
