### PR TITLE
Updating Brazilian Portuguese strings

### PR DESCRIPTION
**Pull request by nicolas-suzuki**
Added missing translated strings. 
Fixed some incorrect translations. 
Standardized some words across all application's strings.

### CODE REVIEW

**Review by tessus — CHANGES_REQUESTED** [review]
Thanks for the update, but please do not commit the `.mo` file.

**Comment by tessus** [comment]
@laurent22 I have added the `.mo` files to `.gitignore`.

**Comment by nicolas-suzuki** [comment]
@tessus should fr_FR.mo be removed too?

**Review by tessus — APPROVED** [review]
Great. Thanks.

**Comment by tessus** [comment]
> should fr_FR.mo be removed too?

Yes, I've already deleted it. Thanks.

**Pull request merged**
