### PR TITLE
added feature of select all and closes #2721

### LINKED ISSUE #2721: No option for select all in notes
In any notebook, while selecting notes, let just I have so many notes in a notebook and I want to delete most of them, for that, there is no option of select all in the navbar. It's necessary for users if they want to edit or delete most of the notes except few, so they need to select all features.

Screenshot_1583891971

## Environment

Joplin version:  1.0.320
Platform: Mobile
OS specifics: No

## Describe what you expected to happen

I expected it to have an option to select all, so that if I want to delete most of them at a  time. I can just select all and deselect the few I don't want to delete. It would be so much easier for users.

I would like to work on this.

### PR DESCRIPTION
**Pull request by ishantgupta777**
closes #2721 

I added an option to select all notes at a time. I added a button that will appear when the user selects any note and then they can click on them to select all notes of that particular screen. This way they can easily manipulate multiple notes.

Tests:
1. I tested manually that the icon is only appearing on the screen when users choose any note and nowhere else. And also checked configuration and other pages, just to be sure.
2. I checked that when user clicks on select all button, only the notes of that page are getting selected and no other notes. I confirmed this by logging the changing values in the reducer.
3. I checked that after selecting all the notes, deleting, duplicating and all the other options are working.
4. I checked that after selecting all the options if we deselect some options, everything goes as expected.

@PackElend can you please add gsoc2020 label and have a look at this PR. 

select_all

### CODE REVIEW

**Comment by laurent22** [comment]
Code looks very good, and indeed thank you for re-using the existing NOTE_SELECT_ALL action. However, when I click this button a second time, I would expect all the notes to get unselected. Could you add this feature please?

I guess there could be an action "NOTE_SELECT_ALL_TOGGLE", which would work like this:

- If not all notes are selected, select them all.
- If all notes are selected, unselect them all.

**Comment by ishantgupta777** [comment]
> Code looks very good, and indeed thank you for re-using the existing NOTE_SELECT_ALL action. However, when I click this button a second time, I would expect all the notes to get unselected. Could you add this feature please?
> 
> I guess there could be an action "NOTE_SELECT_ALL_TOGGLE", which would work like this:
> 
> * If not all notes are selected, select them all.
> * If all notes are selected, unselect them all.

Sure I will surely add that feature. I also think of the same feature but I didn't add it, coz in screen header, we already have a back button, which does the same thing, deselecting all notes. So I thought there was no need for the same. But if you want, I will start working on this feature.

**Comment by ishantgupta777** [comment]
> Code looks very good, and indeed thank you for re-using the existing NOTE_SELECT_ALL action. However, when I click this button a second time, I would expect all the notes to get unselected. Could you add this feature please?
> 
> I guess there could be an action "NOTE_SELECT_ALL_TOGGLE", which would work like this:
> 
> * If not all notes are selected, select them all.
> * If all notes are selected, unselect them all.

As you suggested, I added the actions and the toggle functionality. I tested it and it works fine and everything looks good to me. Please have a look and let me know if there is a need to change something.

**Comment by laurent22** [comment]
Perfect, thanks @ishantgupta777!

**Pull request merged**
