### PR TITLE
Desktop: Fixes #10037: Changed the minimum width of layout items

### LINKED ISSUE #10037: Desktop: Note list does not scale properly with window.
### Operating system

Windows

### Joplin version

2.14.17

### Desktop version info

Joplin 2.14.17 (prod, win32)

Client ID: 0a80033d17974af2a611ab52d4b3fc8e
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 094175c

ABC Sheet Music Plugin: 1.0.3
Autolinker: 1.0.4
Backup: 1.4.0
Enhancement: 1.2.1
Plugin Bundle: 0.5.5

### Current behaviour

Ok so the note list doesn't scale properly with the window and its quite annoying to have to manually size it every time I change the size of the window the best way I can show the behavior is a video 

https://github.com/laurent22/joplin/assets/1302391/7272ad16-7540-4ea5-848c-41295941b81b

### Expected behaviour

It should scale proportionally to its relative size. 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ab-elhaddad**
This is a quick fix for #10037 
It may not be the best solution for the issue, but for now, it serves the purpose.

### Before

https://github.com/laurent22/joplin/assets/113056556/9584f8e5-b2a1-4bb8-8e38-0aefd0f80114

### After

https://github.com/laurent22/joplin/assets/113056556/652a5d8c-939e-4668-9a90-fdcdbeeb2ee2

### CODE REVIEW

**Comment by ab-elhaddad** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by personalizedrefrigerator** [comment]
Several tests are failing in CI:

<details>

````Summary of all failing tests
➤ YN0000: [@joplin/app-desktop]: FAIL gui/ResizableLayout/utils/useLayoutItemSizes.test.js (12.35 s)
➤ YN0000: [@joplin/app-desktop]:   ● useLayoutItemSizes › should leave room for the resizer controls
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:     expect(received).toEqual(expected) // deep equality
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:     - Expected  - 4
➤ YN0000: [@joplin/app-desktop]:     + Received  + 4
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       Object {
➤ YN0000: [@joplin/app-desktop]:         "col1": Object {
➤ YN0000: [@joplin/app-desktop]:           "height": 100,
➤ YN0000: [@joplin/app-desktop]:     -     "width": 100,
➤ YN0000: [@joplin/app-desktop]:     +     "width": 105,
➤ YN0000: [@joplin/app-desktop]:         },
➤ YN0000: [@joplin/app-desktop]:         "col2": Object {
➤ YN0000: [@joplin/app-desktop]:           "height": 100,
➤ YN0000: [@joplin/app-desktop]:     -     "width": 100,
➤ YN0000: [@joplin/app-desktop]:     +     "width": 105,
➤ YN0000: [@joplin/app-desktop]:         },
➤ YN0000: [@joplin/app-desktop]:         "root": Object {
➤ YN0000: [@joplin/app-desktop]:           "height": 100,
➤ YN0000: [@joplin/app-desktop]:           "width": 200,
➤ YN0000: [@joplin/app-desktop]:         },
➤ YN0000: [@joplin/app-desktop]:         "row1": Object {
➤ YN0000: [@joplin/app-desktop]:           "height": 50,
➤ YN0000: [@joplin/app-desktop]:     -     "width": 100,
➤ YN0000: [@joplin/app-desktop]:     +     "width": 105,
➤ YN0000: [@joplin/app-desktop]:         },
➤ YN0000: [@joplin/app-desktop]:         "row2": Object {
➤ YN0000: [@joplin/app-desktop]:           "height": 50,
➤ YN0000: [@joplin/app-desktop]:     -     "width": 100,
➤ YN0000: [@joplin/app-desktop]:     +     "width": 105,
➤ YN0000: [@joplin/app-desktop]:         },
➤ YN0000: [@joplin/app-desktop]:       }
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       124 | 		const sizes = result.current;
➤ YN0000: [@joplin/app-desktop]:       125 |
➤ YN0000: [@joplin/app-desktop]:     > 126 | 		expect(sizes).toEqual({
➤ YN0000: [@joplin/app-desktop]:           | 		              ^
➤ YN0000: [@joplin/app-desktop]:       127 | 			root: { width: 200, height: 100 },
➤ YN0000: [@joplin/app-desktop]:       128 | 			col1: { width: 100, height: 100 },
➤ YN0000: [@joplin/app-desktop]:       129 | 			col2: { width: 100, height: 100 },
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       at Object.toEqual (gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:126:17)
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:   ● useLayoutItemSizes › should not allow a minWidth of 0, should still make space for the item
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:     expect(received).toBe(expected) // Object.is equality
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:     Expected: 160
➤ YN0000: [@joplin/app-desktop]:     Received: 95
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       190 | 		const sizes = result.current;
➤ YN0000: [@joplin/app-desktop]:       191 |
➤ YN0000: [@joplin/app-desktop]:     > 192 | 		expect(sizes.col1.width).toBe(160);
➤ YN0000: [@joplin/app-desktop]:           | 		                         ^
➤ YN0000: [@joplin/app-desktop]:       193 | 		expect(sizes.col2.width).toBe(40); // default minWidth is 40
➤ YN0000: [@joplin/app-desktop]:       194 | 	});
➤ YN0000: [@joplin/app-desktop]:       195 |
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       at Object.toBe (gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:192:28)
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:   ● useLayoutItemSizes › should give maximum available space this item can take up during resizing
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:     expect(received).toBe(expected) // Object.is equality
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:     Expected: 90
➤ YN0000: [@joplin/app-desktop]:     Received: 50
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       288 |
➤ YN0000: [@joplin/app-desktop]:       289 | 		// maxSize = totalSize - ( [size of items with set size, except for the current item] + [minimum size of items with no set size] )
➤ YN0000: [@joplin/app-desktop]:     > 290 | 		expect(maxSize1.width).toBe(90); // 90 = layout.width - (col2.width + col3.minWidth(=40) )
➤ YN0000: [@joplin/app-desktop]:           | 		                       ^
➤ YN0000: [@joplin/app-desktop]:       291 | 		expect(maxSize2.width).toBe(110); // 110 = layout.width - (col1.width + col3.minWidth(=40) )
➤ YN0000: [@joplin/app-desktop]:       292 | 	});
➤ YN0000: [@joplin/app-desktop]:       293 |
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       at Object.toBe (gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:290:26)
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:   ● useLayoutItemSizes › should not allow a minWidth of 0, should still leave space for the item
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:     expect(received).toBe(expected) // Object.is equality
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:     Expected: 160
➤ YN0000: [@joplin/app-desktop]:     Received: 95
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       347 |
➤ YN0000: [@joplin/app-desktop]:       348 | 		// maxSize = totalSize - ( [size of items with set size, except for the current item] + [minimum size of items with no set size] )
➤ YN0000: [@joplin/app-desktop]:     > 349 | 		expect(maxSize1.width).toBe(160); // 160 = layout.width - col2.minWidth(=40)
➤ YN0000: [@joplin/app-desktop]:           | 		                       ^
➤ YN0000: [@joplin/app-desktop]:       350 | 	});
➤ YN0000: [@joplin/app-desktop]:       351 |
➤ YN0000: [@joplin/app-desktop]:       352 | });
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]:       at Object.toBe (gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:349:26)
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]: 
➤ YN0000: [@joplin/app-desktop]: Test Suites: 1 failed, 20 passed, 21 total
➤ YN0000: [@joplin/app-desktop]: Tests:       4 failed, 74 passed, 78 total
➤ YN0000: [@joplin/app-desktop]: Snapshots:   0 total
➤ YN0000: [@joplin/app-desktop]: Time:        22.257 s
➤ YN0000: [@joplin/app-desktop]: Ran all test suites.
````

</details>

**Comment by ab-elhaddad** [comment]
@personalizedrefrigerator 
working on it

**Comment by laurent22** [comment]
Please see my comment on the issue: https://github.com/laurent22/joplin/issues/10037#issuecomment-1984834710 We will go for a different solution

**Pull request closed without merging**
