### PR TITLE
Desktop, Mobile: Update Mermaid: 8.10.2 -> 8.12.1

### LINKED ISSUE #5295: joplin not responding when draw mermaid with indentation
platform：Windows10

image

1. encryption is enabled
2. mermaid gitGraph works well without indentation 
3. i could click the menu but nothing render out, seems the render run into an infinite loop
4. i installed only one plugin: PlantUML

### PR DESCRIPTION
**Pull request by tessus**
Keeping Mermaid up-to-date....

I've run manual tests with all the different supported charts. No issues so far. But I've noticed that the arrows in the flowchart are now slightly thicker (bolder).

I think it fixes #5295 (I couldn't reproduce the problem anymore)

### CODE REVIEW

**Comment by laurent22** [comment]
That's great, thanks for checking. Let's assume it's fixed for now and if it's not we'll re-open the issue anyway.

**Comment by laurent22** [comment]
By the way, I should have checked the commit because I didn't see npm converted all the package-lock files back to v1. I'm going to reconvert to v2 but you might want to upgrade to npm 7 to avoid this.

**Comment by laurent22** [comment]
In fact that seems weird that npm knows enough about the v2 format to downgrade it to v1, but not enough to simply keep it as it is. Sounds like a rather dumb move from the npm team, but then again it's npm.

**Comment by tessus** [comment]
I am using npm 7:

```
[tessus@epsilon3 0 ~/work/joplin fix/update-mermaid {origin/fix/update-mermaid}|✔]$ npm --version
7.21.1
```

**Comment by tessus** [comment]
This is really weird. I checked my system and I have no idea why the lock files were downgraded to a v1 format. I do not have an npm 6 version anywhere. Truly puzzling. If you have any idea how this might have happened, please let me know.

**Pull request merged**
