### PR TITLE
Desktop: Fixes #4754: Roboto font in plugins

### LINKED ISSUE #4754: Desktop: missing Roboto font in plugins
## Environment

Joplin version: 1.7.11
Platform: macOS
OS specifics: Big Sur 11.2.3

## Steps to reproduce

0. Right-click and disable Roboto font in "Font Book" if you have it installed
1. Download and install Joplin on desktop / Mac
2. Run Joplin w/a new profile (e.g. using dev command)
3. Open Preferences => Plugins => enable Favorites and Outline plugins
4. Observe that Favorites displays with one font (Roboto, sans serif) and Outline w/another (serif font / fallback)

image

## Describe what you expected to happen

I expect to see both plugins with identical font appearance.

If you inspect the panes / iframes for each plugin with developer tools, you'll see that each specifies `font-family: Roboto` either explicitly, or indirectly with `font-family: var(--joplin-font-family)`. 

This as advised by the plugin tutorial documentation:

https://joplinapp.org/api/tutorials/toc_plugin/#styling-the-view

However -- only the Favorites plugin appears correctly, because it packages the Roboto font w/the plugin and links to this bundled version.

## Logfile

N/A, this is a presentation issue, nothing wrong w/the underlying application behavior or logic

### PR DESCRIPTION
**Pull request by brttbndr**
This change links the Roboto, Icomoon, and Font-Awesome stylesheets into the index.html used by all plugins.

This makes the fonts available to all plugins, w/out the plugin needed to package and ship the font.

I tested manually by comparing the presentation of Joplin with the Favorites and Outline plugins installed. Without this change, Outline displays incorrectly. With it, both plugins have the correct presentation.

# Before

image

# After

image

### CODE REVIEW

**Comment by laurent22** [comment]
Sounds like a very good change as it means all plugins will now have access to FontAwesome by default. Would you mind adding some doc about this under /readme/api/references/plugin_theming.md please? It should have the header `# Plugin theming`. Then if you could just mention the style files that are including by default that would be great.

**Comment by brttbndr** [comment]
I've added `plugin_theming.md` as requested. As both Font Awesome and icoMoon are currently used in various places in Joplin, I've included them both here.

There's a TOOD here that mentions removing / swapping icons. Does that affect what fonts / icons to include and document in this PR?

https://github.com/laurent22/joplin/blob/cc07016b07bd83dd8d38fba392b7aad8eaf2ca6d/packages/app-desktop/index.html#L11-L18

**Comment by laurent22** [comment]
Thanks for the update, could you also please add a link to your new file in README.md in the Table of Contents, under "Joplin API - References"?

**Comment by laurent22** [comment]
Regarding the TODO comment, I believe it could be removed. I assume it was when we switched from Fork Awesome to Font Awesome?

**Comment by brttbndr** [comment]
Done -- added a link in README, removed the TODO comment.

**Comment by laurent22** [comment]
Looks good now, many thanks for creating the theming doc!

**Pull request merged**
