### PR TITLE
Desktop: Cleaning up the install / update script

### PR DESCRIPTION
**Pull request by mrwulf**
* New `--force` option always downloads the latest version
* New `--notes` option shows the release notes
* Actually print the version installed at the end
* Show download progress, but not extra garbage
* Blue logo

### CODE REVIEW

**Comment by laurent22** [comment]
Looks good to me. Is it common to use `--notes` for release notes? I'd use `--changelog` because "notes" can mean other things.

**Comment by tessus** [comment]
There's no specific argument in the Unix world for that. Both are perfectly valid.
But if you prefer `--changelog`, I can change it and then merrge.

**Comment by mrwulf** [comment]
Either is fine for me- I can change it as well, but probably not until
tomorrow.

-Brandon

**Comment by tessus** [comment]
Thanks for your reply @mrwulf. Let's see what Laurent wants to do.

**Comment by tessus** [comment]
@laurent22 if we could have your input, we'd be able to merge this today.

**Comment by laurent22** [comment]
Also would it make sense to add a help page, now that there are options? Something that will show up when running `--help`.

**Comment by mrwulf** [comment]
OK, I went a little crazy refactoring. Here are the highlights:
- Switched `--notes` to `--changelog`
- Added more complete argument parsing
- Added a `--help` argument to show usage
- Fixed the `--force` option to not actually remove the `~/.joplin/VERSION` file until the new version is being installed
- Download the new version to a temp directory (doesn't leave joplin unusable if the download fails or is cancelled)
- Show the current and desired versions

**Comment by tessus** [comment]
Great, thanks for the changes.

**Comment by tessus** [comment]
@mrwulf I'm sorry, but there was a change to the same file and there's a conflict now.
Any chance you can fix it and then I am allowed to merge.

**Comment by mrwulf** [comment]
Thanks- updated!

**Comment by tessus** [comment]
Great, thank you.

**Pull request merged**
