### PR TITLE
All: Fix calls to non-existent function

### PR DESCRIPTION
**Pull request by mic704b**
Fixes simple typo in function name.

### CODE REVIEW

**Comment by tessus** [comment]
That's kind of weird that this was never caught. Aren't there any negative tests?

**Comment by mic704b** [comment]
> That's kind of weird that this was never caught. Aren't there any negative tests?

It is an error in the throwing of an error!  So it throws, just not what it should throw.

Have added a test now, but it would have passed anyway.

**Comment by tessus** [comment]
LGTM.

**Comment by laurent22** [comment]
Thanks for the fix @mic704b, looks good. Please fix the conflict and when it's done feel free to merge.

**Comment by tessus** [comment]
Ok, great. You can merge.

**Comment by mic704b** [comment]
> Please fix the conflict and when it's done feel free to merge.

Done!

**Pull request merged**
