### PR TITLE
Desktop: Resolves #7662: Fixed ctrl-x behaviour when no text is selected

### LINKED ISSUE #7662: Ctrl-X behaviour when no text is selected
## Environment

Joplin version: 2.9.17 (prod, win 32)
Platform: Joplin for Desktop
OS specifics: Win 10

## Steps to reproduce

1. Select some text, Ctrl-X, confirm it is in the clipboard by doing Ctrl-V
2. Go to any line of text, without selecting text, press Ctrl-X
3. Ctrl-V: it pastes nothing. 

## Describe what you expected to happen

- In other editors, if nothing is selected and Ctrl-X is pressed, it either (1) does not change the clipboard, or (2) cuts the whole line and puts it in the clipboard.
- Ideally, I would hope that if no text is selected then Ctrl-X would cut the whole line, as Joplin already has commands similar to other editors like VS Code that behave in this way to manage a whole line, e.g. move it up and down, delete the whole line, etc. 
- But if not possible to copy/cut a whole line, at least the clipboard should not be changed when using Ctrl-X on a line without anything selected. 

This is a follow up to #7602

### PR DESCRIPTION
**Pull request by abhiippili**
Should fix the behaviour of ctrl + x when the cursor is placed at a line and no text is selected.
This would change the clipboard with the content of the line and also removes the line, essentially doing a cut operation like it would be on vscode.

### CODE REVIEW

**Comment by abhiippili** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by tessus — COMMENTED** [review]
LGTM

**Comment by abhiippili** [comment]
Can this PR be merged ?

**Comment by tessus** [comment]
Laurent merges PRs, so whenever he's got the time and deems this PR for ok, he'll do it. 

I am only supposed to merge PRs for translation and documentation. (And I think I am allowed to merge PRs for the install bash script.)

**Comment by abhiippili** [comment]
Alright. Thanks!

**Comment by laurent22** [comment]
Doesn't even pass the linter...

**Comment by abhiippili** [comment]
Sorry about that. This is one of my first contributions. I'll try to fix where I went wrong

**Comment by laurent22** [comment]
It's on coding_style.md. But also that commit hook should run automatically. Is it not running for you? If there's any error or warning when committing please let us know, as we need this to be working. The point of a linter is that we don't need to deal with things like missing spaces or commas.

**Comment by laurent22** [comment]
@abhiippili, are you still interested in implementing this or should we close the PR?

**Pull request closed without merging**
