### PR TITLE
removed some unneccesary code

### PR DESCRIPTION
**Pull request by Rahulm2310**

### CODE REVIEW

**Comment by tessus** [comment]
I'm not sure why you did that. There's most likely a reason why Laurent commented some of the code.

Also, your formatting made the code less readable. I seriously doubt that this will be merged. Before submitting a PR that removes code, please discuss this first on the forum. There's the development category, which is perfect for such topics.

**Comment by laurent22** [comment]
I think you've ran prettier on the code base, which I really dislike. We use eslint for formatting and coding conventions.

**Comment by Rahulm2310** [comment]
Ok , thanks for replying.Got It !

**Comment by Rahulm2310** [comment]
Hello Sir,
Happy to see that Joplin is participating in GSOC 2020.It is far most the
best note-making application.

Thus, I would love to contribute to Joplin.I have a pretty good experience
in react & react native. This is a golden opportunity for me to work for a
large community like Joplin.

With Regards
Rahul Mohata

**Pull request closed without merging**
