### PR TITLE
fix toc with special characters - finally

### PR DESCRIPTION
**Pull request by tessus**
subject says it all

### CODE REVIEW

**Comment by laurent22** [comment]
I think that's indeed the right solution. Just to be sure, please could you check that it works with Russian and Chinese text headings too? Even better would be to have test units for this, but another time.

**Comment by tessus** [comment]
Yep, will do. But after a 4h Skype session with a friend in Europe and 2 bottles of red wine I will postpone this task to tomorrow. ;-)

**Comment by tessus** [comment]
>  works with Russian and Chinese text headings too?

Yes, it does. Added Japanese (which included a few Chinese characters) and Russion headings and it works like a charm.

**Comment by tessus** [comment]
@laurent22 can we merge this now?

**Comment by laurent22** [comment]
Perfect, thanks for checking @tessus, it's good to merge then.

**Comment by tessus** [comment]
@laurent22 here's the test code I used locally. Maybe you can use it for your test cases:

```
const uslug = require('uslug')

const md = require('markdown-it')({
	  html: true,
	  linkify: true
}).use(require('markdown-it-anchor'), { slugify: s => uslug(s), })
  .use(require('markdown-it-toc-done-right'), { listType: 'ul', slugify: s => uslug(s) })

const str = '[toc]\n\n# 日本語のテキスト\n\nText<br><br><br><br><br><br><br><br><br>\n\n# Немного текста на русском\n\nText<br><br><br><br><br><br><br><br><br>\n\n# heading (special)\n\nText<br><br><br><br><br><br><br><br><br>\n\n# another @ char\n\nText<br><br><br><br><br><br><br><br><br>\n\n# a lot of special characters !@#$%^&*\n\nText<br><br><br><br><br><br><br><br><br>\n\n# test !\n\nText<br><br><br><br><br><br><br><br><br>\n\n# test %\n\nText<br><br><br><br><br><br><br><br><br>\n\n---\n<br><br><br><br><br><br><br><br><br>\n<br><br><br><br><br><br><br><br><br>\n<br><br><br><br><br><br><br><br><br>\n<br><br><br><br><br><br><br><br><br>\n<br><br><br><br><br><br><br><br><br>\n';

console.log(md.render(str));
```

I used the `<br>` so that I could actually jump to the heading in a browser. But I guess they can be removed for the test case.

**Pull request merged**
