### PR TITLE
Translation Greek (el_GR)

### PR DESCRIPTION
**Pull request by XarisA**
Hey, this is the Greek Translation of the Joplin app.
I suppose minor changes could occur due to gender translations.

### CODE REVIEW

**Comment by tessus** [comment]
Awesome, this is great. Thank you for the new language.

**Comment by tessus** [comment]
@laurent22 what is the procedure for adding a new language? Is it just adding a new entry in the README.md or do I also have to register the language? I think to remember there was a list of languages in a separate file, but I'm not sure. So I guess the best way is to merge this PR and then to work on the other items, right?

**Comment by laurent22** [comment]
Normally it should auto-detect any new language. It's mainly with the flags that sometimes there's a problem but in this case it should be fine since the country is specified in the locale code (GR).

**Comment by tessus** [comment]
Yep, I tested it locally. Seems to be straight forward. I'll merge this and update the translations again.

**Pull request merged**
