### PR TITLE
All: Update norwegian translations

### PR DESCRIPTION
**Pull request by matsest**
Complete missing translations and minor corrections

### CODE REVIEW

**Comment by tessus** [comment]
Thank you for the PR.

**Comment by matsest** [comment]
@tessus Should "#, fuzzy" be removed? I see that those translations, e.g. "Search in current note" does not get translated in the .json file, as it's catched by this first clause in build-translation.js
https://github.com/laurent22/joplin/blob/3567a57d6abc8112638b95c8f293ad6ae6c4f0ed/Tools/build-translation.js#L35-L39

**Comment by laurent22** [comment]
There's no need to remove the fuzzy translations from the po file, and they can actually be a guide to improve the translation. But they are indeed skipped when building the JSON file since they are often not quite accurate.

**Comment by tessus** [comment]
If you are sure that the translation is accurate, then yes.
-- 
regards Helmut K. C. Tessarek

(sent from a mobile device)

**Comment by matsest** [comment]
I'm not quite sure what you mean - are the fuzzy-flag for other translators to judge if the translation (msgstr) is not accurate? Or is it related to the accuracy or the msgid string itself?

**Comment by laurent22** [comment]
This is a feature of gettext, it tries to automatically translate some entries based on other existing strings: https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html Usually the translation is relatively close but not accurate enough so that's why I don't include them in the final build.

**Comment by matsest** [comment]
Thanks for the clarification - then I understand. I'm a native Norwegian speaker, so I'll take a look at this in the next translation update.

Support that this detail should be clarified in the README under translation guidelines.

**Comment by tessus** [comment]
> I'm a native Norwegian speaker, so I'll take a look at this in the next translation update.

Awesome, great. Thanks.

@laurent22 here's a draft paragraph for the README. What do you think?

Some translations were done with gettext in an automated fashion and thus might not be very good. A keyword `#, fuzzy` was added to denote this. These lines are excluded when packaging the translations.
If you are a native speaker, please check the `.po` file and remove the `#, fuzzy` line in case the translation is accurate.

**Pull request merged**
