### PR TITLE
Fix casing typo for PluginAssetsLoader.js in gitignore

### PR DESCRIPTION
**Pull request by CalebJohn**

### CODE REVIEW

**Comment by tessus** [comment]
@laurent22 I cam merge stuff like that, right?

**Comment by laurent22** [comment]
@CalebJohn, while you're at it, could you also fix the casing in .eslintignore please? That way we have just one commit for these two fixes.

**Comment by tessus** [comment]
I remember there was another dime that was generated when I built the mobile client. I currently don't have access to my machine, but I'll open a new PR when I do. (I just thought I should mention it.)

**Comment by CalebJohn** [comment]
@laurent22  Done!

**Comment by laurent22** [comment]
Perfect, thanks @CalebJohn!

**Comment by laurent22** [comment]
> I remember there was another file that was generated when I built the mobile client. 

That might have been the new plugin asset file, but that should be fixed in the latest version.

**Pull request merged**
