### PR TITLE
Android: Suggest to check app perms in case of ENOENT error during FS sync

### PR DESCRIPTION
**Pull request by xuhcc**
This error can occur on Android if application doesn't have SD card permission (#1654).

Preview:

### CODE REVIEW

**Comment by laurent22** [comment]
This error handler is used by the terminal, desktop and mobile application and can be triggered for many reasons, most of which are not related to app permissions. I don't think the PR can be improved so unfortunately I'll have to close it, however feel free to open a new one if you find a different approach.

**Comment by xuhcc** [comment]
@laurent22 On Android ENOENT exception has a `nativeStackAndroid` attribute, so it is possible to show permission hint only on this platform.

If you think that this is still too general, then I'll try to find out why `PermissionsAndroid` doesn't work (as noted in https://github.com/laurent22/joplin/commit/c83a61d45d392819197c034af54015ba557c6f9d).

**Comment by laurent22** [comment]
Does the nativeStackAndroid attribute provide more details about the error? Because "ENOENT" actually means that the file cannot be found, so it could be something other than a permission error, even on Android.

**Comment by xuhcc** [comment]
No, `nativeStackAndroid` is empty array.

**Pull request closed without merging**
