### PR TITLE
Improved search feature

### PR DESCRIPTION
**Pull request by marcosvega91**
I have moved the notes search feature to an external module and I add the feature that permit the user to concatenate two or more search string using AND operator

#107

### CODE REVIEW

**Comment by marcosvega91** [comment]
Hi @laurent22 have you any idea why CI fails?

**Comment by alexdevero** [comment]
@marcosvega91 It looks like the test failed because of one dependecy, fsevents. It was probably not caused by your changes.

**Comment by marcosvega91** [comment]
now it passes all checks

**Comment by alexdevero** [comment]
Good work @marcosvega91 👍 .

**Comment by laurent22** [comment]
Closing for now as the search feature will be done differently, as outlined in #144

**Pull request closed without merging**
