### PR TITLE
Desktop: Fixes #9130: Add Electron `--disable-gpu` flag to known flags

### LINKED ISSUE #9130: Joplin desktop does not accept `--disable-gpu` flag
**Joplin desktop does not accept Electron `--disable-gpu` flag.**

At some point I encountered GPU rendering errors on Linux with most Electron applications. And while every other application could be started with `--disable-gpu` flag Joplin desktop refused to accept this flag so I couldn't use it anymore.

I guess this flag is important and desktop app should accept it.

## Environment

Joplin version: latest
Platform: all

I've made a patch for myself.

[Git patch](https://gist.github.com/orl0/6a5e8f46acb000fa1cc33a9b4b2434aa)

I can make a PR if you want.

### PR DESCRIPTION
**Pull request by orl0**
Add Electron `--disable-gpu` flag to known flags in `packages/lib/utils/processStartFlags.ts`

Issue #9130

### CODE REVIEW

**Review by tessus — APPROVED** [review]
LGTM

**Comment by Perkolator** [comment]
Sorry for bothering, but what does this change actually do? Is the `--disable-gpu` switch just ignored now?

**Comment by orl0** [comment]
> Sorry for bothering, but what does this change actually do? Is the `--disable-gpu` switch just ignored now?

It was. Desktop app ignore all unknown flags.

**Comment by Perkolator** [comment]
> > Sorry for bothering, but what does this change actually do? Is the `--disable-gpu` switch just ignored now?
> 
> It was. Desktop app ignore all unknown flags.

Ok. It was the "Electron-specific flag - ignore it" comment that threw me off, and seeing that the splice just removes the argument.. though I have to admit that I'm not fully understanding the code here.

Do you know a way to confirm that the HW acceleration is turned off when running Joplin with the `--disable-gpu` flag?

**Comment by orl0** [comment]
> > > Sorry for bothering, but what does this change actually do? Is the `--disable-gpu` switch just ignored now?
> > 
> > 
> > It was. Desktop app ignore all unknown flags.
> 
> Ok. It was the "Electron-specific flag - ignore it" comment that threw me off, and seeing that the splice just removes the argument.. though I have to admit that I'm not fully understanding the code here.
> 
> Do you know a way to confirm that the HW acceleration is turned off when running Joplin with the `--disable-gpu` flag?

Well... I can see it on my screen when running any Electron app with this flag. If that's not a proof you can run the app in verbose mode. With `--disable-gpu` it wont call for Vulkan lib

**Comment by Perkolator** [comment]
> I can see it on my screen when running any Electron app with this flag.

??? Where in the Joplin app you can see a status/information that the gpu/hw acceleration is disabled? In a similar way that Chrome `chrome://gpu` page shows it?

> If that's not a proof you can run the app in verbose mode.

And how does one do that? I tried `--debug --log-level debug` from terminal but it spits out a warning and Joplin doesn't even start:

```
electron: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
```

And if adding those in `flags.txt`, Joplin starts but I can't see any gpu/hw acceleration stuff in the log.

**Comment by orl0** [comment]
> ??? Where in the Joplin app you can see a status/information that the gpu/hw acceleration is disabled? In a similar way that Chrome `chrome://gpu` page shows it?

IDK. I mean can see glitches in Electron apps with a naked eye. It's caused by bad support for my old intel gpu in Vulkan lib. I've found out that by debuging some apps including Joplin. Flag `--disable-gpu` works for me and fixes all the glitches in any Electron app. Without the flag I had some Vulkan errors in verbose mode and no Vulkan messages with the flag.

> And how does one do that?

I don't remember the exact flag. But the log was quite clear. I've fixed my problem and removed all debug information. I assure you `--disable-gpu` does what it should do. If it's so necessary I could try to repeat the process in a few days.

**Comment by Perkolator** [comment]
> I mean can see glitches in Electron apps with a naked eye.

Ok. My HW acc. problems with Nvidia (after sleep/hibernate GUI might freeze for some seconds, or sometimes longer) are not that severe as yours are. I just wanted to confirm that it really works, I'm like that, I like to confirm things, and like I wrote already, the code changes/comments sow a seed of doubt. :) Thanks for assuring me.

**Comment by orl0** [comment]
> > I mean can see glitches in Electron apps with a naked eye.
> 
> Ok. My HW acc. problems with Nvidia (after sleep/hibernate GUI might freeze for some seconds, or sometimes longer) are not that severe as yours are. I just wanted to confirm that it really works, I'm like that, I like to confirm things, and like I wrote already, the code changes/comments sow a seed of doubt. :) Thanks for assuring me.

np m8 :)

Btw I forgot to mention that I found another way to "fix" my problem. Idk if it works on Windows, but on Linux I just unpacked AppImage and deleted `libvilkan.so.1`

**Comment by Perkolator** [comment]
> Idk if it works on Windows, but on Linux I just unpacked AppImage and deleted `libvilkan.so.1`

I'm also on Linux but I'm not ready to "apply a knife to the app" if the disable flag works.. thanks for offering an alternative way though. :)

**Comment by Perkolator** [comment]
@orl0, hey, I'm again having GUI freezes and again wonder if the flag is really working or not. I have `--disable-gpu --open-dev-tools` in my `flags.txt` and at least the dev-tools is opened when Joplin is started but is the gpu disable flag working when added to `flags.txt`?

I wish there would be a way to see that HW acc. is actually disabled.

**Comment by orl0** [comment]
@Perkolator ok, so I just tried to lunch the app with and without the flag

Without the flag I have insane amount of errors in log like:
<details><summary>Log</summary><pre>
[12356:1227/140021.784090:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in half4 color;flat out half4 vcolor_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
flat in half4 vcolor_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in mediump vec4 color;
flat out mediump vec4 vcolor_S0;
void main() {
    vcolor_S0 = color;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
flat in mediump vec4 vcolor_S0;
void main() {
    mediump vec4 outputColor_S0;
    outputColor_S0 = vcolor_S0;
    {
        sk_FragColor = outputColor_S0;
    }
}

Errors:
link failed but did not provide an info log
[12356:1227/140021.788636:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
</pre></details>

And most part of the app is not visible
<details><summary>Screenshot</summary></details>

With the flag app works as expected.

**Comment by Perkolator** [comment]
> so I just tried to lunch the app with and without the flag

And you have the `--disable-gpu` in the `flags.txt` file only and the app works for you then? (that's what I tried to ask)

**Comment by orl0** [comment]
> > so I just tried to lunch the app with and without the flag
> 
> And you have the `--disable-gpu` in the `flags.txt` file only and the app works for you then? (that's what I tried to ask)

No I don't. I pass the flag in CLI like `cd packages/app-desktop/dist/linux-unpacked/ && ./@joplinapp-desktop --disable-gpu`.

Actually I use the version I forked than patched and build myself.

**Comment by Perkolator** [comment]
> No I don't.

Could I ask you to try to use the flag ONLY in the `flags.txt` and see if it works? I wouldn't ask otherwise but your problems with HW acc. enabled is a sure way to detect if HW acc. is disabled or not (and hopefully your own build is not that different from the stock version and affecting this). Many thanks.

**Comment by orl0** [comment]
> Could I ask you to try to use the flag ONLY in the `flags.txt` and see if it works? I wouldn't ask otherwise but your problems with HW acc. enabled is a sure way to detect if HW acc. is disabled or not (and hopefully your own build is not that different from the stock version and affecting this). Many thanks.

I don't know what `flags.txt` actually is... Just tried to google `electron flags.txt file` with no results. Is there some documentation or something?

**Comment by Perkolator** [comment]
Oh, ok. It's a Joplin specific file, not Electron. [Here it is documented](https://joplinapp.org/help/apps/debugging/) (dunno if that's outdated information though because... ***). Anyhoo, you create the `flags.txt` file in `~/.config/joplin-desktop` folder and then just add the flag(s) in it and save.


*** If I run `Joplin.AppImage --open-dev-tools --debug --log-level debug %u` from CLI, Joplin doesn't start and I get this error:

```
electron: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
```
BUT, if the `--open-dev-tools --debug --log-level debug` is in the `flags.txt` file, Joplin starts fine, so it seems that Joplin parses the flags differently from `flags.txt` file and from CLI.


I know from my own setup that at least `--open-dev-tools` flag works from the `flags.txt` file. I guess the `--disable-gpu` should too but since I'm seeing some GUI freezes again, I started to wonder if it really works.

EDIT: I'm not editing the `~/.local/share/applications/appimagekit-joplin.desktop` file to have the `--disable-gpu` flag in the `Exec` command because I think that Joplin rewrites/recreates that file every time the official "wget" update method is used.. at least the file created/modified datetimes seems to indicate this.

EDIT2: I just wish somebody, who is able to code it, would create this feature as a setting in Joplin... if I remember right, this has been wished here in this repo for years.

**Comment by orl0** [comment]
@Perkolator well, I just tried to run with `flags.txt` and it works quite well.

Except it didn't work on my old version. But this was fixed.

If you are not using latest version consider following:

```sh
cd ~/.joplin
curl -LO 'https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh'
bash Joplin_install_and_update.sh --prerelease --changelog
```

**Comment by Perkolator** [comment]
> Except it didn't work on my old version. But this was fixed.

Umm, what "old version" do you mean? You also suggest to update Joplin with the newest prerelease, but in the Joplin repo, the last version is 2.13.11 which is a stable release. I already have that installed. I update to stable releases as soon as they are released.

**Comment by orl0** [comment]
> > Except it didn't work on my old version. But this was fixed.
> 
> Umm, what "old version" do you mean? You also suggest to update Joplin with the newest prerelease, but in the Joplin repo, the last version is 2.13.11 which is a stable release. I already have that installed. I update to stable releases as soon as they are released.

I didn't update since I patched 2.13.2. Have no idea if it works in stable, try prerelease it should work.

**Comment by Perkolator** [comment]
> try prerelease it should work.

I'm telling you that the last version is 2.13.11, which is a stable. There is no newer prereleases than that stable version. I don't want to use prereleases since I don't have time to test them. Anyhoo, thanks for taking the time to test. I need to think what to do now since the random GUI freezes continue, I'll have to test using the flags in the Desktop Entry exec command (which then means that I can't use the Joplin update script because the script re-writes the Desktop Entry file when it updates Joplin AppImage).. it's just so hard to test because the GUI freezes after sleep/hibernate don't happen every time.

Happy holidays.

**Comment by virotti** [comment]
> --disable-gpu

Thanks @Perkolator for your solution. I was having horrible glitches and even tried disabling GPU acceleration for my whole computer. So I've found your solution and I've just confirmed that adding _--disable-gpu_ to a .txt file named flags.txt inside the JOPLIN .config folder works using the latest Joplin version (3.0.14). 

**Note:** The full path to find the place where you need to create the file in Windows 11 is C:\Users\replace-with-your-user-name\.config\joplin-desktop

**Pull request merged**
