### PR TITLE
WYSIWYG

### PR DESCRIPTION
**Pull request by laurent22**
WYSIWYG in desktop app using TinyMCE, for evaluation purpose only at the moment.

The pull request also includes a refactor of the "NoteText" component, with improved handling of state, which should solve some of the issues with saving and loading notes that have been around for a while. It will also make it easier to switch to a different code editor (instead of Ace Editor) by more clearly defining the interface that an editor must support.

Still to do for WYSIWYG in particular:

- [x] Handle checkboxes
- [x] Handle images upload
- [x] Handle code blocks
- [x] Handle when note updated via sync, or via API

Big issue that maybe has no solution: most Markdown plugins are not supported and most likely any special plugin-specific formatting will be lost when editing a note with the WYSIWYG editor. The exception is fence-delimited Markdown plugins like Mermaid, Fountain or Katex, which are handled separately.

### CODE REVIEW

**Comment by tessus** [comment]
Is this the editor @devonzuegel [mentioned](https://discourse.joplinapp.org/t/wysiwyg-editor-in-joplin/2253/18?u=tessus) a while back?

**Comment by tessus** [comment]
Ok, it's not. I just checked the code.... Sorry for the noise.

**Comment by laurent22** [comment]
I've picked TinyMCE because it's been around forever, so it's stable, has good doc, and you can find answers to questions on SO, forums, etc. because it's widely used. It's also easy to extend, which is important for us.

All other editors I've tried are almost in alpha state. They often look good in demos but when you look closely, there are often big issues, like poor API, difficult to extend, poor quality doc and non existent support.

**Comment by geeksaurav** [comment]
@laurent22 Idk very much, but i worked on kind of similar thing with Vue.
I used QuillJS and TipTap, both were actually very capable and stable.
You checked them too?

**Comment by laurent22** [comment]
I'm not familiar with these, it's possible they would work well too

**Comment by geeksaurav** [comment]
I'd suggest you go ahead and check [QuillJS](https://quilljs.com/)...
It's actually used by major companies, and uses delta type instead of md!

**Comment by geeksaurav** [comment]
And as I've worked with them in VueJS. I'd love to a part of Joplin in this summer under GSoC.
And once again thanks for Joplin, I've already started using it. Was much needed.

**Comment by laurent22** [comment]
Quill indeed could be an option though it would need to be reviewed to see if it can support what we need, but anyway for now TinyMCE has all we need.

**Comment by laurent22** [comment]
I think it's good enough for basic note editing at this point, so I'm going to merge so that it can be evaluated.

Remaining work to do on it will be listed there: https://github.com/laurent22/joplin/issues/2710

**Pull request merged**
