### PR TITLE
Desktop: Make sidebar resizable when note list is not displayed

### LINKED ISSUE #2865: Side bar not resizable when "Toggle Note list" is not selected (edited)
## DESCRIPTION ##  

**The Side Bar is not draggable in desktop when "Toggle Note List" is not selected**

## Environment

Joplin version: Joplin 1.0.195 (prod, darwin)
Platform: Desktop 
OS specifics: macOS MOJAVE 10.14 , Win10 Pro x64 ,  Linux Mint 19.3 x64

**EDIT**
Actually the issue of not being able to resize the sidebar appears specifically when the "Toggle Note List" is not selected.

## Steps to reproduce (edited)

1. Open Joplin desktop app.
2. Create a few Notebooks
3. Make sure "Toggle Note List" is turned off.
4. Try resizing the sidebar.

## Describe what you expected to happen

1. The sidebar should be resizable on drag even when "Toggle Note List" is not selected.

### PR DESCRIPTION
**Pull request by anihm136**
Fixes #2865

Separated the styles for vertical resizers next to the sidebar and note list, and linked their visibility to the respective component.
 
Preview:
ezgif com-optimize

### CODE REVIEW

**Comment by anihm136** [comment]
@PackElend please label me for GSoC

**Comment by laurent22** [comment]
@anihm136, this pull request is relatively close to completion but there's a conflict. Would you be able to fix it?

**Comment by anihm136** [comment]
Sure, I'll sort it out by tomorrow.

**Comment by laurent22** [comment]
@anihm136, I've fixed the conflict now, so we can merge. Thanks for the pull request.

**Pull request merged**
