### PR TITLE
Desktop: Add Notebook Icons

### PR DESCRIPTION
**Pull request by rabeehrz**
Related to issue #2268 

This PR introduces the following changes:

- Remove the Rename dialog and adds the Properties dialog for notebooks
- Add icons for different notebooks which is customizable in the Properties dialog

[](https://gifyu.com/image/I26f)

Part of the credit goes to @bedwardly-down 
His PRs #2427 and #2450 helped me a lot. The conversation between him and Laurent cleared a lot of doubts for me and I was able to implement this.

### CODE REVIEW

**Comment by rabeehrz** [comment]
@PackElend label me please.

**Comment by bedwardly-down** [comment]
Holy hell, man. Good deal. I'm glad I was of help and hope that this gets accepted. Definitely looks amazing in the gif. 🥰

**Comment by rabeehrz** [comment]
> Holy hell, man. Good deal. I'm glad I was of help and hope that this gets accepted. Definitely looks amazing in the gif. 🥰

Hehehe. I'm trying to solve these conflicts right now. Build won't pass unless I solve them.

**Comment by tessus** [comment]
As the CONTRIBUTING.md states: _Coding style is enforced by a pre-commit hook that runs eslint. This hook is installed whenever running npm install on any of the application directory. If for some reason the pre-commit hook didn't get installed, you can manually install it by running npm install at the root of the repository._

Please install the pre-commit hook. This should have fixed all your linter issues, since it still fails.

**Comment by bedwardly-down** [comment]
If you have a linter enabled in your editor or dev tools, I've found that eslint doesn't always seem to fix it, so please check that you have all of them disabled. That was my second biggest frustration here, @rabeehrz

**Comment by bedwardly-down** [comment]
> If you have a linter enabled in your editor or dev tools, I've found that eslint doesn't always seem to fix the linting issues, so please check that you have all of them disabled. That was my second biggest frustration here, @rabeehrz

**Comment by tessus** [comment]
Maybe I'm doing something wrong but I get a fatal error when trying to run it:

```
Fatal error:

Cannot read property 'visible' of undefined

TypeError: Cannot read property 'visible' of undefined
    at MainScreenComponent.render (/Users/tessus/data/work/joplin/ElectronClient/gui/MainScreen.min.js:645:39)
    at finishClassComponent (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:17039:31)
    at updateClassComponent (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:16994:24)
    at beginWork$1 (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:18505:16)
    at HTMLUnknownElement.callCallback (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at beginWork$$1 (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
    at performUnitOfWork (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:22208:12)
    at workLoopSync (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:22185:22)
```

**Comment by tessus** [comment]
Also, it seems that a default icon is added when a folder is created. Please remove that.

Now I have to manually remove the icon every time I create a folder.

**Comment by rabeehrz** [comment]
> Maybe I'm doing something wrong but I get a fatal error when trying to run it:
> 
> ```
> Fatal error:
> 
> Cannot read property 'visible' of undefined
> 
> TypeError: Cannot read property 'visible' of undefined
>     at MainScreenComponent.render (/Users/tessus/data/work/joplin/ElectronClient/gui/MainScreen.min.js:645:39)
>     at finishClassComponent (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:17039:31)
>     at updateClassComponent (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:16994:24)
>     at beginWork$1 (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:18505:16)
>     at HTMLUnknownElement.callCallback (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:347:14)
>     at Object.invokeGuardedCallbackDev (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:397:16)
>     at invokeGuardedCallback (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:454:31)
>     at beginWork$$1 (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
>     at performUnitOfWork (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:22208:12)
>     at workLoopSync (/Users/tessus/data/work/joplin/ElectronClient/node_modules/react-dom/cjs/react-dom.development.js:22185:22)
> ```

Hey. This happened while I was trying to solve the Merge conflicts. There has been modifications to the MainScreen.jsx file in the master branch. That was introducing Merge conflicts. 

Could you checkout `54cab2fde06e0e16a889395a836952b95930d506` and try to run it?

**Comment by rabeehrz** [comment]
> Also, it seems that a default icon is added when a folder is created. Please remove that.
> 
> Now I have to manually remove the icon every time I create a folder.

Okay. I'll remove it. I thought it was supposed to be like that.

**Comment by tessus** [comment]
> Could you checkout 54cab2fde06e0e16a889395a836952b95930d506 and try to run it?

Yes, this works.

> Okay. I'll remove it. I thought it was supposed to be like that.

The problem is that people might not want a default icon. e.g. I don't. This should be a feature for people, who want to set icons for folders. The current behavior forces this onto people.
If there were a setting in `Preferences` to choose a default icon (which could also be empty), it would be ok. But just using an icon from now on is not ok.
I'm not saying you should create a setting, since I don't know, if Laurent even wants an additional option. But this can be done with a follow-up PR anyway. Please just remove the default for now.

**Comment by rabeehrz** [comment]
> > Could you checkout [54cab2f](https://github.com/laurent22/joplin/commit/54cab2fde06e0e16a889395a836952b95930d506) and try to run it?
> 
> Yes, this works.
> 
> > Okay. I'll remove it. I thought it was supposed to be like that.
> 
> The problem is that people might not want a default icon. e.g. I don't. This should be a feature for people, who want to set icons for folders. The current behavior forces this onto people.
> If there were a setting in `Preferences` to choose a default icon (which could also be empty), it would be ok. But just using an icon from now on is not ok.
> I'm not saying you should create a setting, since I don't know, if Laurent even wants an additional option. But this can be done with a follow-up PR anyway. Please just remove the default for now.

Yep. I've removed it. But there is the issue of merge conflict. How do you want me to fix this?
Do you want me to keep resolving the merge conflict as I go? Or is it okay if I solve the conflicts at the end?

**Comment by tessus** [comment]
> But there is the issue of merge conflict. How do you want me to fix this?
Do you want me to keep resolving the merge conflict as I go? Or is it okay if I solve the conflicts at the end?

I'm not sure I understand. The conflicts have to be solved before the PR gets merged. It's your choice when you do it. IMO it's easier to solve them right away. That's what I do.

**Comment by laurent22** [comment]
There's a lot of copy-and-pasted code in there - all the styles, logic for the buttons and controls, etc. all come from NotePropertiesDialog.

I get the feeling that we shouldn't accept any dialog-related PR at this point, it's just more and more copy and pasted code every time, because we don't have a framework to create and manage dialogs.

**Comment by tessus** [comment]
Unfortunately this still doesn't work. Something is wrong with the merge/rebase.

**Comment by laurent22** [comment]
Also we have this text in the GSoC introduction:

> First of all, please read CONTRIBUTING.md and BUILD.md as they contain **very important information about the project** and how to contribute.

If you have read it you would have found this in CONTRIBUTING.md:

> For new React components, please use [React Hooks](https://reactjs.org/docs/hooks-intro.html). For new code in general, please use TypeScript (unless you are modifying a file that was originally in JavaScript).

Your code neither use React Hooks nor TypeScript.

**Comment by laurent22** [comment]
Closing as there are too many issues and fixing them would require a new pull request.

**Comment by rabeehrz** [comment]
> Also we have this text in the GSoC introduction:
> 
> > First of all, please read CONTRIBUTING.md and BUILD.md as they contain **very important information about the project** and how to contribute.
> 
> If you have read it you would have found this in CONTRIBUTING.md:
> 
> > For new React components, please use [React Hooks](https://reactjs.org/docs/hooks-intro.html). For new code in general, please use TypeScript (unless you are modifying a file that was originally in JavaScript).
> 
> Your code neither use React Hooks nor TypeScript.



> Also we have this text in the GSoC introduction:
> 
> > First of all, please read CONTRIBUTING.md and BUILD.md as they contain **very important information about the project** and how to contribute.
> 
> If you have read it you would have found this in CONTRIBUTING.md:
> 
> > For new React components, please use [React Hooks](https://reactjs.org/docs/hooks-intro.html). For new code in general, please use TypeScript (unless you are modifying a file that was originally in JavaScript).
> 
> Your code neither use React Hooks nor TypeScript.

I'm really sorry. I didn't notice this part. I will make a new PR with all the issues fixed.



> There's a lot of copy-and-pasted code in there - all the styles, logic for the buttons and controls, etc. all come from NotePropertiesDialog.
> 
> I get the feeling that we shouldn't accept any dialog-related PR at this point, it's just more and more copy and pasted code every time, because we don't have a framework to create and manage dialogs.

I did that to make it consistent with the Note Properties dialog. I thought that was the way dialogs was handled generally.



> Unfortunately this still doesn't work. Something is wrong with the merge/rebase.

Resolving Merge Conflicts breaks it. I'll open up a new PR :)

**Comment by laurent22** [comment]
Thanks for your understanding but I think we should leave this pull request aside, due to the lack of a proper dialog framework in Joplin. Or if you decide to go ahead, you'll have a pretty big refactoring to do (basically to make sure you can re-use the code from NotePropertiesDialog without copying and pasting it), which I don't think should be done as a first issue.

**Comment by rabeehrz** [comment]
Sure. I’ll pick up another issue and work towards it. 😄

**Comment by bedwardly-down** [comment]
@rabeehrz started after asking me if he could continue my work, @laurent22 . I coached him a tiny bit into starting without giving him the core details or passing aong that final bit of information since he had read the original back and forth between us.

**Comment by laurent22** [comment]
Yes I see what you mean. This is mostly my fault because this is miscategorised with Good first issue label (now removed), while it's in fact rather complex, and now I see it would even require a refactoring of some components.

**Comment by bedwardly-down** [comment]
Is there anyway to archive this whole thing and label it a mass learning experience for all involved? In hindsight, it was a Great First Issue in the sense that it wasn't a complete failure or loss.

**Comment by bedwardly-down** [comment]
Or better yet, label it as "Great First Failure"? 😂

**Comment by laurent22** [comment]
Tessus already labelled the original one as "PR-abandonned", which for us means the PR has potential and can be picked up later as a starting point. Once the dialog stuff is in place, I think it's indeed possible to resume from your work.

**Comment by kowalskidev** [comment]
> 
> 
> There's a lot of copy-and-pasted code in there - all the styles, logic for the buttons and controls, etc. all come from NotePropertiesDialog.

I would like to work on this issue. I checked this PR and I seen that we have already three dialog files created so I think @rabeehrz had the only option to create another dialog file just like three of them In-fact anyone would do the same but now as you are saying that:
>
> I get the feeling that we shouldn't accept any dialog-related PR at this point, it's just more and more copy and pasted code every time, because we don't have a framework to create and manage dialogs.

So it seems like lot of code refactoring will be needed to reduce the code, should I make one universal dialog view file which can be used for all property related dialogs ? so we just need to pass necessary props and it will show dialog accordingly.

**Comment by PackElend** [comment]
> should I make one universal dialog view file which can be used for all property related dialogs ?

if possible it would be greater the less code / more reusable code the better

**Comment by kowalskidev** [comment]
Sure. Should I start working now or I need to wait for Laurent's approval?

**Comment by rabeehrz** [comment]
> Sure. Should I start working now or I need to wait for Laurent's approval?

@kowalskidev I was planning to open up a new Topic on the forums to discuss the implementation of the new Dialog Framework. I think it would be better if you did so as a lot of people will have great ideas regarding the same. I think that would be the best way to proceed.

**Comment by kowalskidev** [comment]
Thanks @rabeehrz for your suggestions. You are right! I should open a new topic on forum for the same, I will open up soon...

**Comment by PackElend** [comment]
> I will open up soon...

don't forget to reference it here

**Comment by kowalskidev** [comment]
Yea Sure

**Comment by laurent22** [comment]
We aren't going to add that many new features at this point. There's still 53 pull requests to review and merge, and 139 bugs to fix. If you want to improve the project, bug fixing is where efforts should go.

**Comment by kowalskidev** [comment]
Okay fine..I will look into potential bugs to work on...

**Pull request closed without merging**
