### PR TITLE
Desktop, Mobile: update Katex to 0.11.1

### PR DESCRIPTION
**Pull request by tessus**
see https://discourse.joplinapp.org/t/katex-text-textasciicircum-does-not-work/4750?u=tessus

### CODE REVIEW

**Comment by laurent22** [comment]
When updating or adding a dependency in package.json, you need to run `npm i` so as to update package-lock.json, which you can then add to the commit.

Otherwise package-lock.json will be updated later in an unrelated commit, which can be confusing (I know I just "git checkout package-lock.json" if it's changed and I haven't modified package.json).

**Comment by tessus** [comment]
Ha, ok. I remember you told me never to commit the lock files thus I didn't. ;-)

I'll do this in a sec.

**Comment by laurent22** [comment]
> Ha, ok. I remember you told me never to commit the lock files thus I didn't. ;-)

Yes, to be clear, package-lock.json shouldn't be committed on its own but if a dependency is changed in package.json, both files should be committed together.

**Comment by tessus** [comment]
Thanks, I'll remember that. I've added the lock files.

**Comment by laurent22** [comment]
When upgrading Katex, let's check the [changelog](https://github.com/KaTeX/KaTeX/blob/master/CHANGELOG.md) from now on and in particular the breaking changes. `\href` support in particular was broken after the update due to a config parameter they've added.

**Comment by tessus** [comment]
@laurent22 good idea. I used a Katex note to test with, but I guess it didn't include all Katex items.

**Pull request merged**
