### PR TITLE
 Mobile: Fixes #3601: Fix uploading resource files to S3 with RN

### LINKED ISSUE #3601: Android S3 sync Error: Raw buffer output not supported for FsDriverRN.readFile
Android sync error "Raw buffer output not supported for FsDriverRN.readFile" occurs when attempting to synchronize notes with Mac using the S3 (beta) configuration. Android and Mac are confirmed able to access S3 bucket. Android is able to write notes to S3 and Mac will see changes, but Android is not able to receive any changes from S3. Unknown if other Android sync configurations cause this issue.

## Environment

Joplin version: Android version 1.0.336, Mac version 1.0.233
Platform: Android (primarily) and Mac
OS specifics: Android 10 (security patch level Jul 5, 2020), Mac OS Catalina 10.15.6

## Steps to reproduce

1. Set up S3 sync from Mac
2. Synchronize notes from Mac
3. Set up S3 sync from Android
4. Attempt to synchronize notes from Android, receive error
5. Synchronize notes on Mac - view Android notes uploaded. Android is able to write notes to S3, but not read to create/update due to this error.

## Describe what you expected to happen

Android syncs notes in S3 configuration.

## Logfile

```
Date,Level,Message
08-05T16:23:24,30,"""RevisionService::maintenance: Done in 132ms""
08-05T16:23:24,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
08-05T16:23:24,30,"""RevisionService::maintenance: Service is enabled""
08-05T16:23:24,30,"""RevisionService::maintenance: Starting...""
08-05T16:22:53,30,"""DecryptionWorker: cannot start because no master key is currently loaded.""
08-05T16:22:52,30,"""RevisionService::maintenance: Done in 226ms""
08-05T16:22:52,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
08-05T16:22:52,30,"""Settings have been saved.""
08-05T16:22:52,30,"""Saving settings...""
08-05T16:22:52,20,"""Error: Raw buffer output not supported for FsDriverRN.readFile
value@index.android.bundle:1012:3321
index.android.bundle:1422:1911
p@index.android.bundle:112:423
index.android.bundle:112:1740
p@index.android.bundle:112:423
n@index.android.bundle:112:898
index.android.bundle:112:1273
c@index.android.bundle:108:205
b@index.android.bundle:108:1623
_@index.android.bundle:108:488
u@index.android.bundle:112:1257
_invoke@index.android.bundle:112:1309
async@index.android.bundle:112:3681
index.android.bundle:1422:6218
p@index.android.bundle:112:423
index.android.bundle:112:1740
p@index.android.bundle:112:423
n@index.android.bundle:112:898
index.android.bundle:112:1273
c@index.android.bundle:108:205
b@index.android.bundle:108:1623
_@index.android.bundle:108:488
u@index.android.bundle:112:1257
_invoke@index.android.bundle:112:1309
async@index.android.bundle:112:3681
index.android.bundle:1346:374
p@index.android.bundle:112:423
index.android.bundle:112:1740
p@index.android.bundle:112:423
n@index.android.bundle:112:898
index.android.bundle:112:1047
f@index.android.bundle:108:155
index.android.bundle:108:882
y@index.android.bundle:114:661
C@index.android.bundle:114:1025
callImmediates@index.android.bundle:114:3100
callImmediates@[native code]
value@index.android.bundle:26:3247
index.android.bundle:26:1283
value@index.android.bundle:26:2939
value@index.android.bundle:26:1253
value@[native code]
value@[native code]""
08-05T16:22:52,20,"""There was some errors:""
08-05T16:22:52,30,"""Total folders: 1""
08-05T16:22:52,30,"""Total notes: 5""
08-05T16:22:52,30,"""Total resources: 3""
08-05T16:22:52,30,"""createRemote: 7""
08-05T16:22:52,30,"""Operations completed: ""
08-05T16:22:52,30,"""RevisionService::maintenance: Starting...""
08-05T16:22:52,30,"""RevisionService::maintenance: Service is enabled""
08-05T16:22:52,10,"""Error: Raw buffer output not supported for FsDriverRN.readFile
value@index.android.bundle:1012:3321
index.android.bundle:1422:1911
p@index.android.bundle:112:423
index.android.bundle:112:1740
p@index.android.bundle:112:423
n@index.android.bundle:112:898
index.android.bundle:112:1273
c@index.android.bundle:108:205
b@index.android.bundle:108:1623
_@index.android.bundle:108:488
u@index.android.bundle:112:1257
_invoke@index.android.bundle:112:1309
async@index.android.bundle:112:3681
index.android.bundle:1422:6218
p@index.android.bundle:112:423
index.android.bundle:112:1740
p@index.android.bundle:112:423
n@index.android.bundle:112:898
index.android.bundle:112:1273
c@index.android.bundle:108:205
b@index.android.bundle:108:1623
_@index.android.bundle:108:488
u@index.android.bundle:112:1257
_invoke@index.android.bundle:112:1309
async@index.android.bundle:112:3681
index.android.bundle:1346:374
p@index.android.bundle:112:423
index.android.bundle:112:1740
p@index.android.bundle:112:423
n@index.android.bundle:112:898
index.android.bundle:112:1047
f@index.android.bundle:108:155
index.android.bundle:108:882
y@index.android.bundle:114:661
C@index.android.bundle:114:1025
callImmediates@index.android.bundle:114:3100
callImmediates@[native code]
value@index.android.bundle:26:3247
index.android.bundle:26:1283
value@index.android.bundle:26:2939
value@index.android.bundle:26:1253
value@[native code]
value@[native code]""
08-05T16:22:28,30,"""Starting scheduled sync""
08-05T16:22:28,30,"""Preparing scheduled sync""
08-05T16:22:15,30,"""RevisionService::maintenance: Done in 225ms""
08-05T16:22:15,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
08-05T16:22:15,30,"""Settings have been saved.""
08-05T16:22:15,30,"""Saving settings...""
08-05T16:22:15,30,"""RevisionService::maintenance: Service is enabled""
08-05T16:22:15,30,"""RevisionService::maintenance: Starting...""
08-05T16:21:44,30,"""ResourceService::deleteOrphanResources:", "[]""
08-05T16:21:44,30,"""ResourceService::indexNoteResources: Completed""
08-05T16:21:44,30,"""Settings have been saved.""
08-05T16:21:44,30,"""Saving settings...""
08-05T16:21:44,30,"""RevisionService::maintenance: Done in 126ms""
08-05T16:21:44,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
08-05T16:21:44,30,"""ResourceService::indexNoteResources: Start""
08-05T16:21:44,30,"""RevisionService::maintenance: Service is enabled""
08-05T16:21:44,30,"""RevisionService::maintenance: Starting...""
08-05T16:21:20,30,"""Settings have been saved.""
08-05T16:21:20,30,"""Saving settings...""
08-05T16:21:19,30,"""SearchEngine: Updating FTS table...""
08-05T16:21:15,30,"""Settings have been saved.""
08-05T16:21:15,30,"""Saving settings...""
08-05T16:21:14,30,"""Synchroniser is missing credentials - manual sync required to authenticate.""
08-05T16:21:14,30,"""Saving updated Dropbox auth.""
08-05T16:21:14,30,"""Preparing scheduled sync""
08-05T16:21:14,30,"""RevisionService::maintenance: Done in 348ms""
08-05T16:21:14,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
08-05T16:21:14,30,"""Settings have been saved.""
08-05T16:21:14,30,"""Saving settings...""
08-05T16:21:13,30,"""RevisionService::maintenance: Starting...""
08-05T16:21:13,30,"""RevisionService::maintenance: Service is enabled""
08-05T16:21:10,30,"""Settings have been saved.""
08-05T16:21:10,30,"""Saving settings...""
08-05T16:21:10,30,"""DecryptionWorker: cannot start because no master key is currently loaded.""
08-05T16:21:09,30,"""RevisionService::runInBackground: Starting background service with revision collection interval 30000""
08-05T16:21:09,30,"""Application initialized""
08-05T16:21:09,30,"""Running migration: 27""
08-05T16:21:09,30,"""ResourceFetcher: Auto-added resources: 0""
08-05T16:21:09,30,"""Running migration: 20""
08-05T16:21:09,30,"""ResourceFetcher: Auto-add resources: Mode: always""
08-05T16:21:09,30,"""Loading folders...""
08-05T16:21:09,30,"""Loaded master keys: 0""
08-05T16:21:09,30,"""Trying to load 0 master keys...""
08-05T16:21:09,30,"""Sync target: 7""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: mermaid/mermaid_render.js => /data/user/0/net.cozic.joplin/files/pluginAssets/mermaid/mermaid_render.js""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: mermaid/mermaid.min.js => /data/user/0/net.cozic.joplin/files/pluginAssets/mermaid/mermaid.min.js""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/katex.css => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/katex.css""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Typewriter-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Typewriter-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Size4-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Size4-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Size3-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Size3-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Size2-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Size2-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Size1-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Size1-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Script-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Script-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_SansSerif-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_SansSerif-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_SansSerif-Italic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_SansSerif-Italic.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_SansSerif-Bold.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_SansSerif-Bold.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Math-Italic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Math-Italic.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Math-BoldItalic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Math-BoldItalic.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Main-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Main-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Main-Italic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Main-Italic.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Main-BoldItalic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Main-BoldItalic.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Main-Bold.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Main-Bold.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Fraktur-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Fraktur-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Fraktur-Bold.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Fraktur-Bold.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Caligraphic-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Caligraphic-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Caligraphic-Bold.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Caligraphic-Bold.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_AMS-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_AMS-Regular.woff2""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: highlight.js/atom-one-light.css => /data/user/0/net.cozic.joplin/files/pluginAssets/highlight.js/atom-one-light.css""
08-05T16:21:09,30,"""PluginAssetsLoader: Copying: highlight.js/atom-one-dark-reasonable.css => /data/user/0/net.cozic.joplin/files/pluginAssets/highlight.js/atom-one-dark-reasonable.css""
08-05T16:21:09,30,"""PluginAssetsLoader: Importing assets to /data/user/0/net.cozic.joplin/files/pluginAssets""
08-05T16:21:09,30,"""db.ftsEnabled = ", "1""
08-05T16:21:09,30,"""FTS check succeeded""
08-05T16:21:09,30,"""KeychainService: could not set test password - keychain support will be disabled""
08-05T16:21:09,30,"""KeychainService: checking if keychain supported""
08-05T16:21:09,30,"""Loading settings...""
08-05T16:21:09,30,"""Database is ready.""
08-05T16:21:08,30,"""Initializing tables...""
08-05T16:21:08,30,"""Converting database to version 32""
08-05T16:21:08,30,"""Converting database to version 31""
08-05T16:21:08,30,"""Converting database to version 30""
08-05T16:21:08,30,"""Converting database to version 29""
08-05T16:21:08,30,"""Converting database to version 28""
08-05T16:21:08,30,"""Converting database to version 27""
08-05T16:21:08,30,"""Converting database to version 26""
08-05T16:21:08,30,"""Converting database to version 25""
08-05T16:21:08,30,"""Converting database to version 24""
08-05T16:21:08,30,"""Converting database to version 23""
08-05T16:21:08,30,"""Converting database to version 22""
08-05T16:21:08,30,"""Converting database to version 21""
08-05T16:21:07,30,"""Converting database to version 20""
08-05T16:21:07,30,"""Converting database to version 19""
08-05T16:21:07,30,"""Converting database to version 18""
08-05T16:21:07,30,"""Converting database to version 17""
08-05T16:21:07,30,"""Converting database to version 16""
08-05T16:21:07,30,"""Converting database to version 15""
08-05T16:21:07,30,"""Converting database to version 14""
08-05T16:21:07,30,"""Converting database to version 13""
08-05T16:21:07,30,"""Converting database to version 12""
08-05T16:21:07,30,"""Converting database to version 11""
08-05T16:21:07,30,"""Converting database to version 10""
08-05T16:21:07,30,"""Converting database to version 9""
08-05T16:21:07,30,"""Converting database to version 8""
08-05T16:21:07,30,"""Converting database to version 7""
08-05T16:21:07,30,"""Converting database to version 6""
08-05T16:21:07,30,"""Converting database to version 5""
08-05T16:21:07,30,"""Converting database to version 4""
08-05T16:21:07,30,"""Converting database to version 3""
08-05T16:21:07,30,"""Converting database to version 2""
08-05T16:21:06,30,"""Converting database to version 1""
08-05T16:21:06,30,"""Current database version", "0""
08-05T16:21:06,30,"""Checking for database schema update...""
08-05T16:21:06,30,"""Database was open successfully""
08-05T16:21:06,30,"""Starting application net.cozic.joplin-mobile (prod)""
08-05T16:21:06,30,"""====================================""
================================================================================
type,id,updated_time,sync_time,is_conflict
1,1eb5f625d1b6475ca141d3051ecfb741,1596658869740,1596658869740,
1,36464c7dc60f41898675a513a2801469,1596658869634,1596658869634,
1,3d587cbc7590471cbc457fd1553b4b7a,1596658869589,1596658869589,
1,fed12795cf0a41ea90fe175bfd3ef61f,1596658869549,1596658869549,
1,fbb0de4126f34d59b078b28c1554b36b,1596658869479,1596658869479,
2,7151ced5bab0479db5c8b6fca09e59b9,1596658869468,1596658869468,
```

### PR DESCRIPTION
**Pull request by jblunck**
When the mobile application tries to synchronize a note with attached
resource files, e.g. from the notebook "Welcome! (Mobile)", readFile()
is called to return a Buffer although that isn't implemented in
FsDriverRN.readFile(). This is changing the code to return base64
encoded content from react-native and turn it into a Buffer before the S3
putObject() API call is used to create the remote object.

Tested with AVD Android 10.0 target.

### CODE REVIEW

**Comment by jblunck** [comment]
@laurent22 Any feedback on this pull request?

**Comment by laurent22** [comment]
Any information about this pull request? How did you test? What change did you make? I know nothing about S3 sync so it would be good to provide some info.

**Comment by jblunck** [comment]
> Any information about this pull request? How did you test? What change did you make? I know nothing about S3 sync so it would be good to provide some info.

Sorry about that. I've updated the commit to include the analysis of the error and that I've tested it with the Android emulator.

**Comment by laurent22** [comment]
Thanks for clarifying. I've also put your description in the pull request post so that it can be seen from the link in the changelog.

**Pull request merged**
