### PR TITLE
Update links for localisation

### PR DESCRIPTION
**Pull request by vachan-maker**

### CODE REVIEW

**Comment by laurent22** [comment]
Indeed it's auto-generated

**Comment by vachan-maker** [comment]
> 
> 
> Indeed it's auto-generated

Then why do I get a 404 error when clicking on the links? 
https://github.com/laurent22/joplin/blob/dev/packages/app-cli/locales/sr_RS.po

**Comment by vachan-maker** [comment]
Oh man, I wasted my precious time on this.

**Comment by laurent22** [comment]
It's possible that the links are not correct, although to fix it, it would need to be changed in the build-translation file I think.

**Comment by johanhammar** [comment]
@laurent22 I think that should have been fixed in https://github.com/laurent22/joplin/commit/5079cd9ff2b6a8157e9c9fe7b2f81db00affeff2 but it does not seem like it have been run.

And that is also the case for https://github.com/laurent22/joplin/commit/9755a69be8241ae9f30b2f7df0b2cb21bba61968

**Pull request closed without merging**
