### PR TITLE
Added Text Formatting option in Context Menu

### PR DESCRIPTION
**Pull request by mhimanshu712**
After Edit:
rightmenu

### CODE REVIEW

**Comment by mhimanshu712** [comment]
@PackElend Please tag this!

**Comment by laurent22** [comment]
There's never been a feature request for this, so I'm not really keen to merge. I can understand it's hard to find something straightforward to work on for GSoC but we don't add features "just because" - there has to be a need for it.

**Comment by PackElend** [comment]
> There's never been a feature request for this

there is https://discourse.joplinapp.org/t/text-formatting-options-in-context-menu/6385

and I told him to do a PR as it is already coded, so no extra work for him.

But I said it shell be clone of the toolbar, now it is hard coded. I don't know if you can use the same function as both places to avoid managing the same code twice

**Comment by mhimanshu712** [comment]
@laurent22  I will create an issue on Github as well from now on.

**Comment by mhimanshu712** [comment]
Should I create an issue on Github as well for new features, from now on?

**Comment by PackElend** [comment]
> Should I create an issue on Github as well for new features, from now on?

yes please, that is the normal way, sorry, I was to quick suggesting PR straight away

Forum->GH FR->GH PR is the route

**Comment by laurent22** [comment]
To be clear, the reason is that nobody seems to need this feature (in several years, I don't remember anybody every asking for this, not even once) so that's why I'm not so keen on it. Adding features is cheap, maintenance is expensive.

**Comment by mhimanshu712** [comment]
@laurent22, In my opinion, it would make formatting much more convenient.
I understand that you want to keep it minimal, but different people have different tastes.
That's why we have so many options to do the same thing.
But in the end, it's your project!

**Comment by PackElend** [comment]
> And I don't think its maintenance would be that expensive.

if you have an idea how to put toolbar code and context menu in function so that it can be used for both it can be a compromise. More coding for you but less maintenance.

There are discussion about a plug-in approach to allow to have more functions in the toolbar. If that happens, there will be questions, why they are not available in the context menu.

**Comment by laurent22** [comment]
There's a plan to refactor the existing actions into something more modular, which would also enable editable shortcuts and, why not, formatting in context menu (even though nobody is asking for it), but till then I'd rather close this pull request.

**Comment by mhimanshu712** [comment]
Okay @laurent22  
I would like to contribute to refactoring if, it's going to be a team job.

**Comment by PackElend** [comment]
there are some discussion around plug-in/add-on/templates/style-library 
here are a few
https://discourse.joplinapp.org/t/adding-functionality-to-the-toolbar/6315/5
https://discourse.joplinapp.org/t/tasks-calendar-integration/3009/11
https://discourse.joplinapp.org/t/custom-stylesheets/384/29

it may a separate approach for each idea is necessary or some can be combined you could do some research and pull all ideas together in a central feature request  topic in the forum

**Comment by PackElend** [comment]
for the record, high level discussion here
https://discourse.joplinapp.org/t/high-level-discussion-on-plug-in-architecture-template-library/6554

**Pull request closed without merging**
