### PR TITLE
adding translate spanish Latin America

### PR DESCRIPTION
**Pull request by dbinary**
in collaboration with @Fx62

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks, there's already a translation for Spanish Costa Rica, is there a big difference with it?

**Comment by laurent22** [comment]
Yes it's been added not long ago, but it's not a full translation, so maybe we could keep yours instead.

Could you have a look at the [other translation](https://github.com/laurent22/joplin/blob/master/CliClient/locales/es_CR.po) and see if there's something you could add to yours?

**Comment by dbinary** [comment]
Ok I review the other translation.

**Comment by dbinary** [comment]
is basically the same but my translation is complete. Use what works best for you

**Comment by laurent22** [comment]
What country in Latin America should I put? Normally the format is <language>_<country_code>. For example "en_GB".

**Pull request merged**
