### PR TITLE
Merge pull request #1 from laurent22/master

### PR DESCRIPTION
**Pull request by jcgerhard**
Update the fork

### CODE REVIEW

**Comment by jcgerhard** [comment]
OMG! Please forget this request! Big mistake! Sorrrryyy!

**Comment by Abijeet** [comment]
@jcgerhard - https://stackoverflow.com/a/7244456/903324 that should help.

**Comment by jcgerhard** [comment]
@abijeet thank you for the link 🙏. I‘m somewhat new to GitHub. And @laurent22 sorry for the trouble 🙈. Wish you guys a good evening! 😊

**Comment by laurent22** [comment]
No problem, closing the PR then.

**Pull request closed without merging**
