### PR TITLE
Desktop: Seamless-Updates - generated latest-mac-arm64.yml

### PR DESCRIPTION
**Pull request by AliceHincu**
Continuation of this PR: https://github.com/laurent22/joplin/pull/10941

### CODE REVIEW

**Comment by AliceHincu** [comment]
The latest.yml file is generated during the publishing process to provide information about the latest version of the application for automatic updates. `--publish=never` means that all publishing-related actions, including generation of the latest.yml file, are stopped. Inside build-macos-m1.yml, we run the command `yarn dist  --mac --arm64 --publish=never` to avoid publishing in non-production CI/CD scenarios.

This is why latest-mac.yml file was not found, because it wasn't generated at all. I want to test the hook `afterAllArtifactBuild` again. If this does not work then I will change it to `artifactBuildCompleted`.

**Comment by laurent22** [comment]
> The latest.yml file is generated during the publishing process to provide information about the latest version of the application for automatic updates. --publish=never means that all publishing-related actions, including generation of the latest.yml file, are stopped. Inside build-macos-m1.yml, we run the command yarn dist  --mac --arm64 --publish=never to avoid publishing in non-production CI/CD scenarios.

No that's not it - when we release a desktop version we publish the files, so the logic was already fine. Look carefully - that's an "if/else" statement - the "if" parts runs when we create a new release, and the "else" (where publish=never is) is for testing pull requests on CI, so no relevant in your case.

Whatever was not working, this is definitely not the fix

**Comment by laurent22** [comment]
That was the log for the release. It doesn't look like it did something?

And please add very verbose log statements to your code so that we know if it's actually doing something.

For example, when it's checking if a file exists, etc.

Edit: I just checked your logic, this file you added "artifactBuildCompleted" is not even called from anywhere, is it? So we did all this release for nothing - let's try again but please double-check your code very carefully. It's better to spend 10 more minutes double checking everything than waste days waiting for nothing.

```
2024-08-27T17:22:03.6907650Z Building and publishing desktop application...
2024-08-27T17:22:06.2371140Z [17:22:06] Requiring external module ts-node/register
2024-08-27T17:22:08.2131020Z [17:22:08] Using gulpfile ~/work/joplin/joplin/packages/app-desktop/gulpfile.ts
2024-08-27T17:22:08.2132840Z [17:22:08] Starting 'electronRebuild'...
2024-08-27T17:22:08.2139240Z Running: yarn run electron-rebuild --force-abi 122
2024-08-27T17:22:17.3621930Z
2024-08-27T17:22:17.3632470Z [17:22:17] Finished 'electronRebuild' after 9.14 s
2024-08-27T17:22:29.3153820Z   • electron-builder  version=24.13.3 os=23.6.0
2024-08-27T17:22:29.3154660Z   • artifacts will be published  reason=tag is defined tag=v3.1.4
2024-08-27T17:22:29.3203360Z   • loaded configuration  file=package.json ("build" field)
2024-08-27T17:22:29.3221600Z   • @electron/rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies
2024-08-27T17:22:29.3222970Z
2024-08-27T17:22:29.3224480Z To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
2024-08-27T17:22:29.5634520Z   • skipped dependencies rebuild  reason=npmRebuild is set to false
2024-08-27T17:22:29.5635540Z   • packaging       platform=darwin arch=arm64 electron=29.4.5 appOutDir=dist/mac-arm64
2024-08-27T17:22:30.4228680Z   • downloading     url=https://github.com/electron/electron/releases/download/v29.4.5/electron-v29.4.5-darwin-arm64.zip size=95 MB parts=6
2024-08-27T17:22:31.9004350Z   • downloaded      url=https://github.com/electron/electron/releases/download/v29.4.5/electron-v29.4.5-darwin-arm64.zip duration=2.241s
2024-08-27T17:23:05.2585110Z   • downloading     url=*** size=3.3 kB parts=1
2024-08-27T17:23:05.6133730Z   • downloaded      url=*** duration=1.151s
2024-08-27T17:23:05.8767360Z   • signing         file=dist/mac-arm64/Joplin.app platform=darwin type=distribution identity=EA07B3F9F433C61B695CF4210BA17E74A37FFB7D provisioningProfile=none
2024-08-27T17:23:38.5187170Z   • skipped macOS notarization  reason=`notarize` options were set explicitly `false`
2024-08-27T17:23:38.5465130Z Checking if notarization should be done...
2024-08-27T17:23:38.5466940Z Notarizing net.cozic.joplin-desktop found at /Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app
2024-08-27T17:24:38.5835660Z .
2024-08-27T17:25:38.6159140Z .
2024-08-27T17:26:14.4295210Z Staple notarization ticket to the app...
2024-08-27T17:26:14.4402110Z > xcrun stapler staple "/Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app"
2024-08-27T17:26:14.4475650Z Running: xcrun stapler staple "/Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app"
2024-08-27T17:26:14.7418950Z Processing: /Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app
2024-08-27T17:26:14.7420020Z Processing: /Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app
2024-08-27T17:26:14.7420720Z The staple and validate action worked!
2024-08-27T17:26:14.7421550Z Done notarizing net.cozic.joplin-desktop
2024-08-27T17:26:14.7430830Z   • building        target=DMG arch=arm64 file=dist/Joplin-3.1.4-arm64.dmg
2024-08-27T17:26:14.7434410Z   • building        target=macOS zip arch=arm64 file=dist/Joplin-3.1.4-arm64.zip
2024-08-27T17:26:14.7446820Z   • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
2024-08-27T17:27:02.1904410Z   • building block map  blockMapFile=dist/Joplin-3.1.4-arm64.dmg.blockmap
2024-08-27T17:27:04.2464660Z   • publishing      publisher=Github (owner: laurent22, project: joplin, version: 3.1.4)
2024-08-27T17:27:04.2567550Z   • uploading       file=Joplin-3.1.4-arm64.dmg.blockmap provider=github
2024-08-27T17:27:04.2861050Z   • uploading       file=Joplin-3.1.4-arm64.dmg provider=github
2024-08-27T17:28:35.2900490Z   • building block map  blockMapFile=dist/Joplin-3.1.4-arm64.zip.blockmap
2024-08-27T17:28:37.1940960Z   • uploading       file=Joplin-3.1.4-arm64.zip.blockmap provider=github
2024-08-27T17:28:37.1989230Z   • uploading       file=Joplin-3.1.4-arm64.zip provider=github
2024-08-27T17:29:36.4865130Z Renaming release assets for tag v3.1.4 laurent22/joplin
2024-08-27T17:29:36.4900610Z Fetching releases...
2024-08-27T17:29:37.1481050Z Updating asset with URL https://api.github.com/repos/laurent22/joplin/releases/assets/188660304 to have name,  Joplin-3.1.4-arm64.DMG
2024-08-27T17:29:37.4368690Z Post job cleanup.
2024-08-27T17:29:37.8882630Z Post job cleanup.
2024-08-27T17:29:38.0617470Z Cache hit occurred on the primary key node-cache-macOS-yarn-710448c6563b6f059d383e6dacd249c49db196f9e23ae687e8e831eb8e33b734, not saving cache.
2024-08-27T17:29:38.0709000Z Post job cleanup.
2024-08-27T17:29:38.1894500Z [command]/opt/homebrew/bin/git version
2024-08-27T17:29:38.2708110Z git version 2.46.0
2024-08-27T17:29:38.2777640Z Copying '/Users/runner/.gitconfig' to '/Users/runner/work/_temp/d851c2d9-997c-4104-ba40-fb6dbde88653/.gitconfig'
2024-08-27T17:29:38.2786530Z Temporarily overriding HOME='/Users/runner/work/_temp/d851c2d9-997c-4104-ba40-fb6dbde88653' before making global git config changes
2024-08-27T17:29:38.2787680Z Adding repository directory to the temporary git global config as a safe directory
2024-08-27T17:29:38.2795620Z [command]/opt/homebrew/bin/git config --global --add safe.directory /Users/runner/work/joplin/joplin
2024-08-27T17:29:38.2892640Z [command]/opt/homebrew/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-08-27T17:29:38.2939220Z [command]/opt/homebrew/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-08-27T17:29:38.3665890Z [command]/opt/homebrew/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-08-27T17:29:38.3689500Z http.https://github.com/.extraheader
2024-08-27T17:29:38.3697160Z [command]/opt/homebrew/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-08-27T17:29:38.3742600Z [command]/opt/homebrew/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-08-27T17:29:38.4344670Z Cleaning up orphan processes
```

**Comment by AliceHincu** [comment]
> > The latest.yml file is generated during the publishing process to provide information about the latest version of the application for automatic updates. --publish=never means that all publishing-related actions, including generation of the latest.yml file, are stopped. Inside build-macos-m1.yml, we run the command yarn dist  --mac --arm64 --publish=never to avoid publishing in non-production CI/CD scenarios.
> 
> No that's not it - when we release a desktop version we publish the files, so the logic was already fine. Look carefully - that's an "if/else" statement - the "if" parts runs when we create a new release, and the "else" (where publish=never is) is for testing pull requests on CI, so no relevant in your case.
> 
> Whatever was not working, this is definitely not the fix

Inside the "if" part, the publish step happens and the latest.yml file is generated. Inside the "else" part, the publish doesn't happen, so the latest.yml file won't be generated. "Else" part is for testing pull requests on CI. This is why my last PR (https://github.com/laurent22/joplin/pull/10941) threw the error `latest-mac.yml not found`, because it was never generated in the first place. And when I looked up the error and switched to artifactBuildCompleted, this hook was not added inside package.json. This is why the tests worked after, because the renaming function was never called.

When I looked at prereleases, I saw the absence of 'latest-mac-arm64.yml" file. I then noticed that the hook artifactBuildCompleted was never called. This is why I created this PR, to solve this issue, and then I noticed that the tests do not pass with this hook either. Then I realized that `latest-mac.yml` file will never be generated when creating new PRs, because of the command `yarn dist  --mac --arm64 --publish=never` inside the "else" part. 

My solution now is to verify if we are publishing or not. If we are not publishing and we just test the PR, we skip renaming the file since it won't exist. If we are publishing (releasing a new desktop version), then we rename the file, since it should exist. I want to try and test the hook afterAllArtifactBuild again.

**Comment by AliceHincu** [comment]
> That was the log for the release. It doesn't look like it did something?
> 
> And please add very verbose log statements to your code so that we know if it's actually doing something.
> 
> For example, when it's checking if a file exists, etc.
> 
> Edit: I just checked your logic, this file you added "artifactBuildCompleted" is not even called from anywhere, is it? So we did all this release for nothing - let's try again but please double-check your code very carefully. It's better to spend 10 more minutes double checking everything than waste days waiting for nothing.

Yes you are right, I added more logs so we can identify these problems in the future faster. I'll also check my code more carefully. Weird that not all the changes from package.json were staged. Renaming the file from generateSha512.js to afterAllArtifactBuild.js was staged. Probably, by mistake, the line of code containing the other hook was unstaged.

**Comment by laurent22** [comment]
That looks good now, thanks Alice. I'm going to release another version

**Comment by laurent22** [comment]
That didn't work:

```
Checking if notarization should be done...
Notarizing net.cozic.joplin-desktop found at /Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app
.
.
Staple notarization ticket to the app...
> xcrun stapler staple "/Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app"
Running: xcrun stapler staple "/Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app"
Processing: /Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app
Processing: /Users/runner/work/joplin/joplin/packages/app-desktop/dist/mac-arm64/Joplin.app
The staple and validate action worked!
Done notarizing net.cozic.joplin-desktop
  • building        target=DMG arch=arm64 file=dist/Joplin-3.1.7-arm64.dmg
  • building        target=macOS zip arch=arm64 file=dist/Joplin-3.1.7-arm64.zip
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  • building block map  blockMapFile=dist/Joplin-3.1.7-arm64.dmg.blockmap
  • publishing      publisher=Github (owner: laurent22, project: joplin, version: 3.1.7)
  • uploading       file=Joplin-3.1.7-arm64.dmg.blockmap provider=github
  • uploading       file=Joplin-3.1.7-arm64.dmg provider=github
  • building block map  blockMapFile=dist/Joplin-3.1.7-arm64.zip.blockmap
  • uploading       file=Joplin-3.1.7-arm64.zip.blockmap provider=github
  • uploading       file=Joplin-3.1.7-arm64.zip provider=github
Renaming latest-mac.yml file...
  ⨯ latest-mac.yml not found!  failedTask=build stackTrace=Error: latest-mac.yml not found!
    at renameLatestYmlFile (/Users/runner/work/joplin/joplin/packages/app-desktop/afterAllArtifactBuild.js:54:10)
    at mainHook (/Users/runner/work/joplin/joplin/packages/app-desktop/afterAllArtifactBuild.js:61:2)
    at /Users/runner/work/joplin/joplin/packages/app-desktop/node_modules/app-builder-lib/src/index.ts:82:58
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at executeFinally (/Users/runner/work/joplin/joplin/packages/app-desktop/node_modules/builder-util/src/promise.ts:12:14)
Error: Process completed with exit code 1.
```

Also if you look at the log it seems the files have already been uploaded by the time you run your script, so you might need to find a way to run it earlier.

Also I suggest listing all the files in the directory you're checking to see what is there exactly: You can do that using `fs.readdir`. In the "uploading" statements above I don't see a mention of "latest-mac.yml" so maybe it's not being generated.

Finally, are you not able to test some of this on your computer? Using `yarn dist --publish=never` you may be able to simulate at least part of the workflow, so you can see what is generated or not, at what point your script is executed, etc.

Another thing to try would be to run your script during from `notarizeMacApp` - the .yml should be available by then, right? And we know that at that point nothing has been uploaded yet.

Last thing to try is something like the existing `renameReleaseAssets.ts` - you directly access the release, and add or rename any file that you need.

So there are various things to try. If you can do as much tests as possible locally that would be great, and I can create more prereleases too, but obviously that's the time consuming part.

**Pull request merged**
