### PR TITLE
Server: Support for multi platform builds (initial refactor)

### PR DESCRIPTION
**Pull request by piotrb**
This brings back a bunch of the changes from my previous PR, this doesn't actually add ARM support YET, but it moves the code around a bit to make it easier to add that in. I plan to introduce this in a few layers just so entire large PRs don't need to get rolled back.

Previous PR: #5338

I brought back the somewhat contentious pattern of using a `Record<string,string>` to represent buildArgs (I think that's a way nicer way to specify that a string and it allows the more generic code to take care of formatting it all cleanly :) Feel free to object :)

### CODE REVIEW

**Comment by piotrb** [comment]
I've noticed that there is some somewhat annoying pattern you have in here with `jest` and running the `ts` files in general .. requring running of tsc all the time to generate the `js` files for any of it to work right .. would you be opposed to some quality of life PRs that streamline this .. for example allowing `jest` to run the `.ts` files directly .. or making the `buildServerDocker.ts` be ran via ts-node so it doesn't need to be re-compiled each time its changed? (obviously in separate PRs from this one)

**Comment by laurent22** [comment]
No because that would make the project unnecessarily more complex. All that's needed now is to have 'yarn run watch' running in a terminal. Even if we add ts-node, we'll still need yarn watch for the rest of the project anyway.

**Comment by piotrb** [comment]
kk makes sense .. that does make it a bit easier :)

**Comment by laurent22** [comment]
Looking at the diff, I'd prefer if we don't refactor this script at this point. Could we stick to just the minimal changes required to get multi platform builds to work? Also I think the `--platform` flag takes a list of platforms when using buildx, which would remove the need for a loop.

**Comment by piotrb** [comment]
hmm .. good call .. I didn't see that buildx had a more versitile option .. it may allow making multi arch manifests all in one step .. let me give that a try ..

**Comment by piotrb** [comment]
hmm the --platform list mode on buildx is definitely a LOT more finicky .. you have to use a containerized builder .. that has limitations as to how it builds .. so it'd also have to do the push at the same time .. I've been trying to run this locally and I'm super drained waiting on the yarn installs .. (its called 3 times somehow in the dockerfile) .. 

perhaps the initial approach may work better .. where its just an image built per platform and then combined into a manifest at the end .. 

I feel a bit hamstrung here .. you seem to be very particular how you want this done ..

**Comment by piotrb** [comment]
the container build seems terribly unoptimized in general .. that yarn install seems to take forever ..

**Comment by piotrb** [comment]
Like the builds literally take like almost an hour ..

**Comment by laurent22** [comment]
If the --platform doesn't work we can use a loop then. My main issue is that I prefer not to have that kind of refactoring, because there's no unit tests for most of it. That's why I'm suggesting to only add the necessary changes and nothing more, as it's easier to manage.

**Comment by piotrb** [comment]
So ideally this is how I would approach this:

1. these seems to be something wrong with the docker builds duration .. this stuff seems to just be taking WAY too long .. there is probably easy tweaks to drastically reduce this .. 
2. once the build time is a bit more sane .. like <15 min .. ideally less .. incorporate a CI step that basically runs this script, just without pushing it to dockerhub .. in each regular CI run .. this way we make sure the images can build, and the script actually works functionally
3. any nuanced behavior can also be broken out to actual unit tests .. obviously the actual running of docker you don't want in those .. but any of the massaging of the information, getting data, setting tags, etc .. can be unit tested

As long as all of this lives inside one huge `main` method its hard to unit test the pieces, but if we refactor it like I suggest, then a lot of the smaller moving parts could have their functionality unit tested with very simple fast tests.

And the actual build can be tested with the "integration" test that also runs the build and makes sure it builds on all the platforms supported.

**Pull request closed without merging**
