### PR TITLE
docs: build for wsl/linux based system.

### LINKED ISSUE #10304: [docs]: build docs update
### Operating system

Linux

### Joplin version

3.0.2

### Desktop version info

Joplin 3.0.2 (dev, linux)

Client ID: 6523accfeb9a4d6094fa082db00cc8ae
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Backup: 1.4.1

### Current behaviour

Currently the build docs for joplin desktop is insufficient. It throws error related to electron (more specifiaclly to Puppeteer). It states that some packages have error.

### Expected behaviour

The packages it states to have error must be installed too. The additional packages are:
libgbm-dev
libatk-bridge2.0-0 
libgtk-3.0
libasound2

### Logs

_No response_

### PR DESCRIPTION
**Pull request by SySagar**
- All: Resolves #10304: Updated build dependencies readme

### CODE REVIEW

**Comment by SySagar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
CI fails:

```
2024-04-15T06:07:52.0800728Z The following spelling mistakes were found. Please check https://joplinapp.org/help/dev/spellcheck for
2024-04-15T06:07:52.0802228Z information on how to deal with spelling mistakes.
2024-04-15T06:07:52.0814580Z
2024-04-15T06:07:52.0815759Z /home/runner/work/joplin/joplin/readme/dev/BUILD.md:24:110 - Unknown word (libgbm)
2024-04-15T06:07:52.0817600Z /home/runner/work/joplin/joplin/readme/dev/BUILD.md:24:121 - Unknown word (libatk)
2024-04-15T06:07:52.0827732Z /home/runner/work/joplin/joplin/readme/dev/BUILD.md:24:140 - Unknown word (libgtk)
2024-04-15T06:07:52.0829432Z /home/runner/work/joplin/joplin/readme/dev/BUILD.md:24:151 - Unknown word (libasound)
```

**Comment by SySagar** [comment]
What should I do @laurent22 ?

**Comment by laurent22** [comment]
> What should I do @laurent22 ?

Learn to read log messages?

> The following spelling mistakes were found. Please check https://joplinapp.org/help/dev/spellcheck

**Comment by SySagar** [comment]
@laurent22 what I meant was the files changes show 0. Does that mean I have to create new pr or update here somehow?

**Pull request merged**
