### PR TITLE
Android: Set min android version to 5 / sdk 21

### PR DESCRIPTION
**Pull request by roman-r-m**
As per https://github.com/facebook/react-native#-requirements

> React Native apps may target iOS 11.0 and Android 5.0 (API 21) or newer

Resolves https://github.com/laurent22/joplin/issues/4585

### CODE REVIEW

**Comment by laurent22** [comment]
Is it safe to set this without testing the app? In other word, does it compile the app differently when we set this, or is it just for information purposes?

**Comment by roman-r-m** [comment]
> 
> 
> Is it safe to set this without testing the app? In other words, does it compile the app differently when we set this, or is it just for information purposes?

I believe it's the latter, but I can give it a try tomorrow.

**Comment by roman-r-m** [comment]
> Is it safe to set this without testing the app? In other words, does it compile the app differently when we set this, or is it just for information purposes?

Tested this with emulator and found no issues.

**Comment by laurent22** [comment]
Great, let's merge this too then.

**Pull request merged**
