### PR TITLE
Mobile: Add split layout

### PR DESCRIPTION
**Pull request by Tolu-Mals**
This pull request is a continuation of the gsoc tablet layout project

### What's added:
- Split layout functionality
Simultaneous view and editing.
- View button
You can press this to go to view mode instead of the back button

### CODE REVIEW

**Comment by laurent22** [comment]
@Tolu-Mals, now that the other PR has been merged, please fix these conflicts

**Comment by Tolu-Mals** [comment]
> @Tolu-Mals, now that the other PR has been merged, please fix these conflicts

Alright, I'll do that.

**Comment by laurent22** [comment]
> Alright, I'll do that.

Any ETA? Been waiting for 2 days and the PR cannot be reviewed in the meantime

**Comment by Tolu-Mals** [comment]
> Any ETA? Been waiting for 2 days and the PR cannot be reviewed in the meantime

I'm sorry for the delay. I think I messed up the code while resolving the merge conflicts on the my first attempt, so I'm doing it again. It should be done by tomorrow morning.

**Comment by Tolu-Mals** [comment]
I discovered a couple of issues, I'll post an update on the forum and add a link here soon.

**Comment by Tolu-Mals** [comment]
> I discovered a couple of issues, I'll post an update on the forum and add a link here soon.

https://discourse.joplinapp.org/t/joplin-mobile-tablet-layout/25775/19?u=tolumals

**Pull request closed without merging**
