### PR TITLE
Update URL of the flag of Vietnam

### PR DESCRIPTION
**Pull request by PhuNH**
The localization table on the website doesn't show the flag of Vietnam.

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pull request, but the flag actually needs to be updated in a script (since this table is dynamically generated). I've now updated the script and that should fix the issue.

@tessus, do you still have a good setup to run build-translations? I've just tried from WSL and I see it's dropping many translations again so probably I don't have the right version of gettext. If it's working for you, would you mind running the update (on dev branch)? Also if you could let me know what version of gettext works that would be great.

**Comment by tessus** [comment]
@laurent22 just run it on current master:

`Updated pot file. Total strings: 730 => 725`

This seems ok, right? If so, let me know and I'll push the most recent changes.

```
$ gettext --version
gettext (GNU gettext-runtime) 0.19.8.1
```

**Comment by tessus** [comment]
Closing this PR, since the update had to be done in a different place.

**Comment by laurent22** [comment]
> This seems ok, right? If so, let me know and I'll push the most recent changes.

Thanks for looking into it and yes that sounds about right, so please go ahead and push the changes.

**Pull request closed without merging**
