### PR TITLE
android: remove non-free dependencies

### PR DESCRIPTION
**Pull request by muelli**
This disables certain features for the camera, but it allegedly affects the test suite only.
This will hopefully remove non-free dependencies so that the app can be shipped by F-Droid: https://gitlab.com/fdroid/rfp/-/issues/434

### CODE REVIEW

**Comment by muelli** [comment]
[yes](https://gitlab.com/fdroid/rfp/-/issues/434#note_733433408) :)

**Comment by laurent22** [comment]
Thanks, I guess it should do any harm to merge this then. Could you just add a comment above the code to explain why we're excluding this please? (with a link to the fdroid repo discussion)

**Comment by muelli** [comment]
yeah, I can make the change.
Note that I have compiled the "assembleDebug" successfully, not the production version.
My Android-fu is not good enough to know how to do that, but I think somebody should try before merging, in order to not break anybody's build ;-) Also, it's probably clever to do something with the camera, just to be sure that the app still works as intended.

**Comment by laurent22** [comment]
Yes assembleDebug is good enough for testing, but indeed we'd need to test the camera too. It's possible to do so on Android emulator, by creating a new note and attaching a photo to it (in which case it will open the camera simulator).

**Comment by muelli** [comment]
I have successfully compiled a "release" by slightly modifying the configuration to use the signingConfigs.debug key.
I have successfully attached a picture to a note :)

So I guess this is good enough for merging \o/

**Comment by laurent22** [comment]
Brilliant let's merge then, thanks for looking into it @muelli!

**Pull request merged**
