### PR TITLE
Desktop, Mobile: Add option to disable auto-save

### LINKED ISSUE #310: Add option to disable auto-save and auto-sync
Joplin saves and syncs the notes every time there is some change, for example editing the note. This is not necessary. It could also cause issues. Please, add an option to disable this functionality. Also, an option to set the delay before edits are saved and synced could be added as well.

*P.S.: I tried to add this option by myself. However, I couldn't find where the main trigger for saving and syncing is. I've been looking at `Note.jsx`. If you can tell me @laurent22 where should I look, I could solve this.*

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [X] iOS

### Application

- [X] Desktop
- [X] Mobile
- [ ] Terminal

### PR DESCRIPTION
**Pull request by xuhcc**
Following the discussion https://github.com/laurent22/joplin/issues/1588#issuecomment-507842757

Resolves #310

### CODE REVIEW

**Comment by laurent22** [comment]
Whenever someone brings up the issue of disabling auto save, it's to go around some limitation or bug in Joplin.

I'd rather fix the underlying issue than disble auto save. If sync is the problem then we should add an option to disable sync. If saving notes has a bug, then that bug should be fixed.

**Comment by xuhcc** [comment]
For me it is a matter of personal preference.

And in mobile app, there is indeed a limitation. When auto-save is enabled, it is not possible to undo changes.

**Comment by xuhcc** [comment]
@laurent22 

I would argue that even if users want to disable auto-save because of some bug or bad performance (as in #1830), we should provide them with ability to do so. Some issues may take long time to fix, and those related to performance may be unavoidable on older devices.

**Comment by laurent22** [comment]
Sync really relies on notes being saved frequently, in order to avoid conflicts. If we allow disabling auto-save, then we should also add better handling of conflicts (for example by providing some way to diff the conflict). As this part is missing I'd rather not merge it unfortunately. In general auto-save is a sensitive topic so any change to it should be discussed on the forum first.

**Comment by xuhcc** [comment]
I never had conflicts due to manual saving and I don't see how auto-save can help in avoiding them. In my experience, the only source of conflicts is bad connectivity, when change from one device is simply not synced to another device for a prolonged period of time. In general, it is not possible to completely avoid conflicts, so users of file syncing software should be conscious of it anyway.

If anyone is interested in this feature, I'm going to maintain a fork at https://github.com/xuhcc/joplin

**Comment by tessus** [comment]
@xuhcc start a discussion on the forum. maybe your idea attracts a lot of votes....

**Pull request closed without merging**
