### PR TITLE
All: Translation: Update cs_CZ.po

### PR DESCRIPTION
**Pull request by MikkCZ**
TODOs:
- [x] resolve extra commits in the branch
- [x] update list of authors according to the previous PRs https://github.com/laurent22/joplin/issues?q=czech
- [x] update last translator
- [x] review the most visible strings in Joplin for consistent terminology

### CODE REVIEW

**Comment by MikkCZ** [comment]
Not sure why there are so many commits showing up, I probably did something wring during a rebase.

**Comment by tessus** [comment]
Don't worry about the number of commits for now. We squash them anyway. As long as they are your commits it is fine. (Some people merge and have hundreds of unrelated commits in a translation PR, which is not ok.)

**Comment by MikkCZ** [comment]
There were some extra commits, but after I rebased on `dev` branch and force pushed they are gone. I might have started my branch off master or something.

**Comment by MikkCZ** [comment]
I finished the updates I wanted to do. It's ready for review @tessus .

**Comment by tessus** [comment]
Thanks for the update.

**Pull request merged**
