### PR TITLE
New tag adding dialogue

### LINKED ISSUE #1111: [Feature Request] Tag by dropdown list
### Operating system

- Windows
- macOS
- Linux
- Android (?)
- iOS (?)

### Application

- Desktop
- Mobile (?)

At the moment the tags in the desktop app are typed as a comma separated string. This is ok, if you only manage a handful of tags. On the other hand, if it gets more and more, it would be nice, if the app could help you: I would like to have a dropdown menu that allows to quickly add/remove single tags to a note.

There are some similar tags:

- #471 would allow to insert tag names faster rendering this request partly obsolete
- #359 is simplified by this request I think as the batch operation can be done much more easy (from the view of the GUI programming) than handling all the strings individually in the current variant.

### PR DESCRIPTION
**Pull request by CalebJohn**
This adds a new more functional (and attractive) dialogue for adding and removing tags from a note. To remove a tag you simply need to click on the tag twice from the tag dialogue.

fixes #1111 
and partially #471 

The only thing worth mentioning is that I used the autocomplete prop in PromptDialog, I couldn't figure out what this prop was for (perhaps a removed feature?) but it made sense to use it for keeping a list of all notes because that list is used for auto completing tags!

I hope this change fits with the current push to add polish to Joplin.

### Display tags using the TagList
image

### Autocomplete tags using an html5 datalist
image

### Tags wrapping
image

### Prompt about removing tag
image

### CODE REVIEW

**Comment by laurent22** [comment]
Ok for the autocomplete property, I guess I've added it at some point but never finished it. How about the TagItem component? Looks like you replaced it with some new code?

**Comment by CalebJohn** [comment]
Hmmm I only added code to the TagItem component, I'm not sure why git is showing it as being replaced, basically I added a few functions to make the tags interact-able (clicking on tags twice deletes them, and clicking on anything else restores the previous state). The additions to the TagItem component are fairly minor though.

**Comment by laurent22** [comment]
I've merged this but at least for me autocompletion of tags doesn't work, and there's also nothing in the dropdown list (clicking the arrow does nothing). I see the data is there though so not sure why it doesn't work (on macOS)

image

Also the Remove button colour is not right on light theme:

image

**Comment by CalebJohn** [comment]
Hmmm I'll look into it, but if the datalist really isn't working we might have to go with another tag system. I'll make a pull adjusting the color asap.

**Comment by laurent22** [comment]
Unfortunately I didn't notice that adding new tags is also broken, at least on macOS. Adding tags in the field and pressing "OK" just does nothing, and no error.

**Comment by laurent22** [comment]
I'll revert the PR for now and let's see if there's a fix for it.

**Comment by CalebJohn** [comment]
Okay I did some digging and it looks like this is (was) a [bug in Electron on macOS](https://github.com/electron/electron/issues/360). It's already been fixed upstream and will be available in [electron 5.0](https://github.com/electron/electron/issues/14879). With that in mind, it's probably best to leave this closed because I don't see this project upgrading to the 5.0 beta anytime soon. I'll look into other options for easy to use tags.

**Comment by laurent22** [comment]
Are you sure it will be available in v5, as it wasn't very clear to me from that GitHub thread? If it is, it could make sense to wait for that version since they seem to be moving quite fast from one major version to the next.

**Comment by CalebJohn** [comment]
I can't say for certain but someone in the github thread (the second one I linked) mentioned that it will be available in 5 as soon as [this pull is merged](https://github.com/electron/electron/pull/16880). I don't know how long that will be.

That said it's already available on master so it could be already included in some 4x release? I'm not to familiar with electron so I can't speak to how that might work.

**Comment by CalebJohn** [comment]
Just an update on this, the fix was backported to electron 5 but not 4. This means that unless joplin upgrades to electron 5, we will need to continue looking for other solutions.

I did a quick test to see if upgrading to electron 5 is as easy as upgrading the package but it isn't.

**Comment by laurent22** [comment]
Electron 5.0.0 was released recently so I'm waiting for a few versions before doing the upgrade. Hopefully it won't be too complicated.

**Pull request merged**
