### PR TITLE
Desktop: Resolve #4235: Carret for Notebook and Tags in SideBar 

### LINKED ISSUE #4235: Carret for Notebook and Tags in SideBar
## Environment

>Joplin 1.4.19 (prod, win32)
>
>Client ID: 83d92f9b0a0b443ca92b976c9313de51
>Sync Version: 2
>Profile Version: 34
>Keychain Supported: Yes
>
>Revision: de123ee58 (master)

## Describe what you expected to happen
There's not anymore UI feedback indicating the node is open or not

image

It would be nice to put it back

image

### PR DESCRIPTION
**Pull request by jibedoubleve**
## What has been done?
Actually, the folder and the tag header already have a property indicating whether it is expanded or not.

I just had to add a `<StyledHeaderIcon />` that will display a _left_ or _down_ carret depending on the value of this property.

## What does it look like?

image

### CODE REVIEW

**Comment by tessus** [comment]
TBH I don't like this. This moves all my notebooks the number of pixels used for the carret to the right.

There goes my precious screen real estate. I think it's pretty clear, when it is collapsed or expanded. There's no need for a carret.

**Comment by tessus** [comment]
If you really have to add this, can you please create an explicit classname like `sb-nb-carret` and `sb-tag-carret` so that people can remove this via css?

**Comment by laurent22** [comment]
Could we have a screenshot of how it looks with this change? It's an important part of the app and we'd want it be right by default, without having to use custom csd.

**Comment by jibedoubleve** [comment]
@laurent22 : I've updated the comments of the PR. I tried to be as consistent as possible with the rest of the _TreeView_ 
@tessus : Let me see what I can do with the CSS. I'll discuss before pushing new commits as web is a new world to learn for me ;-)

**Comment by laurent22** [comment]
Thanks for the screenshot. I think such a design change should be discussed in the forum to gather more feedback. It’s a good change but for example indentation doesn’t look right to me.

**Comment by tessus** [comment]
I'm still not sure why this is required at all. It's expanded, when you see folders/tags. It's not that complicated.
You only waste a whole bunch of empty pixels.

**Comment by laurent22** [comment]
> I'm still not sure why this is required at all. It's expanded, when you see folders/tags. It's not that complicated.

Yes, that's one opinion, and we would get more on the forum. @jibedoubleve, if you can, please post the screenshot on the forum to see what other users think and maybe we'll also get some ideas on how to better position the cursor.

**Comment by jibedoubleve** [comment]
[Here][1]'s the link

[1]:https://discourse.joplinapp.org/t/carret-for-notebook-and-tags-in-sidebar/12625

**Comment by jibedoubleve** [comment]
@tessus 

> 
> 
> If you really have to add this, can you please create an explicit classname like `sb-nb-carret` and `sb-tag-carret` so that people can remove this via css?

I thought about what you've asked. The way I understand is this: I added a class `sb-carret` that user can customise in `userchrome.css`. Bear in mind I use `renderHeader` method for both `Tag` and `Notebook`, therefore I cannot easily have separate classes for them. Furthermore, I think there little added value in separating behaviour for `Tag` and `Notebook`

```html
<StyledHeaderIcon className={extraProps.isExpanded ? 'fas fa-caret-down sb-carret' : 'fas fa-caret-right sb-carret'} />
```

What do you think?

**Comment by tessus** [comment]
This should work until you also adjust the indentation, in which case removing the carrets would not remove the indentation.

As I mentioned before, I don't think this change is necessary at all, because it is always clear when they are expanded/collapsed. There don't have to be additional indicators that tell me what I already know.

Personally I would not accept/merge such a PR, but it will be Laurent's decision.

I've also added my opinion on the forum and I guess we'll see how others think about it...

**Comment by laurent22** [comment]
It's a good change but the implementation is not right. With the extra indentation the Notebook icon is too much to the right, while it should be before the "All notes" icon. So it means moving everything below more to the right, or moving the top icon a bit more to the left, or making the top indentation smaller.

But to be honest I don't have time to look into this, so I can only suggest to wait and see if you get more feedback on the forum, which would allow iterating towards a solution. Perhaps after the holidays you'll have more answers.

**Comment by jibedoubleve** [comment]
This is my last change untill users (in)validate this feature. I just wanted to have something clean, even if this PR won't be integrated. From now on, I'll wait untill users decide.

### The change

I've tried to _fix_ the indentation. I inlined the `padding-left` in the style of the `<div/>` because firstly there are only two headers and it implies little code and secondly, as far as I undertand the class names `folders` and `tags` are only used for `userchrome.css` and I didn't find no way to fill it (maybe by lack of knowledge)

image

**Comment by laurent22** [comment]
Sorry for the very late reply, but I'm not too sure what to do about this PR. On one hand, I think you're right and we should add something to show the collapsed/expanded state, but on the other hand I'm not so keen about how it looks.

For example the header would now almost be aligned with the items below, which makes it more difficult to see it's a header. But I also don't know what to suggest as an alternative.

That's what's tricky about design changes, it's difficult to get somewhere without seeing multiple concepts and going over multiple iterations.

**Comment by laurent22** [comment]
Closing for now as I think we're lacking of spec or design of what needs to be done exactly. Feel free to let us know if you'd like to work on it again later on.

**Comment by jibedoubleve** [comment]
I'm a bit out of time for the moment, but I'll try to put some propositions later on the [Discourse thread](https://discourse.joplinapp.org/t/carret-for-notebook-and-tags-in-sidebar/12625).

I don't see a lot of enthusiasm on this feature, then closing the PR until it becomes more a thing is a good idea.

**Pull request closed without merging**
