### PR TITLE
Update Greek translation

### PR DESCRIPTION
**Pull request by dimitristsilis**
Add missing translations

### CODE REVIEW

**Comment by dimitristsilis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tessus** [comment]
I am not sure what's going on, but this is not an update. It seems to be a new file. Can you please shed some light on this?

**Comment by tessus** [comment]
The file is in the root of the project. It should be in `packages/tools/locales/`

**Comment by dimitristsilis** [comment]
I will make a new pull request with the correct file. It seems that my .po file lost the lines preceded by "#", somehow.

**Pull request closed without merging**
