### PR TITLE
Desktop: Fixes #9960: Modified setting to store profile languages

### LINKED ISSUE #9960: Creating a profile changes the language of Joplin
### Operating system

Windows

### Joplin version

2.14.14

### Desktop version info

Joplin 2.14.14 (prod, win32)

Client ID: 0e33609c84614b3092102ff00887b36e
Sync Version: 3
Profile Version: 45
Keychain Supported: Yes

Revision: ecb6ac3

### Current behaviour

1. Change your Joplin language other than the operating system language
2. Create a new profile
3. The language for the new profile is the same as for the operating system 
4. Change back to your original profile 
5. The language has now been changed to that of the operating system here too

### Expected behaviour

The language should not be changed automatically when creating a new Joplin profile

### Logs

_No response_

### PR DESCRIPTION
**Pull request by GuptTmay**
Hi, This pr fixes [#9960](https://github.com/laurent22/joplin/issues/9960)

Quick summary of what I did:
- Modified  spellChecker.languages  isGlobe settingItem so that it store/take its value from profile setting itself (not from global setting.json)
- Modified SpellCheckerServices.ts to make default spellChecker language to set 'en-US' when profile is created for the first Time

Here are the test for windows:
default
existing
newProfile

Here is a test video if needed: 

https://github.com/laurent22/joplin/assets/138118622/b117fb2b-bb9b-4a15-8bd5-b10c2af7afd7

I have tested this for windows.
I will be giving tests for Android soon

(P.S - This is my first PR so please guide me if anything is wrong)

### CODE REVIEW

**Comment by GuptTmay** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
Sorry you didn't understand the original issue. The author wasn't talking about the spellchecker languages but about the application locale, under General => Language

**Comment by GuptTmay** [comment]
Thanks for the feedback and sorry for the misunderstanding. I will look into it. Can I resubmit a new pr for this issue?

**Comment by PackElend** [comment]
> Can I resubmit a new pr for this issue?

Sure

**Pull request closed without merging**
