### PR TITLE
Desktop: Changing bold-text preview color for Aritim-dark theme

### LINKED ISSUE #3011: Changing bold-text color for arititmdark theme
In the current state bold text are changed to green colour while the normal text is white in colour.

## Environment

Joplin version: Joplin 1.0.197 (dev, win32)
Platform: Windows
OS specifics: No

## Describe what happens
image

## Describe what you expected to happen
image

### PR DESCRIPTION
**Pull request by Rishgod**
fixes #3011 

## Describe what happens
image

## Describe what you expected to happen
image

### CODE REVIEW

**Comment by laurent22** [comment]
@TobiasDev, I think that change makes sense, what do you think?

**Comment by TobiasDev** [comment]
Sorry yes! I already fixed that locally and wanted to submit it, but this also looks good! :)

**Comment by TobiasDev** [comment]
Or wait, it shouldn't be white, it should be #d3dae3 for it to have the same text color as everything else.

**Comment by Rishgod** [comment]
> Or wait, it shouldn't be white, it should be #d3dae3 for it to have the same text color as everything else.

I did that on purpose as it stood out more, but I'll change it back if you say so!

**Comment by laurent22** [comment]
How does it look with the latest change?

**Comment by TobiasDev** [comment]
He changed so bold now also has the default text color. :) so looks fine from me.

**Comment by Rishgod** [comment]
> How does it look with the latest change?

there isn't much of a difference if any

color code: #d3dae3 [currently using and is similar to normal text color code]
image

---

color code: #ffffff
image

**Comment by CalebJohn** [comment]
Thanks @Rishgod!

**Pull request merged**
