### PR TITLE
fix(Android/SharePackage): revert changes to share package and fix it

### PR DESCRIPTION
**Pull request by jd1378**
remove some checks from Safx module document helper to allow content provider Uris to work properly

fixes the last accidentally merged commit of #6932  
and fixes the share problem , a part of #6942

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the update. Have you been able to check that it actually fixes the sharing problem?

**Comment by jd1378** [comment]
I have shared and attached files and images multiple times, so yeah I tested it myself, but wouldn't hurt to try it yourself as well

**Comment by jd1378** [comment]
and sorry for the trouble 😅

**Comment by wh201906** [comment]
For 63117fd, sharing images/files and attaching images/files work in most of the cases. But the Joplin itself ~~crashes~~ won't be waken up properly sometimes.

Maybe we need to change the `launchMode` of Joplin's main activity or file sharing activity? Similar to the test result of https://github.com/jd1378/joplin/commit/b39ae635fb39c85cc734de80d88b8d3d55bdf561 mentioned in https://github.com/laurent22/joplin/issues/6942#issuecomment-1278375572, the crashe never happens When I open Joplin then do nothing else. If I shared a file to Joplin then keep the app in the background, the next sharing is more likely to fail.

In all, I think users can share files to Joplin now, but sometimes they might ~~run into crashes~~ fail to wake up Joplin by sharing a file to it.

**Comment by jd1378** [comment]
did it work perfectly in [v2.9.2](https://github.com/laurent22/joplin-android/releases/tag/android-v2.9.2) ?
want to know if it's still an issue with my module or It would happen anyway

**Comment by wh201906** [comment]
Sharing images works perfectly, but sharing files fails. The latter will show `index=2 length=2`

**Comment by wh201906** [comment]
I can reproduce the ~~crash~~ bug on 63117fd in certain steps now.
After sharing a image to Joplin, you will enter the viewing page of the created note. 
If you return to the notebook page, switch to the gallery app then sharing something to Joplin, the app ~~won't crash~~ works fine.
If you don't return to the notebook page, switch to the gallery app then sharing something to Joplin, ~~the app will crash~~ the bug happens.

<details>
<summary>Logs</summary>

The log of Joplin for the former
```
10-14T20:19:57,30,"""SearchEngine: Updated FTS table in 117ms. Inserted: 1. Deleted: 0""
10-14T20:19:57,40,"models/Setting: ""Settings have been saved.""
10-14T20:19:57,40,"models/Setting: ""Saving settings...""
10-14T20:19:57,30,"""SearchEngine: Updating FTS table...""
10-14T20:19:52,30,"""Sync cancelled - no sync target is selected.""
10-14T20:19:52,30,"""Preparing scheduled sync""
10-14T20:19:47,40,"""Scheduling sync operation...", "5000""
10-14T20:19:47,40,"""Scheduling sync operation...", "5000""
10-14T20:19:47,40,"""Scheduling sync operation...", "5000""
10-14T20:19:47,30,"""Updating lat/long of note 0b0e41c701884100ab008ef89dfd33ee""
10-14T20:19:47,30,"""SearchEngine: Updated FTS table in 701ms. Inserted: 2. Deleted: 0""
10-14T20:19:47,40,"models/Setting: ""Settings have been saved.""
10-14T20:19:47,40,"models/Setting: ""Saving settings...""
10-14T20:19:47,40,"models/Setting: ""Settings have been saved.""
10-14T20:19:47,30,"RevisionService: ""maintenance: Done in 777ms""
10-14T20:19:47,30,"RevisionService: ""collectRevisions: Created revisions for 1 notes""
10-14T20:19:47,40,"models/Setting: ""Settings have been saved.""
10-14T20:19:47,40,"models/Setting: ""Saving settings...""
10-14T20:19:47,40,"models/Setting: ""Saving settings...""
10-14T20:19:46,40,"RevisionService: ""collectRevisions: Saved revision 3065793b9c024b059d54cf8971663d22 (Last rev was more than 600000 ms ago)""
10-14T20:19:46,30,"""Original dimensions ", "{"width":1025,"height":771}""
10-14T20:19:46,30,"""Original dimensions ", "{"width":1025,"height":771}""
10-14T20:19:46,30,"""about to attach resource {"name":"1665749986380.jpg","mimeType":"image/jpeg","uri":"content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fcom.miui.gallery%2Fcache%2FSecurityShare%2F1665749986380.jpg"}""
10-14T20:19:46,30,"""Got file: content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fcom.miui.gallery%2Fcache%2FSecurityShare%2F1665749986380.jpg""
10-14T20:19:46,30,"""Got type: image/jpeg""
10-14T20:19:46,30,"""Got file: content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fcom.miui.gallery%2Fcache%2FSecurityShare%2F1665749986380.jpg""
10-14T20:19:46,30,"""Got type: image/jpeg""
10-14T20:19:46,30,"""about to attach resource {"name":"1665749986380.jpg","mimeType":"image/jpeg","uri":"content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fcom.miui.gallery%2Fcache%2FSecurityShare%2F1665749986380.jpg"}""
10-14T20:19:46,40,"""Scheduling sync operation...", "5000""
10-14T20:19:46,30,"""Received shared data""
10-14T20:19:46,30,"""SearchEngine: Updating FTS table...""
10-14T20:19:46,30,"RevisionService: ""maintenance: Service is enabled""
10-14T20:19:46,30,"RevisionService: ""maintenance: Starting...""
```
The log of Logcat for the former
```
2022-10-14 20:19:46.533 2267-3201/net.cozic.joplin W/unknown:ReconnectingWebSocket: Couldn't connect to "ws://localhost:8081/message?device=...&app=net.cozic.joplin&clientid=BridgeDevSupportManager", will silently retry
2022-10-14 20:19:46.641 2267-2405/net.cozic.joplin W/ReactNativeJS: 'In most cases you should not have more MenuProviders in your app (see API documentation). In other cases use skipInstanceCheck prop.', '\n    at MenuProvider (address at index.android.bundle:1:5051103)\n    at DeprecatedComponent (address at index.android.bundle:1:5039962)\n    at RCTView\n    at View\n    at AnimatedComponent (address at index.android.bundle:1:733329)\n    at AnimatedComponentWrapper\n    at RCTView\n    at View\n    at SideMenuComponent (address at index.android.bundle:1:5293306)\n    at Connect(SideMenuComponent) (address at index.android.bundle:1:4987579)\n    at RCTView\n    at View\n    at AppComponent (address at index.android.bundle:1:1222561)\n    at Connect(AppComponent) (address at index.android.bundle:1:4987579)\n    at Provider (address at index.android.bundle:1:4985188)\n    at Root (address at index.android.bundle:1:1227726)\n    at RCTView\n    at View\n    at RCTView\n    at View\n    at AppContainer (address at index.android.bundle:1:837756)\n    at Joplin(RootComponent) (address at index.android.bundle:1:913328)'
2022-10-14 20:19:46.741 2267-2405/net.cozic.joplin W/ReactNativeJS: `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
2022-10-14 20:19:46.742 2267-2405/net.cozic.joplin W/ReactNativeJS: `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```
The log of Joplin for the latter
```
10-14T20:20:29,30,"RevisionService: ""maintenance: Done in 11408ms""
10-14T20:20:29,30,"RevisionService: ""collectRevisions: Created revisions for 1 notes""
10-14T20:20:29,40,"models/Setting: ""Settings have been saved.""
10-14T20:20:29,20,"""Could not attach file:", "Error: file not found: /storage/emulated/0/Android/data/com.miui.gallery/cache/SecurityShare/1665749986380.jpg
Code: E_GET_SIZE_FAILURE
Error: file not found: /storage/emulated/0/Android/data/com.miui.gallery/cache/SecurityShare/1665749986380.jpg
    at promiseMethodWrapper (address at index.android.bundle:1:104404)
    at getSize (address at index.android.bundle:1:798145)
    at anonymous (address at index.android.bundle:1:5099240)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at _callee14$ (address at index.android.bundle:1:5099174)
    at call (native)
    at tryCatch (address at index.android.bundle:1:274737)
    at invoke (address at index.android.bundle:1:275738)
    at anonymous (address at index.android.bundle:1:274885)
    at anonymous (address at index.android.bundle:1:5087518)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:5087345)
    at imageDimensions (address at index.android.bundle:1:5099033)
    at _callee15$ (address at index.android.bundle:1:5100967)
    at call (native)
    at tryCatch (address at index.android.bundle:1:274737)
    at invoke (address at index.android.bundle:1:275738)
    at anonymous (address at index.android.bundle:1:274885)
    at anonymous (address at index.android.bundle:1:5087518)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:5087345)
    at resizeImage (address at index.android.bundle:1:5099522)
    at _callee16$ (address at index.android.bundle:1:5103262)
    at call (native)
    at tryCatch (address at index.android.bundle:1:274737)
    at invoke (address at index.android.bundle:1:275738)
    at anonymous (address at index.android.bundle:1:274885)
    at anonymous (address at index.android.bundle:1:5087518)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:5087345)
    at attachFile (address at index.android.bundle:1:5101052)
    at _callee6$ (address at index.android.bundle:1:5118535)
    at call (native)
    at tryCatch (address at index.android.bundle:1:274737)
    at invoke (address at index.android.bundle:1:275738)
    at anonymous (address at index.android.bundle:1:274885)
    at call (native)
    at tryCatch (address at index.android.bundle:1:274737)
    at invoke (address at index.android.bundle:1:274970)
    at anonymous (address at index.android.bundle:1:275182)
    at tryCallOne (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:333845)
    at _callTimer (address at index.android.bundle:1:332590)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:332890)
    at callReactNativeMicrotasks (address at index.android.bundle:1:334941)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:109780)
    at anonymous (address at index.android.bundle:1:107808)
    at __guard (address at index.android.bundle:1:109611)
    at flushedQueue (address at index.android.bundle:1:107719)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:107662)""
10-14T20:20:29,30,"""Got type: image/jpeg""
10-14T20:20:29,30,"""Got file: content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fcom.miui.gallery%2Fcache%2FSecurityShare%2F1665749986380.jpg""
10-14T20:20:29,30,"""about to attach resource {"name":"1665749986380.jpg","mimeType":"image/jpeg","uri":"content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fcom.miui.gallery%2Fcache%2FSecurityShare%2F1665749986380.jpg"}""
10-14T20:20:29,40,"models/Setting: ""Saving settings...""
10-14T20:20:29,40,"RevisionService: ""collectRevisions: Saved revision aeb01696b7da4f32875b4354d145ee46 (Last rev was more than 600000 ms ago)""
10-14T20:20:29,40,"""Scheduling sync operation...", "5000""
10-14T20:20:28,30,"""Received shared data""
10-14T20:20:18,30,"RevisionService: ""maintenance: Service is enabled""
10-14T20:20:18,30,"RevisionService: ""maintenance: Starting...""
```
The log of Logcat for the latter
```
2022-10-14 20:20:28.811 2267-3530/net.cozic.joplin W/unknown:ReconnectingWebSocket: Couldn't connect to "ws://localhost:8081/message?device=...&app=net.cozic.joplin&clientid=BridgeDevSupportManager", will silently retry
2022-10-14 20:20:28.884 2267-2405/net.cozic.joplin W/ReactNativeJS: 'In most cases you should not have more MenuProviders in your app (see API documentation). In other cases use skipInstanceCheck prop.', '\n    at MenuProvider (address at index.android.bundle:1:5051103)\n    at DeprecatedComponent (address at index.android.bundle:1:5039962)\n    at RCTView\n    at View\n    at AnimatedComponent (address at index.android.bundle:1:733329)\n    at AnimatedComponentWrapper\n    at RCTView\n    at View\n    at SideMenuComponent (address at index.android.bundle:1:5293306)\n    at Connect(SideMenuComponent) (address at index.android.bundle:1:4987579)\n    at RCTView\n    at View\n    at AppComponent (address at index.android.bundle:1:1222561)\n    at Connect(AppComponent) (address at index.android.bundle:1:4987579)\n    at Provider (address at index.android.bundle:1:4985188)\n    at Root (address at index.android.bundle:1:1227726)\n    at RCTView\n    at View\n    at RCTView\n    at View\n    at AppContainer (address at index.android.bundle:1:837756)\n    at Joplin(RootComponent) (address at index.android.bundle:1:913328)'
2022-10-14 20:20:29.195 2267-2267/net.cozic.joplin E/unknown:ReactNative: Tried to remove non-existent frame callback
2022-10-14 20:20:29.229 2267-2405/net.cozic.joplin W/ReactNativeJS: `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
2022-10-14 20:20:29.230 2267-2405/net.cozic.joplin W/ReactNativeJS: `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
2022-10-14 20:20:29.280 2267-2405/net.cozic.joplin W/ReactNativeJS: EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
2022-10-14 20:20:29.280 2267-2405/net.cozic.joplin W/ReactNativeJS: EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
2022-10-14 20:20:29.283 2267-2405/net.cozic.joplin W/ReactNativeJS: EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
2022-10-14 20:20:29.295 2267-2406/net.cozic.joplin W/unknown:ReactNative: StatusBarModule: Ignored status bar change, current activity is null.
2022-10-14 20:20:29.314 2267-2406/net.cozic.joplin W/unknown:ReactNative: StatusBarModule: Ignored status bar change, current activity is null.
2022-10-14 20:20:29.719 2267-2405/net.cozic.joplin W/ReactNativeJS: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
        in NoteScreenComponent
2022-10-14 20:20:29.753 2267-2405/net.cozic.joplin W/ReactNativeJS: '20:20:29:', 'Could not attach file:', [Error: file not found: /storage/emulated/0/Android/data/com.miui.gallery/cache/SecurityShare/1665749986380.jpg]
```

</details>

**Comment by laurent22** [comment]
Does it actually crash? Because there are still log entries after the error message? Or does it not print any error info when it crashes?

**Comment by wh201906** [comment]
I'm not sure if it's a crash. When the bug happens, The Joplin just shows up for less than a second then disappears.

**Comment by laurent22** [comment]
There should be a stack trace in logcat when the crash happens. Could you see if you can get it?

**Comment by wh201906** [comment]
I have posted the log in Logcat above. Now I'm sure the app doesn't crash, because it doesn't show the stack trace with Error level. And my Android Studio shows I'm always on the same process. Sorry for my subjective conclusion and improper words.
But the Joplin can't be waken up properly. It just shows then disappears.

**Comment by jd1378** [comment]
this permission denial is something I can't quite understand
why it doesn't throw first time and why it does second time ? do you have any info ?
my first guess is that different activities of share package messes up permissions some how
my reasoning is because when you simply comment [`currentActivity.finish();`](https://github.com/laurent22/joplin/blob/63117fdc4cabb26aaa1a67d7d44c5c25da4faa9a/packages/app-mobile/android/app/src/main/java/net/cozic/joplin/share/SharePackage.java#L70) it fixes the problem.
but that shouldn't be the proper fix, we have to cleanup share acitivity anyway

**Comment by jd1378** [comment]
adding `android:launchMode="singleTask"` to share activity at least caused the error to be shown properly (kept app open and showed error dialog), but didn't fix the problem
setting `android:launchMode="singleTop"` caused the current behavior to repeat

Edit: `singleInstance` result is same as `singleTop`

**Comment by jd1378** [comment]
So the permission lives as long as the share activity lives according to the info @wh201906 provided [here](https://github.com/laurent22/joplin/issues/6942#issuecomment-1277559390)
once the share activity is finished, the permission is revoked
but even though its re-opened, the permission stays revoked it seems ?

**Comment by roman-r-m** [comment]
> but even though its re-opened, the permission stays revoked it seems ?

I suppose sharing the 2nd time creates another copy of the `ShareActivity`

**Comment by jd1378** [comment]
> > but even though its re-opened, the permission stays revoked it seems ?
> 
> I suppose sharing the 2nd time creates another copy of the `ShareActivity`

I think so, but why the permission is not given to the second copy again ?

**Comment by jd1378** [comment]
is it possible to handle the share inside MainActivity itself ? 
If so, I think that the solution to this problem is to do that

**Comment by wh201906** [comment]
> So the permission lives as long as the share activity lives according to the info @wh201906 provided [here](https://github.com/laurent22/joplin/issues/6942#issuecomment-1277559390)

I got a new statement just now.
https://developer.android.com/training/secure-file-sharing/request-file.html#OpenFile
It says
```
The permissions are temporary, so once the client app's task stack is finished, the file is no longer accessible outside the server app. 
```
By the way, https://developer.android.com/training/secure-file-sharing/retrieve-info give you a proper way to get the metadata, then you don't have to use DocumentFile

**Comment by wh201906** [comment]
> why it doesn't throw first time and why it does second time ? do you have any info ?

It's also strange that the `react-native-fs` just works without touching anything else in the current code.

**Comment by wh201906** [comment]
> adding `android:launchMode="singleTask"` to share activity at least caused the error to be shown properly (kept app open and showed error dialog), but didn't fix the problem setting `android:launchMode="singleTop"` caused the current behavior to repeat
> 
> Edit: `singleInstance` result is same as `singleTop`

I have another assumption about the `launchMode`
The MainActivity has `launchMode=singleTask`. When the ShareActivity gets the intent and activate MainActivity for the rest of the work, SharedActivity will be destroyed because it's on the top of the task stack, according to the document
https://developer.android.com/guide/components/activities/tasks-and-back-stack#ManifestForTasks
```
Meanwhile all of the other activities on top of it are destroyed.
```

**Comment by jd1378** [comment]
I can confirm react-native-fs does it without any problem, 
but I can't understand why
maybe because it does the transfer inside a async task ?

**Comment by jd1378** [comment]
Well Actually it does not work, it was working unexpectedly
[after repeating the test with `react-native-fs`](https://github.com/laurent22/joplin/pull/6928/files), it also has the same problem

**Comment by jd1378** [comment]
>  https://developer.android.com/training/secure-file-sharing/request-file.html#OpenFile

the old info you sent seems to be more accurate because of the fix I mentioned about finishing activity (or are they meaning the same ? idk)

**Comment by jd1378** [comment]
maybe we can debounce the share activity close by 2-3 minutes ?
that will probably fix the problem majority of the users will face

**Comment by wh201906** [comment]
It works perfectly with the tests we talked these days. Thank you for fixing it!
By the way, I wonder why you set `android:launchMode="singleTask"` for the ShareActivity

**Comment by jd1378** [comment]
1. > adding android:launchMode="singleTask" to share activity at least caused the error to be shown properly (kept app open and showed error dialog)
2. to reuse the same activity instead of launching new ones (I don't think It's needed, didn't test enough though)

tell me if I'm missing something about the singleTask launch mode that may create an issue in the future

**Comment by wh201906** [comment]
I'm not familiar with `launchMode`. I think the current version is good enough.

**Comment by wh201906** [comment]
~~By the way, I wonder if #6951 exists after this fix.~~
Seems not reproducible. Never mind.

**Comment by jd1378** [comment]
@laurent22 it's ready, can we merge ?

**Comment by laurent22** [comment]
Ok let's merge

**Pull request merged**
