### PR TITLE
Mobile - Swipeable Notes/todos & Linting

### LINKED ISSUE #2742: Mobile - Swipe to delete Todos/Notes On Note Screen
## Environment

OS specifics: React Native

## Steps to reproduce

1. Current Build

## Describe what you expected to happen
It would be a good UX practice to incorporate Swiple To Delete items

### PR DESCRIPTION
**Pull request by blackwolf08**
Closes #2742 

# ScreenShots
Screenshot_1584022335
Screenshot_1584022341
Screenshot_1584022348

### CODE REVIEW

**Comment by Rishgod** [comment]
@blackwolf08  there are a lot of linting errors make sure you have eslint and prettier configured properly!

**Comment by blackwolf08** [comment]
@Rishgod I have run eslint before committing, nevertheless, I'll check again, thanks!

**Comment by blackwolf08** [comment]
> @blackwolf08 there are a lot of linting errors make sure you have eslint and prettier configured properly!

@Rishgod I've not used Prettier in the following project but ran eslint --fix on root dir.

**Comment by Rishgod** [comment]
> @Rishgod I have run eslint before committing, nevertheless, I'll check again, thanks!

Watch this [video](https://www.youtube.com/watch?v=SydnKbGc7W8) if you still have a problem.

**Comment by Rishgod** [comment]
Well I just try to do this from Vscode its really really easy, If you configure it properly you'll never have problems with Failed PR's because of linting.(you have to press Ctrl+S, save the files for error to go)

eslint

**Comment by laurent22** [comment]
I don't know why you think it's a good idea to commit 60 files when your changes are just on one. Sorry but I'm closing this PR till it's ready for review.

**Pull request closed without merging**
