### PR TITLE
Pull Request for displaying tags under the notes title input

### PR DESCRIPTION
**Pull request by ghost**
[Feature Request] Display assigned tags at Note edit/view pane

This is a PR for https://github.com/laurent22/joplin/issues/469 enhancement.

This is the image after enhancement
tags-display

### CODE REVIEW

**Comment by laurent22** [comment]
Sorry I can't merge this as there's too many white space changes (removing/adding newlines and spaces, etc.) so not only it might cause conflicts but it's also hard to tell what's actually been changed.

When making changes please make sure that your editor doesn't automatically make such white space changes - the commit should basically only contain the changes and nothing more.

I'd be glad to review the pull request again once this is fixed, thanks!

**Comment by Karrthik12** [comment]
Hey Sorry about the issues with white spaces. I have deleted them now. You can review this PR now.

**Comment by laurent22** [comment]
Thanks for the update. I see there duplicate logic to dispatch CURRENT_NOTE_TAGS. Since the tags are displayed only on the toolbar, maybe they should be loaded there only and save into the component state? That way, we won't need the global logic to update the current note tags.

Also [here](https://github.com/laurent22/joplin/pull/579/files#diff-db701303789376d6bc4dff58324ce37fR19), the style should make use of theme.js in particular for colors, font sizes, etc.

**Comment by Karrthik12** [comment]
Hey we can directly load the tags there only but lets assume a situation we have some tags present to a note and we deleted one tag from the side bar, I wrote that dispatch so that it displays the current tags to that note after a tag is deleted.

**Comment by laurent22** [comment]
Not sure if there's still someone working on this as the user has been deleted? (@Abijeet maybe?)

I agree that the approach in this PR is indeed the right one. We just need to reduce the duplicated code, and for this I think one way would be to put the note-tag update code in the Redux middleware. To make that possible, you'll need to dispatch more actions from models/NoteTag - in particular all the functions related to adding, removing or updating NoteTags. Then you can watch for these actions in the middleware and update the current note tags accordingly.

**Comment by laurent22** [comment]
Closed abandoned pull request.

**Comment by laurent22** [comment]
Yes unfortunately there's still some work to do on it and the submitter is gone.

In general I won't merge incomplete PR and won't try to fix them myself either, because in this case it's often easier for me to do it all from scratch (which I may do at some point). I don't mind if someone else take the PR and try to fix it though.

**Comment by foxmask** [comment]
I understand ; it's logical but sad for the two PR (the other with the number of posts in a folder) you closed because uncomplet .

**Pull request closed without merging**
