### PR TITLE
(Desktop) Fixes #4769: highlight existing text in global search field 

### LINKED ISSUE #4769: highlight existing text in global search field
When using the shortcut (default: `CtrlCmd+Shift+F`) or the menu item `Edit > Search in all notes`, the focus is set to the global search field.

However, if there's already text in the field, the cursor is placed at the end and typing appends to the existing search term.

This change should highlight the current text, so that it will be replaced by the new search term.

/ref https://discourse.joplinapp.org/t/search-across-notes-selects-existing-search-terms/16252

# Before

gsf1

# After

gsf2

### PR DESCRIPTION
**Pull request by coderrsid**
Fixes #4769 

### Problem : 
When using the shortcut (default: CtrlCmd+Shift+F) or the menu item Edit > Search in all notes, the focus is set to the global search field. However, if there's already text in the field, the cursor is placed at the end and typing appends to the existing search term.

### Solution: 
This change should highlight the current text, so that it will be replaced by the new search term.

### Unit Test
Not required as it's a selection of text if the focus on input element.

### Manual Testing (after merging)

1. Use shortcut (default: CtrlCmd+Shift+F) or the menu item Edit > Search in all notes, the focus is set to the global search field.
2. If there's already text in the field, all the text in field is highlighted, and new characters will replace it.

## After
Screen-Recording-2021-03-30-at-3

### CODE REVIEW

**Comment by laurent22** [comment]
Please read the guidelines before posting a pull request. You didn't provide test units, didn't explain why they are missing, didn't provide steps to manually test. Just because it's obvious to you doesn't mean you can just ignore the guidelines.

**Comment by tessus** [comment]
He posted a video how it looks after. That is IMO the test case for this issue. 

(Only the before case was taken from my original issue.)

**Comment by coderrsid** [comment]
> Please read the guidelines before posting a pull request. You didn't provide test units, didn't explain why they are missing, didn't provide steps to manually test. Just because it's obvious to you doesn't mean you can just ignore the guidelines.

Ohh sorry laurent, didn't mean to do that. Obviously, i forgot to mention about the unit tests. Although if you look at description `PROBLEM`, those are the steps to test problem and solution. Although, i'll add them as bulleted points as needed. Didn't mean to ignore any, fault's on my side. On it already.

**Comment by tobiasb** [comment]
I'm just wondering, is there a plan to merge this anytime soon?

**Comment by coderrsid** [comment]
I'm thinking that too. Not able to make any other fixes too.

**Comment by laurent22** [comment]
Yes that looks good, thanks for the pull request @coderrsid.

**Pull request merged**
