### PR TITLE
Fix typos in translations (PL)

### PR DESCRIPTION
**Pull request by PiotrNarel**
Hi!

I found some typos in the Polish translation. This PR fixes them :)

### CODE REVIEW

**Comment by PiotrNarel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by PiotrNarel** [comment]
recheck

**Comment by 700grm** [comment]
LGTM

**Review by tessus — CHANGES_REQUESTED** [review]
Please revert the changes to the `.json` file. It is generated.

**Comment by PiotrNarel** [comment]
@tessus done :)

**Comment by tessus** [comment]
Hmm, it seems that you directly changed the file. 

You are supposed to use Poedit, otherwise unwanted errors can occur. e.g. you changed a "fuzzy" translation, which will never be used, becaused it has the status "fuzzy".
If you had used poedit, you would have seen it flagged as fuzzy and after translating it, it would have been a valid entry.

I will run the workflow, but please use poedit. As mentioned before, your translations of the strings marked as fuzzy won't be used.

**Review by tessus — CHANGES_REQUESTED** [review]
Please see my earlier comment.

**Comment by PiotrNarel** [comment]
Thanks for review. I looked at the pull request again. I see now why poedit marked the translation as fuzzy. I will add the correction in the next commit :)

**Review by tessus — APPROVED** [review]
Thanks for the update!

**Comment by mikey75** [comment]
Not my cup of tea but what is 'Urzytkowanik' ?

**Comment by PiotrNarel** [comment]
@mikey75 

image

There was probably an error in the previous translation. I made changes to an uncommented area of ​​the code. I'm working on improving the translation. I will make further corrections (in comment area also) in the next pull requests.

**Pull request merged**
