### PR TITLE
Documentation update: Add instruction for installing extension locally

### PR DESCRIPTION
**Pull request by bytrangle**
The process for installing extension in dev mode consists of only three steps, regardless of the browser platform. They are not meant to replace the very act of referencing the official documentation. However, I hope including these steps will make it easier for new contributors to get started.

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks but for this kind of info usually I link to an external official doc, because testing an extension in dev mode is not specific to Joplin. Are there maybe better links we could use for this?

**Comment by bytrangle** [comment]
@laurent22 A better link for installing extension in Chrome is at this [Getting Started tutorial](https://developer.chrome.com/docs/extensions/mv3/getstarted/). If readers follow the link that you gave, which is a FAQ page, they will have to get to the Getting Started page to understand how to install anyway.

**Comment by laurent22** [comment]
Indeed this link would be better. Would you mind changing the pull request to just update this link?

**Comment by laurent22** [comment]
Thanks for the update @bytrangle but could you change only the link? Because there are many other unrelated changes.

**Comment by laurent22** [comment]
As the pull request couldn't be merged in its current state, I've ended up manually adding the link you've provided. Thanks for looking into it.

**Pull request closed without merging**
