### PR TITLE
All: Update farsi/persian translation fa.po

### PR DESCRIPTION
**Pull request by mimeyn**
Hi,

Latest update for Persian language.

### CODE REVIEW

**Comment by laurent22** [comment]
Thank you for the PR but unfortunately there are some conflicts. If you could take a look and fix them that would be great

**Comment by mimeyn** [comment]
Thanks, @laurent22 ;

I changed  version of poedit multiple times for these conflict issues,
Which version of the poedit are you using to generate po files?
Can you send the download link of the specific version of poedit?🙂

**Comment by laurent22** [comment]
@mimeyn, I've just fixed the conflict on my side. Thanks for the updated translation!

**Comment by mimeyn** [comment]
Thank you so much, @laurent22 ❤️.

I apologize for this occurred conflict and for taking your time.🙏🙏

**Pull request merged**
