### PR TITLE
All: Translation: Update es_ES.po

### PR DESCRIPTION
**Pull request by Elaborendum**
Is this the correct way to do this? Sorry, I'm still pretty new at this.

### CODE REVIEW

**Comment by tessus** [comment]
Something is not right with this PR. There's a conflict that has to be resolved before it can be merged.
Also, you removed a translation (yes it was an old translation, but we keep them around.)

Please fix the conflict and then I'll review again.

**Comment by laurent22** [comment]
Closing for now, but please let us know if you'd like to complete the pull request and we'll re-open.

**Comment by tessus** [comment]
The OP fixed the conflict as requested.

**Review by tessus — COMMENTED** [review]
Everything looks good now. Thanks.

It seems that fixing the conflict also put back the deleted "old" translation. Cheers.

**Pull request merged**
