### PR TITLE
Desktop: Add support to open profile dir from options screen

### PR DESCRIPTION
**Pull request by johanhammar**
As discussed in https://discourse.joplinapp.org/t/feature-request-add-open-profile-directory-help-menu-item/11773/

### CODE REVIEW

**Comment by johanhammar** [comment]
I am not sure what is causing the check to fail. Any hints would be appreciated

**Comment by laurent22** [comment]
Sorry I hadn't realised that it would need this kind of code to get it working, and that's probably why I hadn't make it a link before. I'd rather keep the setting screen generic as the more we add bespoke code to it the harder it becomes to maintain it.

On that thread, it was mentioned that the link could be added to the Help menu. I think that's reasonable too. Would you be able to add it there instead? And by the way, to open a link please use `bridge().openItem(...)`. All calls to the main process need to go through this bridge because we'll probably have to refactor it all when Electron drops the remote package, as they are planning to do soon. And if it's all the calls are on the same class, it will be easier.

**Comment by tessus** [comment]
> I am not sure what is causing the check to fail. 

It has nothing to do with your code. The failing test has to do with the plugin system. Maybe a race condition or something, otherwise it would have failed for both runs.

> it would need this kind of code 

What do you mean by that? Is it too complex? Isn't there a way to build a generic function that allows to disply a link and then use a callback?
I'm just wondering how other apps handle this. While it makes sense to keep the code clean, there must still be a way to do that. I'm just curious. That's all.

**Comment by laurent22** [comment]
> What do you mean by that? Is it too complex? Isn't there a way to build a generic function that allows to disply a link and then use a callback?

There's always a way but I don't want to make the config screen logic more complex just for this.

**Comment by laurent22** [comment]
Thanks for the PR but I'll add the feature myself as it's faster than having to discuss everything single detail.

**Pull request closed without merging**
