### PR TITLE
Desktop: Fix drop cursor styling issue (#11336)

### LINKED ISSUE #11336: Drag and drop preview caret invisible in dark mode
### Operating system

macOS

### Joplin version

3.1.23

### Desktop version info

Joplin 3.1.23 (prod, darwin)

Client ID: 11cb0a2d420047cd9119a44d443e827c
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: b3ea127

Backup: 1.4.2
Note Statistics: 1.0.4

### Current behaviour

Version 3.1.22 fixed issue #11274 "Dragging and dropping text no longer shows preview caret", so that there is a drag-and-drop preview caret now, but it's black even in dark mode, which makes it nearly invisible:

https://github.com/user-attachments/assets/ef349bff-4f53-4555-94fc-647541ebdafd

It can be seen in the highlighted text, but nowhere outside of it.

### Expected behaviour

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by LEVIII007**
# Summary
This pull request fixes the drop cursor styling issue in the desktop editor. Previously, the drop cursor's color was inconsistent and difficult to configure. This change ensures the drop cursor's color is directly customizable and aligns with the app's theme settings.

Fixes #11336
 
Note
This pull request targets release-3.1.23

Demo after change : 
Screenshot showing the drop cursor in white colour while dragging a file in dark mode: 

https://github.com/user-attachments/assets/1046bf18-2f3d-4d2d-a1e9-9e967469266e

### CODE REVIEW

**Comment by LEVIII007** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
recheck

**Comment by LEVIII007** [comment]
@laurent22 It seems the action is unable to update the readme/cla_signatures.json file due to required status checks. All contributors, including myself, have signed the CLA as indicated in the comments, but this error is still blocking the checks.

Could you please take a look or advise on how to resolve this?

Thank you for your time and help!

**Comment by LEVIII007** [comment]
recheck

**Comment by laurent22** [comment]
recheck

**Comment by laurent22** [comment]
Looks good, thanks for the fix

**Pull request merged**
