### PR TITLE
Mobile, Desktop: Ukrainian translation

### PR DESCRIPTION
**Pull request by click0**
1. Minor translation errors have been fixed.
2. Added missing translation phrases.
3. Added translation for Android application.

### CODE REVIEW

**Comment by click0** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by tessus — CHANGES_REQUESTED** [review]
As explained in the docs https://joplinapp.org/help/dev/localisation the .po file has to be changed with Poedit.

The json files are generated and thus must not be edited.

**Comment by click0** [comment]
> As explained in the docs https://joplinapp.org/help/dev/localisation the .po file has to be changed with Poedit.
> 
> The json files are generated and thus must not be edited.

Too bad.
We'll have to convert the data from .json to .po ...

**Comment by tessus** [comment]
I am also not so sure about the 2 text files. I have never seen them added by a translation PR. Did you talk to Laurent or clarify that in the forum?

You can have a look at previous translation PRs: https://github.com/laurent22/joplin/pulls?q=is%3Apr+label%3Atranslation+is%3Aclosed

**Comment by click0** [comment]
I still see discrepancies in the original phrases between the .json and .po files. 
It seems that they were not added to the .po files.

> Did you talk to Laurent or clarify that in the forum?
I try not to communicate on forums.

P.S. I switched to other projects for translation.

**Comment by tessus** [comment]
> I still see discrepancies in the original phrases between the .json and .po files.
> It seems that they were not added to the .po files.

I think you got it backwards. The .po files are the source. The json files are generated from the .po files. If there are phrases in the json files that are not in the .po file, iy means those have been removed in newer code.

**Pull request closed without merging**
