### PR TITLE
fix for issue #430 - Ticked checkbox requires uppercase X

### PR DESCRIPTION
**Pull request by solariz**
Now upper and lowercase X is accepted for checking a checkbox.

### CODE REVIEW

**Comment by laurent22** [comment]
Does toggling the checkboxes work? I see that [X] is referenced in toggleTickAt too and maybe other places.

**Comment by solariz** [comment]
yes you are right, small x is a toggle issue. I will go through it.

**Comment by solariz** [comment]
ok I guess I got everything just one small thing I missing I can't find currently maybe you have a hint.
If the Checkbox is checked the MD text will change the color of the whole line in purple, if it is left open its green. Where can I find the formatting mechanism?

screenshot_2018-04-20_14-33-16

**Comment by laurent22** [comment]
The Markdown theme would have to be edited. Maybe something to report on the [Ace project](https://github.com/ajaxorg/ace)

**Pull request closed without merging**
