### PR TITLE
All: Update Mermaid: 8.12.1 -> 8.13.5

### PR DESCRIPTION
**Pull request by tessus**
I ran tests with a bunch of different Mermaid diagrams. I usually use these to test Mermaid releases.

So far I haven't seen any issues. There have been many fixes since 8.12.1, but the main concern for me were a few security issues that have been fixed.

### CODE REVIEW

**Comment by laurent22** [comment]
Could you remove the extra package-lock files please? I think we only need the one in /renderer

**Comment by tessus** [comment]
Ok, sure. I thought we always commit all that are changed because of this process. See 185ee9c89

But I'll remove them.

**Comment by tessus** [comment]
I will have to force-push though, since I had to reset the HEAD~2. (btw, I referenced the wrong commit in the last comment. I've updated it.)

**Comment by laurent22** [comment]
By the way, are you on npm 7? Because somehow npm reverted the package-lock to v1 in your pull request. And it's reverting it to v2 on my computer.

**Comment by laurent22** [comment]
Right, that makes no sense, but then again npm rarely does. Hopefully we'll have less troubles after the switch to yarn.

**Comment by tessus** [comment]
I checked, if there were any .npmrc in the source tree, but nope. At least nothing that came from me. 

```
[tessus@epsilon3 0 ~/work/joplin dev {upstream/dev} ↓·17|⚑3]$ find . -name .npmrc
./packages/server/node_modules/cmake-js/node_modules/npmlog/.npmrc
[tessus@epsilon3 0 ~/work/joplin dev {upstream/dev} ↓·17|⚑3]$ cat ./packages/server/node_modules/cmake-js/node_modules/npmlog/.npmrc
save-prefix = ~
proprietary-attribs = false
```

Yes, let's hope that yarn is better. Although I don't even know how to install yarn properly. Only yarn 1 is available on MacPorts and `npm install yarn` also shows only yarn 1. There's an npm package yarn2, but no yarn3. The corepack method seems a bit iffy, but I guess we'll find out what the proper way is to install and use yarn3.

**Comment by laurent22** [comment]
You should indeed use the corepack method to enable Yarn. You don't need to install it actually since it will be part of the repository (under the .yarn folder). That way we can be sure we're all working with the same version.

**Pull request merged**
