### PR TITLE
Update it_IT

### PR DESCRIPTION
**Pull request by Mannivu**
Further update of Italian translation

### CODE REVIEW

**Comment by tessus** [comment]
Thanks!

**Comment by livingc0l0ur** [comment]
Hi, I reviewed and finished the Italian translation, but I didn't understand how to upload the .po file; Can you help me?

**Comment by Mannivu** [comment]
> Hi, I reviewed and finished the Italian translation, but I didn't understand how to upload the .po file; Can you help me?

To upload a file, you have to fork this project, upload the file to your fork, then open a [pull request](https://docs.github.com/articles/using-pull-requests)

**Comment by livingc0l0ur** [comment]
Ciao Manuel, non so se posso scrivere in italiano, comunque ho provato a fare come hai scritto. Non so se ho sbagliato qualcosa (mi sono appena iscritto su GitHub). Questo è il link della richiesta di pull che ho aperto: https://github.com/livingc0l0ur/joplin/pull/1/commits/1002f5d59eb62e599c670f2e77564f332b49eb6b

**Comment by tessus** [comment]
Please have a look here: https://discourse.joplinapp.org/t/how-to-create-a-pull-request-pr/15052?u=tessus

**Comment by tessus** [comment]
Oh, just saw that you have already opened a PR. This happens, when you read your mails from oldest to newest.

**Comment by livingc0l0ur** [comment]
Hi Helmut, sorry if I made any mistakes but this is the first time I work on GitHub. @Mannivu helped me to open my first pull request.

**Comment by tessus** [comment]
No, all looks good. Thanks!

**Comment by livingc0l0ur** [comment]
Ok, It's a Pleasure!

**Pull request merged**
