### PR TITLE
fix(plugin-api): Add missing platform field from type definition

### PR DESCRIPTION
**Pull request by rxliuli**
document: https://joplinapp.org/api/references/plugin_api/interfaces/versioninfo.html

### CODE REVIEW

**Comment by rxliuli** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by personalizedrefrigerator** [comment]
Thank you for contributing!

Be aware that `packages/generator-joplin/generators/app/templates/api/types.ts` is auto-generated from `packages/lib/services/plugins/api/types.ts`:

https://github.com/laurent22/joplin/blob/8d8c91ef509ed7b3b4a2c6e4e9d342ecfe88a9a5/packages/lib/services/plugins/api/types.ts#L237

Because a similar change is already present in `lib/services/plugins/api/types.ts`, I suspect that the `generator` package's types need to be updated. [The updateTypes.sh script](https://github.com/laurent22/joplin/blob/dev/packages/generator-joplin/updateTypes.sh) should update them.

**Comment by rxliuli** [comment]
> Thank you for contributing!
> 
> Be aware that `packages/generator-joplin/generators/app/templates/api/types.ts` is auto-generated from `packages/lib/services/plugins/api/types.ts`:
> 
> https://github.com/laurent22/joplin/blob/8d8c91ef509ed7b3b4a2c6e4e9d342ecfe88a9a5/packages/lib/services/plugins/api/types.ts#L237
> 
> Because a similar change is already present in `lib/services/plugins/api/types.ts`, I suspect that the `generator` package's types need to be updated. [The updateTypes.sh script](https://github.com/laurent22/joplin/blob/dev/packages/generator-joplin/updateTypes.sh) should update them.

Yes, I've also seen the source file, but currently, the new project generated by yo joplin doesn't include the correct type definitions. Updating hasn't helped either.

https://github.com/user-attachments/assets/cbedb4da-53fb-48a4-9cbe-ae6c3d9bb77e

**Comment by personalizedrefrigerator** [comment]
> Yes, I've also seen the source file, but currently, the new project generated by yo joplin doesn't include the correct type definitions. Updating hasn't helped either.

This should be fixed by #10844.

A new version of [generator-joplin's NPM package](https://www.npmjs.com/package/generator-joplin?activeTab=readme) may also need to be released (`yo joplin` gets the template information from NPM).

**Pull request closed without merging**
