### PR TITLE
Desktop: Fixes #4162 : Added onDrop prop in ItemList.jsx

### LINKED ISSUE #4162: Custom sort does not work
Custom sort does not work : I can't manage to order my notes. Sometimes, a note refuses to move, sometimes it jumps quite randomly
 
## Environment
Joplin version:  1.4.18 
Platform:  Linux
OS specifics:  Ubuntu 20.10

### PR DESCRIPTION
**Pull request by Rishabhraghwendra18**
Fixes: #4162 
Description:
Since all notes are dragged & droped within the note list `div` container , which is this [file](https://github.com/laurent22/joplin/blob/80b16dd17e227e3f538aa221d7b6cc2d81688e72/packages/app-desktop/gui/ItemList.jsx) should have a `onDrop` prop which was missing . This PR added this prop in the file due to which now notes are responsive to move within 1-2 attempts, whereas before it takes more than 3 attempts to sort the notes.

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pull request. We need to know how to test this so please could you provide step by step instructions on how to replicate the bug (without your fix). And then we can try with and without your fix to check that it works.

**Comment by Rishabhraghwendra18** [comment]
You just need to sort the notes in a notebook just by dragging & dropping notes on top of each other .

## Without my fix
If we try to sort the notes just by dragging & dropping notes on top of each other , the notes refuse to get in order as shown in this [video](https://github.com/laurent22/joplin/issues/4162#issuecomment-857827201) in one of the issue's comment . 

You can clearly see that the note is refusing to move down once it got to top . You have to make more than 3-4 attempts to drop the notes at preferred location . 

## With my fix
With my fix , now it's possible to get the notes in the sorted order in 1-2 attempts . 

I have debugged the application and found out that whenever we try to sort the notes the application tries to refresh . If it's not able to refresh we will not get the notes in the sorted order otherwise we will get the notes in sorted order . The problem lies in the `div` container which has all the notes listed and within which we have to drag up and down the notes . The container doesn't have the `onDrop` event listener that's why notes are not getting into sorted order .

**Comment by Rishabhraghwendra18** [comment]
@laurent22 may you review my changes ?

**Comment by laurent22** [comment]
For me it works on desktop, so we'll need proper step by step instructions to really replicate the bug. Provide a JEX files with the relevant notes if needed.

**Comment by roman-r-m** [comment]
> For me it works on desktop, so we'll need proper step by step instructions to really replicate the bug. Provide a JEX files with the relevant notes if needed.

It's easy to see the problem if you have "Show uncompleted to-dos on top" enabled and have some to-dos in the folder.

**Comment by roman-r-m** [comment]
But I also managed to reproduce it without any to-dos:

https://user-images.githubusercontent.com/995612/141370587-ee35c728-f620-4eaf-a2bc-83c537da9677.mp4

**Comment by Rishabhraghwendra18** [comment]
> But I also managed to reproduce it without any to-dos:
> 
>  reorder-bug.mp4

may you tell me which joplin version are you using ?

**Comment by roman-r-m** [comment]
> > But I also managed to reproduce it without any to-dos:
> > reorder-bug.mp4
> 
> may you tell me which joplin version are you using ?

It was a custom build approximately matching this commit https://github.com/laurent22/joplin/commit/6879481fd58874278018df1eacd04cef27e62119

**Comment by Rishabhraghwendra18** [comment]
Ok... I now tested it again with v2.6.0 (without my changes) and it looks like this bug is fixed there . As I explained in the issue's comment that when we suffle the notes the app tries to refresh itself and I think this [function](https://github.com/laurent22/joplin/blob/80762572cf698cb75718810b045dcebb980359f9/packages/app-desktop/gui/NoteList/NoteList.tsx#L168) or this [function](https://github.com/laurent22/joplin/blob/f495db139171165246c696883fec0ad8e8084b31/packages/lib/BaseApplication.ts#L289) maybe are responsible for arranging the notes & refreshing the app .

Before released versions of 2.5.7 (on which I have reproduced the issue) this issue presists . Now looking at v2.6.0 , I think some changes in the code base has fixed the issue .

I made the PR because as I have seen lots of drag & drop tutorial in reactjs , the container div in which these notes are dropped should have `onDrop` prop

**Comment by roman-r-m** [comment]
> Ok... I now tested it again with v2.6.0 (without my changes) and it looks like this bug is fixed there . As I explained in the issue's comment that when we suffle the notes the app tries to refresh itself and I think this [function](https://github.com/laurent22/joplin/blob/80762572cf698cb75718810b045dcebb980359f9/packages/app-desktop/gui/NoteList/NoteList.tsx#L168) or this [function](https://github.com/laurent22/joplin/blob/f495db139171165246c696883fec0ad8e8084b31/packages/lib/BaseApplication.ts#L289) maybe are responsible for arranging the notes & refreshing the app .
> 
> Before released versions of 2.5.7 (on which I have reproduced the issue) this issue presists . Now looking at v2.6.0 , I think some changes in the code base has fixed the issue .

Nope, I can still see this issue on 2.6.1. It just takes a few attempts to reproduce

**Comment by laurent22** [comment]
I'd prefer to close this pull request for now, as I think we need a consistent way to replicate this, otherwise we can't really validate any fix.

**Pull request closed without merging**
