### PR TITLE
Desktop: Resolves #4433 md importer create resources for local files

### LINKED ISSUE #4433: Import of markdown directory only adds linked images
When importing Markdown from a directory I can successfully import linked images such as `image`. These get transformed into something like `image`. However, other files such as pdfs or pptx cannot be successfully imported. The link remains as is and the file cannot be opened from within Joplin.

## Environment

Joplin version: 1.4.19
Platform: Windows

## Steps to reproduce

1.  Create a directory with a markdown file refering to a non-image file within this directory.
2.  Import this directory into Joplin

## Describe what you expected to happen

The non-image file does not get imported.

### PR DESCRIPTION
**Pull request by JackGruber**
Currently only images are imported as a resource.
With this PR all local files are imported and linked as a resource.

### CODE REVIEW

**Review by laurent22 — COMMENTED** [review]
The code looks good, and thanks for converting the test unit to TypeScript. How does the feature work when you try to import a Markdown file that has links to remote URLs. Is it going to try to fetch all these remote pages?

**Comment by JackGruber** [comment]
There is no status for remote files, so they are not downloaded and images or files with a remote link remain unchanged. 

https://github.com/laurent22/joplin/blob/ffaed8f170f076405b709c19a42924d3f389ce20/packages/lib/services/interop/InteropService_Importer_Md.ts#L73-L75

**Comment by laurent22** [comment]
Thanks for clarifying. I wonder if we could explicitly skip URLs in this loop? As it doesn't feel right to stat URLs and maybe it could break in a future Node version (or worse, it could start working).

**Comment by JackGruber** [comment]
Ok, I just took a closer look.

Assuming the `*.md` to be imported is located in `c:\temp`, it prefixes each file with the directory `c:/temp`.

It tries to check the following files `c:/temp/http://www...` or `c:/temp/file://c:/temp/`.

What I have also just seen is that files which are specified with `file://` are not imported for the same reason.

I can add a filter for `file://` and `http*`, filter `http*` and import `file://` or leave it as it is.

**Comment by laurent22** [comment]
Hmm, no actually it's fine we don't need to support file:// and I was going to say you could check if the file exists before the `stat` call, but that's what `stat` already does and it's designed to return null if the file doesn't exist. So in the end it seems fine, I can't think of any issue with the way it's done now.

The rest of the code is good too, so let's merge. Many thanks for improving this feature!

**Pull request merged**
