### PR TITLE
Desktop: update to electron5.0.1

### PR DESCRIPTION
**Pull request by donaldtone**
1. update electron to 5.0.1
2. update some node modules to fix security issues
`npm audit` found 0 vulnerabilities

test in windows 7 pro, works OK.

### CODE REVIEW

**Comment by tessus** [comment]
Without testing all platforms and all functions updating Electron to 5.x is a very bad idea.

e.g.: see https://github.com/fsevents/fsevents/issues/273

**Comment by laurent22** [comment]
I'm surprised the diff is so small as I'd expect there will be various small issues to fix here and there. 

We also don't batch-upgrade modules without testing all the features concerned by these modules, especially if we're upgrading Electron at the same time (because if there's be a regression we won't know what is causing it).

**Comment by donaldtone** [comment]
In my opinion, Joplin as a production tool, it is better to avoid security issues.
It is a option to put "electron 5.0.1 and updated modules" to a new branch.
This new branch will focus in securities.
In this case, people is able to review and test in different systems.
Anyway, upgrade is necessary sooner or later.

**Comment by laurent22** [comment]
Yes if you could create a second PR with just the module upgrade that would be great, and please test anything that might be related to these upgrades.

And let's leave out the Electron and electron-builder upgrade for another time. I'd rather wait a few more minor versions because the last Electron upgrade was messy due to several regressions in Electron.

**Pull request closed without merging**
