### PR TITLE
Desktop: Fixes #3628: Add scroll offset for dragging notes while scrolled down

### LINKED ISSUE #3628: Scrolling breaks drag and drop reordering of notes
## Environment

Joplin version: 1.0.233
Platform: Linux
OS specifics: Debian 8

## Steps to reproduce
It seems farily common to have a notebook with more notes than can fit on one screen, such that the note list has a scrollbar. Let's say we have scrolled until the end of this list. When we try to drag and drop a note, it will be moved into the top of the list, sometimes even outside the currently visible area.

In the screenshot below, I have tried dragging a note titled "--- section header ---". You can see that the black bar indicating where it will be dropped is in a different position than the mouse.

joplin_drag_and_drop_scroll_not_working

This is because current implementation seems to be using window coordinates to determine the target position (indicated by the black bar in the UI). I guess it should be simple to fix, something like changing [MouseEvent.pageY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageY) to [MouseEvent.clientY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientY). I didn't look into the source code though, so this is just my speculation based on how drag and drop is usually implemented.

### PR DESCRIPTION
**Pull request by DarinDev1000**
The note dragging was not taking into account the scroll distance.
This caused the notes to be dragged to a different location than the mouse.
This scroll offset should fix that [issue](https://github.com/laurent22/joplin/issues/3628).

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the fix, that looks good. Unfortunately I've refactored the NoteList component in the coming UI update, so I prefer to wait till this is ready before merging your pull request, as it will be easier to fix the conflict at that time.

**Comment by DarinDev1000** [comment]
@laurent22 Do you want me to try to fix it in the ui-update branch instead of here?

**Comment by laurent22** [comment]
> Do you want me to try to fix it in the ui-update branch instead of here?

If you could do that, that would be perfect. I assume it's a matter of copying your fix to the new .tsx component.

**Comment by DarinDev1000** [comment]
I created another [pull request](https://github.com/laurent22/joplin/pull/3651) for the ui_update branch.

**Comment by laurent22** [comment]
Closing in favour of #3651

**Pull request closed without merging**
