### PR TITLE
Desktop: Fixes  #7662: Ctrl-X behaviour when no text is selected

### LINKED ISSUE #7662: Ctrl-X behaviour when no text is selected
## Environment

Joplin version: 2.9.17 (prod, win 32)
Platform: Joplin for Desktop
OS specifics: Win 10

## Steps to reproduce

1. Select some text, Ctrl-X, confirm it is in the clipboard by doing Ctrl-V
2. Go to any line of text, without selecting text, press Ctrl-X
3. Ctrl-V: it pastes nothing. 

## Describe what you expected to happen

- In other editors, if nothing is selected and Ctrl-X is pressed, it either (1) does not change the clipboard, or (2) cuts the whole line and puts it in the clipboard.
- Ideally, I would hope that if no text is selected then Ctrl-X would cut the whole line, as Joplin already has commands similar to other editors like VS Code that behave in this way to manage a whole line, e.g. move it up and down, delete the whole line, etc. 
- But if not possible to copy/cut a whole line, at least the clipboard should not be changed when using Ctrl-X on a line without anything selected. 

This is a follow up to #7602

### PR DESCRIPTION
**Pull request by melsonic**
### Before : 
- When some text is selected and `Ctrl+X` cuts the selected text and writes the selected text to the clipboard, but it replaces the clipboard text with an empty string when nothing is selected. 
- In other editors, if nothing is selected and `Ctrl-X` is pressed, it either (1) does not change the clipboard, or (2) cuts the whole line and puts it in the clipboard.
<br>

### After :
- when some text is selected
  -  `Ctrl+X` cuts the selected text and writes the text to the clipboard
- when nothing is selected
  - `Ctrl+X` cuts the entire line and writes it to the clipboard
  - Implementation details  : 
     - CodeMirror has a function `getCursor(n)` which returns the text string of line `n`
     - write the returned string to the clipboard using `clipboard.writeText(text)`
     - using `replaceRange(replacement: string, from: {line, ch}, to: {line, ch}, ?origin: string)` replace the current line with empty string
    
<br>

### Below a screen recording is attached 
[joplin-bug-fix-7662.webm](https://user-images.githubusercontent.com/88551650/219001408-461aaeac-d1f6-42d2-99c7-5f99f7fadf48.webm)

Fixes #7662

### CODE REVIEW

**Comment by melsonic** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/laurent22/joplin/blob/dev/readme/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

where to post the Pull Request

**Comment by melsonic** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
recheck

**Comment by laurent22** [comment]
Please remove all spacing changes. This should be applied via linter rules - and if the linter currently allows it, it should not be changed

**Comment by melsonic** [comment]
> Please remove all spacing changes. This should be applied via linter rules - and if the linter currently allows it, it should not be changed

Please check now @laurent22

**Comment by laurent22** [comment]
Ok that works well, thanks for implementing this @melsonic 

Edit: Let's wait till CI is done

**Pull request merged**
