### PR TITLE
Adding Hungarian translation

### PR DESCRIPTION
**Pull request by szokesandor**
Hello,
I have started to translate Joplin into Hungarian. Currently ~93% is done.
Would you be so kind to merge it?
Thanks

I have questions regarding translation:
1. I think I get the meaning, but really is the 't' and 'd' are mixed a bit in the following string?

Displays only the items of the specific type(s). Can be `n` for notes, `t` for to-dos, or `nt` for notes and to-dos (eg. `-tt` would display only the to-dos, while `-ttd` would display notes and to-dos.

2. can the eg. strings be localised? I could not find them.
Sorts the item by <field> (eg. title, updated_time, created_time).

Sandor

### CODE REVIEW

**Comment by tessus** [comment]
Thanks for the translation. 

To answer your questions. Yes, the source string looks wrong. But @laurent22 has to confirm that.
Changing the source string is always a problem, because it will invalidate all translations. And if I change the source string in all translations, the translations themselves will be wrong. Although that they already are, if the source string is really wrong.

Let's see what Laurent says.

As to your second question. No, those are field names and can't be translated. The CLI app expects the argument to be one of those exact terms.

**Comment by laurent22** [comment]
If there's something incorrect in the source string, that should indeed be fixed in a separate pull request.

**Comment by tessus** [comment]
@laurent22 right, but the question was, if you could confirm that the source string is wrong. (I can also create a bug report, but I thought it would be quicker to get the confirmation here.)

**current:** while `-ttd` would display notes and to-dos.

**should be:** while `-tnt` would display notes and to-dos.

If so, I can change it in the code and update the translations. I can even try to update the translated string in the language files.

@szokesandor I can merge the translation as it is (later today). We can look into the source string later.

**Comment by laurent22** [comment]
> If so, I can change it in the code and update the translations. I can even try to update the translated string in the language files.

Yes if you could do that, that would be great. The source string is indeed wrong and it should be like you said `-tnt`

**Comment by tessus** [comment]
@laurent22 great, will do.

@szokesandor thanks again for the new translation!

**Pull request merged**
