### PR TITLE
Android: fixes http-url image render

### PR DESCRIPTION
**Pull request by amitsin6h**
**"Android" Joplin app**
This change allows the image with http-url to be rendered
Reference of issue #2496 

below block of code from network_security_config.xml file was  causing the problem 
Link to Screenshot from 2020-02-23 18-57-37

### CODE REVIEW

**Comment by laurent22** [comment]
What was the previous code doing, and what is the new code doing?

What's the impact of this change for debugging with the the Android and iOS emulators? Can the app still connect to the packager?

**Comment by tessus** [comment]
This change basically allows to use http traffic at all times (even in the app in the Play Store).

But I agree, the OP should test debugging.

**Comment by amitsin6h** [comment]
@laurent22 @tessus  earlier the block of code inside the <domain-config> allowed the http request from the specific domain and the reason why we were not able to render the images with http-url and after removing the code it just means we don't want to load any specific http domain requests.

I also thought after removing the code will I be able to connect to the debugger or not ?, but I tested the packager after removing the code it still connects successfully.

The test debugging connects and has no problem.
Also, I read the below article I didn't found anywhere written that the app will use http traffic even in the Play Store. But yeah it will use http requests and that is needed to render http url images 
https://developer.android.com/training/articles/security-config

**Comment by tessus** [comment]
> that the app will use http traffic even in the Play Store

No, what I meant was that people can now use http, even when they download the app from the PlayStore.
I know that this change does not only allow people to fetch http images, but also to sync via http. Many will be happy about that.

It's just my personal opinion, but all http traffic should be banned. Even in a local network... it's not rocket science to get TLS working. Anyway, this PR will make a lot of people happy!

**Comment by amitsin6h** [comment]
@PackElend label me, please

**Comment by laurent22** [comment]
> @PackElend label me please.

@PackElend, I don't think people are getting what you mean :D I guess it achieves what you want anyway, but maybe that could be reformulated in the doc.

**Comment by PackElend** [comment]
> > @PackElend label me please.
> 
> @PackElend, I don't think people are getting what you mean :D I guess it achieves what you want anyway, but maybe that could be reformulated in the doc.

--> Mention @PackElend label me please, so that I can track your PRs by adding the label GSoC-2020

better?

**Comment by laurent22** [comment]
> --> Mention @PackElend label me please, so that I can track your PRs by adding the label GSoC-2020
> 
> better?

Yes sure, that's clear now.

**Comment by laurent22** [comment]
Ok thanks for the explanation @amitsin6h, and indeed it's good if it's now possible to use plain http images. I wonder if that would enable WebDAV http URLs too.

**Comment by tessus** [comment]
Yes, this will enable http webdav addresses too

**Pull request merged**
