### PR TITLE
Desktop: Resolves #6085 Add initial support for XDG Folder Specs

### LINKED ISSUE #6085: Joplin hard codes the ~/.config folder instead of following the XDG Directory Spec
This issue already existed here https://github.com/laurent22/joplin/issues/3765 and here https://github.com/laurent22/joplin/issues/887 but both were closed by the stale bot without any further progress. 

Implementing this is needed for alternative installation formats that utilize non hardcoded locations for their folders such as flatpak which stores it under ~/var/app/<app-id>/config

Implementing the base directory spec is a platform agnostic way to do this.

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

### PR DESCRIPTION
**Pull request by BeatLink**
This resolves #6085

This change adds the ability for Joplin to use the existing environment variables for XDG Base Directory Specifications. This allows the application to be flexible in alternate runtime environments such as flatpak, while additionally allowing the user to customize the default location of the profile directory according to their own XDG location preferences. 

This is just the initial change for the main folder. Ideally, further pull requests will implement more granular directory specifications such as XDG_CACHE_HOME, and XDG_DATA_HOME

### CODE REVIEW

**Comment by laurent22** [comment]
As far as I know there's already a flatpak package and it already works without this change? It's been like it is for many years and it worked fine, so I'm not keen to change it. I know some users prefer to have the config dir elsewhere but for this it's possible to use a symlink.

**Comment by BeatLink** [comment]
The flatpak package writes outside of its sandbox *because* this change isn't implemented. See https://github.com/flathub/net.cozic.joplin_desktop/pull/38#issuecomment-1025329443

**Comment by laurent22** [comment]
I'm not very keen to merge this at this point because I think there's some merit in having the app files always in the same location, and I think there should be a wider discussion on whether we really need to change this.

Also I believe there's bug: if someone already has the app running, and that env variable set, then when they install this new version, the app will look for the config in the wrong location, so the user will think that all their notes are gone.

There might be other such subtle bugs we haven't thought of so for now I prefer not to merge, but thanks anyway for looking into this.

**Comment by alexmo1997** [comment]
I urge you to please reconsider. Flatpak packages are not intended to have filesystem=host, it's just a workaround. Not having this fixed completely breaks the flatpak sandbox and is thus inherently insecure.

Edit: Also, joplin as it is kind of supports the xdg basedir spec, as it uses ~/.config, but doesn't really (as it doesn't use the env variable). Half supporting standards is never a good idea.
And as you already have a portable version, I don't think the argument of "having the app files always in the same location" really stands. Flatpak is a container, I'd think about it more as a portable version as a system-installed version.

**Comment by Daeraxa** [comment]
> I'd think about it more as a portable version as a system-installed version.

Not making comment on the flatpak or XDG discussion but this is already the case with the existing appimage, you just have to have a directory on your system called `Joplin-x.x.x.AppImage.home` (or whatever the name of the actual appimage is) and it will create the dirs it normally makes there instead.

Edit - did some more playing and it is a little weirder because the electron cache does appear to use $XDG_CONFIG_HOME.

- Download the latest (or any) appimage
- Create `Joplin-x.x.x.AppImage.home`
- Start the appimage

It creates a .config dir and within it the `Joplin` and `joplin-desktop` dirs.

However if you do the same thing with a `.config` dir instead then it creates the `Joplin` dir but uses your existing `~/.config`. 

`.home` uses `$HOME` but `.config` uses `$XDG_CONFIG_HOME` which explains the behaviour.

**Comment by BeatLink** [comment]
Couldn't all these problems be solved by simply just using the XDG Base Dir Specs? That standard was created to solve all of these various edge cases and different packaging formats. If not breaking the user experience is important, then joplin could simply implement a dialog that prompts the user to move their data from the hard coded locations to the new location when it starts up for the first time with the new changes.

**Comment by Daeraxa** [comment]
I personally agree but the proper area to have this discussion would be on the forum in the features category rather than in a closed PR as it is easier to discuss the implications of the change with a wider audience who can weigh in.

**Pull request closed without merging**
