### PR TITLE
Desktop: update isArm64 function

### PR DESCRIPTION
**Pull request by ifurther**
Using `process.arch` to detect the arch

### CODE REVIEW

**Comment by ifurther** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
This is to fix which bug?

**Comment by ifurther** [comment]
Fix the usage of process.platform, which indicates the operating system, and process.arch, which indicates the CPU architecture.

**Comment by laurent22** [comment]
> Fix the usage of process.platform, which indicates the operating system, and process.arch, which indicates the CPU architecture.

Which was causing which bug?

**Comment by ifurther** [comment]
In Github Action, the m1 machine didn't run the for loop
https://github.com/laurent22/joplin/blob/13a3c2ca74a6ac466feffa62f03068760a7d55c8/packages/app-desktop/tools/electronRebuild.js#L34-L41

**Comment by laurent22** [comment]
So keychain support is not working on macOS M?

**Comment by laurent22** [comment]
Sorry I'm not able to make an informed decision about this change since I'm not sure what is broken.

Feel free to comment again if you can describe exactly what's not working at the moment, or point me to the right GitHub issue

**Pull request closed without merging**
