### PR TITLE
[Docs] A few more GSoC ideas

### PR DESCRIPTION
**Pull request by roman-r-m**

### CODE REVIEW

**Comment by tessus** [comment]
Not sure, if I would mark 7 and 8 as difficulty level high. I believe they're either low or medium. Also, these 2 ideas are basically one. I think they can be combined, but maybe I'm wrong. Laurent, what do you think?

**Comment by laurent22** [comment]
It's hard to tell exactly how difficult a task would be. For example for the tablet layout idea maybe I'll set it to difficult instead of medium. I guess if there's a consensus one way or the other we can always update the difficulty at a later time.

For idea 7 I think we should mention that it should work on CLI too as it probably won't be a lot more work. Not sure about combining with 8, perhaps we could if idea 7 is not enough for a complete project.

**Comment by roman-r-m** [comment]
I guess the difficulty mainly depends on the skill set and experience of a student. For me they both seem hard but on the other hand 9 is medium.

In any case, changed both 7 & 8 to medium. Also added a note that export should work in CLI.

**Comment by roman-r-m** [comment]
I'm not sure if 7 & 8 are the same. For 7 a good candidate might be pdf.js but I'm not familiar with it enough to say if it could also be used to create pdf documents.

**Comment by tessus** [comment]
Sure, we can leave it as is for now. Firstly it's just an ideas document and secondly GSoC has not even started.
Thanks for the change! Let's merge.

**Pull request merged**
