### PR TITLE
Desktop: Close `Goto Anything` modal on outside click

### PR DESCRIPTION
**Pull request by coderrsid**
Issue fixed [Closing of Goto Anything modal](https://discourse.joplinapp.org/t/closing-of-modal-when-clicked-outside-of-it/7480/7)
Screen-Recording-2020-03-30-at-1 (1)

### CODE REVIEW

**Comment by tessus** [comment]
Did you test, if the modal still closes, when pressing `Esc`? What about other modal windows? Any side-effects?

**Comment by coderrsid** [comment]
Actually tessus, I've made changes only in the Goto Anything component and don't worry it won't affect any other component.

**Comment by laurent22** [comment]
Looks good, thanks!

**Comment by coderrsid** [comment]
Sure. 😄

**Pull request merged**
