### PR TITLE
Desktop: Fixed the nord theme layout background

### LINKED ISSUE #2961: Desktop : Layout in the nord theme has a different background.
## Environment

Joplin version: 1.0.195
Platform: Windows

## Steps to reproduce

1. In the editor, press Ctrl+L
2. The background of the layout is different

nord-theme-overlay-issue

It only persists in nord theme. In all other themes, it is consistent.Ex: In dark theme
joplin-dark

## Describe what you expected to happen
The background should remain consistent in the editor and layout.

### PR DESCRIPTION
**Pull request by Rahulm2310**
Before:
nord-theme-overlay-issue

After:
fixednord

fixes #2961

### CODE REVIEW

**Comment by coderrsid** [comment]
Why so many commits for a single line change. Can you please clear the branch ?

**Comment by BrainyBoi** [comment]
> Can you please clear the branch ?
I am unable to. Could you please help

**Comment by Rahulm2310** [comment]
> Can you please clear the branch ?
I am unable to. Could you please help

**Comment by coderrsid** [comment]
This is one of the best resource for learning about the commits CRUD in branches.
https://sethrobertson.github.io/GitFixUm/fixup.html
If you still don't get it, then i'll explain myself for sure.

**Pull request closed without merging**
