### PR TITLE
Desktop: removed gaps between NoteList and vertical resizers.

### PR DESCRIPTION
**Pull request by innocuo**
This change is based on proposed design updates I posted in the forums. [This is the related thread](https://discourse.joplinapp.org/t/some-design-suggestions-is-this-worth-implementing/2212).

I'm posting this as a different PR because I think it's the only change that could behave different in other operating systems than the one tested (I tested on MacOS 10.13.6).

### CODE REVIEW

**Comment by innocuo** [comment]
One interesting thing about the vertical resizers with this change: if you set their opacity to 1, the sidebar resizer doesn't work. This is because the NoteList renders on top of it. However, if you set opacity to 0 (which is the correct setting), the resizer renders on top of the NoteList.

[This stackoverflow question has a good explanation about what's going on](https://stackoverflow.com/questions/2837057/what-has-bigger-priority-opacity-or-z-index-in-browsers). It's not a bug or issue, it's completely expected. This behavior already exists on the current build, so I'm not creating or changing it, just taking advantage that the resizer already has an opacity of 0.

**Comment by tessus** [comment]
The space is used for the vertical scrollbar. If you remove this space, the scrollbar will paint over the notes' title text, won't it?

**Comment by laurent22** [comment]
Thanks, I'll need to test but I think that might work. @tessus, this is the vertical space for the "resizer" component. The vertical space for the scrollbar I guess should still be there with this change.

**Comment by innocuo** [comment]
the scrollbar is actually an issue on the right side (at least on mac). This is something I didn't think about, as I'm testing with very few notes.

The right side now competes for the scrollbar and the resizer. 
The left side works ok, because the sidebar scrollbar is next to the resizer.

So this PR won't quite work. A workaround to achieve the same "gapless" column would be to have the notelist panel draw the vertical grey bar, leaving the resizer to its right (so it'd be a similar layout to how the sidebar and its resizer). That way it wouldn't need a negative margin on the right

**Comment by laurent22** [comment]
I merged this before seeing your comment. In my test on macOS it looks fine - there's still room for the scrollbar (see below)

image

If you're having something different, could you post a screenshot that shows the issue?

**Comment by innocuo** [comment]
@laurent22 I added a new PR where I explain the issue at #1467 

Why does it say Appveyor error: build cancel on this and my previous PR though?

**Comment by tessus** [comment]
>Why does it say Appveyor error: build cancel on this and my previous PR
>though?

It seems there's been an AppVeyor problem for the last 3 days.

Laurent will have to look into it.

**Comment by laurent22** [comment]
AppVeyor messages can be ignored in general. In fact, I'd like to remove them from the GitHub UI because they are generally not relevant.

**Pull request merged**
