### PR TITLE
All: Fix basic search

### PR DESCRIPTION
**Pull request by naviji**
https://discourse.joplinapp.org/t/chinese-search-for-multiple-keywords-does-not-work-as-expected/12142

When searching for "地球 月球"

`const term = parsedQuery.terms[key][0].value` will only consider "地球".

Instead, since `parsedQuery.terms[key]` is an array of terms, we must first join them together to get a single term.

### CODE REVIEW

**Comment by naviji** [comment]
It seems this is intentional. There's a test case in `services_SearchEngine` that checks whether only the first term is considered.
Why is this needed?

```js
it('should support field restricted queries with Chinese characters', asyncTest(async () => {
    ...
    // For non-alpha char, only the first field is looked at, the following ones are ignored
    expect((await engine.search('title:你好 title:hello')).length).toBe(1);
}));

```

**Comment by laurent22** [comment]
Thanks for the fix @naviji. It's ready to merge but there's one conflict, which means you need to move your change to packages/lib

**Comment by naviji** [comment]
What about the failing test?

**Comment by laurent22** [comment]
Sorry I missed your earlier comment. I'm not sure actually, I think that was put in place for GotoAnything, but obviously a lot has changed about the search engine since then.

If you think this test no longer apply too, let's comment it out for now.

**Comment by laurent22** [comment]
Ok I'm not sure what to do about this pull request. Your fix seems to make sense and I don't know why there was this test from before. Let's merge and see if anyone complains :)

**Pull request merged**
