### PR TITLE
Mobile/iOS: Fixes #7469: Scroll NoteViewer markdown container instead of body/root

### LINKED ISSUE #7469: iOS: Note viewer inertial scroll is slower/stops earlier than native inertial scrolling
## Environment

Joplin version: 37ad9116593c8cc612835cb83ae18bf00487e0af, 2.9.1
Platform: Mobile
OS specifics: iOS 16 (iPhone), simulator and physical device

## Steps to reproduce

1. Create a long note
2. Switch to the note viewer
3. Scroll down from the top of the note (using inertial scrolling)
4. Open a long website (e.g. in Safari), scroll down using inertial (fling) scrolling
5. Compare scrolling behavior

## Describe what you expected to happen

Inertial scrolling behavior should be the same in the note viewer as in other apps.

## Screen recordings

https://user-images.githubusercontent.com/46334387/208219276-35481aa4-cc0c-4bfb-b084-70e536f07b4a.mp4

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
When the `body` or `html` elements scroll, inertial/momentum scroll behavior is different from such scrolling in other apps. With this PR, a `div` that contains the rendered note content scrolls instead.

Should fix #7469.

### CODE REVIEW

**Comment by laurent22** [comment]
In order to contribute to the project, it is now required to sign a Contributor License Agreement (CLA) as described in this announcement: [Joplin is switching to the GNU Affero General Public License v3 (AGPL-3.0)](https://joplinapp.org/news/20221221-agpl/). Your contributions will remain open source and you only need to sign this document once. Please download it from [here](https://github.com/laurent22/joplin/blob/dev/readme/cla.md) and send it over. If you have any question about it please let me know.

**Comment by laurent22** [comment]
recheck

**Comment by personalizedrefrigerator** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by personalizedrefrigerator** [comment]
recheck

**Comment by laurent22** [comment]
All good, thanks @personalizedrefrigerator!

**Pull request merged**
