### PR TITLE
Mobile : fixed the placeholder text color for the notebook title input in Edit Notebook screen

### PR DESCRIPTION
**Pull request by Rahulm2310**
The placeholder text for the notebook title input on Edit Notebook screen is visible in light theme but not on dark & OLED dark theme. So, this PR fixes that.

**Before:**
placeholderissue2

**After:**
placeholderissuesolve

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@PackElend please label me

**Comment by CalebJohn** [comment]
LGTM

**Comment by 098432960** [comment]
Pä Thy Bøy

**Comment by 098432960** [comment]
Pä Thy Bøy

**Comment by 098432960** [comment]
> Pä Thy Bøy

098432960
FB_IMG_1577300236897

**Comment by 098432960** [comment]
bongboksloy@gmail.com
FB_IMG_1577300236897

**Comment by laurent22** [comment]
Thanks @Rahulm2310, there was just one conflict that I've fixed now.

**Comment by Rahulm2310** [comment]
Thanks! @laurent22 @CalebJohn

**Pull request merged**
