### PR TITLE
Add more features to embedded pdf viewer

### PR DESCRIPTION
**Pull request by asrient**
## Major features added to the viewer

- Scroll progress persistence across re-renders.
- Zoom in/ zoom out.
- Print pdf.
- Download pdf.

## Fixes

- Fixes an issue where scroll progress is wrong on window resize or zoom in/out due to dimension of each page changing.

### Scroll progress persistence

This is done by storing and retrieving the scroll progress (scrollTop) of the viewer in SessionStorage. This means the progress of each viewer is lost only on app restarts.
For this to work we needed to assign a unique id to each viewers (links) that would remain same across re-renders which proved to be a bit challenging. Currently I'm generating the IDs following the convention: 
```
NoteId.resourceId.index
```
Where `index` is the n'th time that particular resource is appearing in that note.

This will have certain limitations when we have same resource referenced multiple time in the same note and their relative ordering changes, although it would be a rare use-case ([discussion](https://discourse.joplinapp.org/t/how-to-identify-elements-in-codemirror-uniquely/26564)).

## Demo

Screenshot 2022-08-12 at 11 03 40 PM

### Zoom and download
https://user-images.githubusercontent.com/44570278/184413082-a2d7bf01-29de-46fd-ad50-5367a3f3230c.mov

### Scroll persistence
https://user-images.githubusercontent.com/44570278/184413672-36b7ac69-e9bf-4876-9b9c-8e8488465d7f.mov

### Print
https://user-images.githubusercontent.com/44570278/184413966-f8d34dd1-5ca5-47ec-b72a-28ca0fc7d7e5.mov

## Links

https://discourse.joplinapp.org/t/coding-phase-week-7-report/26723
https://discourse.joplinapp.org/t/coding-phase-week-8-report/26820
https://discourse.joplinapp.org/t/how-to-identify-elements-in-codemirror-uniquely/26564

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks. Any reason these features are grouped together? Could there be one pr per feature?

**Comment by sdip15fa** [comment]
Hi, just some feedback, maybe print and download can be icons and scroll enabled by default?

**Comment by asrient** [comment]
> Thanks. Any reason these features are grouped together? Could there be one pr per feature?

I did this mostly to put these features out there as fast as possible, because these are some important missing features that people might complain about. Would you like me to create them separately?

**Comment by asrient** [comment]
> Hi, just some feedback, maybe print and download can be icons and scroll enabled by default?

Sure, we can have those buttons as icons. I think enabling scroll by default defeats purpose of having this feature in the first place. I think people wouldn't like their previously seen working pdf-view to get disabled when they were away working on someting else. Making them click it for the first time, makes them aware "you need to click it first to scroll". You can find more discussion on the intent and more here:
https://discourse.joplinapp.org/t/coding-phase-week-4-report/26446
https://discourse.joplinapp.org/t/coding-phase-week-2-and-3-report/26339

**Comment by laurent22** [comment]
> I did this mostly to put these features out there as fast as possible, because these are some important missing features that people might complain about. Would you like me to create them separately?

Yes please. It's a lot of work to review all this, and it helps to split it into smaller parts.

**Comment by laurent22** [comment]
Also if you could create that list of features so that we can track the progress and see what's left to do.

**Pull request closed without merging**
