### PR TITLE
Android: Fixes #7946: Sorting overlay window does not respect user theme

### LINKED ISSUE #7946: Sorting overlay window does not respect user theme
## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Set theme to Nord, let's say.
2. Click the döner menu on top right.
3. The sorting window appears all white in an otherwise Nordic theme.

## Describe what you expected to happen

Apply user theme to sorting window as well.

### PR DESCRIPTION
**Pull request by gitstart**
Fixes [#7946](https://github.com/laurent22/joplin/issues/7946)

Problem:
https://user-images.githubusercontent.com/89805719/226156535-109117c0-8894-4f5e-b8d9-f8b356dfaa81.jpg

Solution:
https://www.loom.com/share/e3076b0efe76470f8820543724f04122

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gitstart** [comment]
Hi @laurent22 
Would you mind reviewing this PR it is a great fix for #7946 
Thanks

**Comment by laurent22** [comment]
We would need to see screenshots for such a change, could you provide them please? And how does it look in portrait vs landscape mode?

**Comment by gitstart** [comment]
This will be updated soon @laurent22

**Comment by gitstart** [comment]
> We would need to see screenshots for such a change, could you provide them please? And how does it look in portrait vs landscape mode?


@laurent22  Here is the 
Before:
image
and
After:
https://www.loom.com/share/e3076b0efe76470f8820543724f04122

**Comment by laurent22** [comment]
Thanks for the providing the screenshot and video. The blue text on dark background is a bit hard to read and doesn't respect the WCAG contrast we aim for. Could you maybe change it white (or very light gray)?

**Comment by gitstart** [comment]
@laurent22 
This has been updated with the changes
and here is how it looks now on dark theme
image

**Pull request closed without merging**
