### PR TITLE
fix #572 - Translation submenu

### LINKED ISSUE #572: Translation Sub-Menu "sort notes by >"
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

### Description

concerns 

* "Updated date"
* "Created date"
* "Title"

#### 1rst try

I tried to add the (french) translation for the sub menu "sort by notes" which displays :

By adding them to CliCli/locale/fr_FR.po

```
msgid "Updated date"
msgstr "Date mise à jour"
```

But the build process erases the `joplin.pot` file and recreate it from the strings (surrounded by `_()`) it found in the source.

But as the strings come from calulated object, the translation process never found the string sand then never get the strings at all.

I spotted those string here :

```
ElectronClient/app/lib/models/Note.js:			user_updated_time: 'updated date',
ReactNativeClient/lib/models/Note.js:			user_updated_time: 'updated date',
```

the function is

```
        static fieldToLabel(field) {
                const fieldsToLabels = {
                        title: 'title',
                        user_updated_time: 'updated date',
                        user_created_time: 'created date',
                };

                return field in fieldsToLabels ? fieldsToLabels[field] : field;
        }
```

then `fieldToLabel` is used in a `toTitleCase()` function:
```
options[noteSortFields[i]] = toTitleCase(Note.fieldToLabel(noteSortFields[i]));
```
even with `_()` in 

```
options[noteSortFields[i]] = toTitleCase(_(Note.fieldToLabel(noteSortFields[i])));
```

does not do the trick.

#### 2nd try in `fieldToLabel`

I also try to use _()

```
        static fieldToLabel(field) {
                const fieldsToLabels = {
                        title: _('title'),
                        user_updated_time: _('updated date'),
                        user_created_time: _('created date'),
                };

                return field in fieldsToLabels ? fieldsToLabels[field] : field;
        }
```
then when building the translation, the fuzzy function translate that correctly and then comments them with '# ~ " 

```
# fuzzy
#~ msgid "updated date"
#~ msgstr "date mise à jour"
```

#### conclusion
I wanted to contribute but I think I reached my limit :) I feel that the build process of translation, in that specific case, does not allow to translate those string, but i'm not sure

### PR DESCRIPTION
**Pull request by foxmask**
Translation submenu

### CODE REVIEW

**Comment by laurent22** [comment]
The changes to the pot and po files is going to cause many conflicts unfortunately. To fix this issue we just need a commit with these three lines - https://github.com/laurent22/joplin/pull/575/files#diff-8aa7742258453cc6c613612ff3db2f35R20 And then they'll be picked up the next time all the translations are updated.

**Comment by foxmask** [comment]
So I just commit the 3 lines: 

```
			title: _('title'),
			user_updated_time: _('updated date'),
			user_created_time: _('created date'),
```

plus the french translation added to 


* ElectronClient/app/locales/fr_FR.json
* ReactNativeClient/locales/fr_FR.json

?

**Comment by laurent22** [comment]
In fact I've looked at it too quickly. Since I haven't built the translations in a while there was no conflicts so I've merged it. Thanks for the update!

**Comment by foxmask** [comment]
ok :) 
thanks

**Pull request merged**
