### PR TITLE
Desktop: Resolves #3529: Fix AppImage Icon

### LINKED ISSUE #3529: Joplin Appimage does not have correct Icon (Pop!_OS, Linux)
Hi, in this #https://github.com/TheAssassin/AppImageLauncher/issues/323#issuecomment-660677262 issue I already reported 
on the issue the author asked me to report directly in Joplin repo.

Joplin App does not have the correct application icon on my desktop panel (see screenshot). It instead uses a different one. Yet the icon in the Topbar is the correct one...

The author of AppImageLauncher suggested to analyze via  `appimagelint` - see log below.

What can I do against? Where are icons stored in Appimages? Please help. Thank you!

## Environment

Joplin version: 1.0.227
Platform: Linux 64Bit 
OS specifics: Pop!_OS 20.04

## Steps to reproduce

1. Install Joplin via Appimage and manage via Appimage Launcher
2. Open Joplin
3. Use Joplin normally

## Describe what you expected to happen
Joplin icon should appear on the left panel.

Screenshot from 2020-07-19 20-07-58

## Logfile

<pre><font color="#3465A4">appimagelint.cli[5281]</font> <font color="#06989A">[INFO]</font> Running check &quot;Icons validity and location check&quot;
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Extracting icon name from desktop file: /tmp/.mount_JoplinRIiES4/joplin.desktop
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/joplin.png
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#73C48F">✔</font>] Valid icon in AppDir root
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/.DirIcon
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#73C48F">✔</font>] Valid icon file in .DirIcon
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/usr/share/icons/hicolor/0x0/apps/joplin.png
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[ERROR]</font> <font color="#CC0000">Icon resolution doesn&apos;t match resolution in path: (0, 0) (file resolution is (256, 256))</font>
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[WARNING]</font> <font color="#C4A000">no other icons found</font>
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#F15D22">✖</font>] Other integration icons valid</pre>

### PR DESCRIPTION
**Pull request by Jesssullivan**
Appends  `&& update-desktop-database ~/.local/share/icons` in addition to `~/.local/share/applications`.  
Checked on Budgie 20.04 LTS.

@Tiger862000 Does this work for you on Pop!_OS?

### CODE REVIEW

**Comment by Jesssullivan** [comment]
Resolves #3529- just double checked from a Pop VM:
image

**Comment by Tiger862000** [comment]
@Jesssullivan and @laurent22 
Sorry for the delay my PC was broken
It did not work for Pop!OS. Encountered the same problem with another application.
I installed Joplin as an Appimage.
As a workaround I had to select the icon manually using the AppEditor tool

**Comment by Jesssullivan** [comment]
> @Jesssullivan and @laurent22 
> 
> Sorry for the delay my PC was broken
> 
> It did not work for Pop!OS. Encountered the same problem with another application.
> 
> I installed Joplin as an Appimage.

Are you installing the AppImage via the official Joplin install script?  
(Not AppImageLauncher or linter)

Icon installs correctly in a fresh PopOS VM.

**Comment by nullbasis** [comment]
I just installed version 1.0.242 via the official install script on the homepage, and the desktop icon wasn't installed.

**Comment by Jesssullivan** [comment]
> I just installed version 1.0.242 via the official install script on the homepage, and the desktop icon wasn't installed.

What OS?  Have you rebooted since installing?

**Comment by nullbasis** [comment]
Sorry, Ubuntu 20.04. I haven't rebooted, I don't usually need to do that when I install an appimage.

**Comment by Jesssullivan** [comment]
> Sorry, Ubuntu 20.04. I haven't rebooted, I don't usually need to do that when I install an appimage.

Screenshot from 2020-09-06 18-35-24
Hmm, cannot reproduce on 20.04- 
perhaps try a `sudo update-icon-caches /usr/share/icons/*`?

**Pull request merged**
