### PR TITLE
Desktop: Support executing codemirror commands when using execCommand

### PR DESCRIPTION
**Pull request by CalebJohn**
I was helping @tessus with something and it came up that this could be useful. And actually with the wording I think the previous behaviour was a bit confusing/wrong.

### CODE REVIEW

**Comment by CalebJohn** [comment]
The exact case that inspired this change was adding the `joinLines` command to the context menu.
```
await joplin.commands.execute('editor.execCommand', {
    name: 'joinLines',
});
```
CodeMirror has a [selection of commands](https://codemirror.net/doc/manual.html#commands) that are typically bound to keys, but can also be called with `codemirror.execCommand(name)`. These commands were previously inaccessible without using a contentScript. There is no change to executing codemirror functions, this just adds the ability to also execute commands.

A benefit of this is that will give plugin developers more power to control the codemirror editor without having to write a contentScript.

**Comment by laurent22** [comment]
Sounds good, and that would indeed be useful. I think it would be good to add some plugin documentation about this as it's a bit hard to discover. Maybe you could add a new section on top of JoplinCommand.ts (below the "Executing Joplin's internal commands" section) with an example? Also is there a list of the Code Mirror commands we support that we can point to?

**Comment by CalebJohn** [comment]
That's a good suggestion @laurent22 adding documentation was long overdue. It's done now, I didn't build the docs locally but they should be good to go.

**Comment by laurent22** [comment]
Looks good, thanks for the update and doc!

**Pull request merged**
