### PR TITLE
Overlap Removed

### LINKED ISSUE #2768: OK button Overlapped with Calendar
## Environment

Joplin version: 1.0.194
Platform: Linux

## Steps to reproduce

1. Go to any notebook
2. click on the alarm icon
3. click on the input field
Screenshot from 2020-03-16 11-08-52

## Describe what you expected to happen
Ok button should be clearly visible

Screenshot from 2020-03-16 11-22-08 (copy)

### PR DESCRIPTION
**Pull request by ishriom53tyagi**
"Desktop" for the linux app (Electron app)
fixes #2768

### CODE REVIEW

**Comment by ishriom53tyagi** [comment]
@PackElend can you guide me through how to resolve these falied test.Although it works fine in my localhost.

**Comment by laurent22** [comment]
Thanks but I don't think there's a requirement to have the ok button visible..

**Comment by PackElend** [comment]
so you close the but too?

**Comment by laurent22** [comment]
> so you close the but too?

Sorry what do you mean? This date dialog is a popup so there's no requirement that it aligns with anything, and in fact alignment would be lost if we change the styling, etc. I unfortunately don't see the value in this pull request which is why I prefer not to merge.

**Comment by ishriom53tyagi** [comment]
@laurent22   Is there any change we can do with this issue or should i close this issue??

**Comment by PackElend** [comment]
> Sorry what do you mean?

sorry I meant bug #2768 (too much answering to question today etc. 🙄 )

**Pull request closed without merging**
