### PR TITLE
Mobile: fixes the visiblity of "Path:" text

### PR DESCRIPTION
**Pull request by amitsin6h**
**Android Joplin app**
- This PR makes the "Path:" text visible properly  
- Reference of issue #2867 

Screenshot_20200323-153046

### CODE REVIEW

**Comment by amitsin6h** [comment]
@PackElend please label me.

**Comment by ishantgupta777** [comment]
Bro, can you please enter a text/path with big-name, I think that will also overflow, coz this is just because the screen size, the path is visible properly in my one plus 6 and the emulator I am using.
Screenshot_1584966598

**Comment by amitsin6h** [comment]
@ishantgupta777 so the problem is font does not auto-scale. Then we need to use % values everywhere in styles to make it responsive.

**Comment by ishantgupta777** [comment]
> @ishantgupta777 so the problem is font does not auto-scale. Then we need to use % values everywhere in styles to make it responsive.

I don't think that's an issue, we can slide those with our finger, so is there any need of fixing that path text?

**Comment by amitsin6h** [comment]
WhatsApp Image 2020-03-23 at 3 05 46 PM

See we can scroll to see the complete path from the Textinput but, the "Path: " will not be visible as you can see in the image. So giving it proper ratio fix the issue for every screen and that is what I did.

**Comment by laurent22** [comment]
Wrapping is weird on this one. Can't we just specific that the label shouldn't wrap letters (only words)?

**Comment by amitsin6h** [comment]
WhatsApp Image 2020-03-24 at 4 10 381 PM

The warping of the letter was due to the `marginRight: 20` in TextInput I just replaced it with `paddingRight: 20` it solved the problem. So, this way we don't need to use any fixed width and it will not wrap letter.

**Comment by amitsin6h** [comment]
> Wrapping is weird on this one. Can't we just specific that the label shouldn't wrap letters (only words)?
WhatsApp Image 2020-03-24 at 4 10 381 PM

The warping of the letter was due to the `marginRight: 20` in TextInput I just replaced it with `paddingRight: 20` it solved the problem. So, this way we don't need to use any fixed width and it will not wrap letter.

**Comment by laurent22** [comment]
> The warping of the letter was due to the marginRight: 20 provided to style of TextInput I just replaced it with paddingRight: 20 and it solved the problem. So, this way we don't need to use any fixed width and it will not wrap letter.

Ok that would be a good fix I think. Please could you apply it to your pull request?

**Comment by amitsin6h** [comment]
> > The warping of the letter was due to the marginRight: 20 provided to style of TextInput I just replaced it with paddingRight: 20 and it solved the problem. So, this way we don't need to use any fixed width and it will not wrap letter.
> 
> Ok that would be a good fix I think. Please could you apply it to your pull request?

Okay, I will do the changes in the PR
Thank you Sir

**Pull request merged**
