### PR TITLE
Update desktop.md

### PR DESCRIPTION
**Pull request by ScriptInfra**
- Adjusted general information location.
- Added title for png.
- Added steps to uninstall Joplin Notes on Linux (taken from the forum).

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks but we won't add these uninstallation instructions there, since we don't even have the installation instructions. I don't know where that should go, but at least not here.

**Comment by ScriptInfra** [comment]
> Thanks but we won't add these uninstallation instructions there, since we don't even have the installation instructions. I don't know where that should go, but at least not here.

Thanks @laurent22 - what do you think about adding it under the Installation section on the https://joplinapp.org/help/ page?

**Comment by laurent22** [comment]
I think it should be added as a command to the existing installation script.

**Comment by ScriptInfra** [comment]
> I think it should be added as a command to the existing installation script.

Thanks @laurent22 - Until the uninstall is scripted should we hold off on any documentation updates around it?

**Comment by laurent22** [comment]
Yes for now

**Pull request closed without merging**
