### PR TITLE
mobile: add version info

### PR DESCRIPTION
**Pull request by tessus**
This change adds the application version to the `Configuration` screen.

/ref #233

### CODE REVIEW

**Comment by laurent22** [comment]
Brilliant, thanks @tessus! By the way, if you wanted you could mention on the original version info module that you've created a fork. An issue with React Native is that many modules end up being abandoned, so other users might be interested in your recently updated fork.

**Comment by tessus** [comment]
@laurent22 yep, I mentioned my new repo in a ticket asking if the project was dead. After a week I got a reply that it was not dead and they closed the ticket. Yet, they only merge a few things, close others w/o further explanation. IMO the handling of that project sucks. That's why I created my own.

**Comment by laurent22** [comment]
Hmm, yes just saw their answer. It sounds like they simply want to keep ownership of the project since they're a company, but don't have time to actually maintain it. Maybe submit it to JS.coach if you want to give your module more visibility - there are several version packages but most of them are dead so a recently updated one would probably be accepted. https://js.coach/?collection=React+Native

**Comment by tessus** [comment]
great, thx for the info and link.

**Pull request merged**
