### PR TITLE
Mobile: Added functionality of adding due dates for todos and sorting on their basis

### PR DESCRIPTION
**Pull request by ishantgupta777**
I have added an option to add due dates for todos, which is like their expire date and time. And using that I am giving users the option to sort them.

The sorting mechanism I used for notes is:
1. incomplete todos with a less due date will be on top
2. incomplete todos with more due date afterward and then incomplete todos with no due dates.
3. completes todos with a less due date
4. complete todos with the more due date
5. complete todos with no due dates
6. notes ( sorted on their updated time, created time, id )

For this, I have added a new column in the notes table, **due_date**, which can be used further to add this feature in desktop also.

**For more info about this feature and the users who want this:**
[Discourse Link of Feature Request with GSoC-2020 label](https://discourse.joplinapp.org/t/feature-request-todo-expiration-dates-for-sorting)

**Link for release apk of Joplin with this feature**
https://drive.google.com/file/d/10q_Z04aeHSFbaCCdu-i5L34P2MOO94aJ/view

Here is the working of this feature:

sort_due_date_last

### CODE REVIEW

**Comment by ishantgupta777** [comment]
@laurent22  sir I am getting Travis error, again and again, is this because I added a new column to the notes table? I mean if I add any new column to any table, will Travis always give the error? Or are there any other reasons?

**Comment by laurent22** [comment]
You have a failing test on Travis with a clear error message. As a first step you'd need to check that error message, and try to replicate it on your machine.

You also need to make yourself familiar with the concept of database migration. There's a big comment on joplin-datababase.js that explains it, but you also need to know the basic concept to make sense of it.

**Comment by ishantgupta777** [comment]
> You have a failing test on Travis with a clear error message. As a first step you'd need to check that error message, and try to replicate it on your machine.
> 
> You also need to make yourself familiar with the concept of database migration. There's a big comment on joplin-datababase.js that explains it, but you also need to know the basic concept to make sense of it.

Thank you so much, sir, I fixed the errors and now all the test cases are passed. Please have a look whenever you are free.

**Comment by ishantgupta777** [comment]
@PackElend  sir can you please label me?

**Comment by laurent22** [comment]
I'm not able to review that to be honest. There was no spec so I don't know what was supposed to be implemented, and I see a new "due_date" note property which duplicates the existing "todo_due" property. I don't know how that will work with sync either, in particular for existing notes that don't have this property.

I think too much can go wrong, and too much work to get this pull request somewhere, so I'm sorry but I'd prefer to close.

**Comment by ishantgupta777** [comment]
> I'm not able to review that to be honest. There was no spec so I don't know what was supposed to be implemented, and I see a new "due_date" note property which duplicates the existing "todo_due" property. I don't know how that will work with sync either, in particular for existing notes that don't have this property.
> 
> I think too much can go wrong, and too much work to get this pull request somewhere, so I'm sorry but I'd prefer to close.

Sir, I implemented this feature because it was a GSoC labeled topic in the forum and also for the new due_date part, I think is right now, we can choose a date for notes when we want the alarm but due_date and alarm are two different things,  people will be able to choose a due_date for the notes/todos and sort them on that basis, so todos that needed to be completed early will show on top. 

Please see the request for this feature sir:
https://discourse.joplinapp.org/t/feature-request-todo-expiration-dates-for-sorting/2867?u=ishantgupta777
https://discourse.joplinapp.org/t/feature-request-todo-expiration-dates-for-sorting/2867/21?u=ishantgupta777
Rest is up to you sir. If you think that implementing this can break something, then closing this is okay.

**Comment by PackElend** [comment]
for the time being we must allow Laurent to use his time most efficiently. 
There is a lot of extra code what cannot be checked quickly. 

@ishantgupta777 you may ask in forum topic who can beta test this feature, to make sure that we don't break anything. 

> and I see a new "due_date" note property which duplicates the existing "todo_due" property.

you need also to clarify the difference mentioned by Laurent

for feature cases, try to read between the lines and think about it how to ease the situation for all the participants 😉

**Comment by ishantgupta777** [comment]
> for the time being we must allow Laurent to use his time most efficiently.
> There is a lot of extra code what cannot be checked quickly.
Sir, I totally agree with you and I am not asking to review it now sir. And If you all think that it can break anything than I am ready to fix and if required close it.

> you need also to clarify the difference mentioned by Laurent

Sir I already did in my last comment sir. The difference between current todo_date and due_date sir,. Did I miss anything sir?

> you may ask in forum topic who can beta test this feature, to make sure that we don't break anything.

Sir I already asked in the group and also send the apk there, but I didn't receive any response sir.
https://discourse.joplinapp.org/t/feature-request-todo-expiration-dates-for-sorting/2867/31?u=ishantgupta777

**Comment by PackElend** [comment]
> Sir I already asked in the group and also send the apk there, but I didn't receive any response sir.

wrong category, you find the beta test call here https://discourse.joplinapp.org/t/todo-expiration-dates-for-sorting/7916

> Sir I already did in my last comment sir.
so missed that but your sentence is far too long, it is very hard to read. Do shorter sentences and use line breaks, list etc. 
What you basically say is:
1. due_date 
have to be completed until this date
1. todo_due
it is just a reminder, an alarm to remind me to finish this todo 

isn't it?
Do you see how close the wording of these properties is in the sense of meaning?
You need to improve your wording to avoid misunderstandings

**Comment by ishantgupta777** [comment]
> > Sir I already asked in the group and also send the apk there, but I didn't receive any response sir.
> 
> wrong category, you find the beta test call here https://discourse.joplinapp.org/t/todo-expiration-dates-for-sorting/7916
> 
> > Sir I already did in my last comment sir.
> > so missed that but your sentence is far too long, it is very hard to read. Do shorter sentences and use line breaks, list etc.
> > What you basically say is:
> 
> 1. due_date
>    have to be completed until this date
> 2. todo_due
>    it is just a reminder, an alarm to remind me to finish this todo
> 
> isn't it?
> Do you see how close the wording of these properties is in the sense of meaning?
> You need to improve your wording to avoid misunderstandings

I got your point, sir, thank you so much. I cleared everywhere with the comments in the code. But I think a new name will be a better option.

**Comment by laurent22** [comment]
@ishantgupta777, the issue with this PR is that we didn't have a clear specification for it, and while we appreciate your efforts, the current implementation is not quite what we're after. More importantly, we don't know even what we're after because of the lack of spec so I'm not able to say what needs to be changed, and it's not currently high priority to implement this. For that reason, I'm afraid we're going to park this pull request for now.

**Pull request closed without merging**
