### PR TITLE
API: Adds ability to paginate data

### PR DESCRIPTION
**Pull request by laurent22**
This will be needed for plugins that process a large amount of data. In that case, we don't want to fetch everything from the database in one go but instead fetch one page at a time.

Unfortunately it will mean a number of breaking changes:

* `/folders` will no longer return a tree of folders but a flat, paginated list. To get the old behaviour back (still needed by the clipper), the `?as_tree=1` should be added to the URL.

* `/:resources` and `/:resources/:id/:link` calls will always return paginated data. Please see the doc for more info as well as a method to restore the old behaviour: https://joplinapp.org/api/references/rest_api/ (ADD ANCHOR)

* `/search` will also return paginated data.

### CODE REVIEW

**Comment by msbentley** [comment]
Hi @laurent22 - is there a way to get the joplin version using the API, or is the API versioned in some way? Just for future reference and to try and handle different versions in code. I guess these breaking changes will be few, so perhaps it doesn't matter, but just for information!

**Comment by laurent22** [comment]
No, I thought about it but maintaining multiple versions of the API would not be feasible, and indeed I hope not necessary as there should be few such breaking changes. In fact that's the only breaking change since the API was released but if I see that frequent changes are necessary, I'll investigate versioning.

**Comment by eromawyn** [comment]
At the moment : 
- perl-Joplin-API is unmaintened, and did not implement these API changes, as sciurius no longer uses Joplin : https://github.com/sciurius/perl-Joplin-API/issues/1
- python joplin-api is unmaintened, and did not implement these API changes, as foxmask no longer uses Joplin : https://discourse.joplinapp.org/t/joplin-api-python/1359/37

And myself, I am now starting to wonder if it a good idea to migrate to Joplin...

**Comment by marph91** [comment]
@eromawyn: If you are still interested, you could try out https://github.com/marph91/joppy.

**Pull request merged**
