### PR TITLE
Minor update in UI icon.

### PR DESCRIPTION
**Pull request by kartiksaxena532**
Mobile : Resolved a minor UI inconsistency for using a filled icon in the notes search tab!
most of the page in primary page used outline icons and the side navigation used the filled icons.
changed a bit of an inconsistency
Screenshot (410)
Screenshot (409)

replaced filled icon from the outline icon!

### CODE REVIEW

**Comment by kartiksaxena532** [comment]
recheck

**Comment by kartiksaxena532** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kartiksaxena532** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kartiksaxena532** [comment]
recheck

**Comment by laurent22** [comment]
Sorry I'm not sure this is better. Icons are indeed inconsistent but changing just one is not going to help. We need to review the whole app and make it consistent everywhere

**Pull request closed without merging**
