### PR TITLE
Revise and complete Norwegian translation (no) and rename to correct locale: nb_NO

### PR DESCRIPTION
**Pull request by matsest**
Completed the translation for Norwegian (bokmål) as well as renamed the locale to its [correct locale name](http://www.localeplanet.com/icu/nb-NO/index.html) in the documentation and .po file name.

If the renaming requires other changes in the source files, please comment and I'll revise the PR. 

Thanks for a great app.

-matsest

### CODE REVIEW

**Comment by laurent22** [comment]
Many thanks for the PR. The locale name change would need to be done in build-translation.js because that's what's used to automatically build the readme, website, flag links, etc. I might do it at some point but for now, I'll only merge the .po file.

**Comment by matsest** [comment]
Thanks @laurent22! I was not sure about those files in this case. I see that the generator failed to output the language to the README, index, etc as it's blank. 

Needs to be updated in
https://github.com/laurent22/joplin/blob/db6878b978b050b2d329bb3bcf1af08f9a032ccc/ReactNativeClient/lib/locale.js#L87

**Comment by laurent22** [comment]
Ok that will be fixed. I don't really get the story about no/nb. "nb" is the Bokmål language - is that basically the Norwegian language? If so, why not used the "no" code directly? Or are there more than one language in Norway? In which case should I display "Bokmål" instead of "Norwegian" in the list of languages?

**Comment by matsest** [comment]
Sorry, I should probably reasoned that more clearly. In Norway there are two official written languages, which are considered equal. It's bokmål (most common) and nynorsk, which have locales nb_NO nn_NO, respectively (language_COUNTRY form). The correct name for the latter  is 'Norwegian Bokmål'.

**Pull request merged**
