### PR TITLE
Mobile: Fixes #5705: do WiFi connectivity check, iff option is enabled

### LINKED ISSUE #5705: Only do the WiFi connectivity check if the associated option is enabled
In order to get the "Synchronise only over WiFi connection" option to work the mobile application checks for WiFi connectiviy on startup: https://github.com/laurent22/joplin/blob/fc64c8264c71a0f66eeb8f235ad3af984463518c/packages/app-mobile/root.tsx#L734

And doing so makes a call to "clients3.google.com": https://github.com/react-native-netinfo/react-native-netinfo/issues/212

If it's possible, this call should only happen when the "Synchronise only over WiFi connection" connection is enabled. Due to privacy concerns over using a Google URL for the check, we could also look at using an alternative.

### PR DESCRIPTION
**Pull request by tessus**
- set URL to joplinapp.org and make the check verify status code 200
- add a hidden (non public) Reachability URL setting for mobile, which bis set to `joplinapp.org`
- only add listener if the "sync only via Wifi" is set

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for looking into this.

> only add listener if the "sync only via Wifi" is set

The issue with this is that the user will need to restart the app for the setting to be active. This is not great UX and for those who rely on this it would be a regression. But the change of url otherwise is fine.

**Comment by tessus** [comment]
> The issue with this is that the user will need to restart the app for the setting to be active.

Yes, I mentioned this in the issue #5705 before I started this PR. Since I did not get an answer to that I thought it was ok.

**Comment by laurent22** [comment]
What do you want to do about this PR @tessus?

**Comment by tessus** [comment]
As mentioned in the issue:

_If we added a check before creating the listener at startup, the app would have to be restarted for a change (of "only sync via WiFi" setting) to be effective. Am I correct?
If so, is that ok? If not, what can be done? I checked the NetInfo docs and using a React Hook will still have the same problem._

I still do not know how to change it so that a restart is not necessary. On the other side, how many times will someone change that setting?

Merging the PR is better than ignoring the fact that the current code violates Joplin's privacy ambitions. Or we revert the commit that introduced the sync over Wifi only. Personally I don't care either way, because I have blockers and firewalls on all my devices. Not doing anything is not good for Joplin's image.

**Comment by laurent22** [comment]
Ok but for now we aren't going to merge this PR as it is so either we only do the url change, or we close it. It's to you.

**Comment by tessus** [comment]
Then we close it. I won't be responsible for a half-baked solution that goes against my opinion.

**Comment by laurent22** [comment]
Everything's urgent and critical depending on who you ask, but as a first step the url change would have been good, pending a more complete solution.

**Pull request closed without merging**
