### PR TITLE
Desktop: Use a proxy when variable GLOBAL_AGENT_HTTP_PROXY is defined

### PR DESCRIPTION
**Pull request by aviret**
This PR comes from the first [message and suggestion in the forum](https://discourse.joplinapp.org/t/development-implement-a-behind-a-proxy-sync-solution/1043) of bhlevca.

To test it, you could install a proxy with [mitmproxy](https://mitmproxy.org) os OSX: 

`$ brew install mitmproxy`

`mitmproxy --listen-host 127.0.0.1 --listen-port 8085`

Define variable GLOBAL_AGENT_HTTP_PROXY, then run:

$ export GLOBAL_AGENT_HTTP_PROXY=http://localhost:8085
$ ./run.sh 

Tests have been made on Linux and OSX. It's Ok with the notes, but I'm not sure with the resources files, complete tests are needed.

### CODE REVIEW

**Review by tessus — COMMENTED** [review]
This is a great start, but I think there are 2 issues:

- requires an env var
- only works for desktop app

How would you run this with the distributed app. e.g. on macOS? Do you go to the terminal, set the env var and start joplin via the command line?
I think this might be too complicated for people who are just used to clicking an icon.

So to fix this, we should add proxy options in settings. I can help with that, but we have to figure out how we can set the values for `global-agent` within Joplin without the need for an env var. That's more of a `global-agent` question than Joplin question.

As for the second part, I Think it might be ok to first only have this available on desktop, but we should  certainly figure out, whether we can use `global-agent` on mobile as well.

We will also need @laurent22's input on this.

**Comment by laurent22** [comment]
I agree with tessus, it should be done via an option in the config because the env variable is too technical and on Windows (60% of our users), setting a system env variable requires a reboot which is not exactly user friendly.

It's ok if it only works on desktop for now.

**Comment by aviret** [comment]
Thanks for you comments, and I agree that setting an env. variable is not easy for everybody, but as a Linux user, I will use this now. I will try to see how to add this parameters in the config screen, but this could take some time. BTW if we could have it in the config screen, I think it could be possible to move the bootstrap in the common part.

**Comment by tessus** [comment]
As I said, I can help you with the settings. What you can do is figuring out how to set the values with the `global-agent` package.

e.g. what happens, if the proxy requires a username and password? how do I set those things in the app? is there something like `global.username` I can set?

**Comment by aviret** [comment]
The config parameters could be updated after the bootstrap by `global.GLOBAL_AGENT.HTTP_PROXY='http://TEST:test@localhost:8085';`

If a username and password is needed, you could set them in the URL.
For the test with mitmproxy, start it like this
`mitmproxy --listen-host 127.0.0.1 --listen-port 8085 --proxyauth TEST:test`

**Comment by tessus** [comment]
Awesome, this was all I needed. I'll add the entries to the settings tomorrow. I also have to look into https, since most proxies use https. Also, I'm not sure how passwords are escaped. e.g. how would a password like `$%bla&:bla` be used? Or is it just not possible to use `:` or special characters in a password? The global_agent documentation is really lacking.

**Comment by tessus** [comment]
Yep, I found a way to use passwords with special characters.
I will open a new PR, but cherry-pick your first commit. I'll ask Laurent to do a merge commit instead of squash so that you'll have this commit attributed to you.

**Comment by tessus** [comment]
I still have to run some tests, but the code is there. I'll create a new PR with the changes soon.

**Comment by tessus** [comment]
Ok, after my tests I have to inform you that the global-agent package only works with http proxies.

This makes it utterly useless. No company allows an unencrypted proxy in their network. We can't use this. What sense does it make to add proxy support for proxy servers that are not used anywhere, except for testing in a home network?

I probably should have done these tests before implementing all the UI stuff and tests and whatnot.

**Comment by tessus** [comment]
Btw, you can have a look at the code, in case you are intereated how settings from the config screen are used: https://github.com/tessus/joplin/commit/f9436cb51f35abafbe19f652f55474b7ecc9e6ad

But I won't create a PR and I doubt Laurent will merge proxy support which is highly insecure.

**Comment by aviret** [comment]
Thanks for the code !

And I understand why this could not be merged ! Hopefully for me, we are behind an http proxy, so this is working, but until when...

**Comment by tessus** [comment]
@laurent22 what's your take on this? shall I close the PR?

**Comment by laurent22** [comment]
Yes I guess so. Why is it written everywhere on their GitHub page that it's a "Global HTTP/HTTPS proxy agent" if it doesn't support https?

**Comment by tessus** [comment]
`global-tunnel` supports https, which we can't use because it won't work with node 11 and above.

The `global-agent` package does not support https proxy.

**Comment by tessus** [comment]
Well, we can also add the http proxy and tell people that their data is not safe unless they use E2EE.

**Comment by tessus** [comment]
@laurent22 Anyway, please let me know what you want to do. Either way, I'll still open a PR and close it as abandoned. This way, somebody may pick it up again or can find it more easily when looking for a starting point.

**Comment by ImportTaste** [comment]
I think an advanced settings file for obscure power user stuff like this would be appropriate, I would personally be able to make use of this.

**Comment by laurent22** [comment]
Let's close this PR then, and if someone find a more reliable way they can start from here.

**Comment by GammaPi** [comment]
> useless

Actually, an http proxy support on desktop is not useless, because unencrypted http/socks proxy is often the inbound protocol of many encrypted proxy such as tor, shadowsocks, wireguard .etc. I'm using Joplin app image on Linux and it doesn't work with proxychains or system proxy. This makes Joplin hard to sync with services behind proxy. We just need to inform user that http proxy is not encrypted and let them use this with another proxy application.

#1117 related

**Comment by tessus** [comment]
It's actually a bit more complicated. A proxy can read your encrypted traffic. It doesn't matter, if your proxy runs http or https.

You can test this by running a mitm proxy and use it to proxy a connection to a https website. You will see all traffic to the https site in clear text.

I'm really not sure how to justify an option that compromises your data.

**Comment by ImportTaste** [comment]
> It's actually a bit more complicated. A proxy can read your encrypted traffic. It doesn't matter, if your proxy runs http or https.
> 
> You can test this by running a mitm proxy and use it to proxy a connection to a https website. You will see all traffic to the https site in clear text.
> 
> I'm really not sure how to justify an option that compromises your data.

My SOCKS5 server comes from PIA, whom have testified (under threat of perjury) that do they do not log anything: https://www.privateinternetaccess.com/helpdesk/kb/articles/do-you-log-2 _(Yes, I'm aware I could just perform all activities from behind a VPN, but it would not work well for my remote server's current networking setup.)_

My concern is keeping my activity from the eyes of an ISP that gets more overbearing every day.

**Comment by tessus** [comment]
> have testified (under threat of perjury) that do they do not log anything

I don't want to burst your bubble, but that's a lie. This is a US company which means they are required by law to add backdoors to their SW (at request and/or from the beginning). The question you have to answer for yourself: do you trust the US gov (or any gov for that matter)?

**Comment by GammaPi** [comment]
> It's actually a bit more complicated. A proxy can read your encrypted traffic. It doesn't matter, if your proxy runs http or https.
> 
> You can test this by running a mitm proxy and use it to proxy a connection to a https website. You will see all traffic to the https site in clear text.
> 
> I'm really not sure how to justify an option that compromises your data.

Thanks for your reply! But that is not the case. If I browse the web in the browser, say https://www.google.com and let the browser use an http proxy. The traffic should still be encrypted by tls and immune to MITM attack.

You can verify this exactly using mitm proxy. If you browse an https site, the browser will tell you that the certificate is wrong because mitm have to use an self-signed MITM certificate and your browser doesn't trust it. Using https over a http/socks tunnel will not decrypt your traffic. I guess you might trusted the certificate provided by mitmproxy or clicked "proceed to unsafe connection" in the browser, so it can decrypt all your traffic. But as long as you don't manually trust an MITM certificate (and that's the default) you will be fine.

Furthermore, as I stated earlier, users should use another local proxy application such as tor/shadowsocks/wireguard, in that case, all traffic is encrypted by another protocol and attackers even won't be able to know which site the user is visiting by sniffing their packets. 

If user visit an **http site** and use **http/socks proxy**, then sniffers can see **[which site the user is visiting]**+**[data the user exchange with web server]**.
If user visit an **https site** and use **http/socks proxy**, then sniffers can only see **[which site the user is visiting]**.
If user visit an **https site** and use **tor proxy**, then sniffers can only see **[the user is using tor service]**.

If user visit an https site and use tor/shadowsocks, then sniffers cannot tell whom this user is talking to or what the user is talking. Even if an attacker control the whole tor network/shadowsocks server, they can only see which the site the user is visiting, but not be able to decrypt https traffic without additional effort.

**Comment by ImportTaste** [comment]
> > have testified (under threat of perjury) that do they do not log anything
> 
> I don't want to burst your bubble, but that's a lie. This is a US company which means they are required by law to add backdoors to their SW (at request and/or from the beginning). The question you have to answer for yourself: do you trust the US gov (or any gov for that matter)?

If that were the case, [they wouldn't be in the middle of trying to make them](https://www.engadget.com/2019/07/31/how-ag-barr-is-going-to-get-encryption-backdoors/). Wherever you got your information is wrong, there is no legal requirement for VPNs to do that (yet).

**Comment by tessus** [comment]
@GammaPi 

> You can verify this exactly using mitm proxy. 

I said the exact same thing in a previous comment. You tested with the browser, I did it with Joplin (the PR I created and closed).
So please test with that branch and repeat your statement.

@ImportTaste You can't be serious. Things like those are used to keep customers happy. I couldn't find a canary on their web site and I wonder why. But.... yep, go ahead and trust them. Good luck.

**Comment by GammaPi** [comment]
> @GammaPi
> 
> > You can verify this exactly using mitm proxy.
> 
> I said the exact same thing in a previous comment. You tested with the browser, I did it with Joplin (the PR I created and closed).
> So please test with that branch and repeat your statement.

Thanks for your clarification! Sorry, I misunderstood your previous reply.

**Comment by tessus** [comment]
@GammaPi no worries. In the situation you described, your statement is theoretically correct.

However, please note that there are ways to get around these warnings in the browser or other clients as well. Keyword: ad-hoc cert creation (with a valid intermediary).

**Comment by ImportTaste** [comment]
> @ImportTaste You can't be serious. Things like those are used to keep customers happy. I couldn't find a canary on their web site and I wonder why. But.... yep, go ahead and trust them. Good luck.

They address the canary in the first article I linked you. The fact of the matter is they do get served warrants that they comply with... by telling the federal court that they have nothing to give them because they maintain no logs.

**Comment by GammaPi** [comment]
Today, I again encountered the scenario that webpage cannot be saved without a proxy.
I'll try to test your joplin+http proxy branch in your repo. @tessus

**Comment by GammaPi** [comment]
I can confirm tessus's test.
Joplin failed to realize the tls certificate is a self-signed one.
But this shouldn't be http proxy protocol's fault. I'm curious why Joplin don't verify https certificate as it is supposed to.

**Comment by piccobit** [comment]
Just my 2 cents and, please, correct me if I'm wrong, but the discussion shows a lot of misunderstanding how a proxy works:

HTTPS traffic is **NOT** proxied by using a _HTTPS_ proxy, because that really would involve a MITM, it is proxied using the [CONNECT](https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_tunneling) method. Only the initial connection request is HTTP - after that, the proxy server simply proxies the established TCP connection between the client and the HTTPS server:

> First and foremost, HTTPS uses SSL/TLS which by design ensures end-to-end security by establishing a secure communication channel over an insecure one. If the HTTP proxy is able to see the contents, then it's a man-in-the-middle eavesdropper and this defeats the goal of SSL/TLS. So there must be some tricks being played if we want to proxy through a plain HTTP proxy. 
> The trick is, we turn an HTTP proxy into a TCP proxy with a special command named CONNECT. Not all HTTP proxies support this feature but many do now. The TCP proxy cannot see the HTTP content being transferred in clear text, but that doesn't affect its ability to forward packets back and forth. In this way, client and server can communicate with each other with help of the proxy. This is the secure way of proxying HTTPS data.
> There is also an insecure way of doing so, in which the HTTP proxy becomes a man-in-the-middle. It receives the client-initiated connection, and then initiate another connection to the real server. In a well implemented SSL/TLS, the client will be notified that the proxy is not the real server. So the client has to trust the proxy by ignoring the warning for things to work. After that, the proxy simply decrypts data from one connection, reencrypts and feeds it into the other.
> Source: [Stackoverflow](https://stackoverflow.com/a/40885184)

**Comment by bernd-wechner** [comment]
> My SOCKS5 server (which I'm able to 'convert' to a HTTP proxy with [brook](https://github.com/txthinking/brook/issues/622#issuecomment-583830312))

I'm a late arrival, but have a SOCKS5 server and can browser through it using Firefox.  What I'd like to do is route Joplin though it, but it seems not to work. I wonder if this (your comment) is a clue as to why? Am new to this, and looked at brook but ther eis no simple documentation on it at all. I wonder if you'd be able to share a little about how you used brook to basically acts as a HTTP(S) proxy routing through a Sock5 proxy?

**Comment by bernd-wechner** [comment]
Worked out Brook, but alas it's nuked by bitdefender which I lack control over ;-). So it would be nice if Joplin could use a SOCKS5 proxy ...

**Pull request closed without merging**
