### PR TITLE
Android:  Fixes #6026: Long path in "Export profile" prevents tapping OK button

### LINKED ISSUE #6026: Long path in "Export profile" prevents tapping OK button
Having long value in the "Export profile" path, the UI formatting gets corrupted and it is impossible to hit the OK button.

## Environment

Joplin version: 2.6.8
Platform: Android
OS specifics: Android 12, Pixel 3a

## Steps to reproduce

1. Type long path in the "Export profile" field (longer than a screen width)
2. Try to hit OK to start the export.

## Describe what you expected to happen

image

The UI formatting is broken and the OK button is no longer accessible.

It is a minor issue, as the phone orientation can be changed to horizontal or shorter path can be used. However, I report it, as it would be probably somehow "easy" to fix, together with some other changes in the Configuration UI.

## Logfile

Not needed.

### PR DESCRIPTION
**Pull request by Tolu-Mals**
# Summary
This fixes #6026 . The ok button no longer moves out of the screen when you enter a very long export profile path.

### Steps to Manually Test:
- Open navbar
- Click "Configuration"
- Scroll down and click "Export profile"
- Type a really long path

<details>
<summary>Screenshots</summary>
<br>
Before:

ConfigBefore

After:
ConfigAfter
</details>

### CODE REVIEW

**Comment by laurent22** [comment]
Seems like a reasonable fix, but did you try in landscape mode? The flex weight I think means that it will take a percentage of the total width so I don't know how that will look. It might be fine, but please check and provide a screenshot.

**Comment by Tolu-Mals** [comment]
> Seems like a reasonable fix, but did you try in landscape mode? The flex weight I think means that it will take a percentage of the total width so I don't know how that will look. It might be fine, but please check and provide a screenshot.

Here's a screenshot:

AfterFixHorizontal 1

**Comment by laurent22** [comment]
Thanks, but it looks like it's not right then. The "Path" label as a static width now, but it should be dynamic because it's translated in other languages. Same for the "OK" button. Basically both "Path", and "OK" should simply fit to the text content. Only the path width should be dynamic.

As mentioned [here](https://github.com/laurent22/joplin/blob/dev/CONTRIBUTING.md#automated-tests), if you provide a manual testing plan, you should include 5 different tests, not just the one case that nicely works for you.

In this particular case, you should have included a test in portrait, in landscape, and in different languages.

**Comment by Tolu-Mals** [comment]
> Thanks, but it looks like it's not right then. The "Path" label as a static width now, but it should be dynamic because it's translated in other languages. Same for the "OK" button. Basically both "Path", and "OK" should simply fit to the text content. Only the path width should be dynamic.
> 
> As mentioned [here](https://github.com/laurent22/joplin/blob/dev/CONTRIBUTING.md#automated-tests), if you provide a manual testing plan, you should include 5 different tests, not just the one case that nicely works for you.
> 
> In this particular case, you should have included a test in portrait, in landscape, and in different languages.

Thanks for the feedback. I'll work on a better implementation and add the appropriate tests as well.

**Comment by Tolu-Mals** [comment]
I noticed that "OK" and "Path" aren't being translated at the moment. Would it be okay to include that in this pull request?

**Comment by laurent22** [comment]
Right, it's true it's not, and no we aren't going to translate it. So you just need to test in landscape and portrait then.

**Comment by Tolu-Mals** [comment]
Screenshots:
<br>
Potrait:

Potrait 1

Landscape:

Landscape 1

**Comment by laurent22** [comment]
So what's your thoughts on that OK button floating there on the right?

**Comment by Tolu-Mals** [comment]
> So what's your thoughts on that OK button floating there on the right?

It doesn't look too good. I'll apply a marginLeft: auto to that.

**Comment by Tolu-Mals** [comment]
> So what's your thoughts on that OK button floating there on the right?

It doesn't look too good. I should be able to apply a margin to move it to the edge.

**Comment by Tolu-Mals** [comment]
### Update:
<br>

Landscape:
Screenshot_20220406-140400_Joplin 1


Potrait:
Potrait_new 1

**Comment by Tolu-Mals** [comment]
Update:
<br>

Landscape:

Screenshot_20220406-140400_Joplin 1


Potrait:

Potrait_new 1

**Comment by laurent22** [comment]
Thanks @Tolu-Mals. I think it's still not quite right because the text field doesn't take the full width, but that's good enough I guess, and I'm not sure it's possible to do any better.

**Pull request merged**
