### PR TITLE
Desktop: added more shortcuts and a menu/toolbar item for mark

### PR DESCRIPTION
**Pull request by tessus**
I fixed the disabled shortcut on macOS. It was set to an empty string, which results in an error on macOS.
Thus I changed it to null, as it was set for Linux/Windows.

~~I have added the following menu item and tool bar item:~~

~~- Mark~~

I have added the following shortcuts and their default

- New notebook (disabled)
- New sub-notebook (disabled)
- Export to PDF (disabled)

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pull request but we won't add non-standard Markdown shortcuts like Mark, as I prefer to keep the core lean, and variations to be made by plugins. The other changes are fine but please remove the default shortcut for Export to PDF.

**Comment by laurent22** [comment]
Thanks, but now that I see these commands with null shortcuts, I think there's a problem.

The command service was implemented in such a way that all commands are available in any context, the goal being that you can list them even if they are not currently active. I think I had the keymap editor in mind when I've made it that way but somehow that got lost along the way and we're manually adding null shortcuts to that list. Instead, we should fetch all the command names from the service, and automatically add them to the shortcut editor.

I'll have a look at it, and that means we won't need to manually add null shortcuts every time we add a new command.

**Comment by tessus** [comment]
Yep, this makes sense. I just followed the previous example for Print, which was disabled by default. It never came to me that we could just read the command service array.
A lot of the refactoring went by me, so I have to familiarize myself with the code again.

**Comment by laurent22** [comment]
Ok that should be fixed in 45024149343d93953b00ab75c368064486b29bf9

**Pull request closed without merging**
