### PR TITLE
DESKTOP : Added a Markdown-it plugin to support embedded youtube videos

### LINKED ISSUE #2706: Create a Markdown-it plugin to support embedded videos
Videos would be embedded like so:

    [My YouTube video](https://www.youtube.com/watch?v=StTqXEQ2l-Y)

So it is valid Markdown that works as a simple link by default.

However, when the plugin is enabled, it would parse the Markdown links in the page and, when it is a video, display a video player. For now, we only need to support YouTube, but the code should be generic enough to add more video platforms later on.

### PR DESCRIPTION
**Pull request by Rishabh-malhotraa**
fixes #2706 

I added the plugin for embedding a youtube video, 
if the plugin is selected in the options menu then the title `(youtube)[https://www.youtube.com/embed/pDmYNK68IEc]` would convert it into.

`<iframe width="560" height="315" src="https://www.youtube.com/embed/pDmYNK68IEc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

I've tried to make the plugin really modular so it new video sites can be added really easily, as of right now it only supports youtube, but other video players can be easily added!

## CHANGES

embed-video

embed-video-2

### CODE REVIEW

**Comment by Rishgod** [comment]
@PackElend label me, please.

**Comment by laurent22** [comment]
I had a quick look but it seems quite complicated and I don't understand most of it at this point.

I thought all it needed to do is get the YouTube URL from the link_open rule, then create a YouTube iframe from it. Why is there for example a tokenizer class? Why is fence rule changed?

**Comment by tessus** [comment]
Hmm, I was just wondering, if it would make sense to create a `markdown-it-embed-youtube` plugin like the other `markdown-it-xxx` plugins on npm. e.g. https://www.npmjs.com/package/markdown-it-mark 

In this case, it is a markdown-it plugin, which we only load into Joplin. This has 2 advantages. The package can be used by everyone who uses markdown-it and the dev gets more exposure.

But maybe it's just a dumb idea.

**Comment by Rishgod** [comment]
Yes that's actually a really good idea, @laurent22 @tessus, rather than adding this plugin to rules folder, how about I publish this plugin on my own github and then joplin pull it from npm. (this will encapsulate all the markdown-it api documentation which might be tricky for people who did not read their docs(believe me it's tricky even for people who read their docs >.<) )

**Comment by laurent22** [comment]
I agree with this, also if you could answer my questions:

> Why is there for example a tokenizer class? Why is the fence rule changed?

For me this feature can be implemented in 20 lines or so, but there's more than 100 lines in there and it's not clear what it's for. I'm afraid I won't merge code I can't make sense of even if it works.

**Comment by laurent22** [comment]
Ok I found that most of this code was copied from there:

https://github.com/nkjmsss/bend-editor/tree/462eab4e3525255186a2ddec3b750f11262632c2/src/components/editor/markdown-it/plugin/blockEmbed

Borrowing code is fine, but that's something you should tell us. It also explains why there's a bunch of unrelated code, and from your lack of answers I'm guessing you don't know either what this code does.

Closing this for now until the pull request can be reduced to only what's needed.

**Comment by PackElend** [comment]
@Rishgod would you mind take a stance on what is said by laurent.
Transparency and honesty is not negotiable.

**Comment by Rishgod** [comment]
>@Rishgod would you mind take a stance on what is said by laurent.
Transparency and honesty is not negotiable.

@laurent22 @PackElend It's my bad, I should have been more transparent about the source code,
I'll keep that in mind from next time onwards.
 Um about the explaining the source code, I can do it right here, but yes you are right about the files containing a lot of unnecessary info, I'm working on a better solution to this, I'll explain my approach when I make a PR to the same

**Comment by Adi-Shuji** [comment]
Hi @Rishabh-malhotraa , Where can I download the plugin from?

**Pull request closed without merging**
