### PR TITLE
Update Katex to v0.12.0

### PR DESCRIPTION
**Pull request by ThatcherC**
I want to use bra-ket notation to write some notes about quantum stuff. Joplin's current Katex dependency is 0.11.1, which does not support this notation. Katex 0.12.0 (the current stable release) does support this notation, so I propose to update Joplin's dependency to the new version.

### CODE REVIEW

**Comment by tessus** [comment]
The last time we update KaTeX it broke a few things.

Did you use the updated KaTeX module in your local Joplin instance for a while?

**Comment by ThatcherC** [comment]
I haven't used my local instance much yet - all my notes are in an instance of the stable release of Joplin right now. 

What kind of problems did you see before? Are there specific things I should look out for, or just any unusual-looking math rendering?

Ideally we could have a reference Joplin note that made use of a lot of Katex behavior, and then manually or automatically check how that renders with new Katex versions.

**Comment by tessus** [comment]
I really can't recall the specifics, but some basic Katex functionality was broken after the update.

Unfortunately we don't have any automated tests for Katex. Such a note would be of great help, but we don't have it. We'd need input from users. So, if he had a few examples what people are using most, it would certainly help.

**Comment by laurent22** [comment]
In v0.11, they had a few breaking changes which they had documented but we forgot to check. In this release it looks like the only breaking change is support for IE 9/10 going  away so we should be good. https://github.com/KaTeX/KaTeX/releases

**Pull request merged**
