### PR TITLE
Update wording for font settings

### PR DESCRIPTION
**Pull request by CalebJohn**
ref [forum](https://discourse.joplinapp.org/t/testing-v1-8-1-editor-font-editor-font-settings/16233)

The current wording is a bit confusing.

### CODE REVIEW

**Comment by dpoulton-github** [comment]
## Suggestion

**Editor font family**

This is the font used for the main body text within the Markdown editor. If the font is incorrect or empty Joplin will default to using a generic proportional font. A proportional font is one where the width of a character varies depending on the letter typed.

*(This assumes that Joplin should default to a proportional font as it currently does in the v1.8.1 pre-release)*

**Editor monospace font family**

This is the font used for specific types of text within the Markdown editor that require a monospace font to display legibly (tables, checkboxes, code). If the font is incorrect or empty Joplin will default to using a generic monospace font. A monospace font is one where the width of a character is identical for all letters typed.

**Comment by amandamcg** [comment]
I like explaining how these are used, it also confused me. Here's my take  –  made it a little shorter and put it under a single header to be clear that they are related.

---

# Markdown Editor

## Font Size
[ 15 ] px

## Default Font Family
Used for display text. If not found, a generic proportional (variable width) font is used.

## Monospace Font Family

Used where a fixed width font is needed to lay out text legibly (e.g. tables, checkboxes, code). If not found, a generic monospace (fixed width) font is used.

**Comment by CalebJohn** [comment]
Thanks @dpoulton-github  and @amandamcg 

I ended up updating to use @amandamcg's wording. AFAIK it's not possible to add headings to the settings menu. It would be nice to have headings to organize settings better, but I think that will have to come in a separate pull request.

**Comment by laurent22** [comment]
Great, thanks for clarifying the description.

**Pull request merged**
