### PR TITLE
Mobile, Resolves #3872: Enable background sync

### LINKED ISSUE #3872: background sync on mobile devices
There are various issues ([1](https://github.com/laurent22/joplin/issues/727), [2](https://github.com/laurent22/joplin/issues/1029), [3](https://github.com/laurent22/joplin/issues/1501), [4](https://github.com/laurent22/joplin/issues/1645), [5](https://github.com/laurent22/joplin/issues/3671), …) and threads ([1](https://discourse.joplinapp.org/t/android-background-sync-interval/1746), [2](https://discourse.joplinapp.org/t/automatic-sync-on-phone-app/3056)) on it but it's still not clear to me what exactly isn't technically possible to implement regarding this.

[This comment from September 2018 says](https://github.com/laurent22/joplin/issues/727#issuecomment-418877957):

> Cannot currently be fixed due a limitation of the underlying framework

Which might be true but that's what libraries are for, right?

And [this comment from October 19](https://discourse.joplinapp.org/t/automatic-sync-on-phone-app/3056/8) claims:

> we rely on existing libs, which for now don’t exist on React Native

But it doesn't mention _which_ exact libraries would be needed. The logic for syncing is obviously already there. So in theory only the support for doing exactly this sync in a background task would be needed.
And there are libraries for react-native that are doing exactly this since a few years. For example
* [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch) for Android & iOS (first version from August 2016)
* [`react-native-sync-adapter`](https://github.com/ferrannp/react-native-sync-adapter) using the Android SyncAdapter (first version from April 2017)
* [`react-native-background-task`](https://github.com/jamesisaac/react-native-background-task) again for Android & iOS (first version from February 2017)
* [`react-native-background-job`](https://github.com/vikeri/react-native-background-job) for Android (available since December 2016)

Also there's [this comment from June 2019](https://github.com/laurent22/joplin/issues/1645#issuecomment-500384473)

> Most likely not possible. Android phones these days have services that kill off apps that aren't used, whether you want to keep them running or not. https://dontkillmyapp.com/

Well,

1. it only affects certain vendors in an extreme way. Not every phone is affected.
2. The exact same website you mentioned shows some workarounds for this issue.
3. Apps are usually killed after a while — not immediately. So Joplin could probably still sync for a while until it would be killed.
4. Some FOSS apps which are showing notifications while they are running doesn't seem to be affected (or at least doesn't be to seem affected so often). For instance [DNS66](https://github.com/julian-klode/dns66) or [personalDNSfilter](https://github.com/IngoZenz/personaldnsfilter).

I would obviously understand if the issue would only be the lack of people working on this. In that case this issue could be kept open for tracking, avoiding duplicates and having the possibility to show this issue for possible contributors, so that they know what's still open.

But currently the given answers are at least somehow lacking some information (or not relevant / true).

Thus it would be great if someone could clarify what's really missing here.

**PS:** Thank you for your work!

### PR DESCRIPTION
**Pull request by camgraff**
## Overview
I recently started using Joplin and am loving it so far. However, the lack of background sync bothered me and seemingly a few others as well, see:
#3872 
https://discourse.joplinapp.org/t/android-background-sync-interval/1746/43
https://discourse.joplinapp.org/t/background-synchronization-sync-for-ios/10472

This PR aims to get a working implementation of background sync on both Android (working) and iOS (wip, see below).

## Solution Details
I used [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch) to handle scheduling the recurrent background syncs. NOTE: there is a limitation that these background jobs can only run at best every 15 mins and are limited to ~30 seconds of execution time. So, for long running syncs this still might not be adequate. 

Even with this library, a challenge is that **callbacks to `setTimeout` and `setInterval` do not run reliably if the app is in the background**. The callbacks will not be run until the app is brought back to the foreground.

Conveniently `setTimeout` and `setInterval` are [already in the `shim`](https://github.com/laurent22/joplin/blob/ebf92605aeabbd686d57952ab6b946d2db8dcf27/packages/lib/shim.ts#L293-L299). So, we can override these functions to check if the app is currently in the background and if so, just run the callback immediately instead.

## Testing
For testing this in an emulator, there are [instructions in the README of `react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch#debugging-1). 

I have tested on Android and **this is working in the emulator and on a real device**. I have noticed that the background sync does not always run at the scheduled intervals though. Sometimes, I will only get a sync every 30mins or 1hr instead of 15 mins. I suspect this is due to Android killing the app in the background, but am still looking into it more.

For iOS, the only task remaining is to [link `react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch/blob/master/docs/INSTALL-AUTO-IOS.md). However, I have no way to test on iOS, so if someone else wants to handle this let me know! Otherwise, I can try to find the time to set up my work Macbook for testing.

Also, if anyone has suggestions for how to set up some automated tests, that would be great. I'm new to mobile development, so feedback is always appreciated!

### CODE REVIEW

**Comment by roman-r-m** [comment]
Does the sync only run when the app is running?

**Comment by camgraff** [comment]
> Does the sync only run when the app is running?

On Android it should run regardless. That's what these lines do https://github.com/laurent22/joplin/pull/4925/files#diff-b30ec16beba186d84c76e720993c1b30c83e2ede06fe0248555a3582d95587e7R130-R131

On iOS, based on [this issue](https://github.com/transistorsoft/react-native-background-fetch/issues/225#issuecomment-591200260) it looks like the sync will not run if the app has been killed.

**Comment by laurent22** [comment]
Seeing how unreliable background tasks are I'm not sure we should add this. People will rely on this and expect it to work, except half of the time it won't, so I'm not sure the situation would have improved.

**Comment by roman-r-m** [comment]
> On Android it should run regardless. That's what these lines do https://github.com/laurent22/joplin/pull/4925/files#diff-b30ec16beba186d84c76e720993c1b30c83e2ede06fe0248555a3582d95587e7R130-R131

I thought you need to set up a headless task to run the sync without starting the whole app.

**Comment by camgraff** [comment]
> I thought you need to set up a headless task to run the sync without starting the whole app.

I think you're right and I misread the docs. We would need to set up a headless task to run background tasks after app termination. Those lines that I link just ensure that the background *events* are fired, but those events are not necessarily handled if the app has been terminated by the user.

**Comment by camgraff** [comment]
> Seeing how unreliable background tasks are I'm not sure we should add this. People will rely on this and expect it to work, except half of the time it won't, so I'm not sure the situation would have improved.

Obviously it's your decision as the maintainer. But, even if it only runs half as often as scheduled, then most of the time your notes would be up to date as soon as you open the app and would avoid waiting for that initial sync which seems like an improvement to me.

**Comment by roman-r-m** [comment]
> > I thought you need to set up a headless task to run the sync without starting the whole app.
> 
> I think you're right and I misread the docs. We would need to set up a headless task to run background tasks after app termination. Those lines that I linked just ensure that the background _events_ are fired, but those events are not necessarily handled if the app has been terminated by the user.

Exactly.

If you're interested, I've tried it here https://github.com/roman-r-m/joplin/tree/background-sync-diy though it's far from complete. And at that point I was mostly interested in how to get headless JS working with Android's WorkManager which is the recommended way of running such tasks.

**Comment by camgraff** [comment]
> > Seeing how unreliable background tasks are I'm not sure we should add this. People will rely on this and expect it to work, except half of the time it won't, so I'm not sure the situation would have improved.
> 
> Obviously it's your decision as the maintainer. But, even if it only runs half as often as scheduled, then most of the time your notes would be up to date as soon as you open the app and would avoid waiting for that initial sync which seems like an improvement to me.

Also, at least for Android I believe we can bypass a lot of the OS throttling of background tasks using [`forceAlarmManager`](https://github.com/transistorsoft/react-native-background-fetch#config-boolean-forcealarmmanager-false) which would make the background sync much more reliable, if that's desired.

**Comment by roman-r-m** [comment]
> There's little doubt there will be hard to fix bugs with this feature too since it happens in background. For example I don't know how it works but maybe sync will happen in one thread in the background, then the user opens the app and sync starts in a second thread, but the app doesn't support multiple sync operations running at the same time. I don't know if it's possible but I expect there will be many annoying bugs like this to look at.

While I agree that only code that does not have bugs in the code that is never executed, I also think that the mobile apps are one of the strongest selling points for Joplin, for example when compared to Obsidian and others. It certainly was for me when I was switching from OneNote. And the situation when people have to install an app to keep the screen open just to let Joplin sync is not very nice.

**Comment by laurent22** [comment]
> I also think that the mobile apps are one of the strongest selling points for Joplin, for example when compared to Obsidian and others. It certainly was for me when I was switching from OneNote. And the situation when people have to install an app to keep the screen open just to let Joplin sync is not very nice.

This is true, and the mobile app is and has always been very important, but on the other hand we have to be realistic and do with what we have. If what we have is unreliable background sync, then I prefer not to add it. Same for the editor, this is top priority for me, but the beta editor we've added at some point had too many problems so was removed.

I don't think we should settle on half solutions - if we can't do something properly then it's best not to do it at all. Just look at the BoostNote mobile app - they had plenty of features, but it was so buggy and hard to maintain that no-one wanted to work on it anymore so they had to drop it. Let's try not to get there with Joplin mobile and weight our options carefully.

**Comment by laurent22** [comment]
Thanks for making this change, but as mentioned earlier I'd prefer to close the PR as I'm not confident with merging this at this point.

**Comment by alexanderadam** [comment]
> Seeing how unreliable background tasks are I'm not sure we should add this.

Well, background sync works most of the time pretty well for most apps, doesn't it?
And some apps that have difficulties are adding some disclaimer, for instance linking to https://dontkillmyapp.com/ where workarounds are described for nearly every particular vendor. I'm sure Joplin could link to it as well, on the settings screen where background sync could be activated, right?

> People will rely on this and expect it to work, except half of the time it won't, so I'm not sure the situation would have improved.

Well, even _if_ it would only work in 50% of all cases, this would be 50% more than it is now, because we have now roughly 0% working background sync, right?
People usually expect note taking apps with some kind of "cloud integration" to do a background sync.

> Additionally it means we'll have forever bug reports about sync not always working in the background and we won't be able to fix it.

A bug report like #3872? :wink:
I read about people wanting this since years (I linked some posts in the ticket in case you're curious).

> If what we have is unreliable background sync, then I prefer not to add it.

Joplin currently has an unreliable sync in general since it's _not_ very obvious that Joplin stops syncing only because the screen goes off. 
Would you be fine if your messenger or your email client would stop syncing if your screen goes off? Would you consider this obvious, reliable and a good user experience? :thinking: 


Or [how @tangodev summarizes this](https://github.com/laurent22/joplin/issues/3872#issuecomment-814491633):
> "Babysitting" a sync is just sad.


Would it a possibility to at least consider it to activate it via feature switch / setting in the similar way the beta editor was tested?
Or would it be possible to provide some API endpoints that would allow to add this functionality as a plugin (are plugins possible in the mobile build :thinking:)?

If both answers are "no": what is missing in particular that you would consider merging this? I mean, [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch#react-native-background-fetch---) itself seems well maintained and matured after all and [over thousand GitHub projects are relying on it](https://github.com/transistorsoft/react-native-background-fetch/network/dependents?package_id=UGFja2FnZS0xODE0NTY2Ng%3D%3D), so I guess it's probably not too unreliable then, right?

**PS:** @laurent22, thank you for Joplin and @camgraff thank you so much for giving this a shot! :rocket:

**Comment by tangodev** [comment]
Two things:

1) Did the "state of the art" change enough that a new, drop-in solution exists?
2) If not, I propose that **some** solution gets implemented. Currently there's no information, because there's no feature to test. And without information the Fear stays and no feature gets implemented. And so this cycle continues for years and every few months someone files a bug or finds existing ones and gets (rightfully so) upset. We need **something** so we can generate feedback.

**Comment by alexanderadam** [comment]
> 1. Did the "state of the art" change enough that a new, drop-in solution exists?

I mean, currently [1,157 other projects](https://github.com/transistorsoft/react-native-background-fetch/network/dependents?package_id=UGFja2FnZS0xODE0NTY2Ng%3D%3D) are using this exact same library that was included in this PR.
Not included the projects that are not open source or hosted somewhere else than GitHub.

But Laurent also wrote

> If what we have is unreliable background sync, then I prefer not to add it.

Since iOS and Android sync depending on usage patterns and might not sync at all if you don't open an app for a while, this implies that a sync is always "unreliable". You can't predict the timing or duration of a sync.
Hence Laurent _implicitly_ said that he won't ever merge anything regarding background sync (_at least as long Android & iOS are integrating battery optimization_).

But then again, [Laurent also wrote in October 2019 that libraries for sync doesn't exist although they existed for a long time](https://github.com/laurent22/joplin/issues/3872#issue-715689835). :shrug:

**Comment by gal064** [comment]
@laurent22 is there any way to get you to reconsider?

This is a critical feature and not having it makes the mobile workflow so much harder. When I open the mobile app, I (i) need to wait for it to sync (ii) make the changes (iii) manually invoke sync and wait before closing the app.

My suggestion, especially given a PR already exists, is to deploy this feature as beta and see how well it works. I think that's the best path forward for two reasons:
 * even if the sync works randomly only 25% of the time, that's still a huge win. We can just set the sync to be more frequent than we'd like (e.g. 15 minutes instead of 1 hour)
 * Deploying it in beta will allow us to measure the reliability. If you get a ton of bug reports, then you can easily revert. But, if people are happy and don't even notice some syncs are missing, than we can just keep it.


Happy to help preparing the PR

**Comment by semyl** [comment]
> Joplin currently has an unreliable sync in general since it's not very obvious that Joplin stops syncing only because the screen goes off.
Would you be fine if your messenger or your email client would stop syncing if your screen goes off? Would you consider this obvious, reliable and a good user experience? 🤔

I'll just chime in to second this and say that when I started using Joplin, I was losing data because I didn't realise the mobile app _wasn't_ syncing in the background. And so I ended up with a bunch of confusing conflicts (and sometimes still do, even though I try to be particularly careful now to wait for the sync to Complete when both starting the app, and finishing editing a note). 

It isn't ideal, and is one of the main reasons I avoid using the app (Android) unless I absolutely have to. 

I notice patterns and so adjusted my behaviour according to how the app "works" so that I'd get a mostly reliable experience. But there are also going to be Joplin users (or potential users) who won't notice that and instead will just lose content into the Conflicts folder, leading them to not trust Joplin.

**Comment by tangodev** [comment]
> I notice patterns and so adjusted my behaviour according to how the app "works" so that I'd get a mostly reliable experience. But there are also going to be Joplin users (or potential users) who won't notice that and instead will just lose content into the Conflicts folder, leading them to not trust Joplin.

This is a much bigger issue than us, techies, are willing to admit. The "regular user" has no investment and no incentive to use Joplin (unlike us, the top 1% of users, the power users etc.). This is esp. true in the beginning, when one is just trying out the Joplin ecosystem (i.e. desktop, mobile and data storage).

Not having proper sync is a deal breaker for most people and only the most loyal and emotionally invested (us) are willing to put up with this. Because we believe in data privacy, open standards etc. But the casual user has little knowledge about that and they'll just end up pissed and go to Evernote or whatever.

This is extra problematic, since now, Joplin has its 1st party cloud offering, Joplin Cloud. Imagine this sales pitch: "great note-taking program, does not sync with mobile unless you invent crummy workarounds and bend your workflow to them. So it's not a great program". Laurent, I assume, wants Joplin Cloud to be successful, but this is a dealbraker for anyone using mobile any consistent amount. The weakest link (mobile version) ends up pulling down the rest of an otherwise great product.

While I understand the desire of the team to give users a robust experience and the (justified) fear of maintaining something that may turn out to be kludge'y, I can **not** wrap my head around the resistance towards *at least trying*.

**What is there to lose by having an alpha/beta feature hidden with a toggle so that us, the power users, can test this and generate feedback?**

**Comment by danepowell** [comment]
Android supports sync adapters natively, or at least it did the last time I wrote one, it was really pretty straightforward: https://github.com/danepowell/honeydew-android/blob/main/app/src/main/java/com/danepowell/honeydew/sync/GrocerySyncAdapter.java

I don't know anything about react native, but I have to imagine it supports shipping custom components like this... hopefully? 🤞

**Comment by gal064** [comment]
@laurent22 Any thoughts given the comments above.

I think it's totally fair if your opinion still holds, but I think it's worth getting a proper resolution.

**Comment by NikEyX** [comment]
I am also disappointed with the fact that currently no background sync solution being offered. I'd rather take a half-baked solution that works 50% of the time, than no solution at all. As others have said: big disclaimer with "this is an alpha feature" should be adequate.

With that in mind, I don't know about React Native, but there are several ways to have background sync working in native Android which I would assume should work if the workload can be kept under 30 secs. If that doesn't work (which it should, even if not 100% reliable), one could consider a workaround where you create a foreground service (with START_STICKY flag), which ensures that the process can work in the background. The drawback of this is that you'll have a notification up the whole time, which can be hidden manually. This would be a totally acceptable "fix" for the meantime. Can anyone with React Native knowledge chime in if this is feasible?

**Pull request closed without merging**
