### PR TITLE
"Fixes #6292" for Notebook icon does not show in 'Move to Notebook' dropdown menu

### LINKED ISSUE #6292: Notebook icon does not show in 'Move to Notebook' menu
Notebook icons are not appearing in Move to Notebook(below image) menu.
bug-pic

## Environment

Joplin version: 2.7.15 (prod)
Platform: Linux
OS specifics: Ubuntu 20.04 LTS

## Steps to reproduce

1. Make a notebook with some icon
2. Make a note/todo and right click on it.
3. On clicking dropdown menu it shows list of notebook without icons.

## Describe what you expected to happen
Notebook icons should be displayed in the drop down list.

### PR DESCRIPTION
**Pull request by BalanaguYashwanth**
**Desktop: "Fixes https://github.com/laurent22/joplin/issues/6292" for Notebook icon does not show in 'Move to Notebook' dropdown menu**

- "Desktop" for the macOS (Electron app) tested, but didn't have windows/linux device to test.

**Before Fix**
image

**After Fix**
image

### CODE REVIEW

**Comment by laurent22** [comment]
Too many problems here, so I'd rather not merge, sorry

**Comment by BalanaguYashwanth** [comment]
Let me remove those conflicts and raise another time

**Comment by laurent22** [comment]
Please don't. We haven't decided if we're doing GSoC next year and we have no resources for PR review at this time

**Comment by BalanaguYashwanth** [comment]
This is small change to solve this bug via this PR, Can you give me one chance, 

Won't push any change that makes conflicts. Only push main changes

**Pull request closed without merging**
