### PR TITLE
Update Croatian translation

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by milotype** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by laurent22** [comment]
thanks!

**Comment by tessus** [comment]
@laurent22 are we ok to remove old translations now? j

**Comment by laurent22** [comment]
Oh sorry we're not actually. @milotype, I will revert, but please resubmit and don't remove the old translations

**Comment by laurent22** [comment]
<s>Reverted in https://github.com/laurent22/joplin/commit/d18a4be31ff6578c48526e3c743508425a0dc2fd</s>

**Comment by laurent22** [comment]
Reverted in 1071a455b6c7f47e434a9a709fa5808f29988bb3

**Pull request merged**
