### PR TITLE
Desktop: scroll to selected folder/tag in the list

### PR DESCRIPTION
**Pull request by roman-r-m**
Resolves https://github.com/laurent22/joplin/issues/4885

### CODE REVIEW

**Comment by laurent22** [comment]
Hmm, yes this is not an obviously correct behaviour I think. We implement this and two months later someone opens an issue asking to not scroll the sidebar when jumping with GotoAnything because they lose their context (VSCode for example doesn't scroll anything).

So I'm not sure we need to change something here.

**Comment by roman-r-m** [comment]
Ok, fair enough. Shall I close the issue too then?

**Comment by AdvisedlyAlburn** [comment]
How about adding an option in the settings?

**Comment by laurent22** [comment]
> Personally I use it to go to a folder, if I focus on a folder of course I want Joplin to scroll to it.

This certainly makes sense.

**Comment by roman-r-m** [comment]
> > Personally I use it to go to a folder, if I focus on a folder of course I want Joplin to scroll to it.
> 
> This certainly makes sense.

So shall I add the option then?

**Comment by laurent22** [comment]
No option, and jumping to a note shouldn't scroll the sidebar. But jumping to a notebook however should scroll the sidebar, I think that makes sense.

**Pull request closed without merging**
