### PR TITLE
Desktop: Fix katex formula render

### LINKED ISSUE #2811: Mac App Renders formula source code
Joplin app renders a portion of formula source code before the correct rendering:

Screen Shot 2020-03-19 at 12 53 18 PM

## Environment

Joplin version: Joplin 1.0.194 (prod, darwin)
Platform: Mac OS 10.15.3 (19D76)

### PR DESCRIPTION
**Pull request by sealch**
Fixed #2811 

Joplin rendered formula source code.
Detailed comparison:

- Before:

Screenshot 2020-03-22 at 15 30 18

- After:

image

### CODE REVIEW

**Comment by laurent22** [comment]
Will fix

**Comment by sealch** [comment]
> Will fix

What do you mean? This should fix the issue

**Comment by laurent22** [comment]
I mean I'll fix.

**Comment by sealch** [comment]
> I mean I'll fix.

Haven't I already fixed it? Or do you want to do extra enhancements?

**Comment by laurent22** [comment]
You've deleted a bunch of code, which might have fixed your issue but obviously broke something else. Do I really need to mention that the code you've deleted had a purpose? So again: I will fix it, you don't need to do anything.

**Pull request closed without merging**
