### PR TITLE
Backtick changes

### PR DESCRIPTION
**Pull request by tessus**
- revert 7dee930
- add shortcut ``` cmd+` ``` / ``` ctrl+` ```
- add menu item for `Inline code`

### CODE REVIEW

**Comment by laurent22** [comment]
Looks good, but let's just call the menu item "Code" like the toolbar button tooltip.

**Comment by tessus** [comment]
Done, the reason I used `Inline Code` at first was because I thought about creating another one for `Code block`. But there's another issue open which suggests to make it more intelligent. (#1606) In that case `Code` is better.

**Comment by laurent22** [comment]
Looks good then, thanks for the update!

**Comment by tessus** [comment]
You're welcome.

**Pull request merged**
