### PR TITLE
ALL: Implement the interface display like Evernote

### PR DESCRIPTION
**Pull request by wljince007**
Implement the interface like Evernote, code blocks automatically wrap; when the table is too wide, the horizontal scroll bar floats on the PC end.

The current table of Joplin does not wrapped up by div, making the interface width larger than the table width. When the table is very wide, when dragging, the interface is mostly empty and unfriendly. Here, we try to fix the interface width, automatically wrap the code block, and only allow manual dragging of tables left and right in the interface. This is more user-friendly for reading long documents, and also achieves a floating horizontal scrollbar display effect for tables on the PC, achieving interactive logic similar to Evernote.

# Implementation Description
## packages/renderer/MdToHtml/rules/[table_open.ts,table_close.ts] : add table a div wrapper
```
<div class="joplin-table-div" data-handy-scroll>
      <table class="maps-to-line" source-line="186" source-line-end="312">
     .....
      </table>
</div>
```
## handy-scroll :  make  scrollbar floating.  Handy dependency-free floating scrollbar widget.  from: 
https://github.com/Amphiluke/handy-scroll

## packages/renderer/noteStyle.ts : make  .joplin-table-div scrollbar show, code scrollbar hidden.
```
pre.hljs {
	overflow: hidden;
}

#rendered-md {
	overflow-x: hidden;
}

.joplin-table-div{
	overflow-x: auto;
}

code {
	white-space: pre-wrap;
	overflow: hidden;
}
```

# screenshot
## Evernote on pc
evernote_pc

## Evernote on ios
evernote_ios

## Joplin Current status on PC
pc_now

## Joplin make Evernote likes on PC
pc_new

## Joplin Current status on android
android_now

## Joplin make Evernote likes on android
android_new

## Joplin Current status on ios
ios_now

## Joplin make Evernote likes on ios
ios_new

### CODE REVIEW

**Comment by laurent22** [comment]
Thank you for the change but this is quite a major one and we don't have the resources to review this. At first sight, the fact that it uses jQuery, that it adds a lot of code in a place where there's no unit testing is not ideal for us. Since it seems to be mostly a change to the Markdown renderer maybe you could simply create a separate content script plugin?

**Comment by wljince007** [comment]
Thanks for your guidance, I well try to remove jquery.

**Comment by wljince007** [comment]
Please forgive my ignorance, I am very sorry, I don't understand "create a separate content script plugin" means how to do. Both PC end and mobile end want to modify the Markdown renderer, I don't known where the content script plugin is likely to be placed, please give me more guidance, thank you.

**Comment by laurent22** [comment]
The plugin for now would indeed only work in desktop. We're hoping to add mobile support at some point

**Comment by wljince007** [comment]
use handy-scroll replace jquery dependence:
handy-scroll : make scrollbar floating. Handy dependency-free floating scrollbar widget. from:
https://github.com/Amphiluke/handy-scroll

**Pull request closed without merging**
