### PR TITLE
WIP: Fixes CPU usage when creating a new notebook.

### PR DESCRIPTION
**Pull request by Abijeet**
# Test cases
- [ ] Creating a new notebook.
- [ ] Adding a tag to a new note.
- [ ] Updating an existing tag.
- [ ] Deleting a tag removes it from the note.
- [ ] Adding a new tag to a note.
- [ ] Renaming a tag changes the tag in the note.
- [ ] Tags appear in the same order on the dialog box and on the note.
- [ ] Creating a new note.

Signed-off-by: Abijeet <abijeetpatro@gmail.com>

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for looking into this. I think the proper way to fix this is to use the middleware on app/app.js and to listen to the needed action.

That way we'd have a clean cycle: action => middleware => rendering, while now action dispatching is a bit mixed with rendering, which in turns triggers more rendering so it's hard to make sense of it. If you need some info on how the middleware works, feel free to let me know (It's basically like the regular Redux middleware but setup a bit more complicated way to support the mobile and desktop app with shared code).

**Comment by Abijeet** [comment]
> @Abijeet just wanted to follow up.

Hey @tessus -  Been a little busy, will try to take a look at it next week.

**Comment by tessus** [comment]
@Abijeet no worries, I just wanted to ask for the status. I'm curious that's all. Happy New Year!

**Comment by laurent22** [comment]
Happy new year @Abijeet, thanks for your great contributions to this project!

**Comment by tessus** [comment]
@Abijeet Are you still working on this or shall we close this PR?

**Comment by laurent22** [comment]
Closing this for now @Abijeet but feel free to request to re-open when a fix is ready.

**Pull request closed without merging**
