### PR TITLE
"Desktop" Complete Spanish translation

### PR DESCRIPTION
**Pull request by gmag11**
Add missing translations

### CODE REVIEW

**Comment by tessus** [comment]
Thanks for the update, but why did you re-wrap the file? Maybe you changed the preferences for Poedit:

image

**Comment by gmag11** [comment]
Sorry about that. It's my first time with Poedit and maybe made a mistake. I can rework the translation to get original wrap length.

**Comment by tessus** [comment]
Don't worry about it for now. I don't think it matters, I just didn't understand why the file got re-wrapped. Now I do. ;-)

Let's ask @laurent22 if this is a problem.

**Comment by laurent22** [comment]
Looks good, thanks for the update!

**Pull request merged**
