### PR TITLE
Desktop: Fix rendering of tabs in code blocks

### LINKED ISSUE #2330: Pasted tab character is rendered as 8 characters long in codeblock
## Environment

Joplin version: 1.0.178
Platform: Windows
OS specifics: Windows 8.1(.1)

## Steps To Reproduce

1. Paste text that has tab character(s), from some other editor to a codeblock in Joplin.

= Joplin rendered view shows 1 tab char as 8 characters long in the codeblock.

## Describe what you expected to happen:

The rendered view should show a tab char exactly the same length (but do not convert to spaces) as when a tab key is pressed in Joplin (inserts 4 space chars, not a tab char). The 8 characters long indentation becomes a problem when inserting code that has nested indentations.

***

Here's a link to a text file that can be used for this test: [Paste code test.txt](https://github.com/laurent22/joplin/files/4090880/Paste.code.test.txt)

Few pictures:

Paste code test - notepad2

Paste code test - rendered

### PR DESCRIPTION
**Pull request by mic704b**
Fixes #2330

# Summary of the Issue
Tabs entered directly into the code block are rendered as **4 spaces**.
Tabs pasted into the code block from an external source are rendered as **8 spaces**.

# Solution
The solution is a simple renderer plugin [markdown-it-expand-tabs](https://www.npmjs.com/package/markdown-it-expand-tabs)

The solution ensures the tabs are displayed correctly and consistently in Joplin code blocks, no matter the source.

It also ensures the tabs are kept as tabs, in order for Joplin to maintain the pasted code in its original form.  This means the user can copy the code back out and get back exactly what they pasted in.

# Comment
To build the `ElectronClient`, the new package (as well as all the other `joplin-renderer` dependencies) need to be added to the `package.json`.  However for now, I've only added it to the `joplin-renderer` `package.json` until a solution to the build problem is decided.

### CODE REVIEW

**Comment by laurent22** [comment]
There are a few linter errors, probably due to the fact that I've imported recently the renderer into the repo.

**Comment by mic704b** [comment]
Yes, I'll check them out as soon as I can.  They are coming up in files completely unrelated to this PR, so I thought maybe I branched at a bad time.  I'll look into it.

**Comment by tessus** [comment]
@mic704b just to clarify something: tabs are not converted to spaces in the editor, right? This is only for the preview, thus rendering, correct?

I don't want my markdown be messed with. If I use a tab, I want a tab in my source file.

**Comment by mic704b** [comment]
> @mic704b just to clarify something: tabs are not converted to spaces in the editor, right? This is only for the preview, thus rendering, correct?

If you enter a tab in the code block in Joplin, then the tab is converted to 4 spaces.  This is the existing behaviour, I have not changed this here.

If you copy code from outside Joplin that contains tabs, and paste into a code block, then those tabs will be retained in Joplin.  This PR just means they will be displayed as 4 spaces (instead of 8).

If you then copy that code and paste into another editor, those tabs will be there.

> I don't want my markdown be messed with. If I use a tab, I want a tab in my source file.

If I understand you correctly, then yes, your tabs will be completely retained. It concerns just how they are displayed.  I thought it was important from a coder point of view, so wanted to make sure of that.

**Comment by mic704b** [comment]
> There are a few linter errors, probably due to the fact that I've imported recently the renderer into the repo.

@laurent22  this branch now also contains fixes for the various linter issues that are existing on master.  The changes related to this PR topic are contained only in the first two commits on this branch.

**Comment by laurent22** [comment]
Thanks for the explanation @mic704b. Indeed it's useful as it means rendered code will take less horizontal space.

**Pull request merged**
