### PR TITLE
GsoC first public draft of documentation 

### PR DESCRIPTION
**Pull request by PackElend**

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the documentation @PackElend. It's difficult to review in a diff like this, so I'm going to merge and I'll read it and make any change or fix directly from text editor (in particular I want to add links between the various documents and tweak them so they work in the website).

Or is there something you'd like to add to the doc first?

**Comment by PackElend** [comment]
you are welcome

how could that improved in feature cases?

Le lun. 18 nov. 2019 à 09:15, Laurent Cozic <notifications@github.com> a
écrit :

**Comment by laurent22** [comment]
>  how could that improved in feature cases?

Hmm, not sure what you mean? I haven't read it in detail yet so I don't know what can be improved yet.

**Comment by PackElend** [comment]
I meant the PR & merge process

Le lun. 18 nov. 2019 à 10:25, Laurent Cozic <notifications@github.com> a
écrit :

**Comment by laurent22** [comment]
> I meant the PR & merge process

The PR is fine and we can merge as it is. Right now I need to update the website build process to add the GSoC doc to it. Once it's there, it's easier to incrementally improve it.

I've also added an "Improve this doc" link at the bottom of each page on the website, which links to the correct document on GitHub. This will also make it easier to contribute.

**Comment by laurent22** [comment]
@PackElend, I've fixed a few issues with the GSoC files (mostly formatting) and added them to the website building tool, so they will now show up here: https://joplinapp.org/gsoc/

One thing I wasn't sure about, and didn't include, is the file GSOC2019.md: If I'm not mistaken it seems to be a file to introduce the "Ideas" documentation, is that correct? In that case, couldn't we put it as a section at the bottom of the main web page? For now, that's what I've done - I've put a section that links to the ideas.

If you think it should be done differently please let me know.

All the GSoC files are there: https://github.com/laurent22/joplin/tree/master/readme/GSoC

Also I've given you write permission to the repo, so you can open any of these doc files directly and change them if you want.

**Comment by PackElend** [comment]
great.
I have splited it to keep the overview at a certain point that the text 
could get to long.  I have to admit it doesn't look that bad :). If it 
gets too long we may split again, will see.



Am 20.11.2019 um 20:04 schrieb Laurent Cozic:

**Pull request merged**
