### PR TITLE
Image File Compression

### PR DESCRIPTION
**Pull request by Peppernrino**
Ran a series of lossless compression algorithms to make the images smaller. Total reduction of 1,599,059 bytes.

Example here: https://pastebin.com/MTtcVck2

### CODE REVIEW

**Comment by laurent22** [comment]
With 916 files being changed, that's a lot of things that need to be checked to make sure nothing is affected by the change. I guess nothing is but can't be completely sure.

Also many of the changed files aren't really used or are only for the website so the gain in size for each app is smaller.

For these reasons, I'm afraid I can't accept the pull request. Thanks though for proposing an improvement, it's appreciated anyway.

**Comment by Peppernrino** [comment]
I've been going around doing this for all the programs that I use on a daily basis, and I can assure you I check the files before submitting them for integrity. I understand that some people don't, and reviewing all those files might take a bit. They're just the same images, but smaller. It's a fairly incremental change, and nothing Earth-shattering, so take it or leave it. lol

As for anything being changed, I joked in my pull with Bitcoin about how as long as the files aren't hashed by SHA256 or something, we should be good... and after looking at how they do their compression stuff, I think they actually ARE stored by SHA256 in there. lmao. So yeah, if you're not sure the images won't break anything, no big deal. :D 

I'm just trying to contribute where I can (about to open an issue for this program actually), and I am totally able to contribute CPU cycles for compression. :P

**Comment by laurent22** [comment]
I appreciate you want to improve the project and I assume all the images are still valid and would still work. However there's a tiny little risk that something will not and that's why I prefer to avoid this.

For example, the icon files are used by many tools to build the releases. Most likely these files, after compression, are still fine but who knows, maybe one of the tools expects a specific header that has been stripped off; or expect it in a specific binary format, which has now changed. I've seen stuff break for seemingly trivial changes. Or maybe it won't break but a particular version of a particular Linux desktop release will no longer display the icon.

So that's why I tend no to accept pull request that automatically changes many files - I simply cannot predict if everything is going to work the same with the change. The exception to that is if the change can bring a significant, measurable improvement - let's say for example the apps are now 10% faster to load. That would be worth the risk, but otherwise I play safe :-)

**Comment by Peppernrino** [comment]
All good homie. Keep up the good work. :)

**Pull request closed without merging**
