### PR TITLE
Android: Add menu item to save attachments to device storage

### PR DESCRIPTION
**Pull request by roman-r-m**
ezgif com-gif-maker(8)

### CODE REVIEW

**Comment by laurent22** [comment]
For this pull request too I'm wondering if there's an existing module we could use? Wouldn't something like react-native-document-picker do the job?

**Comment by roman-r-m** [comment]
I don't know of any existing lib. `react-native-document-picker` is to open an existing document, this one is to create a new file.
Maybe it could be done with dir picker and RNFS but the advantage of this method is you get a URI to the target file and don't need to bother with files and, most importantly, permissions.
With RNFS it's not possible to write to external SD card, with this method it works.

Besides, there's not much code there. If it helps, I can add detailed comments to clarify what's going on.

**Comment by laurent22** [comment]
I think it's a useful feature but I prefer to limit how much native code is added directly to the mobile app as it will be hard to maintain over time. Even modules that are used by thousands of people often break on new React Native releases, so it's unlikely we'll be immune to that, except we'll have less people to debug and fix issues.

I wouldn't mind if we use the dir picker/rnfs method even if it's a bit more complicated, because at least we know that rnfs is likely to be stable and quickly fixed when a new RN version requires it.

**Comment by roman-r-m** [comment]
> I think it's a useful feature but I prefer to limit how much native code is added directly to the mobile app as it will be hard to maintain over time. Even modules that are used by thousands of people often break on new React Native releases, so it's unlikely we'll be immune to that, except we'll have less people to debug and fix issues.

Ok, fair enough. I don't think native code breaks any more than JS code and at least you can get compilation error if, say, a method is renamed, but it's your call.

**Pull request closed without merging**
