### PR TITLE
Mobile: Fixes #8041: Shortcuts icon not displayed correctly on Android 

### LINKED ISSUE #8041: Shortcuts icon not displayed correctly on Android
屏幕截图 2023-04-12 024756

### PR DESCRIPTION
**Pull request by simonla**
Current: 
Snipaste_2023-04-12_03-20-42

icon download from: [Google-Material-Icons](https://fonts.google.com/icons?icon.set=Material+Icons&selected=Material+Icons+Outlined:add:&icon.platform=android&icon.query=add)

### CODE REVIEW

**Comment by simonla** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by simonla** [comment]
recheck

**Comment by laurent22** [comment]
That's very good, thanks for adding this. Does it work with dark theme too?

How about on tablet, does it scale properly without looking pixelated?

**Comment by simonla** [comment]
dark mode：
image-20230412032750295

**Comment by simonla** [comment]
I will test on pad later

**Comment by simonla** [comment]
Looks good on a tablet @laurent22 

Snipaste_2023-04-13_03-52-10

**Comment by simonla** [comment]
@laurent22 hi~ Can we merge this PR?

**Comment by laurent22** [comment]
Thanks for checking. Also, I should have brought that up earlier but the icons aren't quite what we want. How about using icons similar to those on the desktop app? So a "note" icon for "new note" and a "checkmark" icon for "new todo"

Capture d’écran 2023-04-20 à 11 06 36

**Comment by simonla** [comment]
> Thanks for checking. Also, I should have brought that up earlier but the icons aren't quite what we want. How about using icons similar to those on the desktop app? So a "note" icon for "new note" and a "checkmark" icon for "new todo"
> 
> Capture d’écran 2023-04-20 à 11 06 36

I agree with your opinion, but it's not easy to implement. The icons you mentioned have been embedded into the icon font file, which cannot be directly used on Android. And the images already used on iOS are different from the ones you mentioned.

**Comment by roman-r-m** [comment]
I think you can download the icons as SVG from https://fontawesome.com/icons

**Comment by laurent22** [comment]
What's the status of this PR @simonla? Unfortunately we can't merge with these icons - it needs to be "note" or maybe "file" icon for the note, and a checkmark or similar for the todo

**Comment by laurent22** [comment]
Closed stale PR

**Pull request closed without merging**
