### PR TITLE
Mobile: Fix #7253: Fix CodeMirror syntax highlighting regression

### LINKED ISSUE #7253: Beta Editor: Syntax highlighting not working
## Environment

Joplin version: a0c87d6d4bc94eb31d0f181d464ae68bcd5394a5
Platform: Android
OS specifics: Android 12

### With the app
1. Create a note with the following content:
```
# Heading 1
## Heading 2

*Test*... This is a **test**.
```
2. Enable the beta editor
3. Edit the note 

### With the editor demo page
1. Open `packages/app-mobile/components/NoteEditor/CodeMirror/demo.html` in a browser
2. Replace the content of the textbox with
````
Testing...

# Foo
## Foobar

*test*... This is a **test**.

| Foo | |
|-------|--|
|     |   |

_foo_

`test`. ```test```

```js

function foo() {
    alert(3);
}

```


````

This results in the following:
screenshot of editor with only partial highlighting

## Describe what you expected to happen

The headers and bolded/italic regions should have different sizes/styles.

## Notes

Updating the CodeMirror dependencies seems to fix the issue. I plan to submit a pull request soon.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
This PR adds a test that should prevent future regressions caused by updating `@lezer/highlight` without updates to the other CodeMirror dependencies.
It also updates CodeMirror to fix the most recent update-related regression.

 - https://github.com/laurent22/joplin/issues/7253 started happening again, possibly due to https://github.com/laurent22/joplin/pull/7349 (`@lezer/highlight` was updated but the CodeMirror packages that it's used with were not).
 - A unit test has been added to ensure that syntax highlighting works correctly.

### CODE REVIEW

**Comment by laurent22** [comment]
Looks like there's a failing test: https://github.com/laurent22/joplin/actions/runs/3589093535/jobs/6041175028#step:12:687

**Comment by personalizedrefrigerator** [comment]
> Looks like there's a failing test: https://github.com/laurent22/joplin/actions/runs/3589093535/jobs/6041175028#step:12:687

I'm not experiencing this locally. This might be happening because the syntax tree isn't being parsed within the 100ms timeout.

https://github.com/laurent22/joplin/blob/d3cdcf8b9fa3b2ceaafafd0a5841a6ebf2a8f95e/packages/app-mobile/components/NoteEditor/CodeMirror/markdownMathParser.test.ts#L8

I'll create a separate PR increasing this to 500 ms. (Edit: ~~See https://github.com/laurent22/joplin/pull/7403~~ See https://github.com/laurent22/joplin/pull/7405)

**Comment by laurent22** [comment]
So this one is ok to merge then?

**Comment by personalizedrefrigerator** [comment]
> So this one is ok to merge then?

Yes! This should be good to merge!

**Pull request merged**
