### PR TITLE
Lib: joplin server recusive publishing

### PR DESCRIPTION
**Pull request by sdip15fa**
Recursive publishing of notes is [already supported by joplin server](https://github.com/laurent22/joplin/commit/29a1cc). It should be available for clients.

### CODE REVIEW

**Comment by laurent22** [comment]
not working yet

**Comment by sdip15fa** [comment]
> not working yet

According to my understanding and tests, it does work with the latest joplin server code (from this repo), but probably not for the official joplin server docker image, which was published a few months ago. Do we need to wait until then?

**Comment by laurent22** [comment]
The feature is buggy, it needs to be fixed first

**Comment by sdip15fa** [comment]
> The feature is buggy, it needs to be fixed first

Oh. What bugs, specifically?

**Comment by dannykorpan** [comment]
Any updates on this?

**Pull request closed without merging**
