### PR TITLE
Desktop: Seamless-Updates: generate latest-mac.yml file

### PR DESCRIPTION
**Pull request by AliceHincu**
This PR is for generating latest-mac.yml file so that Electron's autoUpdater can work on MacOs

### CODE REVIEW

**Comment by laurent22** [comment]
There's an error:

```
npm ERR! code ENOADDPROP
npm ERR! Can't add property build.mac.target.target to an Array.
```

**Comment by AliceHincu** [comment]
https://www.electron.build/configuration/mac.html

_Defaults to default (dmg and zip for Squirrel.Mac)_

I switched to the default option since it's the same thing as adding zip and dmg separately. I do not know why the other changes to build-macos-m1.yml did not work, but this seems to work. Default arch is x64.

**Comment by laurent22** [comment]
We need to be careful with these changes because GitHub Action currently is setup to build two macOS apps - the Intel one and the M1 one. I'm not confident this is not broken after your change, and I also prefer to explicitly set the configuration instead of using "default" (because we don't know what this means).

Could you try locally on your computer - how can you **add** the zip target to the configuration without removing what's already there? I'm not sure why there was an error earlier but it seems that was the right approach

**Comment by AliceHincu** [comment]
It seems that setting each one of them individually worked. This can finally be merged. I looked again at why the others did not work:
- When I wanted to set the target as a list of dictionaries, I used "x64" (which targets Intel-based Macs) instead of "arm64" (which targets Apple Silicon Macs). Regarding the error _'Invalid configuration object. electron-builder 24.13.3 has been initialized using a configuration object that does not match the API schema'_, I don't think you can set the whole target with `npm pkg set`: https://docs.npmjs.com/cli/v7/commands/npm-pkg .  In their examples and docs, they set each value of a dict individually.

- When I wanted to set the target as the string 'dmg, zip', I only overwrote the architecture of the first one (dmg). The second one (zip) was still using "x64" since I did not overwrite it. If inside the package.json the target is written as a list, I can't set it to be a string, hence the error _'Property target already exists and is not an Array or Object.'_. When overwriting the target value, it should be of the same type.

**Comment by laurent22** [comment]
That looks good now, thanks Alice!

**Pull request merged**
