### PR TITLE
Update ar.po

### PR DESCRIPTION
**Pull request by Hachemdr**
### This is an updated version of ar.po.
I have read the CLA Document and I hereby sign the CLA.

### CODE REVIEW

**Comment by Hachemdr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Hachemdr** [comment]
recheck

**Comment by laurent22** [comment]
recheck

**Comment by laurent22** [comment]
The file is invalid:

```
Step: Validating translations...
Error: Command failed: msgfmt -v "/home/runner/work/joplin/joplin/packages/tools/../../packages/tools/locales/ar.po"
/home/runner/work/joplin/joplin/packages/tools/../../packages/tools/locales/ar.po:978:21: syntax error
/home/runner/work/joplin/joplin/packages/tools/../../packages/tools/locales/ar.po:978: keyword "s" unknown
/home/runner/work/joplin/joplin/packages/tools/../../packages/tools/locales/ar.po:994:7: syntax error
/home/runner/work/joplin/joplin/packages/tools/../../packages/tools/locales/ar.po:1934:28: syntax error
/home/runner/work/joplin/joplin/packages/tools/../../packages/tools/locales/ar.po:1934: keyword "s" unknown
msgfmt: found 5 fatal errors
```

You should use podedit to update it

**Comment by laurent22** [comment]
Please recreate with a fix if you would like to submit this

**Pull request closed without merging**
