### PR TITLE
Mobile: Added Front Camera toggle when taking a picture with Joplin Camera

### PR DESCRIPTION
**Pull request by daehruoydeef**
Added toggle switch to use front camera. React-native-camera by default uses back camera if the specified camera (front) is not found. Tested on Android and iOS(Simulator, no real images just blackscreens with the date attached).

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pull request! In general when using a camera app the front/back settings is remembered across uses. Wouldn't it make sense to do the same here? At least if it could be persistent across a session that would be great, and if it's reset after the app restarts that's fine.

**Comment by daehruoydeef** [comment]
I agree, it would be more ux friendly if the camera remembered it´s state.
In my projects I used AsyncStorage to persist values like settings however I feel like this does not need an extra library. Without diving to deep into the rest of the code is there a easy way to persist a value? I see redux is used for most of the state managment, but I cannot bring any experience to the table if it comes to redux.

**Comment by laurent22** [comment]
Persistent settings are defined in models/Setting.js. Whenever you call for example `Setting.save('cameraType', 1)` it is saved to the database. The associated Redux state is also updated. So you can connect to `state.settings.cameraType` from your view (search for "state.settings" for examples on how this is done).

I guess in your case you'd need to define that new setting, and turn CameraView into a controlled component. Then you can connect to the setting from the parent component and set the `cameraType` prop on CameraView.

This is not too complicated once you get the idea. If you need more info, let me know.

**Comment by laurent22** [comment]
Note that the state persistence is a nice to have feature, but not essential. If it's too complex we can leave it aside for now since you PR already stands on its own.

**Comment by daehruoydeef** [comment]
Yes, given the complexity this would involve I would also opt for merging now and adding the state persistence later. 
I would really like to add state persistence but right now I cannot devote the needed time and resources at it.

**Comment by laurent22** [comment]
We're good to go then, thanks for the PR @daehruoydeef!

**Pull request merged**
