### PR TITLE
Desktop: add proxy setting

### PR DESCRIPTION
**Pull request by flobz**
After seeing this  <https://github.com/laurent22/joplin/pull/2515> pull request, I added proxy option to the setting panel like it was asked.
Global-agent still doesn't support proxy over https but people can use a local intermediary proxy to connect to a corporate proxy. That's what I do.

### CODE REVIEW

**Comment by tessus** [comment]
There was already a PR availabe for that: #2558

We closed it. So why do you think this one will not?

**Comment by flosers** [comment]
You closed it because global-agent doesn't works with https proxy but there is a workaround: use an intermediate proxy on the host. Furthermore I think that a lot of people are like me forced to use an intermediary proxy because, a lot company use a proxy with ntlm auth which is not supported by a lot of software so I'm forced to use a proxy like cntlm.

**Comment by laurent22** [comment]
I can't evaluate if this pull request is useful and I can't test it, so not sure if we can merge. We'll need some sort of consensus from interested users I think.

**Comment by flobz** [comment]
> I can't evaluate if this pull request is useful and I can't test it, so not sure if we can merge. We'll need some sort of consensus from interested users I think.

You can test it with CNTLM, if you add this line to cntlm.conf  "NoProxy *".  Like this cntlm will not forward trafic to a parent proxy but will directly send request to the destination server. 

The #2558 pr is do the same and seems to be more complete. 

Anyway a lot of people ask for proxy, because without it  you can't use it in a lot of company. Even if this solutions doesn't work with https proxy directly, with an intermediary proxy it works. So I think that this feature will allow more user to use Joplin.

**Comment by laurent22** [comment]
Thanks for the pull request but we won't merge it at this point. Even we did merge a proxy PR, it would probably be that one, which is more complete: #2558

**Comment by GammaPi** [comment]
The problem with global-tunnel is, when enabled, Joplin won't verify tls certificate anymore.
See issue #2515

**Pull request closed without merging**
