### PR TITLE
Desktop: Add monospace enforcement for certain elements

### PR DESCRIPTION
**Pull request by CalebJohn**
This adds forced monospace for Tables, Code blocks and Checkboxes in the CodeMirror editor. 

This was briefly [discussed on the forum](https://discourse.joplinapp.org/t/plugin-rich-markdown/15053/71)

For checkboxes and code blocks, I piggy back on the CodeMirror highlighting and add the monospace class.

For tables I couldn't do that. Instead table check for a valid header, and then enter table mode. This just means that all lines following the valid header will be monospace until a line is reached that does not contain a '|' character.

I also enforce monospace on any line that begins with a '|', the assumption being that those lines are likely going to become a part of a table, and it's better to start writing in monospace rather than snapping to monospace once the header is finished.

Something I haven't done yet is to add a setting that enables this behaviour. I'm not sure if it will be necessary.
We'll at least need a way for the user to specify which monospace font they want to use.

### CODE REVIEW

**Comment by tessus** [comment]
I'm already using a monospace font in Joplin (Codemirror editor). Does this override my settings? If so, can I please have an option to disable this behavior?

**Comment by CalebJohn** [comment]
@tessus 

Yes it will override your set font. I've just pushed another commit that adds an option for for the monospace font, so you'll need to set both if you want them to be the same.

**Comment by tessus** [comment]
Btw, it's still in a draft state.

**Comment by CalebJohn** [comment]
Thanks @tessus Just wanted to give it another review myself before taking it out of the draft state. 

As a summary, this PR enforces monospace for 
- Tables
- Checkboxes
- Code (blocks, indented, inline)

**Comment by laurent22** [comment]
Thanks for the pull request @CalebJohn, that looks good. What would be the default fonts? Is it monospace everywhere by default or regular font for text, and monospace for table, code, etc.?

**Comment by CalebJohn** [comment]
> What would be the default fonts? Is it monospace everywhere by default or regular font for text, and monospace for table, code, etc.?

It's monospace everywhere by default. Currently, there are still cases where the transition from proportional font -> monospace, can cause a "pop" when the width of text changes, so for users sake I left monospace as the default. 
I can make "Open Sans" the default in settings though. Just give me the word.

**Comment by tessus** [comment]
I've just tested it and it seems that if the second one is left empty, it will still use my monospace font, and not a random one.

> so you'll need to set both if you want them to be the same.

Apparently that's not the case for some reason. Pretty cool.

image

**Comment by laurent22** [comment]
> It's monospace everywhere by default. Currently, there are still cases where the transition from proportional font -> monospace, can cause a "pop" when the width of text changes, so for users sake I left monospace as the default. I can make "Open Sans" the default in settings though. Just give me the word.

Yes if you could make the proportional font the default that would be great, as I think it's the better default. Let's see what feedback we get and if it causes problem we can review the default afterwards.

I'm not sure Open Sans is available everywhere? Would it make sense to make the generic "sans-serif" as default instead?

**Comment by CalebJohn** [comment]
> Apparently that's not the case for some reason. Pretty cool.

Sadly, that's a bug. I've just fixed it in this commit.

> I'm not sure Open Sans is available everywhere? Would it make sense to make the generic "sans-serif" as default instead?

For some reason I thought Open Sans was the default viewer font. I changed the fallback font to use Avenir, Arial, sans-serif, to align with the viewer. I undid the previous change that adds Open Sans.

**Comment by laurent22** [comment]
All good then, let's merge.

**Pull request merged**
