### PR TITLE
Fix scroll note keyboard on IOS

### PR DESCRIPTION
**Pull request by marcosvega91**
Hi, 

I have fixed the issue that not permit the user to view edited text when keyboard is opened.
I try both on IOS and Android.
Tell me if it's right

Thanks

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the pull request.

Do we need to use both `KeyboardAvoidingView` and the keyboard event listener? Since `KeyboardAvoidingView` is supposed to automatically resize we shouldn't need to manually add padding, or am I missing something? Basically I'm wondering if we can use only one or the other?

**Comment by marcosvega91** [comment]
Hi,

I have used a dummy view at the bottom because using only `KeyboardAvoidingView` the text field goes under the autocompletion bar at the top the the keyboard.

**Comment by laurent22** [comment]
Right, that makes sense. I'll give it a try in Android and if it's all working I'll merge.

Actually in the meantime please could you make sure the indentation is done with tabs and not spaces?

**Comment by marcosvega91** [comment]
I have done it right now

**Comment by alexdevero** [comment]
Is there any progress on this PR?

**Comment by laurent22** [comment]
I think it's almost good to merge but first the indentation and tabs need to fixed (there's a mix of spaces and tabs).

**Comment by laurent22** [comment]
As I'll probably release an iOS version this weekend, it'd be nice to have this fix in.

**Comment by alexdevero** [comment]
@laurent22 different indentation and style (tabs) are annoying. Why there is no `.editorconfig` with predefined config? Many IDEs honor and follow it. In `README.md` should be a link to `CONTRIBUTING.md` or some info about coding style. Not everyone will take the time to search for info about code style.

Example config:
```
# editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = crlf
indent_style = tab
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
```

**Comment by marcosvega91** [comment]
@alexdevero you’re right, another way is to add a prettier task to packadge.json and run it before commit. You can also add a task to run with CI integration that that in every PL if the code is formatted right.

**Comment by laurent22** [comment]
I've now added a pull request template and linked to CONTRIBUTING.md (which, granted, did not exist when this pull request was made) in README.md. I will see about other options later.

**Comment by alexdevero** [comment]
@marcosvega91 You are right. @laurent22 something similar is a `pre-commit` npm plugin.

**Comment by RCJacH** [comment]
Is it me or is this issue not resolved in the new iOS version?

**Comment by alexdevero** [comment]
@RCJacH the PR is still open. No it is not resolved.

**Comment by laurent22** [comment]
It's indeed not merged yet since, as I mentioned, formatting and indentation needs to be fixed first. I know those are relatively minor issues but if each PR introduces different coding styles the code base will be hard to maintain.

**Comment by alexdevero** [comment]
@laurent22 it seems that @marcosvega91 fixed the indentation issue in 277ad90.

**Comment by marcosvega91** [comment]
Today I’ll check if all is okay and in case is not I’ll commit :)

**Comment by marcosvega91** [comment]
I'have checked but it seams ok

**Comment by alexdevero** [comment]
@marcosvega91 thanks. @laurent22 can you please take a look the code?

**Comment by laurent22** [comment]
There was still spaces instead of tabs in several places but I've fixed it afterwards. It should now be part of version 0.10.9. Please check when it's available in the App Store and confirm if it's working.

**Comment by alexdevero** [comment]
Unfortunately, no. The keyboard still covers the lower part content and it is not possible to scroll farther to make this content visible. The same applies to open submenu (Attach photo, Log, Status, etc.). If you edit a note and open the submenu bottom part of the menu is hidden behind the keyboard and it is not possible to scroll farther to make this part visible.

_I checked this on the latest version available in the App Store._

**Comment by marcosvega91** [comment]
I think it’s not the latest

**Comment by alexdevero** [comment]
I just checked the App Store. It is.

**Comment by marcosvega91** [comment]
In the Apple store I see the version 0.10.8 but he said that the fix will be in the 0.10.9

**Comment by alexdevero** [comment]
My mistake. Thank you @marcosvega91.

**Comment by marcosvega91** [comment]
You have to wait for one day before Apple approve the version

**Comment by laurent22** [comment]
Yes they haven't reviewed 0.10.9 yet.

**Comment by alexdevero** [comment]
It looks like your fix worked @marcosvega91!

**Comment by RCJacH** [comment]
It works! I just have to clear all the empty lines at the eof that I added to my notes. Just to notify, right after entering editing mode, when clearing pre-existent (empty) lines at end of file, the view will scroll back up to top; Deleting new lines within the same editing session will not scroll view back to top.

**Comment by alexdevero** [comment]
@RCJacH is right. Scrolling now works in the way that all content is visible. It doesn't work when new line is inserted or deleted. The same applies to selecting text. Screen will not scroll and it is therefore not possible to select more than the text that is already visible.

**Pull request merged**
