### PR TITLE
Mobile: improve delete dialog

### LINKED ISSUE #4701: Language: Plural instead of singular when deleting 1 note
## Environment

Joplin version: 1.7.5, database v34
Platform: Android
OS specifics: 10

## Steps to reproduce

1. Long-press a note
2. Tap rubbish-bin-icon
3. "Delete these notes?" appears

## Describe what you expected to happen

"Delete this note?" appears

Not only more grammatically correct, but removes the user wondering "wait, did I select more than 1 note"?

## Logfile

None relevant to issue

### PR DESCRIPTION
**Pull request by tessus**
fixes #4701

image

image

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks for the fix. Could you actually move this logic (and the one in NoteListUtil) under models/Note.ts please. It could be a function like `deleteMessage` that takes the noteIds as input. Not sure if it's the best place to put that function, but it's better than having duplicated logic.

**Comment by tessus** [comment]
I thought about but didn't know where to put it. But I can put it in Note.ts
I hoped you'd suggest a file.... 🙂

I'm heading out now, but will be looking at it later tonight or tomorrow.

**Comment by tessus** [comment]
I'm sorry, I was busy migrating my server over the past 2 days. I will be looking into it in the next few days.

**Comment by tessus** [comment]
Sorry that it took this long. Work was a bit crazy lately.

**Comment by tessus** [comment]
@laurent22 shall I rebase? The CI run failed for some reason, but it seems the tests were fixed in dev HEAD.

**Comment by laurent22** [comment]
No this is fine, it was indeed some problem with the dev branch, so let's merge. Thanks for the fix!

**Pull request merged**
