### PR TITLE
Update de_DE.po

### PR DESCRIPTION
**Pull request by psjnek**

### CODE REVIEW

**Comment by WebSnke** [comment]
recheck

**Comment by laurent22** [comment]
recheck

**Comment by laurent22** [comment]
@WebSnke, in order to sign the CLA you need to add a comment with this text:

> I have read the CLA Document and I hereby sign the CLA

**Comment by psjnek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by psjnek** [comment]
> @WebSnke, in order to sign the CLA you need to add a comment with this text:
> 
> > I have read the CLA Document and I hereby sign the CLA

Ok, thanks.

**Pull request merged**
