### PR TITLE
Mobile: Fix CodeMirror test failure

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
This should (hopefully) fix randomly failing tests related to CodeMirror.

# Summary
Many of the beta markdown editor's tests rely on a fully-parsed syntax tree. CodeMirror seems to incorrectly report that it has fully parsed the syntax tree when this is not the case. It is more likely that CodeMirror won't finish parsing the syntax tree in cases where there is high CPU load.

# Getting the tests to fail locally
For me, running all tests on one CPU core previously (before this PR) caused tests to fail consistently. On Linux, this can be done with the command `taskset --cpu-list 1 /bin/sh -c 'yarn test'`.

# Potential issues
- [`LanguageDescription`s are loaded asynchronously. We need to wait to make sure they are actually loaded.](https://discuss.codemirror.net/t/listen-on-editor-being-ready-rendered/3692/11)
    - CodeMirror-related tests now wait for all supported languages to load. This was added to `createEditor` to ensure that all tests that use `createEditor` (most of the CodeMirror-related tests) do this.
- [The previous version of `@codemirror/language` had a bug where `ensureSyntaxTree` didn't always ensure that the syntax tree exists.](https://discuss.codemirror.net/t/full-document-parsing/5440/4)
    - This is fixed by updating to the latest CodeMirror.
- CodeMirror seems to have a bug in which syntax trees aren't fully parsed (even with `ensureSyntaxTree`) when there is high CPU load.
    - This is worked around by waiting for test-specific syntax tree nodes to exist. For example, we might wait for a `BulletList` node to exist in the syntax tree if a test depends on it.

The last change seems to have fixed the issue. The other two, if the bug causing the last is fixed, should improve reliability. **Should I break this up into three separate pull requests?**

# Notes
- Some tests modify the document then rely on the syntax tree for the modified document. These tests were broken into multiple different tests to simplify waiting for the syntax tree to have a specific state.
    - It is possible that additional tests need to be restructured — I restructured tests until all tests consistently pass with `taskset --cpu-list 1 /bin/sh -c 'yarn test'`. It is possible I missed some.

### CODE REVIEW

**Comment by personalizedrefrigerator** [comment]
It looks like the failure for [`8928ae1828324a5a4d0758c10fba951f3337ed2c`](https://github.com/personalizedrefrigerator/joplin/actions/runs/3759365315/jobs/6388844623#step:12:658) was not CodeMirror-related (it was related to Electron).

**Comment by personalizedrefrigerator** [comment]
The CI failed for 4d10bce73689206e93cd9ecf7fcfc73b9f04be76 in a way that shouldn't be fixed by d21bdd251e23bac4e378f86806aabd0763843a92. (See [the log](https://github.com/laurent22/joplin/actions/runs/3759532457/jobs/6389213363#step:12:683)).

```
➤ YN0000: [@joplin/app-mobile]: FAIL components/NoteEditor/CodeMirror/markdownCommands.toggleList.test.ts
➤ YN0000: [@joplin/app-mobile]:   ● markdownCommands.toggleList › should correctly replace an unordered list with a numbered list
➤ YN0000: [@joplin/app-mobile]: 
➤ YN0000: [@joplin/app-mobile]:     expect(received).toBe(expected) // Object.is equality
➤ YN0000: [@joplin/app-mobile]: 
➤ YN0000: [@joplin/app-mobile]:     - Expected  - 7
➤ YN0000: [@joplin/app-mobile]:     + Received  + 7
➤ YN0000: [@joplin/app-mobile]: 
➤ YN0000: [@joplin/app-mobile]:     - 1. 1
➤ YN0000: [@joplin/app-mobile]:     + - 1
➤ YN0000: [@joplin/app-mobile]:     - 2. 2
➤ YN0000: [@joplin/app-mobile]:     + - 2
➤ YN0000: [@joplin/app-mobile]:     - 3. 3
➤ YN0000: [@joplin/app-mobile]:     + - 3
➤ YN0000: [@joplin/app-mobile]:     - 4. 4
➤ YN0000: [@joplin/app-mobile]:     + - 4
➤ YN0000: [@joplin/app-mobile]:     - 5. 5
➤ YN0000: [@joplin/app-mobile]:     + - 5
➤ YN0000: [@joplin/app-mobile]:     - 6. 6
➤ YN0000: [@joplin/app-mobile]:     + - 6
➤ YN0000: [@joplin/app-mobile]:     - 7. 7
➤ YN0000: [@joplin/app-mobile]:     + 1. 7
➤ YN0000: [@joplin/app-mobile]: 
➤ YN0000: [@joplin/app-mobile]:       57 |
➤ YN0000: [@joplin/app-mobile]:       58 | 		toggleList(ListType.OrderedList)(editor);
➤ YN0000: [@joplin/app-mobile]:     > 59 | 		expect(editor.state.doc.toString()).toBe(
➤ YN0000: [@joplin/app-mobile]:          | 		                                    ^
➤ YN0000: [@joplin/app-mobile]:       60 | 			'1. 1\n2. 2\n3. 3\n4. 4\n5. 5\n6. 6\n7. 7'
➤ YN0000: [@joplin/app-mobile]:       61 | 		);
➤ YN0000: [@joplin/app-mobile]:       62 | 	});
```

This test relies on CodeMirror marking the entire unordered list as an unordered list. Because the test fails with a difference in output and not an "Unable to generate syntax tree in ${timeout}" error, `syntaxTreeAvailable` must return `true`, implying that CodeMirror thinks a syntax tree is available.

**Comment by personalizedrefrigerator** [comment]
The most recent failure seems to have happened before tests could run. Re-running CI.

**Comment by laurent22** [comment]
Would it be possible to check ourselves that the state is ready, for example by appending an element and waiting for it to be present? If it is we know that the state is ready and can proceed with the other checks.

**Comment by personalizedrefrigerator** [comment]
> Would it be possible to check ourselves that the state is ready, for example by appending an element and waiting for it to be present? If it is we know that the state is ready and can proceed with the other checks.

We could try that. I'm worried that removing the element (e.g. so `editor.state.doc.toString()` doesn't have trailing content) will trigger a re-parse and thus we'll have a similar situation to the present. It's worth trying though.

If that doesn't work, one way to limit random failures is to re-run failed tests. `yarn test-ci` could map to `yarn test || yarn test -f` instead of just `yarn test`. This would reduce the likelihood of randomly failing tests.

I plan to try running the tests on a slower machine — I'm still trying to get them to fail locally.

**Comment by personalizedrefrigerator** [comment]
I've gotten them to start failing locally! Running all tests on one CPU (e.g. with `taskset --cpu-list 1 /bin/sh -c 'yarn test'`) causes at least one of the tests to fail consistently.

**Comment by laurent22** [comment]
That's very good if you can replicate it consistently. Maybe something you can bring up to the CodeMirror forum if it's a bug in the lib?

**Comment by personalizedrefrigerator** [comment]
> Would it be possible to check ourselves that the state is ready, for example by appending an element and waiting for it to be present? If it is we know that the state is ready and can proceed with the other checks.

This is now being tried. Tests still fail with `taskset --cpu-list 1 /bin/sh -c 'yarn test'`, but I think less often than previously. 

`createEditor` now appends content that includes `$3+\text{3}$` to the CodeMirror document, and waits for the node representing `\text` in the syntax tree. Because it pauses for `500`ms if `\text` isn't present in the syntax tree, it could just be that the reduced CPU load is allowing tests to pass more often.

The next thing to try could be to re-structure the tests to permit additional content at the end of the CodeMirror document — currently, `createEditor` removes the extra content before returning the editor, which I think triggers a re-parse, which doesn't always finish by the time we try to use the editor. If the document isn't changed, a re-parse may not be triggered.

**Comment by laurent22** [comment]
@personalizedrefrigerator, it looks like the tests are passing now. Do you think it's ready to merge?

**Comment by personalizedrefrigerator** [comment]
> @personalizedrefrigerator, it looks like the tests are passing now. Do you think it's ready to merge?

This should be ready to merge.

**Comment by laurent22** [comment]
Thanks for the fix!

**Comment by laurent22** [comment]
@personalizedrefrigerator, unfortunately the random failures are still happening:

https://github.com/laurent22/joplin/actions/runs/3985346992/jobs/6832874648#step:12:707

	FAIL components/NoteEditor/CodeMirror/markdownCommands.toggleList.test.ts
	➤ YN0000: [@joplin/app-mobile]:   ● markdownCommands.toggleList › should correctly replace an unordered list with a checklist
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:     expect(received).toBe(expected) // Object.is equality
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:     - Expected  - 6
	➤ YN0000: [@joplin/app-mobile]:     + Received  + 6
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:     - - [ ] 1
	➤ YN0000: [@joplin/app-mobile]:     - - [ ] 2
	➤ YN0000: [@joplin/app-mobile]:     - - [ ] 3
	➤ YN0000: [@joplin/app-mobile]:     - - [ ] 4
	➤ YN0000: [@joplin/app-mobile]:     - - [ ] 5
	➤ YN0000: [@joplin/app-mobile]:     - - [ ] 6
	➤ YN0000: [@joplin/app-mobile]:     + - 1
	➤ YN0000: [@joplin/app-mobile]:     + - 2
	➤ YN0000: [@joplin/app-mobile]:     + - 3
	➤ YN0000: [@joplin/app-mobile]:     + - 4
	➤ YN0000: [@joplin/app-mobile]:     + - 5
	➤ YN0000: [@joplin/app-mobile]:     + - 6
	➤ YN0000: [@joplin/app-mobile]:       - [ ] 7
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:       74 |
	➤ YN0000: [@joplin/app-mobile]:       75 | 		toggleList(ListType.CheckList)(editor);
	➤ YN0000: [@joplin/app-mobile]:     > 76 | 		expect(editor.state.doc.toString()).toBe(
	➤ YN0000: [@joplin/app-mobile]:          | 		                                    ^
	➤ YN0000: [@joplin/app-mobile]:       77 | 			'- [ ] 1\n- [ ] 2\n- [ ] 3\n- [ ] 4\n- [ ] 5\n- [ ] 6\n- [ ] 7'
	➤ YN0000: [@joplin/app-mobile]:       78 | 		);
	➤ YN0000: [@joplin/app-mobile]:       79 | 	});
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:       at components/NoteEditor/CodeMirror/markdownCommands.toggleList.test.ts:76:39
	➤ YN0000: [@joplin/app-mobile]:       at fulfilled (components/NoteEditor/CodeMirror/markdownCommands.toggleList.test.ts:8:58)
	➤ YN0000: [@joplin/app-mobile]:       at tryCallOne (node_modules/promise/lib/core.js:37:12)
	➤ YN0000: [@joplin/app-mobile]:       at node_modules/promise/lib/core.js:123:15
	➤ YN0000: [@joplin/app-mobile]:       at flush (node_modules/asap/raw.js:50:29)

Or was the fix not applied to this particular test?

**Comment by laurent22** [comment]
Another random failure on a different test. Just documenting it here in case we want to look into it at some point, but for now I'm going to have to disable them because it's a problem on CI.

	➤ YN0000: [@joplin/app-mobile]: FAIL components/NoteEditor/CodeMirror/markdownCommands.toggleList.test.ts
	➤ YN0000: [@joplin/app-mobile]:   ● markdownCommands.toggleList › should properly toggle a sublist of a bulleted list
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:     expect(received).toBe(expected) // Object.is equality
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:     - Expected  - 1
	➤ YN0000: [@joplin/app-mobile]:     + Received  + 1
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:       # List test
	➤ YN0000: [@joplin/app-mobile]:        * This
	➤ YN0000: [@joplin/app-mobile]:        * is
	➤ YN0000: [@joplin/app-mobile]:       	1. a
	➤ YN0000: [@joplin/app-mobile]:     - 	2. test
	➤ YN0000: [@joplin/app-mobile]:     + 	* test
	➤ YN0000: [@joplin/app-mobile]:        * of list toggling
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:       91 | 		// Indentation should be preserved when changing list types
	➤ YN0000: [@joplin/app-mobile]:       92 | 		toggleList(ListType.OrderedList)(editor);
	➤ YN0000: [@joplin/app-mobile]:     > 93 | 		expect(editor.state.doc.toString()).toBe(
	➤ YN0000: [@joplin/app-mobile]:          | 		                                    ^
	➤ YN0000: [@joplin/app-mobile]:       94 | 			'# List test\n * This\n * is\n\t1. a\n\t2. test\n * of list toggling'
	➤ YN0000: [@joplin/app-mobile]:       95 | 		);
	➤ YN0000: [@joplin/app-mobile]:       96 |
	➤ YN0000: [@joplin/app-mobile]: 
	➤ YN0000: [@joplin/app-mobile]:       at components/NoteEditor/CodeMirror/markdownCommands.toggleList.test.ts:93:39
	➤ YN0000: [@joplin/app-mobile]:       at fulfilled (components/NoteEditor/CodeMirror/markdownCommands.toggleList.test.ts:8:58)
	➤ YN0000: [@joplin/app-mobile]:       at tryCallOne (node_modules/promise/lib/core.js:37:12)
	➤ YN0000: [@joplin/app-mobile]:       at node_modules/promise/lib/core.js:123:15
	➤ YN0000: [@joplin/app-mobile]:       at flush (node_modules/asap/raw.js:50:29)

**Pull request merged**
