### PR TITLE
Portuguese translation

### PR DESCRIPTION
**Pull request by laurent22**
Author name: Diogo Caveiro

### CODE REVIEW

**Comment by tessus** [comment]
@laurent22 Can I add this? I tested it locally and the translation works. Not sure why CI failed.

**Comment by tessus** [comment]
I think the CI failure is not related to the translation.

**Comment by laurent22** [comment]
I can't replicate the failure so I think it's indeed good to merge. I don't think we had pt_PT translation before (only BR) so we'll need to check if it shows up correctly in app.

**Comment by tessus** [comment]
Yep, this is what I've tested.

**Pull request merged**
