### PR TITLE
Android: Use native UI to select the directory for file system sync

### PR DESCRIPTION
**Pull request by roman-r-m**
It won't allow using an external SD card because due to Android limitations writing to external storage requires using a different API which isn't supported by react-native-fs.

Demo (ignore the weird colours, I think it's from compressing the gif):

ezgif com-gif-maker(7)

### CODE REVIEW

**Comment by laurent22** [comment]
Hmm, I'm not sure we should add this actually. File system sync is only half-supported because I think it will become obsolete at some point. It's already not working on iOS and a bit unreliable on Android, and since there are also more and more restrictions on Android I think it won't work at all some day. Originally file system sync was for testing only.

Because of that, I'm not so keen to improve support for it, especially if it means adding a lot of native code. Perhaps if there was an existing package we could use? But even then I'm not sure we should bother.

**Comment by roman-r-m** [comment]
> Perhaps if there was an existing package we could use?

There is https://github.com/lokdevp/react-native-directory-picker but on the main page there it says:
> warning Using this component is not recommended. This is a workaround.

The code here isn't that different from that package, maybe slightly more tailored to Joplin.

**Comment by roman-r-m** [comment]
> Because of that, I'm not so keen to improve support for it, especially if it means adding a lot of native code. Perhaps if there was an existing package we could use? But even then I'm not sure we should bother.

On the other hand you can say that since file system sync this isn't completely supported then we can afford to add this even if it's not perfect on best-effort basis.

**Comment by laurent22** [comment]
I'm wondering, is the code to pick a directory specific to Joplin? If not, perhaps it would make sense to make it a package that we could then include?

**Comment by roman-r-m** [comment]
> I'm wondering, is the code to pick a directory specific to Joplin? If not, perhaps it would make sense to make it a package that we could then include?

I don't think there's anything specific, maybe other than the fact that it disallows picking from an external sd card but that's more of a react-native specifics.

I can package it separately, no problem. Tbh, not sure what difference it makes but it's fine by me.

**Comment by roman-r-m** [comment]
I search Github again in hope that someone has done this already but alas.
There's https://github.com/lokdevp/react-native-directory-picker which is very similar but appears unmaintained, and also https://github.com/oceanbit/react-native-directory-picker which has some iOS code (no idea working or not) but on the Android side it's not fully implemented

**Comment by davidbaumann** [comment]
So on Android with Joplin 2.8.1 12 I can't find a way to open the folder selection at all.
I changed the target to File System, then tried to click everywhere, but nothing happened.

**Pull request closed without merging**
