### PR TITLE
Desktop: Fixed focus for viewer-only layout mode

### LINKED ISSUE #2810: When in Viewer-only mode, Ctrl+Shift+B should focus the viewer panel
Currently, the Ctrl+Shift+B shortcut is assigned to focus the note editor. However, when the current layout is viewer-only, it doesn't make sense to focus the editor. Instead it should focus the viewer panel.

### PR DESCRIPTION
**Pull request by coderrsid**
Fixes #2810

### CODE REVIEW

**Comment by coderrsid** [comment]
Why these build errors are there in both platforms?

image
image

**Comment by anihm136** [comment]
Those seem to be ESLint errors. Not sure how they got through the pre-commit hook though

**Comment by Rishgod** [comment]
> Why these build errors are there in both platforms?
> 
> image
> image

rebase your pr

**Comment by coderrsid** [comment]
> rebase your pr

It's still not working mahn!

**Comment by Rishgod** [comment]
> rebase your pr
> 
> It's still not working mahn! It's still showing the trailing commas issue in the file i haven't even touched

okay just redownload everything, have a fresh install of Joplin

**Comment by coderrsid** [comment]
> okay just redownload everything, have a fresh install of Joplin

So you mean make a new PR?

**Comment by coderrsid** [comment]
Is this all happening because i removed my package-lock.json file? .Btw, just out of curiosity, everytime i make a new local copy of forked repo and do `npm install` , a package-lock.json file is created obviously. So should i just commit it ? as it shows an extra file for commiting.

**Comment by Rishgod** [comment]
> > okay just redownload everything, have a fresh install of Joplin
> 
> So you mean make a new PR?

no no, what I do is I have two downloaded folders of Joplin, one is for pushing changes to GitHub and one is for development, in the GitHub folder I haven't done npm install(it's just for pushing commits), I basically do all my testing on the development folders after test it,  I manually add the changes to the GitHub folder and push it to GitHub. once I commit the changes to from my folder I do git stash and git pull so that folder remains up to date. Once you do git stash and git pull. 
git stash saves your changes locally and git pull syncs your GitHub folder with the main branch which will remove the changes you made to the GitHub folder  

So, in this case, you don't need to make a new pr, what you need to do is test locally from the development folder you have that this bug is fixed 

``` console
mkdir Joplin-github && cd Joplin-github
git clone https://github.com/laurent22/joplin.git
```
``` console
make changes to the folder
git fetch --all
git checkout change-focus-viewermode
git add .
git commit -m 'changes'
git push
```

**Pull request closed without merging**
