### PR TITLE
Add Badge "Get it on F-Droid" ...

### PR DESCRIPTION
**Pull request by goyalyashpal**
following Joplin's RFP completion on F-Droid 
https://gitlab.com/fdroid/rfp/-/issues/434

Closes: https://github.com/laurent22/joplin/issues/6218

### CODE REVIEW

**Comment by laurent22** [comment]
Thanks, but instead could you please add it in the "alt download" links? As in `"Download the APK file: 64-bit 32-bit<br/>Get it on F-Droid"` (without image)

**Comment by yashpalgoyal1304** [comment]
> add it in the "alt download" links

yeah, i can do that, but umh, would be curious to know why 😅

**Comment by laurent22** [comment]
We only have one primary download, this is why. Otherwise with all the download options it's confusing for the average user what they are supposed to install

**Comment by yashpalgoyal1304** [comment]
please check

**Comment by laurent22** [comment]
Thanks for the update!

**Comment by roman-r-m** [comment]
@laurent22 this was merged into **master** instead of dev

**Comment by laurent22** [comment]
Oh indeed, why was master branch used for that, that's strange. The commit will have to be cherry picked to dev.

And that makes me realise there's six commits that never made their way to dev. Nobody noticed though so I guess it wasn't important changes.

**Comment by roman-r-m** [comment]
Why not just delete master at this point? It doesn't seem to be used for anything.

**Comment by laurent22** [comment]
Sentimental value I guess as it was the original branch, but it's true it's not used at the moment.

**Comment by JoAllg** [comment]
looking for an f-droid link, I found that this commit is not merged into the dev branch :-) I am sure other users would be happy to find the link easier

**Comment by goyalyashpal** [comment]
Why not:
* rename that "main" branch to "archive-orginal" or the like, and
* make it protected - so, no merging, :. more foolproof, and
* set the primary branch of this repo to "dev" if not already? or rename
"dev" to "main" if thats wanted

Just thinking out loud, havent investigated anything regarding this yet

**Comment by Daeraxa** [comment]
Well at the moment it isn't actually available on F-Droid any more so no sense to try to fix this just yet.

**Pull request merged**
