### PR TITLE
Translation - Korean Langauge

### PR DESCRIPTION
**Pull request by readingsnail**
Some change of Korean Language

and need something - Page size for PDF export & Page Orientation for PDF export is not include po file.

and maybe add to another time format - am/pm xx:xx

### CODE REVIEW

**Comment by tessus** [comment]
> and need something - Page size for PDF export & Page Orientation for PDF export is not include po file.

There are actually a few strings missing, not only the ones related to the PDF export. We'll have to update those. @laurent22, can I run `build-translation.js` and push it, or is there anything else to do?

**Comment by tessus** [comment]
@readingsnail ok, I've updated the translation files. you should be able to do a rebase and add the rest.

**Comment by readingsnail** [comment]
Thanks, i updated now and upload new PR

**Comment by tessus** [comment]
Thanks again for your update!

**Pull request merged**
