### PR TITLE
Update to pt_BR locale (missing strings)

### PR DESCRIPTION
**Pull request by RenatoXSR**
Update a few missing strings in the pt_BR locale for Electron Client app. There were a few missing translations and there a few strings in English.

### CODE REVIEW

**Comment by franzejr** [comment]
This looks great! 
I'm also brazillian. I checked your translations! I just saw some items to be changed:

**1. Typo:**

```
   "Directory": "DIretório",
```

**2. Missing translations:**

```
"Checking... Please wait.": "Checking... Please wait.",
```

```
   "Success! Synchronisation configuration appears to be correct.": "Success! Synchronisation configuration appears to be correct.",
```

```
   "The application has been authorised!": "The application has been authorised!",
```

```
   "Decrypted items: %s / %s": "Decrypted items: %s / %s",
```

Other than that, GTG!

**Comment by RenatoXSR** [comment]
Should we also update the pt_BR.json of the reactive client? 

It seems to have the same strings there.

**Comment by laurent22** [comment]
For translations, please only translate the file pt_BR.po (with something like PoEdit) as I cannot use the JSON file since it's auto-generated.

**Comment by RenatoXSR** [comment]
Alright.

I'll submit a new PR.

I think this one may be closed.

Tks.



Em qua, 7 de nov de 2018 21:39, Laurent Cozic <notifications@github.com
escreveu:

**Comment by laurent22** [comment]
Thanks 👍

**Pull request closed without merging**
