### PR TITLE
Mobile: Resolves #6576: Fix checklist continuation in beta editor

### LINKED ISSUE #6576: Mobile/beta editor: Pressing enter does not continue a checklist
## Environment

Joplin version: e3695c6a80ea10cb5eb2cb46a9df39de02d36986
Platform: Android 12

## Steps to reproduce

1. Enable the beta editor
2. Create a new note with the following content
```md
# Test
- [ ] Checklist item 1
- [ ] Checklist item 2
```
3. Move the caret to the end of `- [ ] Checklist item 2` and press `enter`.

## Describe what you expected to happen
A new line with the content `- [ ]` should be added.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
 * Updates CodeMirror6 to the latest stable release (6.0.0)
 * As a result,
   * Checklist continuation now works
   * Ctrl+F can be used to search
 * Should fix #6576.

## Why was Ctrl+F/search support added?
A configuration change was required to migrate to CodeMirror 6. This new configuration is based on [the CodeMirror6 example setup](https://github.com/codemirror/basic-setup/blob/main/src/codemirror.ts), which includes support for find/replace. If it seems more appropriate, this change can be moved to a separate PR.

**Edit:** Ctrl+F/search support has been removed from this PR. See #6587.

### CODE REVIEW

**Comment by laurent22** [comment]
Yes please could you split into two pull requests?

So I guess there would be:

- PR1: CodeMirror 6 upgrade (which fixes checklist continuation?)
- PR2: Enable Ctrl+F for search. Although is that something we need? Most people don't use a keyboard with their phone

**Comment by tomasz1986** [comment]
> * PR2: Enable Ctrl+F for search. Although is that something we need? Most people don't use a keyboard with their phone

Possibly needed for Chromebooks? And all other laptop-like devices that run Android apps.

**Comment by CalebJohn** [comment]
> Although is that something we need? Most people don't use a keyboard with their phone

As development starts on the code mirror 6 based editor, we'll want to seriously consider using a shared editor across desktop and mobile. I don't see any reason why they can't be shared.

**Comment by laurent22** [comment]
That makes sense, and if it's built-in anyway it doesn't hurt to enable it.

**Comment by personalizedrefrigerator** [comment]
> That makes sense, and if it's built-in anyway it doesn't hurt to enable it.

Done! See #6587

**Comment by laurent22** [comment]
And is this pull request still valid, and what does it contain?

If we still need this PR, please run yarn install as CI is failing at the moment: https://github.com/laurent22/joplin/runs/6947854325?check_suite_focus=true#step:12:94

**Comment by personalizedrefrigerator** [comment]
> And is this pull request still valid, and what does it contain?
> 
> If we still need this PR, please run yarn install as CI is failing at the moment: https://github.com/laurent22/joplin/runs/6947854325?check_suite_focus=true#step:12:94

This pull request updates CodeMirror to the latest version (6.0.0) in the mobile app. This fixes a bug that was resolved upstream (checklist continuation not working).

**Comment by laurent22** [comment]
Thanks for the update. Also just a reminder to please not force push on pull request, as this breaks GitHub code review system since it's not longer possible to know what has been changed since the last push.

If rebasing is not possible, simply merge the dev branch, as that will preserve git history.

**Comment by laurent22** [comment]
Thanks for the fix @personalizedrefrigerator!

**Pull request merged**
