### PR TITLE
Android: add version info

### PR DESCRIPTION
**Pull request by tessus**
This change adds the application version to the `Configuration` screen.

We can also add the Version Info somewhere else, like to the `Status` screen or create a new menu item `About`. I just added it to the `Configuration` item, because I didn't know where to put it otherwise.

As soon as I have the time, I will also implement this for iOS.

### CODE REVIEW

**Comment by laurent22** [comment]
There's a module to get the version number in iOS and Android, couldn't we use this instead? https://github.com/stovmascript/react-native-version

**Comment by tessus** [comment]
I don't know. Maybe. But I wouldn't know how to use that module.

I just know that the code I wrote works. That's how you write native modules. I did some research and most packages read the package.json file which might not have the correct version. Yours shows `0.8.0`.

You can try to use the module you have mentioned. Maybe it works too.

**Comment by laurent22** [comment]
Hmm, yes we should probably give that other module a try since it means a bit less code to maintain and it seems to work on both iOS and Android.

**Comment by tessus** [comment]
Well, in that case somebody else has to do this. I do not understand how to use this module.
Usually you have a function to get the version like `getVersion`, but it looks like this module is used for versioning itself, not to retrieve the version number.

**Comment by tessus** [comment]
Also, you can always replace my code in the future, but at least for now the next Android release would have a version number in the UI. ;-)

**Comment by tessus** [comment]
I really think this is the wrong module:

_Before you publish a new build of your app, run npm version <newversion>._

_react-native-version will then update your android/ and ios/ code. Depending on the script and options you choose, it can also automatically amend the version bump commit and update the Git tag created by npm version. This method should be useful in most cases. If you need more control, take a look at the CLI and options below._

**Comment by tessus** [comment]
This module does the opposite. It writes version information, it does not make it available to the app.

**Comment by tessus** [comment]
@laurent22 any comment on my previous messages? I might have time this weekend to also get it working on iOS. but I won't waste my time, if it's not getting merged anyway.

**Comment by laurent22** [comment]
I don't have time to look at it at the moment, but unfortunately I cannot merge until I'm sure there's no third party module to do this. Your solution technically is good, but the issue is that if it breaks later on (eg. after a RN upgrade) that will be native code that needs to be changed, which can be tricky. With a third-party module, even if it breaks there's a good chance someone else will fix it, especially if many people or companies are relying on it.

**Comment by tessus** [comment]
Well, I can only partly agree with you, because modules can become abandoned and unmaintained as well. In a perfect landscape, I'd agree with you completely. Unfortunately it is not that simple. As an example, look at [sabre/dav](https://evertpot.com/sabredav-eol/). When people are relying on SW, it makes no difference which SW it is. If people relied on the module, they would fix it. If people relied on Joplin, they would fix it.
Btw, I seriously doubt that RN would make a breaking change to their natives module interface.

Just to be clear, I don't have a problem with using a 3rd party module instead, I just don't think it will make any difference in maintenance and peace of mind. That's all.

**Comment by laurent22** [comment]
Thanks @tessus. In terms of module I think this one works: https://github.com/APSL/react-native-version-number but would need to be confirmed.

**Comment by tessus** [comment]
I did a bit more research and there are 2 packages available on npm. One is a bit heavy and loaded with functionality and the other one (you mentioned it in your last comment), which is more lightweight and would fit this use case much better, seems to be dead - or at least the owners don't really care for it anymore.

I'm thinking of creating my own npm package based on the lightweight one. In this case, your desire to use a 3rd party module is satisfied and it can be used by others as well.

Therefore I'm closing this PR for now and create a new one as soon as the package is ready.

**Comment by tessus** [comment]
Please let me know what you think of my idea of creating a new package.

**Pull request closed without merging**
