### PR TITLE
TRANSLATION: Macedonian (98%)

### PR DESCRIPTION
**Pull request by 6-AND-9**
Hello,

I have no idea how to work with GitHub or make a pull request, but here I am. I did a 98% Macedonian translation, with some minor issues (mostly because of missing context). It is ready to be used for sure. I will make an effort to improve the rest of them for the weeks to come.

Cheeers,
- A
[Joplin-mk-translation-98.zip](https://github.com/laurent22/joplin/files/7822458/Joplin-mk-translation-98.zip)

### CODE REVIEW

**Comment by Daeraxa** [comment]
I don't want to knock your enthusiasm or confidence here but you have some real issues with this PR, there are tons of commits here from a couple of years ago and the actual translations aren't in the actual code, just attached in a zip file.

At the very least you should fork the Joplin repo to get the latest version, make a new branch for your translation and put the .po file there ( in `/packages/tools/locales`) then make a PR from that branch.

https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

https://www.better.dev/create-your-first-github-pull-request

Read these for good summaries on how to make a PR (including doing it "properly" by downloading all the code locally with git, making the changes there and pushing those changes back up to github before making the PR for the original rather than just editing directly on github).

It isn't as daunting as it might look, I made a very similar mistake when I first used git and github.

**Comment by tessus** [comment]
I suggest to start over. Save your .po file.

I wrote a guide: https://discourse.joplinapp.org/t/how-to-create-a-pull-request-pr/15052?u=tessus

**Comment by tessus** [comment]
Thanks a bunch for this. If you can't make it work, I can add that file to the source tree.

But for future contributions it would make sense to understand the process. If you still have qusestions after resing the guide, ping me....

**Comment by 6-AND-9** [comment]
Hey @tessus, yes, please do. I have no idea even where to add it. I know I made a mess here (ditto @Daeraxa), sorry for that, will look into your guide but not being a developer I have no idea if it'll stick :D

**Comment by Daeraxa** [comment]
Absolutely zero need to apologise for anything, you are helping improve an open source project and everybody has to start somewhere.
What tessus is saying is that he could implement your changes manually but if you follow those guides and complete the PR correctly then your changes are directly merged into the project and you will get the credit for the changes you contributed. It will also make any future updates you want to make far easier to implement. 
Feel free to ping either of us here if you want any help or create a forum account (it you don't have one) and open a topic or PM.

**Comment by 6-AND-9** [comment]
Alright, I'll make an effort later on today or tomorrow. I need to learn to work with git some day anyways, so why not now :D

**Comment by tessus** [comment]
If you have any questions along the way, please let us know.

**Comment by tessus** [comment]
@6-AND-9 are you stuck at a certain step? We can work on this together. Why don't you tell me where you at and I can tell you what to do next.

**Pull request closed without merging**
