### PR TITLE
Desktop: Fixed the html background color in nord theme

### LINKED ISSUE #2961: Desktop : Layout in the nord theme has a different background.
## Environment

Joplin version: 1.0.195
Platform: Windows

## Steps to reproduce

1. In the editor, press Ctrl+L
2. The background of the layout is different

nord-theme-overlay-issue

It only persists in nord theme. In all other themes, it is consistent.Ex: In dark theme
joplin-dark

## Describe what you expected to happen
The background should remain consistent in the editor and layout.

### PR DESCRIPTION
**Pull request by Rahulm2310**
Before:
nord-theme-overlay-issue

After:
fixednord

fixes #2961

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@PackElend  sir please label me

**Comment by laurent22** [comment]
Does it need to be fixed though? There's no requirement that the text area should have the same colour as the frame. I don't think it looks better or worse in the new version, it's a matter of opinion I think.

**Comment by Rahulm2310** [comment]
@laurent22 You are right sir but as in all other themes, text area do have the same color as that of frame, so that would be nice to make the nord theme consistent with other themes

**Comment by laurent22** [comment]
Thanks for the change, but I feel the theme as it is looks fine, and strict consistency between themes is not required.

**Comment by Rahulm2310** [comment]
@laurent22 sir we did a similar change for OLED theme on mobile then why this shouldn't be fixed

**Pull request closed without merging**
