### PR TITLE
Android: do not show long press menu on press and drag

### PR DESCRIPTION
**Pull request by roman-r-m**
Also note that I was unable to build the android version without adding back `ReactNativeClient/lib/rnInjectedJs/webviewLib.js`

### CODE REVIEW

**Comment by laurent22** [comment]
That looks good, thank you. As for the webviewLib issue, I made many changes to the mobile app due to the RN upgrade so it might be that you needed to rebuild everything from scratch. I've just released the Android app which seems to work fine, but I'll keep that in mind in case I broke something.

Also links could no longer be opened in the desktop app as you've accidentally removed the "onclick" handler. That's fixed in this commit - https://github.com/laurent22/joplin/commit/7e78d7716ba3fa62a516e63bbcfc2a1d3ed3b0c0

**Comment by laurent22** [comment]
@roman-r-m, it looks like there's still an issue with this feature. Every time I try to zoom in or out on a note, it's going to display the popup menu. I think the code needs to differentiate between single finger touch and two fingers touch events, if that's at all possible. Or perhaps rather than simulate the long press event with a timer, maybe there's a built-in long press event we could use?

**Comment by roman-r-m** [comment]
> Or perhaps rather than simulate the long press event with a timer, maybe there's a built-in long press event we could use?

There isn't as far as I could tell. I'll look into filtering out multi-touch events.

**Comment by laurent22** [comment]
@roman-r-m, if you don't mind I will disable this behaviour for now, as this is a bit annoying to have this menu popup every time I zoom in or out of a note.

**Comment by roman-r-m** [comment]
Sure. Sorry for not fixing this faster -- a bit swamped with work recently. I'll have a week off after Christmas, will look into this then.

**Comment by laurent22** [comment]
No worries, I'm just setting enableLongPress to false, so it will just be a flag to turn back on once it's working.

**Pull request merged**
