### PR TITLE
Desktop: Improved amsmath KaTeX support

### PR DESCRIPTION
**Pull request by eh8**
image
Enables proper support for amsmath symbols in set theory.

### CODE REVIEW

**Comment by tessus** [comment]
What happens on mobile though?

**Comment by eh8** [comment]
Mobile is unaffected at the moment, this only improves the ElectronClient

**Comment by tessus** [comment]
I think we should fix this on mobile as well, unless @laurent22 is ok with a fix for desktop only.

**Comment by eh8** [comment]
Hmm, it should be simple to add the font files for the mobile client as
well, when I return home I’ll give it a try.

This being said, this doesn’t fix the missing KaTeX when you export to PDF
issue.

**Comment by tessus** [comment]
Let's wait what Laurent says.

**Comment by laurent22** [comment]
These are the right files, however this folder is auto generated from joplin-renderer, so that's where the files should go. Once they are there, they'll also be auto imported in the mobile app too.

**Comment by tessus** [comment]
@laurent22 great, thx for the info. I'm wondering if we should add a `AUTOGENERATED` stub file in such folders. The stub file should include the source directory.

**Comment by tessus** [comment]
@eh8 did you see Laurent's comment?

**Comment by tessus** [comment]
I think you are still using the wrong directory. Laurent mentioned it is autogenerated.

@laurent22 this is another example of duplicate files in 2 separate directories.
They should be removed from the source tree.

**Comment by eh8** [comment]
Yep, I just reread Laurent's comment. Sorry for the trouble and confusion.

I have correct all the file paths and expanded the font set for KaTeX. This should be a satisfactory fix.

**Comment by tessus** [comment]
Thanks. These are a lot of files... ;-) I guess Laurent will have to decide.

**Comment by eh8** [comment]
Yes, there are indeed a lot of new files. I nticed that the katex.css file
was referencing these non-existent font files, so I added them into the
pack :)

**Comment by laurent22** [comment]
> @laurent22 this is another example of duplicate files in 2 separate directories.
> They should be removed from the source tree.

It depends - where there are duplicate files like this it's often for reason. In this case, the plugin assets rarely ever change, so there's no need to complicate the build process for it. They are just copied there when needed.

**Comment by laurent22** [comment]
I can't make a decision about all these files as I don't know anything about it, so it would be better to limit the pull request to just fix that particular bug for now. Later, if someone knows about these files, and make a case for them being included, we can open another PR.

**Comment by eh8** [comment]
Point taken, but surely it is better to proactively enable full support for KaTeX notation rather than wait for further PRs?

If you are concerned about the authenticity of these files, it is merely yanked from the [official repo.](https://github.com/KaTeX/katex-fonts)

If you still hesitant, please let me know and I will drop the additional files.

**Comment by laurent22** [comment]
That's a lot of fonts to package and load, and that will slow down the rendering of notes. Not to mention there are three versions of each file (woff, woff2, tiff) and only one among those actually need be loaded. Basically we need to understand what we are doing and why.

**Comment by tessus** [comment]
@laurent22 
> It depends - where there are duplicate files like this it's often for reason. In this case, the plugin assets rarely ever change, so there's no need to complicate the build process for it. They are just copied there when needed.

I'm a bit confused now. You mentioned earlier that this directory is autogenerated and the files are automatically copied there, so I'm not sure why you now state the opposite.
Or did I miss something?

**Comment by laurent22** [comment]
It turns out there was a bit more to do to get things working, in particular when printing so I've ended up implementing this here: 95e0e8d459a55cc81dcd7c617cf6619f2c304696

As mentioned above, for now we only include the files that we know we need, and later let's see if we need more of them. Thanks @eh8 for pointing to the right file though.

**Comment by eh8** [comment]
Good call, however I would claim that the additional font files are not slowing down rendering. The console reveals that the CSS file is trying to call references to these files, which don't exist. 

Additionally, only the woff2 file is used in practice since most users are on modern systems that support the convention. This is the fastest and smallest font file implementation compared to standard ttf and woff.

**Pull request closed without merging**
