### PR TITLE
Desktop: Add extra macos keys from #4257

### PR DESCRIPTION
**Pull request by CalebJohn**
See the discussion in #4257 for reference.

The eslintignore and gitignore changes were automatically generated on commit. I can try to remove them if you want.

### CODE REVIEW

**Comment by tessus** [comment]
Btw, while you're at it. Can you also change `MacOS` to `macOS` in that file?

**Comment by tessus** [comment]
qq where can I find the example how to add a codemirror shortcut via a plugin? (You mentioned an example, but I couldn't find it... at least not in `packages/app-cli/tests/support/plugins`)

**Comment by CalebJohn** [comment]
The plugin example was removed because it's no longer up to date. All keybindings should be added via the command system. Unfortunately, that doesn't mean much because the commands system hasn't quite been connected to the editor instances. You might still be able to use the old method which is

```javsacript
CodeMirror.keyMap.default['Ctrl-U'] = 'someCommand';
```
I plan to spend some time on this in the next week or so, hopefully it will be fully connected soon.

**Comment by tessus** [comment]
@CalebJohn I haven't tested it yet, but I'm using `Opt+Left` for `Back` and `Opt+Right` for `Forward`.

```
  {
    "command": "historyBackward",
    "accelerator": "Option+Left"
  },
  {
    "command": "historyForward",
    "accelerator": "Option+Right"
  }
```

Will this PR render my shortcut assignment impossible?

**Comment by CalebJohn** [comment]
Oops, I saw your other comment first. This pull won't affect your keybindings.

**Comment by tessus** [comment]
> Oops, I saw your other comment first.

Haha, same here. ;-)

Thanks, I've just tested it. (I had to get to my computer first. :-))

My keyboard shortcuts still work. It's just that the codemirror shortcuts are not available, since I can't change them (other than changing the source code). This is not a problem for me, and if this is working as designed, I'm ok with it!

**Review by tessus — COMMENTED** [review]
LGTM

**Comment by tessus** [comment]
@CalebJohn it seems that there's now a conflict for these files:

> The eslintignore and gitignore changes were automatically generated on commit.

I've noticed something similar when  I run `npm i` or sometimes just after running `npm run start`.  I often get additional changes to the `Podfile.lock` file or to the 2 files. I usually always add `&& git stash && git stach clear` to the `npm i` command. ;-)

**Comment by CalebJohn** [comment]
Thanks for the heads up. I normally do that, but I think this time it happened while committing, or maybe I just forgot.

**Comment by laurent22** [comment]
Thanks for the update, and happy new year to both of you!

**Pull request merged**
