### PR TITLE
Mobile: Added vertical scroll view for edit mode #2286

### PR DESCRIPTION
**Pull request by vaibhav2ghadge**
added the scroll view but it's not draggable anybody helps me in that..? (for that will make another PR
Screenshot_20200222_122257_net cozic joplin
)

### CODE REVIEW

**Comment by vaibhav2ghadge** [comment]
@laurent22 @tessus can you look into it

**Comment by laurent22** [comment]
I don't understand what this does? For sure that view was already scrollable before, wasn't it?

**Comment by vaibhav2ghadge** [comment]
@laurent22 Yes its already scrollable but it not showing scroll bar so its difficults to visualise size of note in edit mode . in view mode its already present.

**Comment by laurent22** [comment]
> added the scroll view but it's not draggable anybody helps me in that

I think the threshold to create a PR is that it builds, and works. Once it does, we can review and you're free to make changes and improve, but the first step is to prove that what you want to do can be be done (sometimes it cannot).

@PackElend, @tessus, what would be your take on this? Perhaps we should clarify what's the threshold to create a GSoC PR?

**Comment by vaibhav2ghadge** [comment]
it builds, and works it solve one of this problem https://github.com/laurent22/joplin/issues/2286

**Comment by laurent22** [comment]
In the issue you've linked, the problem is that it's not possible to quickly scroll down to the bottom of a note. A scrollbar *that can be dragged* would solve that problem. However your scrollbar currently can't be dragged, so that's why the PR is not complete.

It's ok if the PR has bugs or some problems you missed, but the complete functionality needs to be there.

**Comment by laurent22** [comment]
I will close the pull request for now till this is complete. Feel free to comment here when it's ready and you'd like to reopen.

**Pull request closed without merging**
