### PR TITLE
Desktop: Fixes #3621: Fix highlighting in AceEditor

### LINKED ISSUE #3621: Desktop: Highlighting does not always work
test-3

## Environment

Joplin version: 1.0.233 (dev, linux)
Platform: Linux
OS specifics: Ubuntu 20.04 LTS

## Steps to reproduce

1. Create a note with "abc def"
2. Search for "abc"
3. Then search for "def"
4. "def" is not highlighted

## Describe what you expected to happen
"def" should be highlighted.

## Logfile
No errors or warnings.

It seems a note change (either a change in the note text or a change in the note currently viewed) is needed for highlighting. This should not be the case.

### PR DESCRIPTION
**Pull request by naviji**
Fixes #3621 

I didn't see any performance impact when testing because of this change.

### CODE REVIEW

**Comment by CalebJohn** [comment]
The same code is present in codemirror editor as well, this should be updated there as well.
I think we need to hear from @laurent about what the purpose of this code was. I can't think of a situation where it is really necessary, but maybe we're missing something?

**Comment by laurent22** [comment]
What happened is that initially the effect would run only when `searchMarkers` would change, which is an optimization as you don't want to send ipc messages on each key stroke. Then I've realised that the effect must run also when the body changes so I've added the `renderedBody` dependency, but the results is that now unfortunately the effect runs on each key stroke.

So @naviji's fix is correct in the sense that it will fix #3621, but a better fix would be to make sure IPC message is only sent when:

- The search maker changes
- Or when the body changes AND there are search markers

In other word, no IPC message should be sent when the body changes and there are no search markers (which is the most common case).

**Comment by laurent22** [comment]
@CalebJohn, actually did you apply this fix to CodeMirror? This pull request is not relevant anymore now that Ace Editor is gone, but I'm thinking of leaving it open as a reminder that CodeMirror should be fixed to (if it needs to).

**Comment by CalebJohn** [comment]
Thanks for the reminder. I've created a fix in #3717, I'm closing this now.

**Pull request closed without merging**
