### PR TITLE
[init] the first version of the fa.po file

### PR DESCRIPTION
**Pull request by mmahmoudian**
Providing translation for Persian language

### CODE REVIEW

**Comment by tessus** [comment]
@mmahmoudian thanks a lot for this.

P.S.: your info says "_I don't use github much (no free private repo)_" -> this is not true anymore. They have changed this a while back.

**Comment by mmahmoudian** [comment]
@tessus Thanks for checking this. Perhaps it would be nice to have this path in the README.md file under the Localisation section so prevent further confusion.

Additionally I didn't know how to calculate the completion percentage (too lazy to do it manually or write a code to do it for me), therefore I didn't add a row for Persian in the Localisation table.

P.s: Regarding my Github profile info, I had totally forgot about it and you are right, their policy have changed, but I still trying to avoid Github to be honest since I don't fully trust Microsoft products (yet, and I'll be glad to be proven wrong). Anyhow, I updated the info section :)

**Comment by laurent22** [comment]
Thanks for the translation @mmahmoudian, much appreciated!

You don't need to update the % translated because that's done automatically by the build script.

Note that I don't know much about right to left languages including Persian and Arabic, so once it's merged if you notice any mistake, feel free to let me know. It seems the UI support this outside the box but who knows.

Also I don't know if it will work with search but probably we can make it work if it doesn't.

**Comment by tessus** [comment]
@mmahmoudian 

> Perhaps it would be nice to have this path in the README.md file under the Localisation section so prevent further confusion

Hmm, maybe we could improve this a bit, but the second item links to a file in that directory and since all other translations are in there, I thought it should be obvious. But maybe not.

**Pull request merged**
