### PR TITLE
Server: Enable multi platform builds (take 3)

### PR DESCRIPTION
**Pull request by piotrb**
Ok another try at making this a very small change :)

This depends on #6001 being merged first, a bunch of of the changes here are from that PR.

### CODE REVIEW

**Comment by piotrb** [comment]
For CI I kind of want to run a different code path in that buildServerDocker file .. ideally I'd want to feed it a single platform and run it as a matrix build .. 

How do you currently do the actual release builds? Do you just run the script manually on your local machine?

**Comment by laurent22** [comment]
Same comment as https://github.com/laurent22/joplin/pull/6001#issuecomment-1009881180

**Comment by piotrb** [comment]
Yea this needs cleanup .. I opened the PR for CI runs as well ..

**Comment by laurent22** [comment]
> How do you currently do the actual release builds? Do you just run the script manually on your local machine?

I run `yarn run releaseServer`, which is going to push a tag, which in turn is going to build the Docker image and push it to Docker Hub (it's done in run_ci.sh).

For testing on CI, it's actually the ServerDockerImage job, which is there only to check that nothing got broken in a commit or pull request.

**Comment by piotrb** [comment]
Also I've been running into an issue with ARM builds .. and I think I finally tracked down an issue referencing anything to do with this and I found this .. 

https://github.com/docker/for-mac/issues/5831#issuecomment-939229070

which wasn't super helpful .. 

```
#36 33.39 ➤ YN0000: ┌ Fetch step
#36 80.49 ➤ YN0001: │ Error: Couldn't allocate enough memory
#36 80.49     at ZipFS.allocateBuffer ([worker eval]:2063:13)
#36 80.49     at ZipFS.allocateSource ([worker eval]:2079:39)
#36 80.49     at ZipFS.setFileSource ([worker eval]:2090:27)
#36 80.49     at ZipFS.writeFileSync ([worker eval]:2289:27)
#36 80.49     at extractArchiveTo ([worker eval]:15413:20)
#36 80.49     at async MessagePort.<anonymous> ([worker eval]:15451:3)
#36 81.59 ➤ YN0001: │ Error: Couldn't allocate enough memory
#36 81.59     at ZipFS.allocateBuffer ([worker eval]:2063:13)
#36 81.59     at ZipFS.allocateSource ([worker eval]:2079:39)
#36 81.59     at ZipFS.setFileSource ([worker eval]:2090:27)
#36 81.59     at ZipFS.writeFileSync ([worker eval]:2289:27)
#36 81.59     at extractArchiveTo ([worker eval]:15413:20)
#36 81.59     at async MessagePort.<anonymous> ([worker eval]:15451:3)
```

This is how it fails ..

**Comment by piotrb** [comment]
perhaps this is fixed in a newer version of yarn? except joplin is already on 3.1.1 which is latest .. sigh .. this is bizzare ..

**Comment by piotrb** [comment]
really can't see much issues on yarn's repo that are anything like it .. closest come from some vague closed or no repo issues:

https://github.com/yarnpkg/berry/issues/3580
https://github.com/yarnpkg/berry/issues/3658

This is quite annoying I can't seem to even build myself a working arm build at this rate ...

Some people say that they don't see this issue in Node 14 .. I wonder though ..

**Comment by piotrb** [comment]
Have you ran into anything similar to this?

**Comment by piotrb** [comment]
Tried bumping allowed memory to 16G on docker for mac .. same issue .. 
Tried running on docker for windows .. on a 32G machine .. same issue .. 
Even tried building the arm64 version instead .. and same issue .. 

something about that build just seems to use a lot of memory ..

**Comment by tessus** [comment]
Will this work with #5939 ?

**Comment by laurent22** [comment]
Now that https://github.com/laurent22/joplin/pull/6048 is merged this pull request would probably need to be updated. Also since #6001 doesn't have that many changes I think it's ok to combine them in one pull request only, and it will make it easier to review.

**Comment by laurent22** [comment]
@piotrb, what's your plan for these two pull requests? I realise all these conflicts are quite annoying but do you think you can apply your changes to the new Dockerfile?

**Comment by laurent22** [comment]
Closing for now, but feel free to submit again if you look into it again later.

**Comment by xavivars** [comment]
I guess there's still no arm64 image. I just moved my Joplin server to an arm-based machine, and I had to build the image myself. Not a big deal, for sure, but it would be awesome if this could be integrated somehow

**Comment by laurent22** [comment]
There is one now in the prereleases. It should be available officially in the next few months

**Comment by ahxxm** [comment]
is there an issue to track the process, I tentatively tried joplin server on an arm64 server and got tini complaining about exec format too

**Comment by navilg** [comment]
Where can I find pre-release version for arm ? Any timeline for release ?

**Pull request closed without merging**
